import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import { prisma } from '@/lib/db'
import { SiteHeader } from '@/components/SiteHeader'
import { ShareButtons } from '@/components/ShareButtons'

interface PageProps {
  params: { id: string }
}

// Fetch the shared recipe
async function getSharedRecipe(id: string) {
  try {
    const recipe = await prisma.sharedRecipe.findUnique({
      where: { id },
    })
    return recipe
  } catch {
    return null
  }
}

// Generate dynamic metadata for social sharing
export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const recipe = await getSharedRecipe(params.id)

  if (!recipe) {
    return {
      title: 'Recipe Not Found',
    }
  }

  const baseUrl = 'https://www.dinnerdecisionmaker.com'
  const recipeUrl = `${baseUrl}/recipe/${params.id}`

  const description = recipe.description || 
    `${recipe.title} - ${recipe.ingredients.length} ingredients, ${recipe.instructions.length} steps. Generated by Dinner Decision Maker.`

  return {
    title: recipe.title,
    description,
    openGraph: {
      title: recipe.title,
      description,
      url: recipeUrl,
      siteName: 'Dinner Decision Maker',
      type: 'article',
      images: [
        {
          url: '/logo/logo.webp',
          width: 512,
          height: 512,
          alt: recipe.title,
        },
      ],
    },
    twitter: {
      card: 'summary',
      title: recipe.title,
      description,
      images: ['/logo/logo.webp'],
    },
    alternates: {
      canonical: recipeUrl,
    },
  }
}

export default async function SharedRecipePage({ params }: PageProps) {
  const recipe = await getSharedRecipe(params.id)

  if (!recipe) {
    notFound()
  }

  const shareUrl = `https://www.dinnerdecisionmaker.com/recipe/${params.id}`

  return (
    <div className="min-h-screen bg-background">
      <SiteHeader />
      <main className="mx-auto max-w-3xl px-4 py-8 md:px-6">
        {/* Back link */}
        <Link
          href="/cook"
          className="inline-flex items-center text-sm text-muted-foreground hover:text-foreground mb-6"
        >
          ← Generate your own recipes
        </Link>

        {/* Recipe Card */}
        <article className="rounded-xl border border-border bg-card p-6 md:p-8 shadow-sm">
          {/* Header */}
          <header className="mb-6">
            <h1 className="text-2xl font-bold tracking-tight text-foreground md:text-3xl">
              {recipe.title}
            </h1>
            {recipe.description && (
              <p className="mt-2 text-muted-foreground">{recipe.description}</p>
            )}
          </header>

          {/* Quick Info */}
          <div className="flex flex-wrap gap-4 text-sm text-muted-foreground mb-6 pb-6 border-b border-border">
            {recipe.prepTime && (
              <div className="flex items-center gap-1">
                <span>Prep:</span>
                <span className="font-medium text-foreground">{recipe.prepTime} min</span>
              </div>
            )}
            {recipe.cookTime && (
              <div className="flex items-center gap-1">
                <span>Cook:</span>
                <span className="font-medium text-foreground">{recipe.cookTime} min</span>
              </div>
            )}
            {recipe.servings && (
              <div className="flex items-center gap-1">
                <span>Serves:</span>
                <span className="font-medium text-foreground">{recipe.servings}</span>
              </div>
            )}
            {recipe.cuisine && (
              <div className="flex items-center gap-1">
                <span>Cuisine:</span>
                <span className="font-medium text-foreground">{recipe.cuisine}</span>
              </div>
            )}
            {recipe.difficulty && (
              <div className="flex items-center gap-1">
                <span>Difficulty:</span>
                <span className="font-medium text-foreground">{recipe.difficulty}</span>
              </div>
            )}
          </div>

          {/* Nutrition */}
          {(recipe.calories || recipe.protein || recipe.carbs || recipe.fat) && (
            <div className="mb-6 pb-6 border-b border-border">
              <h2 className="text-sm font-semibold text-foreground mb-2">Nutrition (per serving)</h2>
              <div className="flex flex-wrap gap-4 text-sm text-muted-foreground">
                {recipe.calories && <span>{recipe.calories} cal</span>}
                {recipe.protein && <span>{recipe.protein}g protein</span>}
                {recipe.carbs && <span>{recipe.carbs}g carbs</span>}
                {recipe.fat && <span>{recipe.fat}g fat</span>}
              </div>
            </div>
          )}

          {/* Ingredients */}
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-foreground mb-3">Ingredients</h2>
            <ul className="space-y-2">
              {recipe.ingredients.map((ingredient: string, idx: number) => (
                <li key={idx} className="flex items-start gap-2 text-muted-foreground">
                  <span className="text-primary mt-1">•</span>
                  <span>{ingredient}</span>
                </li>
              ))}
            </ul>
          </section>

          {/* Instructions */}
          <section className="mb-6">
            <h2 className="text-lg font-semibold text-foreground mb-3">Instructions</h2>
            <ol className="space-y-4">
              {recipe.instructions.map((step: string, idx: number) => (
                <li key={idx} className="flex gap-3 text-muted-foreground">
                  <span className="flex-shrink-0 w-6 h-6 rounded-full bg-primary/10 text-primary text-sm font-medium flex items-center justify-center">
                    {idx + 1}
                  </span>
                  <span className="pt-0.5">{step}</span>
                </li>
              ))}
            </ol>
          </section>

          {/* Share Buttons */}
          <div className="pt-6 border-t border-border">
            <h2 className="text-sm font-semibold text-foreground mb-3">Share this recipe</h2>
            <ShareButtons url={shareUrl} title={recipe.title} />
          </div>
        </article>

        {/* CTA */}
        <div className="mt-8 rounded-xl border border-border bg-card p-6 text-center">
          <h2 className="text-lg font-semibold text-foreground mb-2">
            Want recipes like this?
          </h2>
          <p className="text-muted-foreground mb-4">
            Generate personalized recipes from ingredients you have in seconds.
          </p>
          <Link
            href="/cook"
            className="inline-flex items-center justify-center rounded-md bg-primary px-6 py-3 text-sm font-medium text-primary-foreground shadow hover:bg-primary/90"
          >
            Try the Recipe Generator
          </Link>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border py-8 mt-8">
        <div className="mx-auto max-w-3xl px-4 md:px-6 flex justify-between text-sm text-muted-foreground">
          <Link href="/privacy" className="hover:text-foreground">Privacy</Link>
          <Link href="/terms" className="hover:text-foreground">Terms</Link>
        </div>
      </footer>
    </div>
  )
}
