import { Metadata } from 'next'
import { SiteHeader } from '@/components/SiteHeader'
import { PageShell } from '@/components/PageShell'

export const metadata: Metadata = {
  title: 'Terms of Service',
  description: 'Terms of Service for Dinner Decision Maker - rules and guidelines for using our service.',
  alternates: {
    canonical: 'https://www.dinnerdecisionmaker.com/terms',
  },
}

export default function TermsPage() {
  const lastUpdated = 'February 6, 2026'

  return (
    <div className="min-h-screen bg-background">
      <SiteHeader />
      <PageShell title="Terms of Service" description={`Last updated: ${lastUpdated}`}>
        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Agreement to Terms</h2>
            <p className="text-muted-foreground mb-4">
              By accessing or using Dinner Decision Maker at www.dinnerdecisionmaker.com
              (&quot;the Service&quot;), you agree to be bound by these Terms of Service. If you do not
              agree to these terms, please do not use the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Description of Service</h2>
            <p className="text-muted-foreground mb-4">
              Dinner Decision Maker is a free tool that helps you decide what to have for dinner by:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground mb-4">
              <li>Generating recipe ideas based on ingredients you have</li>
              <li>Finding restaurants near you that match your preferences</li>
              <li>Providing a random selection wheel for dinner options</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">User Accounts</h2>
            <p className="text-muted-foreground mb-4">
              You may use some features without an account. To save recipes and preferences,
              you must sign in with Google. By creating an account, you agree to:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground mb-4">
              <li>Provide accurate information</li>
              <li>Maintain the security of your account</li>
              <li>Accept responsibility for all activity under your account</li>
              <li>Notify us of any unauthorized access</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Acceptable Use</h2>
            <p className="text-muted-foreground mb-4">You agree NOT to:</p>
            <ul className="list-disc pl-6 text-muted-foreground mb-4">
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to bypass rate limits or abuse the API</li>
              <li>Scrape, crawl, or collect data from the Service without permission</li>
              <li>Interfere with or disrupt the Service</li>
              <li>Impersonate others or provide false information</li>
              <li>Use automated tools to access the Service (except search engines)</li>
              <li>Reverse engineer or attempt to extract source code</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Rate Limits</h2>
            <p className="text-muted-foreground mb-4">
              To ensure fair access for all users, we implement rate limits on recipe generation
              and restaurant searches. Attempting to circumvent these limits may result in
              temporary or permanent restriction of access.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Generated Content</h2>
            <p className="text-muted-foreground mb-4">
              Recipes generated by our Service are created using artificial intelligence. While
              we strive for accuracy:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground mb-4">
              <li>Generated recipes may contain errors or inaccuracies</li>
              <li>Nutritional information is estimated and may not be precise</li>
              <li>You should use your own judgment regarding food safety</li>
              <li>Check for allergens and dietary restrictions before cooking</li>
              <li>We are not responsible for outcomes from following generated recipes</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Restaurant Information</h2>
            <p className="text-muted-foreground mb-4">
              Restaurant information is provided by Google Places and may not be current.
              We are not responsible for:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground mb-4">
              <li>Accuracy of business hours, location, or ratings</li>
              <li>Quality of food or service at listed restaurants</li>
              <li>Changes in restaurant availability or pricing</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Intellectual Property</h2>
            <p className="text-muted-foreground mb-4">
              The Service, including its design, features, and content (excluding user-generated
              content and AI-generated recipes), is owned by Dinner Decision Maker and protected
              by applicable intellectual property laws.
            </p>
            <p className="text-muted-foreground mb-4">
              You retain ownership of any content you submit (such as wheel preferences).
              AI-generated recipes are provided for your personal use.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Disclaimer of Warranties</h2>
            <p className="text-muted-foreground mb-4">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND,
              EXPRESS OR IMPLIED. WE DO NOT GUARANTEE THAT:
            </p>
            <ul className="list-disc pl-6 text-muted-foreground mb-4">
              <li>The Service will be uninterrupted or error-free</li>
              <li>Results will be accurate or reliable</li>
              <li>The Service will meet your specific requirements</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Limitation of Liability</h2>
            <p className="text-muted-foreground mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, DINNER DECISION MAKER SHALL NOT BE LIABLE
              FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES,
              INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR USE.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Termination</h2>
            <p className="text-muted-foreground mb-4">
              We reserve the right to suspend or terminate your access to the Service at any
              time, with or without cause, with or without notice. You may delete your account
              at any time through your dashboard.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Changes to Terms</h2>
            <p className="text-muted-foreground mb-4">
              We may modify these terms at any time. Continued use of the Service after changes
              constitutes acceptance of the new terms. Material changes will be notified through
              the Service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Governing Law</h2>
            <p className="text-muted-foreground mb-4">
              These terms are governed by and construed in accordance with the laws of the
              United States, without regard to its conflict of law provisions.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-foreground mb-4">Contact</h2>
            <p className="text-muted-foreground mb-4">
              For questions about these Terms of Service, contact us at:
              diane@mageeyemedia.com
            </p>
          </section>
        </div>
      </PageShell>
    </div>
  )
}
