import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const baseRecipes: Record<string, RecipeIdea[]> = {
  rice: [
    {
      title: 'Vegetable Biryani',
      description: 'Fragrant Indian-spiced basmati rice layered with mixed vegetables, caramelized onions, and fresh herbs. Aromatic, colorful, and deeply satisfying.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      cuisine: 'Indian',
      ingredients: [
        '1.5 cups basmati rice, soaked 30 minutes and drained',
        '2 cups mixed vegetables (cauliflower, carrots, green beans, peas)',
        '2 large onions, thinly sliced',
        '1 cup plain yogurt',
        '3 tablespoons ghee or vegetable oil',
        '4 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '2 teaspoons biryani masala or garam masala',
        '1/2 teaspoon turmeric',
        '1/4 teaspoon cayenne pepper',
        '2.5 cups vegetable broth',
        'Pinch of saffron soaked in 2 tablespoons warm milk',
        '1/4 cup fresh cilantro, chopped',
        '1/4 cup fresh mint leaves, chopped',
        '2 tablespoons golden raisins',
        '2 tablespoons cashews, toasted',
      ],
      instructions: [
        'Preheat oven to 350°F. Heat ghee in a large oven-safe pot over medium heat. Fry onions until deep golden brown and crispy, about 12-15 minutes. Remove half for garnish.',
        'Add garlic, ginger, biryani masala, turmeric, and cayenne to the remaining onions. Cook 1 minute until fragrant.',
        'Add mixed vegetables and cook 3-4 minutes. Stir in yogurt and cook 2 minutes.',
        'Spread the drained rice evenly over the vegetables. Pour vegetable broth over the top without stirring. Drizzle saffron milk on top.',
        'Sprinkle with half the cilantro and mint. Cover tightly with foil and a lid. Bake 25-30 minutes until rice is tender and liquid is absorbed.',
        'Let rest covered for 5 minutes. Gently fluff with a fork, mixing layers slightly. Top with reserved fried onions, remaining herbs, raisins, and cashews.',
        'Serve with raita (yogurt with cucumber) on the side.',
      ],
      nutrition: { calories: 440, protein: 12, carbs: 68, fat: 14 },
    },
    {
      title: 'Shrimp Fried Rice',
      description: 'Wok-fired rice with plump shrimp, scrambled eggs, and crispy vegetables in a savory soy-sesame sauce. Better than takeout in 20 minutes.',
      timeMinutes: 20,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Chinese',
      ingredients: [
        '1 pound large shrimp, peeled and deveined',
        '4 cups cooked jasmine rice (day-old works best)',
        '3 large eggs, beaten',
        '1 cup frozen peas',
        '2 carrots, finely diced',
        '4 green onions, sliced (white and green parts separated)',
        '3 tablespoons soy sauce',
        '1 tablespoon oyster sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '3 cloves garlic, minced',
        '1 teaspoon fresh ginger, grated',
        'White pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon vegetable oil in a large wok over high heat until smoking. Add shrimp in a single layer and cook 1-2 minutes per side until pink and curled. Remove and set aside.',
        'Add remaining oil. Toss in carrots and green onion whites, stir-frying 2 minutes. Add peas and cook 1 minute.',
        'Push vegetables to the side. Pour beaten eggs into the wok, scramble until just set, then break into small pieces and mix with vegetables.',
        'Add rice, pressing it flat against the wok to get a slight char. Stir-fry 2-3 minutes, breaking up any clumps.',
        'Add garlic and ginger, stir 30 seconds until fragrant. Pour soy sauce, oyster sauce, and sesame oil over the rice and toss vigorously.',
        'Return shrimp to the wok. Toss everything together for 30 seconds. Season with white pepper.',
        'Garnish with green onion tops. Serve immediately.',
      ],
      nutrition: { calories: 410, protein: 30, carbs: 48, fat: 10 },
    },
    {
      title: 'Coconut Curry Rice with Chickpeas',
      description: 'Creamy coconut rice simmered with chickpeas, spinach, and warming curry spices. A fragrant one-pot vegetarian dinner bursting with flavor.',
      timeMinutes: 35,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '1.5 cups jasmine rice',
        '1 can (14 oz) coconut milk',
        '1 cup vegetable broth',
        '1 can (15 oz) chickpeas, drained and rinsed',
        '3 cups fresh baby spinach',
        '1 red bell pepper, diced',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '2 tablespoons Thai red curry paste',
        '1 tablespoon coconut oil',
        '1 tablespoon lime juice',
        '1 tablespoon soy sauce',
        'Fresh cilantro and lime wedges for serving',
      ],
      instructions: [
        'Heat coconut oil in a large deep skillet or pot over medium heat. Sauté onion and bell pepper until softened, about 4 minutes. Add garlic and ginger, cook 1 minute.',
        'Stir in curry paste and cook 30 seconds until fragrant. Add rice and stir to coat in the curry mixture for 1 minute.',
        'Pour in coconut milk and vegetable broth. Add chickpeas and soy sauce. Stir to combine and bring to a boil.',
        'Reduce heat to low, cover tightly, and simmer 18-20 minutes until rice is tender and liquid is absorbed.',
        'Remove lid and fold in fresh spinach. Cover again for 2 minutes until spinach wilts.',
        'Stir in lime juice. Fluff gently with a fork.',
        'Serve in bowls garnished with fresh cilantro and lime wedges.',
      ],
      nutrition: { calories: 490, protein: 14, carbs: 66, fat: 20 },
    },
    {
      title: 'Korean Beef Rice Bowls',
      description: 'Sweet and savory ground beef with ginger, garlic, and gochujang over steamed rice. Quick, flavorful, and addictive.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Korean',
      ingredients: [
        '1 pound ground beef',
        '3 cups cooked short-grain or jasmine rice',
        '1/4 cup soy sauce',
        '2 tablespoons brown sugar',
        '1 tablespoon sesame oil',
        '1 tablespoon gochujang (or sriracha)',
        '3 cloves garlic, minced',
        '1 teaspoon fresh ginger, grated',
        '2 green onions, sliced',
        '1 tablespoon vegetable oil',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'Heat vegetable oil in a large skillet over medium-high heat. Add ground beef and cook, breaking up with a spoon, until browned and no pink remains, about 5-6 minutes.',
        'Drain excess grease if needed. Add garlic and ginger, stirring for 30 seconds.',
        'In a small bowl, whisk together soy sauce, brown sugar, sesame oil, and gochujang. Pour over the beef and stir to coat. Simmer 2-3 minutes until glossy.',
        'Divide steamed rice among 4 bowls. Top with the Korean beef and sauce.',
        'Garnish with sliced green onions and sesame seeds. Serve immediately.',
      ],
      nutrition: { calories: 480, protein: 28, carbs: 52, fat: 18 },
    },
    {
      title: 'Mushroom Risotto',
      description: 'Creamy Italian risotto with earthy mushrooms and parmesan. Elegant comfort food that rewards patient stirring.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1.5 cups Arborio rice',
        '8 oz cremini mushrooms, sliced',
        '4 cups chicken or vegetable broth, kept warm',
        '1/2 cup dry white wine',
        '1 small onion, finely diced',
        '3 cloves garlic, minced',
        '1/2 cup grated parmesan cheese',
        '3 tablespoons butter',
        '2 tablespoons olive oil',
        '2 tablespoons fresh parsley, chopped',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon olive oil in a large skillet over medium-high heat. Sauté mushrooms until golden and their liquid has evaporated, about 6-7 minutes. Season with salt. Remove and set aside.',
        'Melt 1 tablespoon butter with remaining olive oil in the same pan. Add onion and cook until translucent, about 3 minutes. Add garlic, cook 30 seconds.',
        'Add Arborio rice and stir to toast for 1 minute. Pour in white wine and stir until absorbed.',
        'Add warm broth 1 cup at a time, stirring frequently and waiting for each addition to be absorbed before adding more. This takes about 25-28 minutes.',
        'When rice is creamy and al dente, stir in mushrooms, remaining butter, and parmesan. Remove from heat.',
        'Season with salt and pepper. Garnish with parsley. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 14, carbs: 58, fat: 14 },
    },
    {
      title: 'Chicken Rice Soup',
      description: 'Hearty, comforting soup with tender chicken, rice, carrots, and celery. Perfect for cold nights or when you need a boost.',
      timeMinutes: 40,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 large chicken breasts, diced',
        '1/2 cup long-grain white rice',
        '6 cups chicken broth',
        '2 carrots, diced',
        '2 stalks celery, diced',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '1 bay leaf',
        '2 tablespoons olive oil',
        'Salt and pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium heat. Add diced chicken and cook until no longer pink, about 5 minutes. Remove and set aside.',
        'Add onion, carrots, and celery to the pot. Sauté until vegetables soften, about 5 minutes. Add garlic and cook 30 seconds.',
        'Pour in chicken broth. Add rice, thyme, bay leaf, salt, and pepper. Bring to a boil.',
        'Reduce heat to medium-low. Add chicken back. Simmer uncovered for 20-25 minutes until rice is tender.',
        'Remove bay leaf. Taste and adjust seasoning. Ladle into bowls and garnish with fresh parsley.',
      ],
      nutrition: { calories: 240, protein: 24, carbs: 22, fat: 6 },
    },
    {
      title: 'Stuffed Bell Peppers with Rice',
      description: 'Colorful bell peppers stuffed with seasoned rice, ground beef, and cheese. A hearty baked dinner the whole family will love.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 35,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '4 large bell peppers (any color), tops cut off and seeded',
        '1 pound ground beef',
        '1.5 cups cooked rice',
        '1 can (15 oz) tomato sauce',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried oregano',
        '1 cup shredded mozzarella cheese',
        '2 tablespoons olive oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Place bell peppers upright in a 9x13 baking dish. If needed, trim bottoms slightly so they stand.',
        'Heat olive oil in a large skillet. Brown ground beef with onion until no pink remains, about 6 minutes. Add garlic and oregano, cook 1 minute.',
        'Stir in cooked rice and 1/2 cup tomato sauce. Season with salt and pepper. Remove from heat.',
        'Stuff each pepper with the beef-rice mixture, packing firmly. Pour remaining tomato sauce around the peppers in the dish.',
        'Cover with foil. Bake 30 minutes. Remove foil, top with cheese, and bake 5 more minutes until melted.',
        'Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 520, protein: 36, carbs: 42, fat: 22 },
    },
    {
      title: 'Coconut Rice with Shrimp',
      description: 'Creamy Thai-style coconut rice topped with garlic butter shrimp. Rich, fragrant, and restaurant-worthy.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '1 pound large shrimp, peeled and deveined',
        '1.5 cups jasmine rice',
        '1 can (14 oz) coconut milk',
        '1.5 cups water',
        '3 cloves garlic, minced',
        '2 tablespoons butter',
        '2 tablespoons lime juice',
        '2 tablespoons fresh cilantro, chopped',
        '1/2 teaspoon salt',
      ],
      instructions: [
        'Rinse rice until water runs clear. Combine rice, coconut milk, water, and salt in a medium pot. Bring to a boil.',
        'Reduce heat to low, cover, and simmer 18 minutes until rice is tender and liquid is absorbed. Fluff with a fork and keep warm.',
        'Melt butter in a large skillet over medium-high heat. Add half the garlic and cook 30 seconds until fragrant.',
        'Add shrimp in a single layer. Cook 2 minutes per side until pink and opaque. Add remaining garlic, lime juice, and half the cilantro. Toss to coat.',
        'Serve shrimp over the coconut rice. Garnish with remaining cilantro.',
      ],
      nutrition: { calories: 480, protein: 32, carbs: 52, fat: 18 },
    },
  ],

  pasta: [
    {
      title: 'Spaghetti Aglio e Olio',
      description: 'Classic Italian pasta with garlic, olive oil, and red pepper flakes. Simple, elegant, and ready in 15 minutes.',
      timeMinutes: 15,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 pound spaghetti',
        '6 cloves garlic, thinly sliced',
        '1/2 cup olive oil',
        '1/2 teaspoon red pepper flakes',
        '1/4 cup fresh parsley, chopped',
        '1/2 cup grated parmesan cheese',
        'Salt for pasta water',
      ],
      instructions: [
        'Bring a large pot of salted water to a boil. Cook spaghetti according to package until al dente. Reserve 1 cup pasta water before draining.',
        'While pasta cooks, heat olive oil in a large skillet over medium-low heat. Add garlic and red pepper flakes. Cook until garlic is golden, about 3-4 minutes. Do not burn.',
        'Add drained pasta to the skillet with 1/2 cup reserved pasta water. Toss vigorously to emulsify the sauce.',
        'Remove from heat. Stir in parsley and half the parmesan. Add more pasta water if needed for a silky consistency.',
        'Serve immediately with remaining parmesan.',
      ],
      nutrition: { calories: 520, protein: 16, carbs: 58, fat: 26 },
    },
    {
      title: 'Creamy Baked Ziti',
      description: 'Penne pasta baked with marinara, ricotta, and molten mozzarella. Ultimate comfort food that feeds a crowd.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1 pound ziti or penne pasta',
        '2 cups marinara sauce',
        '2 cups shredded mozzarella cheese',
        '1 cup ricotta cheese',
        '1/2 cup grated parmesan cheese',
        '1 egg, beaten',
        '2 cloves garlic, minced',
        '1 teaspoon dried basil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Cook pasta in salted boiling water until al dente. Drain and set aside.',
        'In a bowl, mix ricotta, egg, half the parmesan, garlic, basil, salt, and pepper until smooth.',
        'Spread 1/2 cup marinara in the bottom of a 9x13 baking dish. Add half the pasta, dot with ricotta mixture, and spread half the remaining marinara. Sprinkle with 1 cup mozzarella.',
        'Layer remaining pasta, marinara, and mozzarella. Top with remaining parmesan.',
        'Cover with foil and bake 25 minutes. Uncover and bake 10 more minutes until bubbly and golden.',
      ],
      nutrition: { calories: 480, protein: 24, carbs: 58, fat: 18 },
    },
    {
      title: 'Classic Mac and Cheese',
      description: 'Creamy stovetop mac and cheese with a rich cheddar sauce. Childhood nostalgia in a bowl.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '12 oz elbow macaroni',
        '3 tablespoons butter',
        '3 tablespoons all-purpose flour',
        '2.5 cups whole milk',
        '2 cups shredded sharp cheddar cheese',
        '1/2 teaspoon mustard powder',
        '1/4 teaspoon paprika',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cook macaroni in salted boiling water until al dente. Drain and set aside.',
        'Melt butter in a large pot over medium heat. Whisk in flour and cook 1 minute until golden.',
        'Gradually whisk in milk. Cook, stirring constantly, until sauce thickens, about 5-6 minutes.',
        'Remove from heat. Stir in cheese until melted and smooth. Add mustard, paprika, salt, and pepper.',
        'Add cooked pasta and toss to coat. Serve immediately.',
      ],
      nutrition: { calories: 540, protein: 24, carbs: 52, fat: 28 },
    },
    {
      title: 'Pad Thai-Style Noodles',
      description: 'Stir-fried rice noodles with shrimp, tamarind, and peanuts. Sweet, tangy, and satisfying.',
      timeMinutes: 30,
      method: 'stir-fry',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '8 oz rice noodles',
        '1/2 pound shrimp, peeled and deveined',
        '2 eggs, beaten',
        '2 cups bean sprouts',
        '3 tablespoons tamarind paste',
        '3 tablespoons fish sauce',
        '2 tablespoons lime juice',
        '2 tablespoons brown sugar',
        '2 tablespoons vegetable oil',
        '3 cloves garlic, minced',
        '1/4 cup crushed peanuts',
        '2 green onions, sliced',
        'Lime wedges for serving',
      ],
      instructions: [
        'Soak rice noodles in warm water for 8-10 minutes until pliable. Drain and set aside.',
        'Whisk together tamarind paste, fish sauce, lime juice, and brown sugar in a small bowl.',
        'Heat 1 tablespoon oil in a large wok over high heat. Add shrimp and stir-fry until pink, about 2 minutes. Remove and set aside.',
        'Add remaining oil. Push noodles to one side, add beaten eggs and scramble. Toss with noodles.',
        'Add garlic, sauce, shrimp, and half the bean sprouts. Toss vigorously for 2 minutes.',
        'Serve topped with remaining bean sprouts, peanuts, and green onions. Serve with lime wedges.',
      ],
      nutrition: { calories: 420, protein: 24, carbs: 52, fat: 12 },
    },
    {
      title: 'Cacio e Pepe',
      description: 'The iconic Roman pasta with just three ingredients: pasta, pecorino cheese, and black pepper. Deceptively simple, incredibly addictive.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 pound tonnarelli, spaghetti, or bucatini',
        '2 cups finely grated Pecorino Romano cheese',
        '2 tablespoons whole black peppercorns, coarsely cracked',
        '1 tablespoon kosher salt for pasta water',
        '2 tablespoons extra virgin olive oil',
      ],
      instructions: [
        'Bring a large pot of salted water to a boil. Cook pasta until 2 minutes short of al dente. Reserve 2 cups starchy pasta water before draining.',
        'While pasta cooks, toast cracked black pepper in a large dry skillet over medium heat for 1-2 minutes until fragrant. Add olive oil and 1 cup pasta water. Simmer until reduced by half.',
        'Add the underdone pasta to the skillet with another 1/2 cup pasta water. Toss and cook 2 minutes until pasta is al dente, adding water as needed.',
        'Remove skillet from heat. Let cool 1 minute. Add pecorino in three batches, tossing vigorously after each addition and splashing in pasta water to create a creamy, emulsified sauce.',
        'The sauce should be glossy and coat each strand. If too thick, add more pasta water a tablespoon at a time.',
        'Serve immediately on warm plates with an extra shower of pecorino and freshly cracked pepper.',
      ],
      nutrition: { calories: 520, protein: 24, carbs: 56, fat: 22 },
    },
    {
      title: 'Pasta Primavera',
      description: 'Fresh vegetables and pasta in a light garlic butter sauce. Celebrate spring produce in one colorful dish.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '12 oz penne or farfalle',
        '2 cups broccoli florets',
        '1 yellow squash, sliced',
        '1 cup cherry tomatoes, halved',
        '3 cloves garlic, minced',
        '4 tablespoons butter',
        '1/4 cup pasta water',
        '1/2 cup grated parmesan',
        '2 tablespoons fresh basil, torn',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cook pasta in salted boiling water until al dente. Add broccoli for the last 2 minutes. Reserve 1/2 cup pasta water. Drain.',
        'Melt butter in a large skillet over medium heat. Add garlic and cook 30 seconds.',
        'Add squash and tomatoes. Sauté 3-4 minutes until tender. Add pasta, broccoli, and pasta water. Toss to combine.',
        'Remove from heat. Stir in parmesan and basil. Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 58, fat: 14 },
    },
    {
      title: 'Tortellini Soup',
      description: 'Hearty soup with cheese tortellini, spinach, and Italian sausage in a rich tomato broth. One-bowl comfort.',
      timeMinutes: 30,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '20 oz cheese tortellini (fresh or frozen)',
        '1 pound Italian sausage, casings removed',
        '6 cups chicken broth',
        '1 can (14.5 oz) diced tomatoes',
        '4 cups fresh spinach',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon dried basil',
        '1/2 cup heavy cream',
        '2 tablespoons olive oil',
        'Parmesan for serving',
      ],
      instructions: [
        'Heat olive oil in a large pot. Add sausage and cook, breaking up, until browned, about 5 minutes. Remove and set aside.',
        'Sauté onion until soft, about 3 minutes. Add garlic and basil, cook 30 seconds.',
        'Add broth and diced tomatoes. Bring to a boil. Add tortellini and cook according to package, about 5-7 minutes.',
        'Stir in spinach and sausage. Add cream and heat through. Do not boil.',
        'Ladle into bowls. Serve with grated parmesan.',
      ],
      nutrition: { calories: 480, protein: 24, carbs: 42, fat: 26 },
    },
    {
      title: 'One-Pot Creamy Tuscan Pasta',
      description: 'Sun-dried tomatoes, spinach, and garlic in a rich cream sauce—all cooked in one pot. Minimal cleanup, maximum flavor.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '12 oz penne or farfalle',
        '2 cups chicken broth',
        '1 cup heavy cream',
        '1/2 cup sun-dried tomatoes, chopped',
        '2 cups fresh spinach',
        '3 cloves garlic, minced',
        '1/2 cup grated parmesan',
        '2 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Combine pasta, broth, cream, sun-dried tomatoes, garlic, Italian seasoning, salt, and pepper in a large pot or deep skillet.',
        'Bring to a boil over medium-high heat. Reduce to a simmer and cook, stirring occasionally, for 12-14 minutes until pasta is al dente and sauce has thickened.',
        'Stir in spinach until wilted. Remove from heat and stir in parmesan.',
        'Let rest 2 minutes. Serve with extra parmesan and black pepper.',
      ],
      nutrition: { calories: 520, protein: 18, carbs: 58, fat: 24 },
    },
  ],

  potatoes: [
    {
      title: 'Loaded Baked Potatoes',
      description: 'Crispy-skinned baked potatoes piled with bacon, cheese, sour cream, and chives. A hearty meal in itself.',
      timeMinutes: 65,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 55,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 large russet potatoes',
        '6 slices bacon, cooked and crumbled',
        '1 cup shredded cheddar cheese',
        '1/2 cup sour cream',
        '1/4 cup sliced green onions',
        '2 tablespoons butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. Scrub potatoes and prick all over with a fork. Rub with oil and salt.',
        'Bake directly on the oven rack for 50-60 minutes until tender when pierced with a fork.',
        'Let potatoes cool 5 minutes. Slice open and fluff the insides with a fork.',
        'Add butter, then top with cheese, bacon, sour cream, and green onions. Season with salt and pepper.',
        'Serve immediately.',
      ],
      nutrition: { calories: 520, protein: 18, carbs: 52, fat: 28 },
    },
    {
      title: 'Hasselback Potatoes with Garlic Butter',
      description: 'Elegantly sliced potatoes that fan open as they bake, creating crispy edges and a creamy center, drizzled with garlic herb butter and cheese.',
      timeMinutes: 65,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 50,
      servings: 4,
      cuisine: 'Swedish',
      ingredients: [
        '4 large russet potatoes',
        '4 tablespoons butter, melted',
        '3 tablespoons olive oil',
        '4 cloves garlic, minced',
        '1 cup shredded gruyere or cheddar cheese',
        '4 slices bacon, cooked and crumbled',
        '2 tablespoons fresh chives, chopped',
        '1 tablespoon fresh thyme leaves',
        '1/2 teaspoon smoked paprika',
        '1 teaspoon salt',
        '1/2 teaspoon black pepper',
        'Sour cream for serving',
      ],
      instructions: [
        'Preheat oven to 425°F. Scrub potatoes clean. Place each potato between two chopsticks or wooden spoon handles and slice crosswise at 1/8-inch intervals, cutting down but not all the way through.',
        'Mix melted butter with olive oil, garlic, thyme, paprika, salt, and pepper. Brush generously over each potato, working the mixture between the slices.',
        'Place potatoes on a baking sheet. Bake 30 minutes, brushing with more butter mixture halfway through.',
        'Remove from oven. Tuck shredded cheese between the slices and sprinkle more on top. Return to oven for 15-20 minutes until potatoes are tender and cheese is melted and golden.',
        'Sprinkle with crumbled bacon and chives. Let rest 5 minutes.',
        'Serve with sour cream on the side.',
      ],
      nutrition: { calories: 460, protein: 16, carbs: 44, fat: 26 },
    },
    {
      title: 'Potato Leek Soup',
      description: 'Creamy, velvety soup with potatoes, leeks, and a touch of cream. Elegant French comfort in a bowl.',
      timeMinutes: 40,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'French',
      ingredients: [
        '2 pounds potatoes, peeled and diced',
        '3 leeks (white and light green parts), sliced',
        '4 cups vegetable or chicken broth',
        '1/2 cup heavy cream',
        '3 tablespoons butter',
        '2 cloves garlic, minced',
        'Salt and white pepper to taste',
        'Chives for garnish',
      ],
      instructions: [
        'Melt butter in a large pot over medium heat. Add leeks and cook until softened, about 5 minutes. Add garlic, cook 30 seconds.',
        'Add potatoes and broth. Bring to a boil, then reduce heat and simmer 20 minutes until potatoes are tender.',
        'Using an immersion blender, purée until smooth. Or transfer to a blender in batches. Return to pot.',
        'Stir in cream. Season with salt and white pepper. Heat through without boiling.',
        'Ladle into bowls. Garnish with fresh chives.',
      ],
      nutrition: { calories: 320, protein: 6, carbs: 48, fat: 12 },
    },
    {
      title: 'Crispy Smashed Potatoes with Herbs',
      description: 'Baby potatoes boiled, smashed, and roasted until shatteringly crispy, then topped with garlic herb butter and parmesan. Addictive and elegant.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 pounds baby potatoes (yellow or red)',
        '4 tablespoons olive oil',
        '3 tablespoons butter, melted',
        '4 cloves garlic, minced',
        '1/3 cup grated parmesan cheese',
        '2 tablespoons fresh rosemary, chopped',
        '2 tablespoons fresh thyme leaves',
        '1 tablespoon fresh chives, chopped',
        '1 teaspoon flaky sea salt',
        '1/2 teaspoon black pepper',
        '1/2 teaspoon red pepper flakes',
        'Sour cream or aioli for serving',
      ],
      instructions: [
        'Place potatoes in a large pot, cover with cold salted water, and bring to a boil. Cook 15-18 minutes until fork-tender. Drain well.',
        'Preheat oven to 450°F. Drizzle a large baking sheet with 2 tablespoons olive oil.',
        'Arrange potatoes on the sheet. Using the bottom of a glass or a fork, press each potato until flattened to about 1/2-inch thick.',
        'Drizzle remaining olive oil over the smashed potatoes. Season generously with salt, pepper, and red pepper flakes.',
        'Roast 20-25 minutes until edges are deeply golden and crispy, flipping once halfway through.',
        'Mix melted butter with garlic, rosemary, and thyme. Drizzle herb butter over hot potatoes. Sprinkle with parmesan and chives.',
        'Serve immediately with sour cream or aioli on the side.',
      ],
      nutrition: { calories: 340, protein: 8, carbs: 38, fat: 18 },
    },
    {
      title: 'Scalloped Potatoes with Ham',
      description: 'Layered potatoes in a creamy cheese sauce with diced ham. Baked until golden and bubbling. Pure comfort.',
      timeMinutes: 75,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 55,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2.5 pounds russet potatoes, thinly sliced',
        '2 cups diced ham',
        '2 cups heavy cream',
        '1 cup shredded cheddar cheese',
        '3 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '2 tablespoons butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Butter a 9x13 baking dish.',
        'Arrange a layer of potato slices in the dish. Sprinkle with some ham, cheese, garlic, thyme, salt, and pepper. Repeat layers, ending with potatoes.',
        'Pour cream over the top. Dot with butter. Cover tightly with foil.',
        'Bake 45 minutes. Uncover and bake 10-15 more minutes until golden and potatoes are tender.',
        'Let rest 10 minutes before serving.',
      ],
      nutrition: { calories: 520, protein: 24, carbs: 42, fat: 32 },
    },
    {
      title: 'Gnocchi with Brown Butter Sage',
      description: 'Pillowy potato gnocchi pan-fried until golden, then tossed in brown butter and crisp sage. Restaurant-quality in minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 pound potato gnocchi (fresh or shelf-stable)',
        '6 tablespoons butter',
        '12 fresh sage leaves',
        '1/2 cup grated parmesan cheese',
        '1/4 teaspoon nutmeg',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Bring a large pot of salted water to a boil. Cook gnocchi until they float, about 2-3 minutes. Drain, reserving 1/4 cup pasta water.',
        'Melt butter in a large skillet over medium heat. Continue cooking until butter foams, turns golden, and smells nutty, about 4-5 minutes.',
        'Add sage leaves and fry until crisp, about 1 minute. Add gnocchi and toss to coat.',
        'Remove from heat. Stir in parmesan, nutmeg, salt, and pepper. Add pasta water if needed for a silky texture.',
        'Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 12, carbs: 52, fat: 20 },
    },
    {
      title: 'Crispy Potato Skins',
      description: 'Hollowed potato halves loaded with cheese, bacon, and green onions. Perfect as a meal or shareable appetizer.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 45,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 large russet potatoes',
        '6 slices bacon, cooked and crumbled',
        '1.5 cups shredded cheddar cheese',
        '1/2 cup sour cream',
        '1/4 cup sliced green onions',
        '2 tablespoons olive oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. Bake potatoes 45-50 minutes until tender. Let cool 10 minutes.',
        'Cut potatoes in half lengthwise. Scoop out flesh, leaving a 1/4-inch shell. Save flesh for another use.',
        'Brush potato skins with olive oil inside and out. Season with salt. Bake 10 minutes until crisp.',
        'Fill each skin with cheese and bacon. Bake 5 more minutes until cheese melts.',
        'Top with sour cream and green onions. Serve hot.',
      ],
      nutrition: { calories: 480, protein: 20, carbs: 42, fat: 28 },
    },
    {
      title: 'Spanish Potato Tortilla',
      description: 'Classic Spanish omelette with thinly sliced potatoes and onions. Satisfying any time of day.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Spanish',
      ingredients: [
        '1.5 pounds potatoes, thinly sliced',
        '1 large onion, thinly sliced',
        '6 large eggs',
        '1/2 cup olive oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a 10-inch nonstick skillet over medium heat. Add potatoes and onion. Cook, turning occasionally, until tender but not brown, about 15-18 minutes. Drain, reserving 2 tablespoons oil.',
        'Beat eggs in a large bowl with salt and pepper. Add the potato-onion mixture and stir to coat.',
        'Heat reserved oil in the skillet over medium heat. Pour in the egg-potato mixture. Cook until edges set, about 5 minutes.',
        'Place a large plate over the skillet. Invert to flip the tortilla onto the plate. Slide back into the skillet to cook the other side 5 more minutes.',
        'Slide onto a serving plate. Cut into wedges. Serve warm or at room temperature.',
      ],
      nutrition: { calories: 380, protein: 14, carbs: 36, fat: 22 },
    },
  ],

  tortillas: [
    {
      title: 'Shrimp Tacos with Mango Salsa',
      description: 'Spiced shrimp nestled in warm tortillas and topped with bright mango-avocado salsa and creamy chipotle drizzle. Fresh, vibrant, and tropical.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound large shrimp, peeled and deveined',
        '8 small flour or corn tortillas',
        '1 ripe mango, diced',
        '1 avocado, diced',
        '1/4 cup red onion, finely diced',
        '1 jalapeño, seeded and minced',
        '3 tablespoons fresh cilantro, chopped',
        '2 tablespoons lime juice',
        '1 teaspoon chili powder',
        '1/2 teaspoon smoked paprika',
        '1/2 teaspoon cumin',
        '2 tablespoons olive oil',
        '1/4 cup sour cream',
        '1 teaspoon chipotle in adobo sauce',
        'Salt to taste',
      ],
      instructions: [
        'Make the mango salsa: combine diced mango, avocado, red onion, jalapeño, 2 tablespoons cilantro, and 1 tablespoon lime juice. Season with salt and set aside.',
        'Mix sour cream with chipotle and remaining lime juice for the drizzle. Set aside.',
        'Pat shrimp dry. Toss with chili powder, smoked paprika, cumin, and salt.',
        'Heat olive oil in a large skillet over medium-high heat. Cook shrimp 2 minutes per side until pink and slightly charred. Remove from heat.',
        'Warm tortillas in a dry skillet or over a flame until pliable and lightly charred.',
        'Assemble tacos: divide shrimp among tortillas, top with mango salsa, chipotle drizzle, and remaining cilantro.',
        'Serve immediately with extra lime wedges.',
      ],
      nutrition: { calories: 390, protein: 28, carbs: 42, fat: 12 },
    },
    {
      title: 'Sweet Potato and Black Bean Wraps',
      description: 'Roasted sweet potato, black beans, and avocado crema rolled in warm flour tortillas. Hearty, healthy, and packed with Tex-Mex flavor.',
      timeMinutes: 35,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '2 medium sweet potatoes, peeled and diced into 1/2-inch cubes',
        '4 large flour tortillas',
        '1 can (15 oz) black beans, drained and rinsed',
        '1 cup cooked brown rice',
        '1 avocado',
        '1/4 cup sour cream',
        '1 tablespoon lime juice',
        '1 teaspoon chili powder',
        '1 teaspoon cumin',
        '1/2 teaspoon smoked paprika',
        '2 tablespoons olive oil',
        '1/2 cup shredded Monterey Jack cheese',
        '2 tablespoons fresh cilantro, chopped',
        'Salt and pepper to taste',
        'Hot sauce for serving',
      ],
      instructions: [
        'Preheat oven to 425°F. Toss diced sweet potatoes with olive oil, chili powder, cumin, smoked paprika, salt, and pepper. Spread on a baking sheet.',
        'Roast 18-20 minutes, flipping halfway, until tender and caramelized at the edges.',
        'While potatoes roast, warm black beans in a small pot with a splash of water. Mash avocado with sour cream, lime juice, and a pinch of salt for the crema.',
        'Warm tortillas in a dry skillet or microwave until pliable.',
        'Spread avocado crema down the center of each tortilla. Layer with brown rice, roasted sweet potato, black beans, and cheese.',
        'Fold in the sides and roll tightly. Toast seam-side down in a skillet 1-2 minutes per side until golden.',
        'Slice in half. Garnish with cilantro and serve with hot sauce.',
      ],
      nutrition: { calories: 540, protein: 18, carbs: 72, fat: 20 },
    },
    {
      title: 'Cheesy Veggie Quesadillas',
      description: 'Crispy tortillas stuffed with melted cheese, black beans, corn, and peppers. Quick vegetarian dinner.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '8 flour tortillas',
        '2 cups shredded Monterey Jack cheese',
        '1 can (15 oz) black beans, drained and rinsed',
        '1 cup corn kernels',
        '1 red bell pepper, diced',
        '1/2 teaspoon cumin',
        '2 tablespoons butter',
        'Salsa and sour cream for serving',
      ],
      instructions: [
        'In a bowl, mix black beans, corn, bell pepper, and cumin.',
        'Heat a large skillet over medium heat. Place one tortilla in the skillet. Sprinkle with 1/4 cup cheese, then bean-veggie mix, then more cheese. Top with second tortilla.',
        'Cook 2-3 minutes until golden. Flip carefully and cook 2 more minutes. Repeat for remaining quesadillas.',
        'Cut into wedges. Serve with salsa and sour cream.',
      ],
      nutrition: { calories: 520, protein: 24, carbs: 52, fat: 24 },
    },
    {
      title: 'Crispy Tortilla Soup Bowls',
      description: 'A rich and smoky tomato-chicken broth ladled over crispy tortilla strips with avocado, cheese, and lime. Warm, crunchy, and deeply comforting.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '6 corn tortillas, cut into 1/2-inch strips',
        '2 large chicken breasts',
        '1 can (14.5 oz) fire-roasted diced tomatoes',
        '6 cups chicken broth',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '1 jalapeño, seeded and minced',
        '1 teaspoon cumin',
        '1 teaspoon chili powder',
        '1/2 teaspoon smoked paprika',
        '2 tablespoons vegetable oil',
        '1 avocado, diced',
        '1/2 cup shredded Monterey Jack cheese',
        '1/4 cup fresh cilantro, chopped',
        '1 lime, cut into wedges',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon oil in a large pot over medium heat. Sauté onion until softened, about 3 minutes. Add garlic, jalapeño, cumin, chili powder, and smoked paprika. Cook 1 minute.',
        'Add fire-roasted tomatoes and chicken broth. Bring to a boil. Add whole chicken breasts, reduce heat, and simmer 15-18 minutes until chicken is cooked through.',
        'Remove chicken, shred with two forks, and return to the pot. Season soup with salt and pepper.',
        'While soup simmers, heat remaining oil in a skillet over medium-high heat. Fry tortilla strips in batches until golden and crispy, about 2-3 minutes. Drain on paper towels and season with salt.',
        'Ladle soup into bowls. Top generously with crispy tortilla strips, diced avocado, cheese, and cilantro.',
        'Serve with lime wedges for squeezing.',
      ],
      nutrition: { calories: 380, protein: 32, carbs: 28, fat: 16 },
    },
    {
      title: 'Black Bean Enchiladas with Green Sauce',
      description: 'Hearty black bean and corn enchiladas smothered in tangy salsa verde and melted cheese. A satisfying vegetarian take on a Mexican classic.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '8 flour tortillas',
        '2 cans (15 oz each) black beans, drained and rinsed',
        '1 cup corn kernels (fresh or frozen)',
        '2 cups salsa verde (green sauce)',
        '2 cups shredded Monterey Jack cheese',
        '1/2 cup ricotta cheese',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon cumin',
        '1/2 teaspoon chili powder',
        '2 tablespoons olive oil',
        '1/4 cup fresh cilantro, chopped',
        '1/2 cup sour cream for serving',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Heat olive oil in a skillet over medium heat. Sauté onion until softened, about 3 minutes. Add garlic, cumin, and chili powder. Cook 1 minute.',
        'Add black beans and corn. Cook 3-4 minutes until heated through. Lightly mash about a third of the beans for texture. Season with salt and pepper. Remove from heat.',
        'Stir ricotta and 1 cup Monterey Jack into the bean mixture.',
        'Spread 1/2 cup salsa verde in the bottom of a 9x13 baking dish. Fill each tortilla with the bean mixture, roll tightly, and place seam-side down.',
        'Pour remaining salsa verde over the enchiladas. Sprinkle with remaining cheese.',
        'Cover with foil. Bake 20 minutes. Remove foil and bake 10 more minutes until cheese is bubbly and golden.',
        'Top with fresh cilantro and sour cream. Serve hot.',
      ],
      nutrition: { calories: 440, protein: 22, carbs: 52, fat: 18 },
    },
    {
      title: 'Fish Tacos',
      description: 'Crispy battered fish with creamy slaw and lime crema in soft tortillas. Fresh and satisfying.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound white fish fillets (cod or tilapia)',
        '8 corn tortillas',
        '1 cup shredded cabbage',
        '1/2 cup sour cream',
        '2 tablespoons lime juice',
        '1/2 cup all-purpose flour',
        '1/2 teaspoon cumin',
        '1/4 cup vegetable oil',
        'Lime wedges and cilantro for serving',
      ],
      instructions: [
        'Mix sour cream and lime juice for crema. Toss cabbage with a pinch of salt.',
        'Cut fish into strips. Mix flour with cumin and salt. Dredge fish in flour.',
        'Heat oil in a skillet over medium-high heat. Fry fish 2-3 minutes per side until golden and cooked through.',
        'Warm tortillas. Top with fish, cabbage, crema, and cilantro. Serve with lime wedges.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 42, fat: 14 },
    },
    {
      title: 'Tortilla Pizza',
      description: 'Crispy tortilla base topped with marinara, cheese, and your favorite toppings. Ready in 10 minutes.',
      timeMinutes: 15,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 2,
      cuisine: 'American',
      ingredients: [
        '2 large flour tortillas',
        '1/2 cup marinara sauce',
        '1 cup shredded mozzarella',
        '1/4 cup pepperoni (optional)',
        'Dried oregano and red pepper flakes',
      ],
      instructions: [
        'Preheat oven to 425°F. Place tortillas on a baking sheet.',
        'Spread marinara on each tortilla. Top with cheese and pepperoni. Sprinkle with oregano.',
        'Bake 8-10 minutes until edges are crisp and cheese is melted.',
        'Slice and serve with red pepper flakes.',
      ],
      nutrition: { calories: 420, protein: 20, carbs: 36, fat: 24 },
    },
    {
      title: 'Chicken Tostadas',
      description: 'Crispy fried tortillas topped with refried beans, shredded chicken, lettuce, and crema. Layers of flavor.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '8 corn tortillas',
        '2 cups shredded cooked chicken',
        '1 can (16 oz) refried beans',
        '2 cups shredded lettuce',
        '1 cup diced tomatoes',
        '1/2 cup sour cream',
        '1/2 cup vegetable oil for frying',
        '1 lime, cut into wedges',
      ],
      instructions: [
        'Heat 1/2 inch oil in a skillet to 350°F. Fry tortillas one at a time until crisp, about 1 minute per side. Drain on paper towels.',
        'Warm refried beans in a small pot or microwave.',
        'Spread beans on each tostada. Top with chicken, lettuce, tomatoes, and a drizzle of sour cream.',
        'Serve with lime wedges.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 42, fat: 16 },
    },
  ],

  bread: [
    {
      title: 'French Toast Dinner',
      description: 'Thick slices of bread dipped in cinnamon egg batter and pan-fried until golden. Sweet or savory—your choice.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '8 thick slices brioche or Texas toast',
        '4 large eggs',
        '1/2 cup milk',
        '1 teaspoon vanilla extract',
        '1/2 teaspoon cinnamon',
        '2 tablespoons butter',
        'Maple syrup for serving',
      ],
      instructions: [
        'Whisk eggs, milk, vanilla, and cinnamon in a shallow dish.',
        'Heat butter in a large skillet over medium heat. Dip bread slices in the egg mixture, coating both sides.',
        'Fry 2-3 minutes per side until golden brown.',
        'Serve with maple syrup.',
      ],
      nutrition: { calories: 380, protein: 14, carbs: 42, fat: 18 },
    },
    {
      title: 'Grilled Cheese and Tomato Soup',
      description: 'Classic pairing of crisp, buttery grilled cheese sandwiches with creamy tomato soup. Ultimate comfort dinner.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '8 slices sourdough or white bread',
        '8 slices American or cheddar cheese',
        '4 tablespoons butter',
        '1 can (28 oz) crushed tomatoes',
        '1 cup vegetable broth',
        '1/2 cup heavy cream',
        '1 teaspoon dried basil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'For soup: combine tomatoes, broth, basil, salt, and pepper in a pot. Simmer 10 minutes. Stir in cream. Keep warm.',
        'For sandwiches: butter one side of each bread slice. Place cheese between unbuttered sides. Griddle butter-side down over medium heat 3-4 minutes per side until golden and cheese melts.',
        'Slice sandwiches and serve with hot soup.',
      ],
      nutrition: { calories: 520, protein: 20, carbs: 48, fat: 30 },
    },
    {
      title: 'Turkey and Avocado Panini',
      description: 'Pressed sandwich with turkey, avocado, tomato, and cheese. Crispy outside, melty inside.',
      timeMinutes: 15,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 2,
      cuisine: 'American',
      ingredients: [
        '4 slices ciabatta or sourdough',
        '8 oz sliced turkey',
        '1 avocado, sliced',
        '4 slices provolone cheese',
        '2 tomato slices',
        '2 tablespoons butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Layer turkey, cheese, avocado, and tomato on two bread slices. Top with remaining bread.',
        'Butter the outsides of each sandwich. Grill in a panini press or skillet with a heavy pan on top 3-4 minutes per side until golden and cheese melts.',
      ],
      nutrition: { calories: 580, protein: 42, carbs: 36, fat: 32 },
    },
    {
      title: 'Bread Bowl Clam Chowder',
      description: 'Creamy New England clam chowder served in a hollowed bread bowl. Dip the bowl when you finish the soup.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 round bread boules (about 6 inches)',
        '2 cans (6.5 oz each) minced clams',
        '4 cups heavy cream',
        '2 cups diced potatoes',
        '1/2 cup diced bacon',
        '1/2 cup diced onion',
        '2 tablespoons butter',
        '2 tablespoons flour',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cut top off each bread boule. Hollow out the center, leaving 1-inch walls. Save bread for croutons or discard.',
        'Cook bacon in a pot until crisp. Add onion, cook until soft. Add butter and flour, stir 1 minute.',
        'Add clam juice (from cans), cream, and potatoes. Simmer 15 minutes until potatoes are tender. Add clams, heat through. Season with salt and pepper.',
        'Ladle chowder into bread bowls. Serve immediately.',
      ],
      nutrition: { calories: 720, protein: 28, carbs: 52, fat: 48 },
    },
    {
      title: 'Bruschetta',
      description: 'Toasted bread topped with fresh tomato, basil, and garlic. Simple Italian appetizer that works as a light dinner.',
      timeMinutes: 20,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 5,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 loaf baguette, sliced 1/2 inch thick',
        '4 Roma tomatoes, diced',
        '1/4 cup fresh basil, torn',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 tablespoon balsamic vinegar',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Brush bread slices with olive oil. Toast under the broiler 1-2 minutes per side until golden.',
        'Mix tomatoes, basil, garlic, vinegar, salt, and pepper in a bowl.',
        'Top each toast with the tomato mixture. Drizzle with more olive oil. Serve immediately.',
      ],
      nutrition: { calories: 280, protein: 8, carbs: 42, fat: 10 },
    },
    {
      title: 'Savory Bread Pudding (Strata)',
      description: 'Layers of bread, cheese, and sausage baked in a custard. Perfect for brunch or a cozy dinner.',
      timeMinutes: 60,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 40,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '8 cups cubed day-old bread',
        '1 pound breakfast sausage, cooked and crumbled',
        '2 cups shredded cheddar cheese',
        '6 large eggs',
        '2 cups milk',
        '1 teaspoon dry mustard',
        '1/2 teaspoon salt',
        '1/4 teaspoon pepper',
      ],
      instructions: [
        'Preheat oven to 350°F. Grease a 9x13 baking dish.',
        'Layer half the bread, half the sausage, and half the cheese. Repeat.',
        'Whisk eggs, milk, mustard, salt, and pepper. Pour over the bread. Press down to soak.',
        'Bake 40-45 minutes until golden and set in the center.',
      ],
      nutrition: { calories: 520, protein: 28, carbs: 36, fat: 30 },
    },
    {
      title: 'Open-Faced Turkey Sandwich',
      description: 'Toasted bread topped with turkey, gravy, and mashed potatoes. Thanksgiving flavors any night.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 thick slices sourdough bread',
        '1 pound sliced roasted turkey',
        '2 cups mashed potatoes',
        '2 cups turkey or chicken gravy',
        '2 tablespoons butter',
      ],
      instructions: [
        'Toast bread until golden. Keep warm.',
        'Warm turkey and gravy in a saucepan. Reheat mashed potatoes.',
        'Place toast on plates. Top with turkey, a scoop of mashed potatoes, and gravy.',
      ],
      nutrition: { calories: 480, protein: 40, carbs: 44, fat: 16 },
    },
    {
      title: 'Crouton-Topped Chicken Casserole',
      description: 'Creamy chicken and vegetable casserole crowned with buttery garlic croutons. Comfort food at its finest.',
      timeMinutes: 50,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '3 cups cubed day-old bread',
        '2 cups shredded cooked chicken',
        '1 can (10.5 oz) cream of chicken soup',
        '1 cup sour cream',
        '2 cups frozen mixed vegetables',
        '1.5 cups shredded cheddar cheese',
        '3 tablespoons butter, melted',
        '1/2 teaspoon garlic powder',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Mix chicken, soup, sour cream, vegetables, 1 cup cheese, salt, and pepper. Spread in a 9x13 dish.',
        'Toss bread cubes with melted butter and garlic powder. Sprinkle over the casserole with remaining cheese.',
        'Bake 30 minutes until bubbly and croutons are golden.',
      ],
      nutrition: { calories: 420, protein: 24, carbs: 36, fat: 22 },
    },
  ],
}

export const baseFaqs: Record<string, FAQ[]> = {
  rice: [
    {
      question: 'What can I make with rice for dinner?',
      answer: 'Rice is incredibly versatile for dinner. Try fried rice, rice bowls (Korean beef, teriyaki chicken, burrito style), jambalaya, risotto, stuffed peppers, rice casseroles, or one-pan Spanish chicken rice. Most dishes come together in 25-45 minutes and work with various proteins and cuisines.',
    },
    {
      question: 'How long does it take to cook rice for a recipe?',
      answer: 'White rice typically takes 15-20 minutes on the stove. Brown rice takes 40-50 minutes. For faster prep, use a rice cooker or make a double batch and refrigerate—day-old rice is actually best for fried rice. Instant rice can cut cook time to about 5 minutes.',
    },
    {
      question: 'Can I use brown rice instead of white rice in recipes?',
      answer: 'Yes, but you will need to adjust liquid and cooking time. Brown rice usually needs 1.5-2 times the liquid and 30-45 minutes. For one-pan dishes, add extra broth and extend the simmer time. Pre-cooking brown rice separately and adding it at the end also works well.',
    },
    {
      question: 'What proteins go well with rice?',
      answer: 'Chicken, beef, shrimp, sausage, and tofu all pair excellently with rice. Asian-style dishes often use chicken or shrimp; Spanish and Cajun recipes favor chicken and sausage. Ground beef works great in bowls and stuffed peppers. Mix and match based on what you have.',
    },
    {
      question: 'How do I keep rice from getting mushy in one-pot recipes?',
      answer: 'Use the correct rice-to-liquid ratio (usually 1:1.5 or 1:2 for long-grain), avoid stirring once the rice is simmering, and let it rest covered for 5 minutes after cooking. Rinsing rice before cooking removes excess starch and helps prevent stickiness.',
    },
  ],

  pasta: [
    {
      question: 'What can I make with pasta for dinner?',
      answer: 'Pasta is a quick dinner staple. Try aglio e olio, carbonara, baked ziti, mac and cheese, primavera, or one-pot Tuscan pasta. Add protein like chicken, sausage, or shrimp. Most dishes take 15-35 minutes and work with pantry basics like olive oil, garlic, and cheese.',
    },
    {
      question: 'How do I make pasta sauce creamy without heavy cream?',
      answer: 'Reserve starchy pasta water and add it to your sauce—it helps emulsify and creates a silky texture. Blend cooked vegetables or use a bit of ricotta or Greek yogurt for body. A splash of the pasta cooking water with butter and parmesan makes a simple, creamy coating.',
    },
    {
      question: 'What is the best pasta shape for different sauces?',
      answer: 'Long shapes like spaghetti and linguine work with olive oil and thin sauces. Short shapes like penne and rigatoni hold chunky sauces and baked dishes. Shells and orecchiette catch small bits. Match the shape to the sauce—thicker sauces need shapes with nooks and ridges.',
    },
    {
      question: 'Can I make pasta ahead of time?',
      answer: 'Cook pasta fresh when possible for best texture. If you need to prep ahead, undercook slightly, toss with a little oil, and store separately from the sauce. Reheat by briefly dunking in boiling water or adding to the sauce with a splash of water. Baked pasta dishes reheat well.',
    },
    {
      question: 'How much pasta should I cook per person?',
      answer: 'A standard serving is about 2 ounces (56g) dry pasta per person, which yields roughly 1 cup cooked. For main dishes with plenty of sauce and protein, 2-3 ounces per person is typical. A pound of pasta usually serves 4-6 people depending on the recipe.',
    },
  ],

  potatoes: [
    {
      question: 'What can I make with potatoes for dinner?',
      answer: 'Potatoes work as a main or side. Try loaded baked potatoes, sheet pan sausage and potatoes, potato soup, beef hash, scalloped potatoes with ham, or crispy potato skins. They pair with chicken, beef, sausage, and eggs. Most dishes take 35-60 minutes.',
    },
    {
      question: 'What is the best potato for baking vs mashing?',
      answer: 'Russet potatoes are ideal for baking and mashing—they are starchy and fluffy. Yukon Golds work well for mashing and roasting with a creamier texture. Red potatoes hold their shape and are good for soups and salads. Match the potato type to your cooking method.',
    },
    {
      question: 'How do I get crispy roasted potatoes?',
      answer: 'Cut potatoes into even pieces, toss with oil and salt, and roast at 425°F on a preheated sheet pan. Do not overcrowd—crowding steams instead of roasts. Parboiling for 5-10 minutes and roughing up the edges before roasting creates extra crispy surfaces.',
    },
    {
      question: 'Can I use frozen potatoes in recipes?',
      answer: 'Yes. Frozen hash browns, diced potatoes, and tater tots work in casseroles, skillets, and sheet pan meals. Reduce cook time slightly since they are precooked. Thaw and pat dry before using in recipes where crispiness matters.',
    },
    {
      question: 'Are potatoes healthy for dinner?',
      answer: 'Potatoes are a good source of vitamins C and B6, potassium, and fiber, especially with the skin on. How you cook them matters—baking, roasting, or boiling is healthier than deep frying. Pair with lean protein and vegetables for a balanced meal.',
    },
  ],

  tortillas: [
    {
      question: 'What can I make with tortillas for dinner?',
      answer: 'Tortillas are incredibly versatile. Make tacos, burritos, quesadillas, enchiladas, tostadas, breakfast burritos, or tortilla pizzas. They work with chicken, beef, fish, beans, and eggs. Most recipes take 20-45 minutes and suit a range of cuisines from Mexican to American.',
    },
    {
      question: 'Flour vs corn tortillas—which should I use?',
      answer: 'Corn tortillas are traditional for tacos and enchiladas, with a distinct flavor and softer texture. Flour tortillas are larger and more pliable—better for burritos and quesadillas. Use corn for authentic Mexican dishes; flour for wraps and heartier fillings.',
    },
    {
      question: 'How do I keep tortillas from breaking when rolling burritos?',
      answer: 'Warm tortillas first so they are pliable—briefly over a flame or in a dry skillet. Do not overfill. Place filling in the center, fold in the sides, then roll from the bottom up. Slightly underfilled burritos hold together better than overstuffed ones.',
    },
    {
      question: 'Can I make tacos with leftover meat?',
      answer: 'Absolutely. Shredded chicken, ground beef, steak, pulled pork, and even leftover roasted vegetables work great in tacos. Warm the meat with a splash of broth or salsa to refresh it. Add fresh toppings like lettuce, salsa, cheese, and lime for a quick dinner.',
    },
    {
      question: 'Are tortillas gluten-free?',
      answer: 'Corn tortillas are naturally gluten-free. Flour tortillas contain wheat and are not. Check labels on store-bought tortillas—some corn tortillas may have cross-contamination. For a gluten-free option, stick to 100% corn tortillas.',
    },
  ],

  bread: [
    {
      question: 'What can I make with bread for dinner?',
      answer: 'Bread is a versatile base. Try French toast, grilled cheese with soup, paninis, bread bowl chowder, bruschetta, savory strata, open-faced sandwiches, or crouton-topped casseroles. Stale bread works perfectly for bread pudding and strata. Most dishes take 15-60 minutes.',
    },
    {
      question: 'What bread is best for grilled cheese?',
      answer: 'Sourdough, Texas toast, and white sandwich bread are popular. Sourdough adds tang and holds up well. Thicker slices toast nicely and hold melty cheese. Avoid very thin or overly soft bread—it can tear. Butter the outside for a crispy, golden crust.',
    },
    {
      question: 'How do I make French toast not soggy?',
      answer: 'Use day-old or slightly stale bread so it absorbs the egg mixture without falling apart. Do not over-soak—a quick dip on each side is enough. Cook over medium heat so the inside cooks through before the outside burns. Serve immediately for the best texture.',
    },
    {
      question: 'Can I use stale bread in recipes?',
      answer: 'Yes. Stale bread is ideal for French toast, bread pudding, strata, croutons, and bread crumbs. It absorbs custard better and toasts more evenly. Store leftover bread in the fridge or freezer if you will not use it within a day or two.',
    },
    {
      question: 'What is a bread bowl and how do I make one?',
      answer: 'A bread bowl is a hollowed-out round loaf used to hold soup or dip. Cut off the top, scoop out the soft interior (save for croutons or discard), and pour in hot soup. The bowl absorbs flavor as you eat. Use sourdough or round boules for best results.',
    },
  ],
}
