import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const comboRecipesUpgrade: Record<string, RecipeIdea[]> = {
  'chicken-breast-pasta': [
    {
      title: 'Creamy Tuscan Chicken Pasta',
      description: 'Sun-dried tomatoes, spinach, and garlic in a rich cream sauce with tender chicken.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, cut into bite-sized pieces',
        '12 oz penne pasta',
        '1/2 cup sun-dried tomatoes (oil-packed), chopped',
        '2 cups fresh spinach',
        '3 cloves garlic, minced',
        '1 cup heavy cream',
        '1/2 cup chicken broth',
        '1/3 cup grated parmesan cheese',
        '2 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water, then drain.',
        'Season chicken with salt and pepper. Heat olive oil in a large skillet over medium-high heat. Cook chicken until golden and cooked through, about 6-7 minutes. Remove and set aside.',
        'In the same skillet, add garlic and sun-dried tomatoes. Cook 1 minute until fragrant.',
        'Pour in heavy cream and chicken broth. Bring to a simmer and cook until slightly thickened, about 3-4 minutes.',
        'Stir in parmesan, Italian seasoning, spinach, and cooked chicken. Toss until spinach wilts.',
        'Add cooked pasta and toss to coat. Add reserved pasta water if needed for desired consistency.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 520, protein: 38, carbs: 48, fat: 22 },
    },
    {
      title: 'Chicken Alfredo',
      description: 'Classic creamy parmesan sauce with seared chicken over fettuccine.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, sliced thin',
        '12 oz fettuccine pasta',
        '1 cup heavy cream',
        '1/2 cup butter',
        '1 cup grated parmesan cheese',
        '2 cloves garlic, minced',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Cook fettuccine according to package directions. Reserve 1/2 cup pasta water, then drain.',
        'Season chicken with salt and pepper. Heat olive oil in a large skillet over medium-high heat. Cook chicken 4-5 minutes per side until golden. Remove and slice.',
        'In the same skillet, melt butter over medium heat. Add garlic and cook 30 seconds.',
        'Pour in heavy cream and bring to a gentle simmer. Cook 2-3 minutes until slightly thickened.',
        'Remove from heat and stir in parmesan until smooth. Season with salt and pepper.',
        'Add cooked pasta and chicken to the sauce. Toss to coat, adding pasta water if needed.',
        'Garnish with parsley and serve.',
      ],
      nutrition: { calories: 580, protein: 36, carbs: 46, fat: 28 },
    },
    {
      title: 'Lemon Chicken Pasta',
      description: 'Bright and zesty lemon butter sauce with herbs and tender chicken.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, cut into chunks',
        '12 oz spaghetti or linguine',
        '3 lemons (juice and zest)',
        '1/2 cup butter',
        '1/3 cup chicken broth',
        '3 cloves garlic, minced',
        '2 tablespoons fresh parsley, chopped',
        '1 teaspoon dried oregano',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water, then drain.',
        'Season chicken with salt and pepper. Heat olive oil in a large skillet over medium-high heat. Cook chicken until golden and cooked through, about 6-7 minutes. Remove and set aside.',
        'In the same skillet, melt butter. Add garlic and cook 30 seconds. Add lemon juice, zest, and chicken broth. Simmer 2 minutes.',
        'Return chicken to the skillet. Add parsley and oregano. Toss to combine.',
        'Add cooked pasta and toss to coat. Add pasta water if needed for consistency.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 490, protein: 34, carbs: 46, fat: 22 },
    },
    {
      title: 'Cajun Chicken Pasta',
      description: 'Spicy Cajun-seasoned chicken in a creamy sauce with bell peppers.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Cajun',
      ingredients: [
        '1 lb chicken breast, sliced',
        '12 oz penne or rigatoni pasta',
        '1 red bell pepper, sliced',
        '1 green bell pepper, sliced',
        '1/2 small onion, sliced',
        '2 tablespoons Cajun seasoning',
        '1 cup heavy cream',
        '1/2 cup chicken broth',
        '1/3 cup grated parmesan',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        'Salt to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water, then drain.',
        'Season chicken with 1 tablespoon Cajun seasoning. Heat olive oil in a large skillet over medium-high heat. Cook chicken until golden, about 5-6 minutes. Remove and set aside.',
        'In the same skillet, sauté bell peppers and onion until softened, about 4-5 minutes. Add garlic and remaining Cajun seasoning. Cook 1 minute.',
        'Pour in heavy cream and chicken broth. Bring to a simmer and cook until thickened, about 3-4 minutes.',
        'Stir in parmesan. Return chicken to the skillet. Add cooked pasta and toss to coat.',
        'Add pasta water if needed. Season with salt. Serve immediately.',
      ],
      nutrition: { calories: 540, protein: 38, carbs: 52, fat: 24 },
    },
    {
      title: 'Chicken Carbonara',
      description: 'Rich and silky egg-based sauce with bacon and parmesan.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, diced',
        '12 oz spaghetti',
        '6 slices bacon, diced',
        '3 large eggs',
        '1 cup grated parmesan cheese',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1/2 teaspoon black pepper',
        'Salt to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Cook spaghetti according to package directions. Reserve 1 cup pasta water, then drain.',
        'Whisk together eggs, parmesan, and black pepper in a bowl. Set aside.',
        'Cook bacon in a large skillet over medium heat until crispy, about 6-8 minutes. Remove with slotted spoon. Leave 2 tbsp fat in pan.',
        'Add olive oil if needed. Cook chicken in the same skillet until golden and done, about 6-7 minutes. Add garlic, cook 30 seconds. Remove from heat.',
        'Working quickly: add hot pasta to the skillet. Pour egg mixture over and toss vigorously, adding pasta water 1/4 cup at a time until sauce is silky.',
        'Add bacon back in. The residual heat will cook the eggs without scrambling. If needed, return to very low heat briefly.',
        'Garnish with parsley and extra parmesan. Serve immediately.',
      ],
      nutrition: { calories: 560, protein: 42, carbs: 46, fat: 26 },
    },
    {
      title: 'Chicken Pesto Pasta',
      description: 'Fresh basil pesto tossed with pasta and grilled chicken.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, sliced thin',
        '12 oz penne or fusilli pasta',
        '1/2 cup basil pesto (store-bought or homemade)',
        '1/4 cup reserved pasta water',
        '1/4 cup grated parmesan',
        '2 tablespoons olive oil',
        '1 cup cherry tomatoes, halved',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water, then drain.',
        'Season chicken with salt and pepper. Heat olive oil in a large skillet over medium-high heat. Cook chicken 3-4 minutes per side until golden. Remove and slice.',
        'In the same skillet, add pesto and 1/4 cup pasta water. Warm over low heat.',
        'Add cooked pasta, chicken, and cherry tomatoes. Toss to coat.',
        'Sprinkle with parmesan. Add more pasta water if needed. Season with salt and pepper.',
        'Serve immediately.',
      ],
      nutrition: { calories: 480, protein: 36, carbs: 48, fat: 18 },
    },
    {
      title: 'One-Pot Chicken Pasta',
      description: 'Everything cooks together for maximum flavor and minimal cleanup.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, cut into chunks',
        '12 oz penne pasta',
        '1 can (14.5 oz) diced tomatoes',
        '2 cups chicken broth',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon dried basil',
        '1 teaspoon dried oregano',
        '1/2 cup heavy cream',
        '1 cup fresh spinach',
        '1/2 cup shredded mozzarella',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet or Dutch oven over medium-high heat. Add chicken and cook until golden, about 5 minutes. Remove and set aside.',
        'Add onion and garlic. Sauté 2 minutes. Add diced tomatoes, chicken broth, basil, and oregano. Bring to a boil.',
        'Add uncooked pasta and stir. Reduce heat to medium, cover, and simmer 12-15 minutes until pasta is tender, stirring occasionally.',
        'Return chicken to the pot. Stir in cream and spinach. Cook 2 minutes until spinach wilts.',
        'Sprinkle with mozzarella. Cover and let melt 1-2 minutes.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 500, protein: 38, carbs: 50, fat: 20 },
    },
    {
      title: 'Chicken Parmesan Pasta',
      description: 'Crispy breaded chicken over pasta with marinara and melted mozzarella.',
      timeMinutes: 40,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, pounded to 1/2 inch thick',
        '12 oz spaghetti',
        '2 cups marinara sauce',
        '1 cup panko breadcrumbs',
        '1/2 cup grated parmesan, divided',
        '1 egg, beaten',
        '1/2 cup flour',
        '1 cup shredded mozzarella',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Fresh basil for garnish',
      ],
      instructions: [
        'Preheat oven to 400°F. Cook spaghetti according to package directions. Drain and set aside.',
        'Set up breading: flour in one dish, beaten egg in another, panko mixed with 1/4 cup parmesan in third. Season chicken with salt and pepper.',
        'Dredge chicken in flour, dip in egg, then coat in panko. Heat olive oil in a large skillet. Fry chicken 3-4 minutes per side until golden. Transfer to a baking dish.',
        'Spoon marinara over each piece. Top with mozzarella and remaining parmesan. Bake 10-12 minutes until cheese melts.',
        'Reheat pasta in remaining marinara. Divide among plates. Top with chicken parmesan.',
        'Garnish with basil. Serve immediately.',
      ],
      nutrition: { calories: 580, protein: 42, carbs: 52, fat: 24 },
    },
  ],

  'ground-beef-rice': [
    {
      title: 'Korean Beef Bowls',
      description: 'Sweet and savory ground beef with ginger and garlic over steamed rice.',
      timeMinutes: 20,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Korean',
      ingredients: [
        '1 lb ground beef',
        '3 cups cooked white rice',
        '1/4 cup soy sauce',
        '2 tablespoons brown sugar',
        '1 tablespoon sesame oil',
        '4 cloves garlic, minced',
        '1 teaspoon fresh ginger, grated',
        '1/2 teaspoon red pepper flakes',
        '2 green onions, sliced',
        '1 tablespoon sesame seeds',
        'Salt to taste',
      ],
      instructions: [
        'In a small bowl, whisk together soy sauce, brown sugar, sesame oil, garlic, ginger, and red pepper flakes.',
        'Heat a large skillet over medium-high heat. Add ground beef and cook until browned, breaking up with a spoon, about 6-7 minutes. Drain excess fat if needed.',
        'Pour the sauce over the beef. Stir and simmer 2-3 minutes until sauce thickens slightly.',
        'Divide rice among 4 bowls. Top with Korean beef.',
        'Garnish with green onions and sesame seeds. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 42, fat: 16 },
    },
    {
      title: 'Stuffed Pepper Skillet',
      description: 'All the flavors of stuffed peppers without the hassle, served over rice.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '3 cups cooked white rice',
        '1 green bell pepper, diced',
        '1 red bell pepper, diced',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 can (15 oz) tomato sauce',
        '1 cup shredded cheddar cheese',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat a large skillet over medium-high heat. Add ground beef and cook until browned, about 6-7 minutes. Drain excess fat.',
        'Add diced bell peppers and onion. Sauté 5-6 minutes until softened. Add garlic and cook 30 seconds.',
        'Stir in tomato sauce and Italian seasoning. Simmer 5 minutes. Season with salt and pepper.',
        'Fold in cooked rice. Top with shredded cheese. Cover and let melt 2-3 minutes.',
        'Serve hot.',
      ],
      nutrition: { calories: 480, protein: 30, carbs: 50, fat: 18 },
    },
    {
      title: 'Taco Rice Bowls',
      description: 'Seasoned taco meat over rice with all your favorite toppings.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 lb ground beef',
        '3 cups cooked white rice',
        '2 tablespoons taco seasoning',
        '1/2 cup water',
        '1 cup shredded lettuce',
        '1 cup diced tomatoes',
        '1/2 cup shredded cheddar cheese',
        '1/2 cup sour cream',
        '1 avocado, sliced',
        '1/4 cup salsa',
        '2 tablespoons chopped cilantro',
        'Lime wedges for serving',
      ],
      instructions: [
        'Cook ground beef in a large skillet over medium-high heat until browned, about 6-7 minutes. Add taco seasoning and water. Simmer 3-4 minutes until thickened.',
        'Divide rice among 4 bowls. Top with seasoned beef.',
        'Add lettuce, tomatoes, cheese, sour cream, avocado, and salsa.',
        'Garnish with cilantro. Serve with lime wedges.',
      ],
      nutrition: { calories: 560, protein: 32, carbs: 48, fat: 28 },
    },
    {
      title: 'Cheesy Beef and Rice Casserole',
      description: 'Baked comfort food with ground beef, rice, and plenty of cheese.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '2 cups cooked white rice',
        '1 can (10.5 oz) condensed cream of mushroom soup',
        '1 cup sour cream',
        '1.5 cups shredded cheddar cheese',
        '1 cup frozen mixed vegetables',
        '1/2 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Grease a 9x13-inch baking dish.',
        'Brown ground beef with onion and garlic in a large skillet. Drain. Season with salt and pepper.',
        'In a large bowl, mix condensed soup, sour cream, and half the cheese. Add cooked rice, beef mixture, and frozen vegetables. Stir to combine.',
        'Transfer to the baking dish. Top with remaining cheese.',
        'Bake 25-30 minutes until bubbly and golden. Let stand 5 minutes before serving.',
      ],
      nutrition: { calories: 420, protein: 24, carbs: 32, fat: 24 },
    },
    {
      title: 'Ground Beef Fried Rice',
      description: 'Quick and easy fried rice with seasoned ground beef and vegetables.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb ground beef',
        '3 cups cooked rice (day-old preferred)',
        '2 eggs, beaten',
        '1 cup frozen peas and carrots',
        '3 green onions, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '2 cloves garlic, minced',
        '1 teaspoon ginger, grated',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon vegetable oil in a large wok or skillet over high heat. Add ground beef and cook until browned, breaking up chunks. Remove and set aside.',
        'Add remaining oil. Add frozen vegetables and stir-fry 2 minutes. Push to the side. Pour in eggs and scramble until set. Mix with vegetables.',
        'Add rice, breaking up clumps. Stir-fry 3-4 minutes until heated and slightly crispy.',
        'Add garlic and ginger. Stir 30 seconds. Add soy sauce and sesame oil.',
        'Return beef to the pan. Toss everything together. Season with salt and pepper.',
        'Garnish with green onions. Serve immediately.',
      ],
      nutrition: { calories: 460, protein: 30, carbs: 42, fat: 22 },
    },
    {
      title: 'Beef and Rice Soup',
      description: 'Hearty and warming soup with ground beef, rice, and vegetables.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '1/2 cup uncooked long-grain rice',
        '6 cups beef broth',
        '1 can (14.5 oz) diced tomatoes',
        '1 onion, diced',
        '2 carrots, diced',
        '2 stalks celery, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '1 bay leaf',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium-high heat. Brown ground beef until no pink remains. Drain and set aside.',
        'In the same pot, sauté onion, carrots, and celery 5 minutes. Add garlic and cook 30 seconds.',
        'Add beef broth, diced tomatoes, rice, thyme, bay leaf, and browned beef. Bring to a boil.',
        'Reduce heat to low. Simmer 18-20 minutes until rice is tender.',
        'Remove bay leaf. Season with salt and pepper. Serve hot.',
      ],
      nutrition: { calories: 280, protein: 22, carbs: 22, fat: 12 },
    },
    {
      title: 'One-Pot Beef and Rice',
      description: 'Simple weeknight dinner with everything cooked in one pot.',
      timeMinutes: 35,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '1.5 cups long-grain white rice',
        '3 cups beef broth',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 can (14.5 oz) diced tomatoes',
        '1 teaspoon paprika',
        '1/2 teaspoon dried oregano',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet or Dutch oven over medium-high heat. Brown ground beef with onion until no pink remains. Drain excess fat. Add garlic and cook 30 seconds.',
        'Add rice and stir 1 minute. Pour in beef broth and diced tomatoes with juice. Add paprika and oregano.',
        'Bring to a boil. Reduce heat to low, cover, and simmer 20-22 minutes until rice is tender and liquid is absorbed.',
        'Remove from heat. Let rest 5 minutes. Fluff with a fork.',
        'Season with salt and pepper. Serve.',
      ],
      nutrition: { calories: 440, protein: 28, carbs: 52, fat: 14 },
    },
    {
      title: 'Mediterranean Beef Rice Bowls',
      description: 'Seasoned beef with feta, cucumber, and tzatziki over rice.',
      timeMinutes: 30,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '1 lb ground beef',
        '3 cups cooked white rice',
        '1 teaspoon dried oregano',
        '1/2 teaspoon cumin',
        '1/2 cup crumbled feta cheese',
        '1 cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '1/2 cup tzatziki sauce',
        '1/4 cup kalamata olives',
        '2 tablespoons olive oil',
        '1 lemon, cut into wedges',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season ground beef with oregano, cumin, salt, and pepper. Heat olive oil in a skillet. Cook beef until browned, about 6-7 minutes. Drain if needed.',
        'Divide rice among 4 bowls. Top with seasoned beef.',
        'Add cucumber, tomatoes, feta, and olives. Dollop tzatziki on top.',
        'Serve with lemon wedges.',
      ],
      nutrition: { calories: 480, protein: 30, carbs: 48, fat: 20 },
    },
  ],

  'ground-beef-pasta': [
    {
      title: 'Classic Bolognese',
      description: 'Rich, slow-simmered meat sauce with tomatoes, wine, and Italian herbs.',
      timeMinutes: 45,
      method: 'slow-cooker',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 35,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1 lb ground beef',
        '12 oz tagliatelle or pappardelle',
        '1 can (28 oz) crushed tomatoes',
        '1/2 cup red wine',
        '1 onion, finely diced',
        '2 carrots, finely diced',
        '2 stalks celery, finely diced',
        '4 cloves garlic, minced',
        '1/2 cup milk',
        '2 tablespoons tomato paste',
        '1 teaspoon dried basil',
        '1 teaspoon dried oregano',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large Dutch oven over medium heat. Add onion, carrot, and celery. Cook 8-10 minutes until softened. Add garlic and tomato paste. Cook 1 minute.',
        'Add ground beef and cook until browned, breaking up with a spoon. Pour in wine and simmer 2 minutes.',
        'Add crushed tomatoes, basil, oregano, salt, and pepper. Bring to a simmer.',
        'Reduce heat to low. Cover and simmer 30 minutes, stirring occasionally. Stir in milk and simmer 5 more minutes.',
        'Cook pasta according to package directions. Drain and divide among bowls. Top with Bolognese. Serve.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 48, fat: 14 },
    },
    {
      title: 'Cheeseburger Mac',
      description: 'Kid-friendly comfort food with ground beef, cheese sauce, and elbow macaroni.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '2 cups elbow macaroni',
        '2 cups beef broth',
        '1 can (10.5 oz) condensed cheddar cheese soup',
        '1/2 cup milk',
        '1 cup shredded cheddar cheese',
        '1/2 onion, diced',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Brown ground beef with onion in a large skillet. Drain excess fat. Add garlic powder, salt, and pepper.',
        'Add uncooked macaroni and beef broth. Bring to a boil. Reduce heat, cover, and simmer 10-12 minutes until pasta is tender.',
        'Stir in cheese soup and milk. Add shredded cheese. Stir until melted and smooth.',
        'If too thick, add a splash of milk. Serve immediately.',
      ],
      nutrition: { calories: 520, protein: 32, carbs: 48, fat: 24 },
    },
    {
      title: 'Baked Ziti with Beef',
      description: 'Layered pasta bake with seasoned beef, ricotta, and bubbly mozzarella.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 30,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1 lb ground beef',
        '16 oz ziti pasta',
        '4 cups marinara sauce',
        '2 cups ricotta cheese',
        '2 cups shredded mozzarella',
        '1/2 cup grated parmesan',
        '1 egg',
        '1 teaspoon Italian seasoning',
        '2 cloves garlic, minced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Cook ziti 2 minutes less than package directions. Drain.',
        'Brown ground beef with garlic. Drain. Stir in marinara. Season with salt and pepper.',
        'Mix ricotta, egg, 1/2 cup parmesan, Italian seasoning, salt, and pepper.',
        'In a 9x13 dish, spread 1 cup meat sauce. Layer half the ziti, half the ricotta mixture, half the remaining sauce, and half the mozzarella. Repeat layers.',
        'Top with remaining parmesan. Bake 25-30 minutes until bubbly and golden. Let stand 10 minutes before serving.',
      ],
      nutrition: { calories: 580, protein: 36, carbs: 52, fat: 28 },
    },
    {
      title: 'American Goulash',
      description: 'Old-fashioned ground beef and elbow macaroni in tomato sauce.',
      timeMinutes: 35,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '2 cups elbow macaroni',
        '2 cans (14.5 oz each) diced tomatoes',
        '1 can (15 oz) tomato sauce',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '2 teaspoons paprika',
        '1 teaspoon Italian seasoning',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large pot. Brown ground beef with onion and garlic. Drain.',
        'Add diced tomatoes, tomato sauce, paprika, Italian seasoning, salt, and pepper. Bring to a boil.',
        'Stir in uncooked macaroni. Reduce heat, cover, and simmer 15-18 minutes until pasta is tender, stirring occasionally.',
        'Adjust consistency with water if needed. Serve hot.',
      ],
      nutrition: { calories: 380, protein: 24, carbs: 44, fat: 12 },
    },
    {
      title: 'Beef Stroganoff Pasta',
      description: 'Creamy mushroom sauce with seasoned beef over egg noodles.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Russian',
      ingredients: [
        '1 lb ground beef',
        '12 oz egg noodles',
        '8 oz mushrooms, sliced',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 cup beef broth',
        '1 cup sour cream',
        '2 tablespoons flour',
        '1 tablespoon Worcestershire sauce',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook egg noodles according to package directions. Drain and set aside.',
        'Brown ground beef in a large skillet. Remove and set aside. Add butter and olive oil. Sauté mushrooms and onion 5-6 minutes. Add garlic, cook 30 seconds.',
        'Sprinkle flour over vegetables. Stir 1 minute. Gradually add beef broth and Worcestershire. Bring to a simmer and cook until thickened.',
        'Reduce heat to low. Stir in sour cream. Return beef to the skillet. Warm through. Season with salt and pepper.',
        'Serve over egg noodles.',
      ],
      nutrition: { calories: 520, protein: 30, carbs: 48, fat: 24 },
    },
    {
      title: 'Taco Pasta',
      description: 'Tex-Mex twist with taco-seasoned beef, tomatoes, and cheese over pasta.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 lb ground beef',
        '12 oz rotini or penne pasta',
        '1 packet taco seasoning',
        '1 can (14.5 oz) diced tomatoes',
        '1 cup salsa',
        '1 cup shredded cheddar cheese',
        '1/2 cup water',
        '2 cups beef broth',
        '2 green onions, sliced',
        'Sour cream for serving',
      ],
      instructions: [
        'Brown ground beef in a large skillet. Add taco seasoning and stir. Add diced tomatoes, salsa, water, and beef broth. Bring to a boil.',
        'Stir in uncooked pasta. Reduce heat, cover, and simmer 12-15 minutes until pasta is tender.',
        'Top with cheese. Cover and let melt 2 minutes.',
        'Garnish with green onions. Serve with sour cream.',
      ],
      nutrition: { calories: 540, protein: 32, carbs: 52, fat: 24 },
    },
    {
      title: 'Skillet Lasagna',
      description: 'All the flavors of lasagna made quick and easy in one skillet.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb ground beef',
        '8 oz mafaldine or broken lasagna noodles',
        '2 cups marinara sauce',
        '1 cup ricotta cheese',
        '1 cup shredded mozzarella',
        '1/2 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon Italian seasoning',
        '1/2 cup water',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Brown ground beef with onion and garlic in a large oven-safe skillet. Drain. Add marinara, water, Italian seasoning, salt, and pepper.',
        'Break noodles and add to the skillet. Bring to a boil, reduce heat, cover, and simmer 15-18 minutes until noodles are tender, stirring occasionally.',
        'Dollop ricotta over the top. Sprinkle with mozzarella. Cover and let cheese melt 2-3 minutes.',
        'Serve from the skillet.',
      ],
      nutrition: { calories: 560, protein: 38, carbs: 48, fat: 26 },
    },
    {
      title: 'Spaghetti and Meat Sauce',
      description: 'The ultimate family classic with homemade meat sauce over spaghetti.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb ground beef',
        '12 oz spaghetti',
        '2 cans (14.5 oz each) diced tomatoes',
        '1 can (6 oz) tomato paste',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon dried basil',
        '1 teaspoon dried oregano',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook spaghetti according to package directions. Reserve 1/2 cup pasta water. Drain.',
        'Heat olive oil in a large skillet. Brown ground beef with onion and garlic. Drain excess fat.',
        'Add tomato paste. Cook 1 minute. Add diced tomatoes, basil, oregano, salt, and pepper. Simmer 15-20 minutes.',
        'Toss spaghetti with meat sauce. Add pasta water if needed. Serve with parmesan.',
      ],
      nutrition: { calories: 520, protein: 32, carbs: 58, fat: 18 },
    },
  ],

  'ground-beef-potatoes': [
    {
      title: "Classic Shepherd's Pie",
      description: 'Savory beef filling topped with creamy mashed potatoes and baked until golden.',
      timeMinutes: 60,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 25,
      cookTime: 35,
      servings: 6,
      cuisine: 'British',
      ingredients: [
        '1.5 lbs ground beef',
        '2.5 lbs potatoes, peeled and cubed',
        '1 onion, diced',
        '2 carrots, diced',
        '1 cup frozen peas',
        '2 cloves garlic, minced',
        '2 tablespoons tomato paste',
        '1 cup beef broth',
        '1/2 cup milk',
        '4 tablespoons butter',
        '2 tablespoons olive oil',
        '1 teaspoon Worcestershire sauce',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Boil potatoes until tender. Drain and mash with butter and milk. Season with salt and pepper. Set aside.',
        'Preheat oven to 375°F. Heat olive oil in a large skillet. Brown ground beef. Remove and set aside.',
        'In same skillet, sauté onion and carrots 5 minutes. Add garlic and tomato paste. Cook 1 minute.',
        'Return beef. Add beef broth and Worcestershire. Simmer 5 minutes. Stir in peas. Transfer to a 9x13 baking dish.',
        'Spread mashed potatoes over the top. Use a fork to create peaks. Bake 25-30 minutes until golden.',
        'Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 42, fat: 18 },
    },
    {
      title: 'Beef and Potato Hash',
      description: 'Crispy diced potatoes with seasoned ground beef, onions, and a fried egg on top.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '4 cups diced potatoes',
        '1 onion, diced',
        '1 teaspoon paprika',
        '1/2 teaspoon garlic powder',
        '4 eggs',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet over medium-high heat. Add diced potatoes. Cook 10-12 minutes until golden and tender, stirring occasionally.',
        'Push potatoes to the side. Add ground beef and onion. Cook until beef is browned. Combine with potatoes. Add paprika and garlic powder. Season with salt and pepper.',
        'Make 4 wells in the hash. Crack an egg into each. Cover and cook 3-4 minutes until eggs are set.',
        'Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 28, fat: 22 },
    },
    {
      title: 'Ground Beef Potato Skillet',
      description: 'One-pan comfort meal with browned beef, tender potatoes, and melted cheese.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '4 medium potatoes, diced',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 cup shredded cheddar cheese',
        '1/2 cup beef broth',
        '1 teaspoon paprika',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet. Add potatoes and onion. Cook 10 minutes until potatoes start to soften.',
        'Push to the side. Add ground beef and garlic. Cook until beef is browned. Combine. Add beef broth and paprika. Simmer 5 minutes.',
        'Top with shredded cheese. Cover and let melt 2-3 minutes. Season with salt and pepper. Serve.',
      ],
      nutrition: { calories: 480, protein: 30, carbs: 36, fat: 26 },
    },
    {
      title: 'Beef Potato Casserole',
      description: 'Layered casserole with seasoned beef, sliced potatoes, and creamy sauce.',
      timeMinutes: 55,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 35,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '4 large potatoes, thinly sliced',
        '1 can (10.5 oz) cream of mushroom soup',
        '1/2 cup sour cream',
        '1 cup shredded cheddar cheese',
        '1 onion, diced',
        '1 teaspoon garlic powder',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Brown ground beef with onion. Drain. Season with garlic powder, salt, and pepper.',
        'Mix cream of mushroom soup and sour cream. In a 9x13 dish, layer half the potatoes. Top with beef mixture and half the soup mixture. Repeat layers. Top with remaining soup and cheese.',
        'Cover with foil. Bake 30 minutes. Uncover and bake 15 more minutes until potatoes are tender and top is golden.',
        'Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 380, protein: 22, carbs: 36, fat: 18 },
    },
    {
      title: 'Loaded Beef and Potato Bowls',
      description: 'Baked potatoes topped with seasoned beef, cheese, sour cream, and green onions.',
      timeMinutes: 45,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground beef',
        '4 large baking potatoes',
        '1 packet taco seasoning',
        '1 cup shredded cheddar cheese',
        '1/2 cup sour cream',
        '2 green onions, sliced',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. Rub potatoes with olive oil and salt. Bake 45-50 minutes until tender. (Or microwave 8-10 minutes.)',
        'Brown ground beef. Add taco seasoning and 1/4 cup water. Simmer 3-4 minutes.',
        'Split potatoes open. Top with seasoned beef, cheese, sour cream, and green onions.',
        'Serve immediately.',
      ],
      nutrition: { calories: 520, protein: 30, carbs: 48, fat: 24 },
    },
    {
      title: 'Cottage Pie',
      description: 'Traditional British comfort dish with savory beef and vegetable filling under mashed potato.',
      timeMinutes: 60,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 25,
      cookTime: 35,
      servings: 6,
      cuisine: 'British',
      ingredients: [
        '1.5 lbs ground beef',
        '2.5 lbs potatoes, peeled and cubed',
        '1 onion, diced',
        '2 carrots, diced',
        '1 cup frozen peas',
        '2 tablespoons tomato paste',
        '1 cup beef broth',
        '1/2 cup milk',
        '4 tablespoons butter',
        '2 tablespoons olive oil',
        '1 teaspoon thyme',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Boil potatoes until tender. Mash with butter and milk. Season with salt and pepper.',
        'Preheat oven to 375°F. Brown beef in olive oil. Remove. Sauté onion and carrots 5 minutes. Add tomato paste and thyme. Return beef. Add broth. Simmer 5 minutes. Stir in peas.',
        'Transfer to 9x13 dish. Spread mashed potatoes on top. Bake 25-30 minutes until golden. Rest 5 minutes. Serve.',
      ],
      nutrition: { calories: 440, protein: 30, carbs: 44, fat: 20 },
    },
    {
      title: 'Tex-Mex Beef Potato Bowl',
      description: 'Seasoned taco beef over crispy potatoes with salsa, cheese, and avocado.',
      timeMinutes: 35,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 lb ground beef',
        '4 cups diced potatoes',
        '2 tablespoons taco seasoning',
        '1 cup shredded cheddar cheese',
        '1/2 cup salsa',
        '1 avocado, diced',
        '1/2 cup sour cream',
        '2 tablespoons olive oil',
        '2 green onions, sliced',
      ],
      instructions: [
        'Heat olive oil in a large skillet. Cook diced potatoes 12-15 minutes until crispy and tender. Season with salt. Remove and divide among bowls.',
        'In same skillet, brown ground beef. Add taco seasoning and 1/4 cup water. Simmer 3 minutes.',
        'Top potatoes with beef, cheese, salsa, avocado, and sour cream. Garnish with green onions. Serve.',
      ],
      nutrition: { calories: 540, protein: 28, carbs: 40, fat: 32 },
    },
    {
      title: 'Stuffed Baked Potatoes',
      description: 'Fluffy baked potatoes filled with savory ground beef and all the fixings.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 40,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 large baking potatoes',
        '1 lb ground beef',
        '1/2 onion, diced',
        '1 cup shredded cheddar cheese',
        '1/2 cup sour cream',
        '2 green onions, sliced',
        '2 tablespoons butter',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. Prick potatoes, rub with oil, bake 45-50 minutes until tender.',
        'Brown ground beef with onion. Season with garlic powder, salt, and pepper.',
        'Cut potatoes in half. Scoop flesh into a bowl, leaving shells. Mix flesh with butter, half the cheese, sour cream, and beef.',
        'Stuff shells with mixture. Top with remaining cheese. Bake 10 minutes until melted. Garnish with green onions. Serve.',
      ],
      nutrition: { calories: 520, protein: 30, carbs: 48, fat: 26 },
    },
  ],

  'sausage-pasta': [
    {
      title: 'Sausage Marinara Pasta',
      description: 'Italian sausage crumbled into rich tomato sauce served over your favorite pasta.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, casings removed',
        '12 oz pasta (spaghetti or penne)',
        '2 cups marinara sauce',
        '3 cloves garlic, minced',
        '1/2 teaspoon red pepper flakes',
        '1/4 cup grated parmesan',
        '2 tablespoons olive oil',
        'Fresh basil for garnish',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water. Drain.',
        'Heat olive oil in a large skillet. Crumble sausage and cook until browned, about 6-8 minutes. Add garlic and red pepper flakes. Cook 30 seconds.',
        'Pour in marinara sauce. Simmer 5-7 minutes. Add pasta water if needed.',
        'Toss with cooked pasta. Top with parmesan and basil. Serve.',
      ],
      nutrition: { calories: 560, protein: 28, carbs: 52, fat: 28 },
    },
    {
      title: 'Creamy Sausage Pasta',
      description: 'Sliced sausage in a luscious cream sauce with parmesan and fresh herbs.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, sliced',
        '12 oz penne pasta',
        '1 cup heavy cream',
        '1/2 cup grated parmesan',
        '3 cloves garlic, minced',
        '1 teaspoon Italian seasoning',
        '2 tablespoons olive oil',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water. Drain.',
        'Heat olive oil in a large skillet. Cook sausage slices until browned. Add garlic and Italian seasoning. Cook 30 seconds.',
        'Pour in heavy cream. Simmer 3-4 minutes until slightly thickened. Stir in parmesan.',
        'Add cooked pasta. Toss to coat. Add pasta water if needed. Garnish with parsley. Serve.',
      ],
      nutrition: { calories: 620, protein: 26, carbs: 50, fat: 38 },
    },
    {
      title: 'Sausage Pesto Pasta',
      description: 'Quick weeknight pasta with sausage, basil pesto, and sun-dried tomatoes.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, sliced',
        '12 oz pasta (penne or rotini)',
        '1/2 cup basil pesto',
        '1/2 cup sun-dried tomatoes, chopped',
        '1/4 cup pasta water',
        '2 tablespoons olive oil',
        'Grated parmesan for serving',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water. Drain.',
        'Heat olive oil in a large skillet. Cook sausage slices until browned, about 6-7 minutes.',
        'Add pesto and sun-dried tomatoes. Thin with pasta water. Add cooked pasta and toss.',
        'Serve with parmesan.',
      ],
      nutrition: { calories: 580, protein: 26, carbs: 50, fat: 32 },
    },
    {
      title: 'Cajun Sausage Pasta',
      description: 'Spicy Cajun-seasoned sausage with peppers and onions in creamy pasta.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Cajun',
      ingredients: [
        '1 lb andouille or smoked sausage, sliced',
        '12 oz penne pasta',
        '1 red bell pepper, sliced',
        '1 green bell pepper, sliced',
        '1 onion, sliced',
        '1 cup heavy cream',
        '2 tablespoons Cajun seasoning',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water. Drain.',
        'Heat olive oil in a large skillet. Cook sausage until browned. Add peppers and onion. Sauté 5 minutes. Add garlic and Cajun seasoning. Cook 1 minute.',
        'Pour in heavy cream. Simmer 4-5 minutes until thickened. Add cooked pasta. Toss to coat. Serve.',
      ],
      nutrition: { calories: 600, protein: 24, carbs: 52, fat: 36 },
    },
    {
      title: 'One-Pot Sausage Pasta',
      description: 'Everything cooks together in one pot for easy cleanup and maximum flavor.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, crumbled',
        '12 oz penne pasta',
        '2 cups chicken broth',
        '1 can (14.5 oz) diced tomatoes',
        '1/2 cup heavy cream',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon Italian seasoning',
        '1 cup shredded mozzarella',
      ],
      instructions: [
        'Brown sausage with onion and garlic in a large pot. Add chicken broth, diced tomatoes, and Italian seasoning. Bring to a boil.',
        'Add uncooked pasta. Reduce heat, cover, simmer 12-15 minutes until pasta is tender.',
        'Stir in cream. Top with mozzarella. Cover and let melt 2 minutes. Serve.',
      ],
      nutrition: { calories: 620, protein: 28, carbs: 52, fat: 36 },
    },
    {
      title: 'Baked Sausage Ziti',
      description: 'Sausage and ziti baked with marinara, ricotta, and melted mozzarella.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, casings removed',
        '16 oz ziti pasta',
        '4 cups marinara sauce',
        '2 cups ricotta cheese',
        '2 cups shredded mozzarella',
        '1/2 cup grated parmesan',
        '1 egg',
        '1 teaspoon Italian seasoning',
      ],
      instructions: [
        'Preheat oven to 375°F. Cook ziti 2 minutes less than package directions. Drain.',
        'Brown sausage. Drain. Mix with marinara. Mix ricotta, egg, 1/2 cup parmesan, and Italian seasoning.',
        'In 9x13 dish: layer half ziti, half ricotta, half meat sauce, half mozzarella. Repeat. Top with parmesan.',
        'Bake 25-30 minutes until bubbly. Rest 10 minutes. Serve.',
      ],
      nutrition: { calories: 580, protein: 34, carbs: 52, fat: 28 },
    },
    {
      title: 'Orecchiette with Sausage',
      description: 'Little ear-shaped pasta with crumbled sausage, broccoli rabe, and garlic.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, casings removed',
        '12 oz orecchiette pasta',
        '1 bunch broccoli rabe, trimmed',
        '4 cloves garlic, minced',
        '1/4 teaspoon red pepper flakes',
        '1/2 cup pasta water',
        '2 tablespoons olive oil',
        'Grated parmesan for serving',
      ],
      instructions: [
        'Cook pasta according to package directions. Add broccoli rabe in last 3 minutes. Reserve 1/2 cup pasta water. Drain.',
        'Brown sausage in olive oil, breaking up with spoon. Add garlic and red pepper flakes. Cook 30 seconds.',
        'Add pasta, broccoli rabe, and pasta water. Toss to combine. Serve with parmesan.',
      ],
      nutrition: { calories: 520, protein: 26, carbs: 50, fat: 26 },
    },
    {
      title: 'Sausage Vodka Pasta',
      description: 'Trendy vodka sauce with Italian sausage for a rich, restaurant-quality meal.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb Italian sausage, casings removed',
        '12 oz penne or rigatoni',
        '1 can (28 oz) crushed tomatoes',
        '1/2 cup heavy cream',
        '1/4 cup vodka',
        '3 cloves garlic, minced',
        '1/2 onion, diced',
        '1/4 cup grated parmesan',
        '2 tablespoons olive oil',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water. Drain.',
        'Brown sausage with onion and garlic. Add vodka and simmer 2 minutes. Add crushed tomatoes. Simmer 10 minutes.',
        'Stir in cream and parmesan. Add cooked pasta. Toss. Add pasta water if needed. Serve.',
      ],
      nutrition: { calories: 620, protein: 28, carbs: 52, fat: 34 },
    },
  ],

  'chicken-breast-broccoli': [
    {
      title: 'Chicken Broccoli Stir-Fry',
      description: 'Quick Asian-style stir-fry with tender chicken and crisp broccoli in savory sauce.',
      timeMinutes: 20,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb chicken breast, sliced thin',
        '3 cups broccoli florets',
        '1/4 cup soy sauce',
        '2 tablespoons oyster sauce',
        '1 tablespoon hoisin sauce',
        '1 tablespoon cornstarch',
        '3 cloves garlic, minced',
        '1 teaspoon ginger, grated',
        '2 tablespoons vegetable oil',
        '2 tablespoons water',
      ],
      instructions: [
        'Mix soy sauce, oyster sauce, hoisin, cornstarch, and water. Set aside.',
        'Heat 1 tablespoon oil in a wok over high heat. Stir-fry chicken 4-5 minutes until done. Remove.',
        'Add remaining oil. Stir-fry broccoli 2 minutes. Add garlic and ginger. Cook 30 seconds.',
        'Return chicken. Pour in sauce. Toss until thickened. Serve over rice.',
      ],
      nutrition: { calories: 280, protein: 32, carbs: 14, fat: 10 },
    },
    {
      title: 'Sheet Pan Chicken and Broccoli',
      description: 'Easy hands-off dinner with roasted chicken and broccoli on one pan.',
      timeMinutes: 35,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb chicken breast, cut into chunks',
        '4 cups broccoli florets',
        '3 tablespoons olive oil',
        '1 teaspoon garlic powder',
        '1 teaspoon paprika',
        '1/2 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F. Line a sheet pan with foil.',
        'Toss chicken with 2 tbsp olive oil, garlic powder, paprika, salt, and pepper. Place on one side of pan.',
        'Toss broccoli with remaining oil, Italian seasoning, salt, and pepper. Place on other side.',
        'Roast 22-25 minutes until chicken reaches 165°F and broccoli is tender. Serve.',
      ],
      nutrition: { calories: 260, protein: 32, carbs: 10, fat: 12 },
    },
    {
      title: 'Chicken Broccoli Alfredo',
      description: 'Creamy pasta with seared chicken, tender broccoli, and rich parmesan sauce.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 lb chicken breast, sliced',
        '12 oz fettuccine',
        '3 cups broccoli florets',
        '1 cup heavy cream',
        '1/2 cup grated parmesan',
        '3 cloves garlic, minced',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
      ],
      instructions: [
        'Cook pasta. Add broccoli in last 4 minutes. Reserve 1/2 cup pasta water. Drain.',
        'Season chicken. Heat olive oil. Cook chicken 5-6 minutes. Remove. Melt butter, add garlic. Pour in cream. Simmer 2 min. Stir in parmesan.',
        'Add pasta, broccoli, and chicken. Toss. Add pasta water if needed. Serve.',
      ],
      nutrition: { calories: 540, protein: 38, carbs: 48, fat: 24 },
    },
    {
      title: 'Teriyaki Chicken Broccoli',
      description: 'Sweet and glossy teriyaki glazed chicken with steamed broccoli florets.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Japanese',
      ingredients: [
        '1 lb chicken breast, cut into pieces',
        '4 cups broccoli florets',
        '1/3 cup soy sauce',
        '3 tablespoons honey',
        '2 tablespoons rice vinegar',
        '1 tablespoon cornstarch',
        '2 cloves garlic, minced',
        '1 teaspoon ginger, grated',
        '2 tablespoons vegetable oil',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'Whisk soy sauce, honey, rice vinegar, cornstarch, and 2 tbsp water. Set aside.',
        'Heat oil. Cook chicken 6-7 minutes. Remove. Stir-fry broccoli 3 minutes. Add garlic and ginger.',
        'Return chicken. Pour teriyaki sauce. Cook until thickened. Garnish with sesame seeds. Serve over rice.',
      ],
      nutrition: { calories: 320, protein: 34, carbs: 28, fat: 8 },
    },
    {
      title: 'Lemon Garlic Chicken Broccoli',
      description: 'Bright and aromatic skillet with crispy chicken and garlicky broccoli.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '1 lb chicken breast, cut into pieces',
        '4 cups broccoli florets',
        '4 cloves garlic, minced',
        '2 lemons (juice and zest)',
        '2 tablespoons olive oil',
        '1/2 cup chicken broth',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season chicken. Heat olive oil. Cook chicken 6-7 minutes. Remove. Add broccoli and garlic. Sauté 4 minutes.',
        'Add lemon juice, zest, chicken broth, and Italian seasoning. Simmer 2 minutes.',
        'Return chicken. Toss to combine. Season with salt and pepper. Serve.',
      ],
      nutrition: { calories: 240, protein: 32, carbs: 12, fat: 8 },
    },
    {
      title: 'Honey Garlic Chicken Broccoli',
      description: 'Sticky-sweet honey garlic sauce coats tender chicken and fresh broccoli.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb chicken breast, cut into pieces',
        '4 cups broccoli florets',
        '1/4 cup honey',
        '3 tablespoons soy sauce',
        '4 cloves garlic, minced',
        '1 tablespoon rice vinegar',
        '1 tablespoon cornstarch',
        '2 tablespoons vegetable oil',
      ],
      instructions: [
        'Mix honey, soy sauce, rice vinegar, cornstarch, and 2 tbsp water. Set aside.',
        'Heat oil. Cook chicken 6 minutes. Remove. Stir-fry broccoli 3 minutes. Add garlic.',
        'Return chicken. Pour honey garlic sauce. Toss until glazed. Serve over rice.',
      ],
      nutrition: { calories: 300, protein: 32, carbs: 32, fat: 8 },
    },
    {
      title: 'Chicken Broccoli Casserole',
      description: 'Creamy comfort food bake with chicken, broccoli, and a crispy topping.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1.5 lbs chicken breast, cooked and diced',
        '4 cups broccoli florets, steamed',
        '1 can (10.5 oz) cream of chicken soup',
        '1 cup mayonnaise',
        '1 cup shredded cheddar cheese',
        '1/2 cup breadcrumbs',
        '2 tablespoons butter, melted',
      ],
      instructions: [
        'Preheat oven to 375°F. Mix cream of chicken soup, mayonnaise, and half the cheese. Fold in chicken and broccoli.',
        'Transfer to 9x13 dish. Top with remaining cheese. Mix breadcrumbs with butter. Sprinkle on top.',
        'Bake 25-30 minutes until bubbly. Serve.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 18, fat: 26 },
    },
    {
      title: 'Chicken Broccoli Lo Mein',
      description: 'Saucy noodles tossed with sliced chicken, broccoli, and Asian seasonings.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb chicken breast, sliced',
        '12 oz lo mein noodles or spaghetti',
        '4 cups broccoli florets',
        '1/4 cup soy sauce',
        '2 tablespoons oyster sauce',
        '1 tablespoon sesame oil',
        '3 cloves garlic, minced',
        '2 tablespoons vegetable oil',
        '2 green onions, sliced',
      ],
      instructions: [
        'Cook noodles. Drain. Add broccoli to boiling water in last 2 minutes. Drain.',
        'Heat oil. Cook chicken 5-6 minutes. Add garlic. Stir-fry 30 seconds. Add broccoli and noodles.',
        'Pour soy sauce and oyster sauce. Toss. Drizzle sesame oil. Garnish with green onions. Serve.',
      ],
      nutrition: { calories: 420, protein: 36, carbs: 50, fat: 10 },
    },
  ],
}

export const comboFaqsUpgrade: Record<string, FAQ[]> = {}
