import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const comboRecipesNew2: Record<string, RecipeIdea[]> = {
  'rotisserie-chicken-rice': [
    {
      title: 'Rotisserie Chicken Rice Soup',
      description: 'Cozy chicken soup with tender rotisserie chicken, rice, carrots, and celery. Ready in under 30 minutes thanks to pre-cooked chicken.',
      timeMinutes: 25,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 rotisserie chicken, meat shredded (about 3 cups)',
        '6 cups chicken broth',
        '1 cup long-grain white rice',
        '2 carrots, diced',
        '2 stalks celery, diced',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '1 bay leaf',
        'Salt and pepper to taste',
        '2 tablespoons fresh parsley, chopped',
      ],
      instructions: [
        'In a large pot, sauté onion, carrots, and celery in 1 tablespoon oil until softened, about 5 minutes. Add garlic and cook 1 minute.',
        'Pour in chicken broth and add bay leaf and thyme. Bring to a boil.',
        'Add rice, reduce heat to medium, and simmer for 15 minutes until rice is tender.',
        'Stir in shredded rotisserie chicken and heat through, about 2 minutes.',
        'Remove bay leaf. Season with salt and pepper.',
        'Ladle into bowls and garnish with fresh parsley. Serve hot.',
      ],
      nutrition: { calories: 280, protein: 24, carbs: 28, fat: 8 },
    },
    {
      title: 'Rotisserie Chicken Fried Rice',
      description: 'Classic fried rice using shredded rotisserie chicken for a fast weeknight dinner. No raw chicken to cook—just heat and eat.',
      timeMinutes: 20,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '2 cups rotisserie chicken, shredded',
        '3 cups cooked rice (day-old works best)',
        '2 large eggs, beaten',
        '1 cup frozen peas and carrots',
        '3 green onions, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '2 cloves garlic, minced',
        '1 teaspoon fresh ginger, grated',
      ],
      instructions: [
        'Heat 1 tablespoon vegetable oil in a large wok or skillet over high heat. Add beaten eggs and scramble until set. Remove and set aside.',
        'Add remaining oil. Add frozen peas and carrots and stir-fry 2 minutes until thawed.',
        'Add cooked rice, breaking up clumps. Stir-fry 3 minutes until rice is heated and slightly crispy.',
        'Add garlic and ginger, stirring 30 seconds until fragrant.',
        'Return eggs to wok. Add shredded rotisserie chicken, soy sauce, and sesame oil. Toss everything together.',
        'Garnish with green onions and serve immediately.',
      ],
      nutrition: { calories: 390, protein: 28, carbs: 42, fat: 12 },
    },
    {
      title: 'Rotisserie Chicken Burrito Bowls',
      description: 'Chipotle-style bowls with rotisserie chicken, cilantro lime rice, black beans, and fresh toppings. Fully assembled in 15 minutes.',
      timeMinutes: 15,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 5,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 cups rotisserie chicken, shredded',
        '3 cups cooked white rice',
        '2 tablespoons fresh lime juice',
        '1/4 cup fresh cilantro, chopped',
        '1 can (15 oz) black beans, drained and rinsed',
        '1 cup corn kernels',
        '1 avocado, sliced',
        '1/2 cup salsa',
        '1/2 cup sour cream',
        '1 teaspoon cumin',
        'Shredded cheese for topping',
      ],
      instructions: [
        'Warm shredded rotisserie chicken in a skillet with cumin. Set aside.',
        'Toss cooked rice with lime juice and cilantro for cilantro lime rice.',
        'Warm black beans and corn in microwave or stovetop.',
        'Divide rice among 4 bowls. Top with chicken, black beans, corn, avocado, salsa, and sour cream.',
        'Sprinkle with shredded cheese. Serve with lime wedges.',
      ],
      nutrition: { calories: 520, protein: 36, carbs: 52, fat: 18 },
    },
    {
      title: 'Rotisserie Chicken Rice Casserole',
      description: 'Creamy baked casserole with rotisserie chicken, rice, and broccoli. Comfort food that comes together fast with pre-cooked chicken.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '3 cups rotisserie chicken, shredded',
        '2 cups cooked white rice',
        '1 can (10.5 oz) cream of chicken soup',
        '1 cup sour cream',
        '1 cup shredded cheddar cheese',
        '2 cups broccoli florets',
        '1/2 cup chicken broth',
        '1/2 teaspoon garlic powder',
        '1/2 cup crushed Ritz crackers',
        '2 tablespoons melted butter',
      ],
      instructions: [
        'Preheat oven to 375°F. Grease a 9x13-inch baking dish.',
        'In a large bowl, mix cream of chicken soup, sour cream, broth, and garlic powder.',
        'Fold in shredded chicken, cooked rice, broccoli, and half the cheese.',
        'Transfer to baking dish. Top with remaining cheese.',
        'Mix crushed crackers with melted butter; sprinkle over top.',
        'Bake 30 minutes until bubbly and golden. Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 420, protein: 30, carbs: 32, fat: 20 },
    },
    {
      title: 'Teriyaki Rotisserie Chicken Rice Bowls',
      description: 'Sweet teriyaki-glazed rotisserie chicken over steamed rice with steamed broccoli. Restaurant-quality bowl in 15 minutes.',
      timeMinutes: 15,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 4,
      cuisine: 'Japanese',
      ingredients: [
        '2 cups rotisserie chicken, shredded',
        '3 cups cooked jasmine rice',
        '1/3 cup teriyaki sauce',
        '2 cups broccoli florets',
        '1 tablespoon sesame oil',
        '1 tablespoon honey',
        'Sesame seeds and green onions for garnish',
      ],
      instructions: [
        'Steam broccoli florets until tender-crisp, about 4 minutes.',
        'In a skillet over medium heat, add rotisserie chicken, teriyaki sauce, and honey. Toss and heat until glaze coats chicken, about 3 minutes.',
        'Divide rice among 4 bowls. Top with teriyaki chicken and steamed broccoli.',
        'Drizzle with sesame oil. Garnish with sesame seeds and sliced green onions.',
      ],
      nutrition: { calories: 410, protein: 32, carbs: 48, fat: 10 },
    },
    {
      title: 'Greek Rotisserie Chicken Rice Bowls',
      description: 'Mediterranean-style bowls with rotisserie chicken, rice, cucumber, tomato, feta, and tzatziki. Fresh and fast.',
      timeMinutes: 15,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 12,
      cookTime: 3,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '2 cups rotisserie chicken, shredded',
        '3 cups cooked rice',
        '1 cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '1/2 red onion, thinly sliced',
        '1/2 cup crumbled feta',
        '1 cup tzatziki',
        '1 teaspoon dried oregano',
        'Fresh dill and lemon wedges',
      ],
      instructions: [
        'Warm rotisserie chicken in microwave or skillet if desired, or serve cold.',
        'Divide rice among 4 bowls. Top with shredded chicken.',
        'Arrange cucumber, tomatoes, and red onion on top.',
        'Add a generous dollop of tzatziki and sprinkle with feta and oregano.',
        'Garnish with dill and serve with lemon wedges.',
      ],
      nutrition: { calories: 440, protein: 34, carbs: 44, fat: 14 },
    },
    {
      title: 'BBQ Rotisserie Chicken and Rice Skillet',
      description: 'One-skillet dinner with smoky BBQ rotisserie chicken, rice, corn, and black beans. Southern comfort in 25 minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cups rotisserie chicken, shredded',
        '1 cup long-grain white rice',
        '2 cups chicken broth',
        '1/2 cup BBQ sauce',
        '1 cup corn kernels',
        '1 can (15 oz) black beans, drained',
        '1 small onion, diced',
        '1 teaspoon chili powder',
      ],
      instructions: [
        'In a large skillet, sauté onion in 1 tablespoon oil until softened, about 3 minutes.',
        'Add rice and stir 1 minute. Pour in chicken broth and bring to a boil.',
        'Reduce heat to low, cover, and simmer 15 minutes until rice is tender.',
        'Stir in shredded chicken, BBQ sauce, corn, and black beans. Heat through 3 minutes.',
        'Season with chili powder. Serve hot.',
      ],
      nutrition: { calories: 450, protein: 28, carbs: 62, fat: 10 },
    },
    {
      title: 'Creamy Rotisserie Chicken and Rice',
      description: 'Rich and creamy one-pan dish with rotisserie chicken, rice, peas, and parmesan. Cozy comfort without the fuss.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cups rotisserie chicken, shredded',
        '1 cup arborio or long-grain rice',
        '2.5 cups chicken broth',
        '1/2 cup heavy cream',
        '1 cup frozen peas',
        '1/2 cup grated parmesan',
        '1 small onion, diced',
        '2 cloves garlic, minced',
      ],
      instructions: [
        'Sauté onion in 2 tablespoons butter until soft. Add garlic; cook 30 seconds.',
        'Add rice and stir 1 minute. Add 1 cup broth; simmer until mostly absorbed.',
        'Continue adding broth 1/2 cup at a time, stirring until rice is creamy and tender, about 18 minutes.',
        'Stir in shredded chicken, peas, cream, and parmesan. Heat through 2 minutes.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 480, protein: 30, carbs: 48, fat: 18 },
    },
  ],

  'canned-tuna-pasta': [
    {
      title: 'Classic Tuna Pasta Salad',
      description: 'Creamy cold pasta salad with canned tuna, peas, celery, and a tangy mayonnaise dressing. Perfect for picnics and meal prep.',
      timeMinutes: 25,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 10,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 cans (5 oz each) tuna in water, drained',
        '12 oz elbow pasta or rotini',
        '1/2 cup mayonnaise',
        '1/4 cup sour cream',
        '2 stalks celery, diced',
        '1 cup frozen peas, thawed',
        '1/4 cup diced red onion',
        '2 tablespoons lemon juice',
        '1 tablespoon Dijon mustard',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Drain, rinse with cold water, and set aside.',
        'In a large bowl, whisk mayonnaise, sour cream, lemon juice, and mustard.',
        'Flake tuna into the dressing. Add celery, peas, and red onion.',
        'Add cooled pasta and toss to coat. Season with salt and pepper.',
        'Chill at least 30 minutes before serving. Store refrigerated up to 3 days.',
      ],
      nutrition: { calories: 380, protein: 22, carbs: 42, fat: 14 },
    },
    {
      title: 'Tuna Noodle Casserole',
      description: 'Old-fashioned comfort food with canned tuna, egg noodles, peas, and a creamy sauce topped with buttery breadcrumbs.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 cans (5 oz each) tuna in water, drained',
        '12 oz egg noodles',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 cup milk',
        '1 cup frozen peas',
        '1/2 cup shredded cheddar cheese',
        '1/2 cup breadcrumbs',
        '2 tablespoons melted butter',
        '1/2 teaspoon onion powder',
      ],
      instructions: [
        'Preheat oven to 375°F. Cook noodles 2 minutes less than package directions. Drain.',
        'In a large bowl, mix cream of mushroom soup, milk, and onion powder.',
        'Fold in flaked tuna, cooked noodles, peas, and half the cheese.',
        'Transfer to 9x13 baking dish. Top with remaining cheese.',
        'Mix breadcrumbs with melted butter; sprinkle over top. Bake 25-30 minutes until bubbly.',
      ],
      nutrition: { calories: 410, protein: 26, carbs: 48, fat: 14 },
    },
    {
      title: 'Mediterranean Tuna Pasta',
      description: 'Light pasta with canned tuna, olives, capers, tomatoes, and olive oil. Fresh Mediterranean flavors on a budget.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (5 oz each) tuna in olive oil, drained',
        '12 oz penne or spaghetti',
        '1 cup cherry tomatoes, halved',
        '1/2 cup kalamata olives, chopped',
        '2 tablespoons capers',
        '3 cloves garlic, minced',
        '1/4 cup olive oil',
        '2 tablespoons lemon juice',
        'Fresh basil and parmesan',
      ],
      instructions: [
        'Cook pasta according to package. Reserve 1/2 cup pasta water. Drain.',
        'In a large skillet, heat olive oil. Add garlic; cook 30 seconds until fragrant.',
        'Add tomatoes and sauté 2 minutes. Add olives, capers, and flaked tuna.',
        'Toss in cooked pasta, lemon juice, and pasta water. Stir to combine.',
        'Garnish with fresh basil and parmesan. Serve warm or at room temperature.',
      ],
      nutrition: { calories: 450, protein: 28, carbs: 48, fat: 16 },
    },
    {
      title: 'Lemon Garlic Tuna Pasta',
      description: 'Bright, zesty pasta with canned tuna, lemon, garlic, and parsley. Simple pantry dinner in 20 minutes.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '2 cans (5 oz each) tuna in olive oil',
        '12 oz linguine or spaghetti',
        '4 cloves garlic, minced',
        '1/4 cup olive oil',
        'Zest and juice of 2 lemons',
        '1/4 cup fresh parsley, chopped',
        '1/4 teaspoon red pepper flakes',
        'Salt and black pepper',
      ],
      instructions: [
        'Cook pasta according to package. Reserve 1/2 cup pasta water. Drain.',
        'In a large skillet, heat olive oil. Add garlic and red pepper flakes; cook 1 minute.',
        'Add flaked tuna (with oil) and lemon zest. Toss 1 minute.',
        'Add cooked pasta, lemon juice, and pasta water. Toss to coat.',
        'Stir in parsley. Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 26, carbs: 48, fat: 14 },
    },
    {
      title: 'Tuna Mac and Cheese',
      description: 'Creamy mac and cheese upgraded with flaked tuna and peas. Kids and adults love this budget-friendly twist.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (5 oz each) tuna, drained',
        '8 oz elbow macaroni',
        '2 cups shredded cheddar cheese',
        '2 tablespoons butter',
        '2 tablespoons flour',
        '2 cups milk',
        '1 cup frozen peas',
        '1/2 teaspoon mustard powder',
      ],
      instructions: [
        'Cook macaroni according to package. Drain and set aside.',
        'In same pot, melt butter. Whisk in flour; cook 1 minute.',
        'Gradually whisk in milk. Simmer until thickened, about 5 minutes.',
        'Remove from heat. Stir in cheese until melted. Add mustard.',
        'Fold in cooked macaroni, flaked tuna, and peas. Heat through. Serve hot.',
      ],
      nutrition: { calories: 520, protein: 36, carbs: 44, fat: 22 },
    },
    {
      title: 'Tuna Pasta Bake',
      description: 'Baked pasta casserole with tuna, tomato sauce, mozzarella, and a crispy cheese topping. Comforting and satisfying.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '2 cans (5 oz each) tuna, drained',
        '12 oz penne or rigatoni',
        '2 cups marinara sauce',
        '1 cup shredded mozzarella',
        '1/2 cup parmesan, grated',
        '1 cup frozen peas',
        '2 cloves garlic, minced',
        '1 teaspoon dried basil',
      ],
      instructions: [
        'Preheat oven to 375°F. Cook pasta until al dente. Drain.',
        'In a large bowl, mix marinara, garlic, and basil. Add pasta, tuna, and peas.',
        'Transfer to 9x13 baking dish. Top with mozzarella and parmesan.',
        'Bake 25-30 minutes until cheese is melted and bubbly.',
        'Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 380, protein: 28, carbs: 44, fat: 10 },
    },
    {
      title: 'Spicy Tuna Pasta with Capers',
      description: 'Quick pasta with tuna, capers, red pepper flakes, and white wine. Bold flavors for a fast weeknight dinner.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '2 cans (5 oz each) tuna in olive oil',
        '12 oz spaghetti',
        '3 tablespoons capers',
        '3 cloves garlic, minced',
        '1/2 teaspoon red pepper flakes',
        '1/4 cup white wine (or chicken broth)',
        '1/4 cup olive oil',
        'Fresh parsley and lemon wedges',
      ],
      instructions: [
        'Cook spaghetti. Reserve 1/2 cup pasta water. Drain.',
        'In a skillet, heat olive oil. Add garlic and red pepper flakes; cook 30 seconds.',
        'Add capers and wine. Simmer 2 minutes.',
        'Add flaked tuna and cooked pasta. Toss with pasta water.',
        'Garnish with parsley. Serve with lemon wedges.',
      ],
      nutrition: { calories: 440, protein: 26, carbs: 48, fat: 14 },
    },
    {
      title: 'One-Pot Tuna Pasta',
      description: 'Everything cooks in one pot—pasta, tuna, tomatoes, and spinach. Minimal cleanup, maximum flavor.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '2 cans (5 oz each) tuna, drained',
        '12 oz penne',
        '1 can (14.5 oz) diced tomatoes',
        '3 cups chicken broth',
        '2 cups fresh spinach',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon Italian seasoning',
      ],
      instructions: [
        'In a large pot, sauté onion in 1 tablespoon oil. Add garlic; cook 30 seconds.',
        'Add penne, diced tomatoes, and chicken broth. Bring to a boil.',
        'Reduce heat; simmer 12 minutes, stirring occasionally.',
        'Stir in spinach and flaked tuna. Cook 2 minutes until spinach wilts.',
        'Season with Italian seasoning, salt, and pepper. Serve with parmesan.',
      ],
      nutrition: { calories: 380, protein: 28, carbs: 50, fat: 6 },
    },
  ],

  'black-beans-rice': [
    {
      title: 'Cuban Black Beans and Rice',
      description: 'Classic Cuban comfort—tender black beans simmered with sofrito, served over fluffy white rice. Authentic and satisfying.',
      timeMinutes: 40,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 30,
      servings: 6,
      cuisine: 'Cuban',
      ingredients: [
        '2 cans (15 oz each) black beans, undrained',
        '1.5 cups long-grain white rice',
        '1 green bell pepper, diced',
        '1 small onion, diced',
        '4 cloves garlic, minced',
        '2 teaspoons cumin',
        '1 teaspoon oregano',
        '2 bay leaves',
        '2 tablespoons olive oil',
        '2 tablespoons red wine vinegar',
      ],
      instructions: [
        'Sauté onion and bell pepper in olive oil until soft. Add garlic; cook 30 seconds.',
        'Add cumin and oregano. Pour in black beans with liquid and 1/2 cup water.',
        'Add bay leaves. Simmer 20 minutes, mashing some beans to thicken.',
        'Meanwhile, cook rice according to package. Fluff and keep warm.',
        'Stir vinegar into beans. Remove bay leaves. Serve beans over rice.',
      ],
      nutrition: { calories: 320, protein: 12, carbs: 58, fat: 6 },
    },
    {
      title: 'Black Bean Rice Burritos',
      description: 'Hearty burritos with black beans, rice, cheese, and fresh toppings. Perfect for meal prep or a family dinner.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz) black beans, drained and rinsed',
        '3 cups cooked rice',
        '6 large flour tortillas',
        '1 cup shredded cheese',
        '1 teaspoon cumin',
        '1/2 teaspoon chili powder',
        '1/2 cup salsa',
        'Sour cream, avocado, and cilantro for topping',
      ],
      instructions: [
        'Warm black beans in a skillet with cumin and chili powder. Mash slightly.',
        'Warm tortillas. Spread rice on each, top with bean mixture and cheese.',
        'Roll burritos, tucking in sides. Optional: toast in skillet for crisp outside.',
        'Serve with salsa, sour cream, avocado, and cilantro.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 68, fat: 8 },
    },
    {
      title: 'Southwestern Black Bean Rice Bowl',
      description: 'Healthy bowl with seasoned black beans, cilantro lime rice, corn, and fresh toppings. Chipotle-style at home.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz) black beans, drained',
        '3 cups cooked rice',
        '2 tablespoons lime juice',
        '1/4 cup cilantro, chopped',
        '1 cup corn kernels',
        '1 avocado, diced',
        '1/2 cup salsa',
        '1 teaspoon cumin',
        'Shredded cheese and lime wedges',
      ],
      instructions: [
        'Season black beans with cumin; warm in skillet or microwave.',
        'Toss cooked rice with lime juice and cilantro.',
        'Divide rice among 4 bowls. Top with black beans, corn, avocado, and salsa.',
        'Add cheese and cilantro. Serve with lime wedges.',
      ],
      nutrition: { calories: 440, protein: 14, carbs: 72, fat: 10 },
    },
    {
      title: 'Caribbean Black Beans and Rice',
      description: 'Island-inspired one-pot with black beans, rice, coconut milk, and Scotch bonnet heat. Creamy and aromatic.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 35,
      servings: 6,
      cuisine: 'Caribbean',
      ingredients: [
        '2 cans (15 oz) black beans, drained',
        '1.5 cups long-grain rice',
        '1 can (13.5 oz) coconut milk',
        '1 cup chicken broth',
        '1 green bell pepper, diced',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 Scotch bonnet or jalapeño, minced',
        '1 teaspoon allspice',
        '2 sprigs thyme',
      ],
      instructions: [
        'Sauté onion, bell pepper, garlic, and Scotch bonnet in oil until soft.',
        'Add rice; stir 1 minute. Pour in coconut milk and broth.',
        'Add black beans, allspice, and thyme. Bring to boil; reduce heat, cover.',
        'Simmer 25 minutes until rice is tender and liquid absorbed.',
        'Remove thyme. Fluff and serve.',
      ],
      nutrition: { calories: 380, protein: 12, carbs: 58, fat: 12 },
    },
    {
      title: 'Black Bean Rice Casserole',
      description: 'Baked casserole with black beans, rice, cheese, and a crispy tortilla chip topping. Comforting and filling.',
      timeMinutes: 50,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz) black beans, drained',
        '2 cups cooked rice',
        '1 cup salsa',
        '1 cup shredded cheddar',
        '1/2 cup sour cream',
        '1 teaspoon cumin',
        '1 cup crushed tortilla chips',
        '2 tablespoons melted butter',
      ],
      instructions: [
        'Preheat oven to 375°F. Grease 9x13 baking dish.',
        'Mix black beans, rice, salsa, sour cream, cumin, and half the cheese.',
        'Transfer to baking dish. Top with remaining cheese.',
        'Mix crushed chips with butter; sprinkle over top. Bake 30 minutes.',
      ],
      nutrition: { calories: 380, protein: 14, carbs: 52, fat: 14 },
    },
    {
      title: 'Black Bean Rice Soup',
      description: 'Hearty soup with black beans, rice, tomatoes, and warming spices. Cozy one-pot meal.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'Latin American',
      ingredients: [
        '2 cans (15 oz) black beans, drained',
        '1/2 cup long-grain rice',
        '1 can (14.5 oz) diced tomatoes',
        '4 cups vegetable broth',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon cumin',
        '1/2 teaspoon chili powder',
        'Lime and cilantro for garnish',
      ],
      instructions: [
        'Sauté onion in a pot until soft. Add garlic, cumin, chili powder; cook 30 seconds.',
        'Add black beans, rice, tomatoes, and broth. Bring to boil.',
        'Reduce heat; simmer 20 minutes until rice is tender.',
        'Season with salt. Serve with lime wedges and cilantro.',
      ],
      nutrition: { calories: 220, protein: 10, carbs: 42, fat: 2 },
    },
    {
      title: 'Cilantro Lime Black Bean Rice',
      description: 'Fresh and zesty one-pot rice with black beans, lime, and cilantro. Simple side or light main.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 can (15 oz) black beans, drained',
        '1 cup long-grain rice',
        '2 cups chicken or vegetable broth',
        '2 limes (juice and zest)',
        '1/4 cup chopped cilantro',
        '1 small onion, diced',
        '2 cloves garlic, minced',
      ],
      instructions: [
        'Sauté onion in oil until soft. Add garlic; cook 30 seconds.',
        'Add rice; stir 1 minute. Pour in broth; bring to boil.',
        'Reduce heat, cover, simmer 18 minutes until rice is tender.',
        'Stir in black beans, lime juice, zest, and cilantro. Heat through. Serve.',
      ],
      nutrition: { calories: 280, protein: 10, carbs: 54, fat: 2 },
    },
    {
      title: 'Spicy Black Bean Rice Skillet',
      description: 'Quick skillet meal with black beans, rice, corn, and cheese. One-pan dinner in 25 minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '2 cans (15 oz) black beans, drained',
        '2 cups cooked rice',
        '1 cup corn kernels',
        '1 cup shredded cheese',
        '1/2 cup salsa',
        '1 teaspoon chili powder',
        '1/2 teaspoon cumin',
      ],
      instructions: [
        'Heat rice in a large skillet. Add black beans, corn, salsa, chili powder, and cumin.',
        'Stir and cook 5 minutes until heated through.',
        'Sprinkle cheese over top. Cover until melted.',
        'Serve with avocado, sour cream, and lime.',
      ],
      nutrition: { calories: 380, protein: 16, carbs: 58, fat: 8 },
    },
  ],

  'chickpeas-rice': [
    {
      title: 'Chickpea Curry with Basmati Rice',
      description: 'Creamy Indian-style chickpea curry with tomatoes and warm spices. Serve over fluffy basmati for a satisfying vegetarian meal.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Indian',
      ingredients: [
        '2 cans (15 oz) chickpeas, drained',
        '3 cups cooked basmati rice',
        '1 can (14 oz) diced tomatoes',
        '1 can (13.5 oz) coconut milk',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon curry powder',
        '1 teaspoon garam masala',
        '1 tablespoon vegetable oil',
      ],
      instructions: [
        'Sauté onion in oil until golden. Add garlic, curry powder, garam masala; cook 1 minute.',
        'Add diced tomatoes and coconut milk. Simmer 10 minutes.',
        'Stir in chickpeas. Cook 10 more minutes until sauce thickens.',
        'Season with salt. Serve over basmati rice with cilantro and lime.',
      ],
      nutrition: { calories: 450, protein: 14, carbs: 62, fat: 16 },
    },
    {
      title: 'Mediterranean Chickpea Rice Bowl',
      description: 'Bowl with chickpeas, rice, cucumber, tomato, feta, and lemon tahini. Fresh and healthy.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (15 oz) chickpeas, drained and rinsed',
        '3 cups cooked rice',
        '1 cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '1/2 cup crumbled feta',
        '1/4 cup tahini',
        '2 tablespoons lemon juice',
        '1 clove garlic, minced',
      ],
      instructions: [
        'Warm chickpeas with a pinch of salt and cumin if desired.',
        'Whisk tahini, lemon juice, garlic, and 2 tablespoons water for dressing.',
        'Divide rice among 4 bowls. Top with chickpeas, cucumber, tomatoes, and feta.',
        'Drizzle with tahini dressing. Serve with lemon wedges.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 58, fat: 14 },
    },
    {
      title: 'Chickpea Rice Pilaf',
      description: 'Fragrant Middle Eastern pilaf with chickpeas, rice, and toasted spices. One-pot vegetarian dinner.',
      timeMinutes: 35,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Middle Eastern',
      ingredients: [
        '1 can (15 oz) chickpeas, drained',
        '1.5 cups basmati rice',
        '2.5 cups vegetable broth',
        '1 onion, diced',
        '2 teaspoons cumin',
        '1/2 teaspoon turmeric',
        '1/4 cup golden raisins (optional)',
        '2 tablespoons olive oil',
      ],
      instructions: [
        'Sauté onion in olive oil until golden. Add cumin and turmeric; cook 30 seconds.',
        'Add rice; stir 1 minute. Pour in broth and chickpeas.',
        'Bring to boil; reduce heat, cover. Simmer 18 minutes.',
        'Fluff with fork. Stir in raisins if using. Serve with yogurt.',
      ],
      nutrition: { calories: 380, protein: 12, carbs: 68, fat: 8 },
    },
    {
      title: 'Indian Chickpea Rice (Chana Pulao)',
      description: 'Aromatic pulao with chickpeas, basmati rice, and whole spices. One-pot Indian comfort food.',
      timeMinutes: 40,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 30,
      servings: 6,
      cuisine: 'Indian',
      ingredients: [
        '2 cans (15 oz) chickpeas, drained',
        '2 cups basmati rice, rinsed',
        '3 cups water',
        '1 onion, sliced',
        '2 bay leaves',
        '1 cinnamon stick',
        '4 cardamom pods',
        '1 teaspoon cumin seeds',
        '2 tablespoons ghee or oil',
      ],
      instructions: [
        'Heat ghee. Toast bay leaves, cinnamon, cardamom, cumin 30 seconds.',
        'Add onion; sauté until golden. Add chickpeas and rice.',
        'Pour in water. Bring to boil; reduce heat, cover.',
        'Simmer 18 minutes until rice is tender. Let rest 5 minutes. Fluff and serve.',
      ],
      nutrition: { calories: 320, protein: 10, carbs: 58, fat: 6 },
    },
    {
      title: 'Chickpea and Rice Stuffed Peppers',
      description: 'Bell peppers stuffed with spiced chickpeas, rice, and cheese. Baked until tender and golden.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (15 oz) chickpeas, drained',
        '2 cups cooked rice',
        '4 bell peppers, tops removed and seeded',
        '1 cup marinara sauce',
        '1/2 cup shredded mozzarella',
        '1 teaspoon Italian seasoning',
        '2 cloves garlic, minced',
      ],
      instructions: [
        'Preheat oven to 375°F. Mix chickpeas, rice, marinara, half the cheese, and seasonings.',
        'Stuff mixture into peppers. Place in baking dish. Add 1/2 cup water to dish.',
        'Cover with foil. Bake 25 minutes. Uncover; top with remaining cheese. Bake 5 more minutes.',
      ],
      nutrition: { calories: 420, protein: 18, carbs: 68, fat: 8 },
    },
    {
      title: 'Chickpea Rice Soup',
      description: 'Hearty vegetarian soup with chickpeas, rice, spinach, and lemon. Comforting and wholesome.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (15 oz) chickpeas, drained',
        '1/2 cup long-grain rice',
        '6 cups vegetable broth',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '4 cups baby spinach',
        '2 tablespoons lemon juice',
        '1 teaspoon cumin',
      ],
      instructions: [
        'Sauté onion until soft. Add garlic and cumin; cook 30 seconds.',
        'Add chickpeas, rice, and broth. Bring to boil; simmer 18 minutes.',
        'Stir in spinach. Cook 2 minutes. Add lemon juice. Season and serve.',
      ],
      nutrition: { calories: 200, protein: 8, carbs: 38, fat: 2 },
    },
    {
      title: 'Chickpea Rice Stir-Fry',
      description: 'Quick stir-fry with chickpeas, rice, and vegetables in a savory sauce. Easy weeknight vegetarian dinner.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '2 cans (15 oz) chickpeas, drained',
        '3 cups cooked rice',
        '2 cups mixed vegetables (broccoli, bell pepper, snap peas)',
        '3 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '1 teaspoon sesame oil',
        '2 cloves garlic, minced',
        '1 tablespoon vegetable oil',
      ],
      instructions: [
        'Heat vegetable oil in wok. Add vegetables; stir-fry 4 minutes until crisp-tender.',
        'Add chickpeas; stir-fry 2 minutes.',
        'Add rice. Pour in soy sauce, rice vinegar, sesame oil. Toss 2 minutes.',
        'Serve immediately with green onions.',
      ],
      nutrition: { calories: 380, protein: 14, carbs: 64, fat: 6 },
    },
    {
      title: 'Coconut Chickpea Rice',
      description: 'Creamy one-pot rice with chickpeas and coconut milk. Thai-inspired and vegan.',
      timeMinutes: 35,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '1 can (15 oz) chickpeas, drained',
        '1.5 cups jasmine rice',
        '1 can (13.5 oz) coconut milk',
        '1 cup water',
        '1 red bell pepper, diced',
        '2 tablespoons lime juice',
        '1 tablespoon curry paste',
        '2 green onions, sliced',
      ],
      instructions: [
        'Combine rice, coconut milk, water, curry paste. Bring to boil.',
        'Add chickpeas and bell pepper. Reduce heat, cover. Simmer 20 minutes.',
        'Fluff rice. Stir in lime juice and green onions. Serve.',
      ],
      nutrition: { calories: 450, protein: 12, carbs: 62, fat: 18 },
    },
  ],

  'ground-turkey-rice': [
    {
      title: 'Ground Turkey Rice Bowls',
      description: 'Lean turkey over rice with broccoli and teriyaki glaze. Healthy meal prep favorite.',
      timeMinutes: 30,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb ground turkey',
        '3 cups cooked rice',
        '2 cups broccoli florets',
        '1/3 cup teriyaki sauce',
        '1 tablespoon sesame oil',
        '2 cloves garlic, minced',
        '1 teaspoon grated ginger',
        'Sesame seeds and green onions',
      ],
      instructions: [
        'Cook ground turkey in skillet until no pink remains. Add garlic and ginger; cook 1 minute.',
        'Add teriyaki sauce. Simmer 2 minutes. Set aside.',
        'Steam broccoli until tender-crisp.',
        'Divide rice among bowls. Top with turkey and broccoli. Drizzle sesame oil. Garnish.',
      ],
      nutrition: { calories: 420, protein: 36, carbs: 48, fat: 10 },
    },
    {
      title: 'Ground Turkey Fried Rice',
      description: 'Quick fried rice with lean turkey, eggs, and vegetables. Lighter than takeout.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb ground turkey',
        '3 cups cooked rice (day-old)',
        '2 eggs, beaten',
        '1 cup frozen mixed vegetables',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 green onions, sliced',
        '2 cloves garlic, minced',
      ],
      instructions: [
        'Brown turkey in wok; remove. Scramble eggs; remove.',
        'Stir-fry vegetables 2 minutes. Add rice; stir-fry 3 minutes.',
        'Return turkey and eggs. Add soy sauce and sesame oil. Toss.',
        'Garnish with green onions. Serve hot.',
      ],
      nutrition: { calories: 380, protein: 32, carbs: 42, fat: 10 },
    },
    {
      title: 'Turkey Rice Stuffed Peppers',
      description: 'Bell peppers stuffed with seasoned ground turkey, rice, and cheese. Lean and satisfying.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb ground turkey',
        '1.5 cups cooked rice',
        '4 bell peppers, tops removed and seeded',
        '1 cup marinara sauce',
        '1 cup shredded mozzarella',
        '1 teaspoon Italian seasoning',
        '1 small onion, diced',
      ],
      instructions: [
        'Brown turkey with onion. Drain. Mix with rice, marinara, half the cheese, and seasoning.',
        'Stuff peppers. Place in baking dish with 1/2 cup water. Cover with foil.',
        'Bake 375°F for 25 minutes. Uncover; top with cheese. Bake 10 more minutes.',
      ],
      nutrition: { calories: 420, protein: 38, carbs: 42, fat: 12 },
    },
    {
      title: 'Ground Turkey Rice Casserole',
      description: 'Creamy baked casserole with ground turkey, rice, and vegetables. Comfort food made lean.',
      timeMinutes: 50,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb ground turkey',
        '2 cups cooked rice',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 cup frozen mixed vegetables',
        '1 cup shredded cheddar',
        '1/2 cup milk',
        '1 teaspoon garlic powder',
      ],
      instructions: [
        'Brown turkey; drain. Preheat oven to 375°F.',
        'Mix turkey, rice, soup, vegetables, milk, garlic powder, half the cheese.',
        'Transfer to 9x13 dish. Top with remaining cheese. Bake 35 minutes.',
      ],
      nutrition: { calories: 320, protein: 28, carbs: 28, fat: 10 },
    },
    {
      title: 'Asian Ground Turkey Rice',
      description: 'Savory turkey with ginger, soy, and vegetables over rice. Quick and healthy.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1 lb ground turkey',
        '3 cups cooked rice',
        '3 tablespoons soy sauce',
        '1 tablespoon hoisin sauce',
        '1 teaspoon grated ginger',
        '2 cloves garlic, minced',
        '1 cup snap peas',
        '1 carrot, julienned',
      ],
      instructions: [
        'Brown turkey in skillet. Add garlic and ginger; cook 1 minute.',
        'Add soy sauce and hoisin. Stir in snap peas and carrot; cook 3 minutes.',
        'Serve over rice. Garnish with green onions.',
      ],
      nutrition: { calories: 380, protein: 34, carbs: 44, fat: 8 },
    },
    {
      title: 'Taco Turkey Rice Skillet',
      description: 'One-skillet taco turkey with rice, black beans, and cheese. Tex-Mex weeknight dinner.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 lb ground turkey',
        '1 cup long-grain rice',
        '2 cups chicken broth',
        '1 can (15 oz) black beans, drained',
        '1 tablespoon taco seasoning',
        '1 cup shredded cheese',
        'Salsa and avocado for topping',
      ],
      instructions: [
        'Brown turkey. Add rice, broth, taco seasoning. Bring to boil.',
        'Reduce heat, cover. Simmer 18 minutes.',
        'Stir in black beans. Top with cheese; cover until melted.',
        'Serve with salsa and avocado.',
      ],
      nutrition: { calories: 480, protein: 40, carbs: 48, fat: 14 },
    },
    {
      title: 'Ground Turkey and Rice Soup',
      description: 'Hearty soup with ground turkey, rice, carrots, and celery. Comforting and light.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb ground turkey',
        '1/2 cup long-grain rice',
        '6 cups chicken broth',
        '2 carrots, diced',
        '2 stalks celery, diced',
        '1 onion, diced',
        '1 teaspoon thyme',
        '2 tablespoons olive oil',
      ],
      instructions: [
        'Brown turkey; set aside. Sauté onion, carrots, celery in oil 5 minutes.',
        'Add broth, rice, thyme. Bring to boil; simmer 18 minutes.',
        'Return turkey. Heat through. Season. Serve with parsley.',
      ],
      nutrition: { calories: 240, protein: 22, carbs: 24, fat: 6 },
    },
    {
      title: 'Greek Turkey Rice Bowls',
      description: 'Mediterranean bowls with ground turkey, rice, cucumber, tomato, and tzatziki.',
      timeMinutes: 30,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '1 lb ground turkey',
        '3 cups cooked rice',
        '1 cucumber, diced',
        '1 cup cherry tomatoes',
        '1/2 cup tzatziki',
        '1/2 cup crumbled feta',
        '1 teaspoon oregano',
        'Lemon wedges',
      ],
      instructions: [
        'Season turkey with oregano. Cook until no pink remains.',
        'Divide rice among bowls. Top with turkey, cucumber, tomatoes.',
        'Add tzatziki and feta. Serve with lemon wedges.',
      ],
      nutrition: { calories: 440, protein: 38, carbs: 44, fat: 14 },
    },
  ],

  'sausage-potatoes': [
    {
      title: 'Sheet Pan Sausage and Potatoes',
      description: 'Easy one-pan dinner with roasted sausage, potatoes, and peppers. Minimal cleanup, maximum flavor.',
      timeMinutes: 45,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb Italian sausage links',
        '1.5 lbs baby potatoes, halved',
        '2 bell peppers, cut into chunks',
        '1 onion, cut into wedges',
        '3 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and pepper',
      ],
      instructions: [
        'Preheat oven to 425°F. Line sheet pan with parchment.',
        'Toss potatoes, peppers, onion with olive oil and seasoning. Spread on pan.',
        'Add sausage links. Roast 30 minutes, flipping halfway, until potatoes are golden and sausage cooked.',
        'Slice sausage. Serve together.',
      ],
      nutrition: { calories: 520, protein: 22, carbs: 42, fat: 32 },
    },
    {
      title: 'Sausage Potato Soup',
      description: 'Creamy, hearty soup with smoked sausage, potatoes, and vegetables. Comfort in a bowl.',
      timeMinutes: 40,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb smoked sausage, sliced',
        '4 cups potatoes, diced',
        '4 cups chicken broth',
        '1 cup heavy cream',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 cup kale or spinach',
        '1/2 teaspoon paprika',
      ],
      instructions: [
        'Brown sausage in pot; remove. Sauté onion 3 minutes. Add garlic; cook 30 seconds.',
        'Add potatoes and broth. Bring to boil; simmer 15 minutes until potatoes tender.',
        'Stir in cream and kale. Return sausage. Heat through. Season and serve.',
      ],
      nutrition: { calories: 420, protein: 18, carbs: 32, fat: 28 },
    },
    {
      title: 'Sausage and Potato Hash',
      description: 'Breakfast-style hash with sausage, crispy potatoes, and onions. Perfect for brunch or dinner.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb breakfast sausage',
        '4 cups diced potatoes',
        '1 onion, diced',
        '1 bell pepper, diced',
        '2 tablespoons vegetable oil',
        'Salt, pepper, paprika',
        '4 eggs (optional)',
      ],
      instructions: [
        'Cook sausage in skillet; remove. Add oil; cook potatoes 10 minutes until golden.',
        'Add onion and pepper; cook 5 minutes.',
        'Return sausage. Season. Optional: make wells, crack in eggs, cover until set.',
      ],
      nutrition: { calories: 480, protein: 22, carbs: 38, fat: 30 },
    },
    {
      title: 'Sausage Potato Casserole',
      description: 'Baked casserole with sausage, potatoes, cheese, and cream. Ultimate comfort food.',
      timeMinutes: 55,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 35,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 lb Italian sausage, crumbled',
        '4 cups sliced potatoes',
        '1.5 cups shredded cheddar',
        '1 cup heavy cream',
        '1/2 cup sour cream',
        '1 teaspoon garlic powder',
        'Salt and pepper',
      ],
      instructions: [
        'Preheat oven to 375°F. Brown sausage; drain.',
        'Layer half the potatoes in 9x13 dish. Top with half the sausage and cheese.',
        'Repeat layers. Mix cream, sour cream, garlic; pour over. Cover with foil.',
        'Bake 30 minutes. Uncover; bake 15 more minutes until golden.',
      ],
      nutrition: { calories: 520, protein: 24, carbs: 28, fat: 36 },
    },
    {
      title: 'Roasted Sausage and Potatoes',
      description: 'Simple roasted dinner with sausage, potatoes, and herbs. Hands-off and delicious.',
      timeMinutes: 50,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 40,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb kielbasa or smoked sausage, sliced',
        '1.5 lbs red potatoes, quartered',
        '3 tablespoons olive oil',
        '1 teaspoon garlic powder',
        '1 teaspoon paprika',
        'Fresh rosemary',
      ],
      instructions: [
        'Preheat oven to 400°F. Toss potatoes with oil and seasonings.',
        'Spread on sheet pan. Roast 25 minutes.',
        'Add sausage. Roast 15 more minutes until potatoes are crisp.',
      ],
      nutrition: { calories: 520, protein: 20, carbs: 42, fat: 32 },
    },
    {
      title: 'Sausage Potato Skillet',
      description: 'One-skillet meal with sausage, potatoes, and peppers. Quick weeknight dinner.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb Italian sausage, sliced',
        '4 cups diced potatoes',
        '1 bell pepper, sliced',
        '1 onion, sliced',
        '2 cloves garlic, minced',
        '1/2 cup chicken broth',
      ],
      instructions: [
        'Brown sausage; remove. Sauté potatoes 10 minutes until starting to soften.',
        'Add pepper and onion; cook 5 minutes. Add garlic.',
        'Return sausage. Add broth. Cover; simmer 10 minutes.',
      ],
      nutrition: { calories: 460, protein: 22, carbs: 38, fat: 28 },
    },
    {
      title: 'Cajun Sausage and Potatoes',
      description: 'Spicy sheet pan dinner with Cajun sausage, potatoes, and corn. Bold and flavorful.',
      timeMinutes: 45,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Cajun',
      ingredients: [
        '1 lb andouille sausage, sliced',
        '1.5 lbs potatoes, cubed',
        '2 ears corn, cut into rounds',
        '2 tablespoons Cajun seasoning',
        '3 tablespoons olive oil',
        '1 bell pepper, diced',
      ],
      instructions: [
        'Preheat oven to 425°F. Toss potatoes, corn, pepper with oil and Cajun seasoning.',
        'Spread on sheet pan. Add sausage. Roast 30 minutes, stirring halfway.',
      ],
      nutrition: { calories: 540, protein: 22, carbs: 48, fat: 32 },
    },
    {
      title: 'Sausage Potato and Green Bean Sheet Pan',
      description: 'Complete sheet pan dinner with sausage, potatoes, and green beans. Easy and balanced.',
      timeMinutes: 45,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 lb Italian sausage',
        '1 lb baby potatoes, halved',
        '1 lb green beans, trimmed',
        '3 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and pepper',
      ],
      instructions: [
        'Preheat oven to 425°F. Toss potatoes with oil and half the seasoning.',
        'Roast 15 minutes. Add sausage and green beans. Toss with remaining seasoning.',
        'Roast 15 more minutes until everything is golden and tender.',
      ],
      nutrition: { calories: 480, protein: 22, carbs: 38, fat: 30 },
    },
  ],
}

export const comboFaqsNew2: Record<string, FAQ[]> = {
  'rotisserie-chicken-rice': [
    {
      question: 'How long does rotisserie chicken and rice last in the fridge?',
      answer: 'Shredded rotisserie chicken and cooked rice both last 3-4 days when stored properly in airtight containers. Combine them in a prepared dish and refrigerate within 2 hours of cooking for best results.',
    },
    {
      question: 'Can I use rotisserie chicken for fried rice?',
      answer: 'Yes! Rotisserie chicken is perfect for fried rice since it\'s already cooked. Simply shred or dice it and add it during the last minute of stir-frying so it heats through without overcooking. It saves time and adds great flavor.',
    },
    {
      question: 'What rice goes best with rotisserie chicken?',
      answer: 'White rice, jasmine rice, and basmati rice all pair well. For burrito bowls, cilantro lime rice is popular. For soup, long-grain rice holds up best. Day-old rice works best for fried rice.',
    },
    {
      question: 'How do I reheat rotisserie chicken and rice?',
      answer: 'Microwave in a covered dish with a splash of water or broth to prevent drying out. For larger portions, reheat in a skillet over medium heat with a bit of oil or sauce. Stir occasionally until heated through.',
    },
    {
      question: 'What can I make with rotisserie chicken and rice besides soup?',
      answer: 'Popular options include burrito bowls, fried rice, teriyaki bowls, Greek bowls, BBQ skillet, and creamy casseroles. Pre-cooked chicken makes all of these fast since you skip the cooking step.',
    },
  ],
  'canned-tuna-pasta': [
    {
      question: 'What pasta is best for tuna pasta?',
      answer: 'Short shapes like penne, elbow macaroni, rotini, and shell pasta hold the tuna and sauce well. For cold salads, rotini and elbow are classic. For hot dishes, penne and rigatoni work great.',
    },
    {
      question: 'Should I use tuna in oil or water for pasta?',
      answer: 'Tuna in olive oil adds more flavor and richness, especially for Mediterranean-style dishes. Tuna in water is lighter and works well for creamy casseroles and mac and cheese where you\'re adding your own fat.',
    },
    {
      question: 'Can I make tuna pasta ahead of time?',
      answer: 'Yes. Tuna pasta salad benefits from chilling for 30 minutes to let flavors meld. Hot tuna casseroles can be assembled ahead and refrigerated up to 24 hours before baking. Add a few minutes to bake time if cold.',
    },
    {
      question: 'How do I make tuna pasta less dry?',
      answer: 'Reserve pasta water when draining and add a splash to the sauce. For salads, use enough mayonnaise or dressing to coat everything. For bakes, include a creamy element like cream of mushroom soup or cheese sauce.',
    },
    {
      question: 'What vegetables go well with tuna pasta?',
      answer: 'Peas, celery, and corn are classics. Mediterranean options include olives, capers, tomatoes, and artichokes. Spinach, broccoli, and bell peppers also pair well. Frozen peas are convenient and thaw quickly.',
    },
  ],
  'black-beans-rice': [
    {
      question: 'Do I need to soak canned black beans for rice?',
      answer: 'No. Canned black beans are already cooked and ready to use. Simply drain and rinse them to reduce sodium, then add to your recipe. Dried beans require soaking and longer cooking times.',
    },
    {
      question: 'What is the ratio of black beans to rice?',
      answer: 'A common ratio is 1 can (15 oz) black beans to 1-1.5 cups uncooked rice (or 3 cups cooked). For heartier dishes, use 2 cans of beans. Adjust based on whether you want beans as a side or the main component.',
    },
    {
      question: 'How do I make Cuban black beans and rice?',
      answer: 'Sauté onion, bell pepper, and garlic (sofrito), add cumin and oregano, then simmer black beans with their liquid. Mash some beans to thicken. Serve over white rice with a splash of vinegar. Bay leaves add traditional flavor.',
    },
    {
      question: 'Can I use brown rice with black beans?',
      answer: 'Yes. Brown rice works well with black beans and adds fiber. Cook it separately or use a one-pot method with extra liquid and longer cook time (about 40-45 minutes for brown rice).',
    },
    {
      question: 'Are black beans and rice a complete protein?',
      answer: 'Yes. Together, black beans and rice provide all nine essential amino acids, making them a complete protein source. This makes the combo popular for vegetarian and vegan diets.',
    },
  ],
  'chickpeas-rice': [
    {
      question: 'Are chickpeas and rice healthy?',
      answer: 'Yes. Chickpeas provide protein, fiber, and minerals. Rice offers energy and pairs well for a balanced meal. Together they form a complete protein, ideal for vegetarian and vegan diets.',
    },
    {
      question: 'What cuisines use chickpeas and rice?',
      answer: 'Indian (chana pulao, chickpea curry), Middle Eastern (pilaf, rice bowls), Mediterranean (Greek bowls), and Thai (coconut chickpea rice). The combo is versatile across many cultures.',
    },
    {
      question: 'Can I use dried chickpeas instead of canned?',
      answer: 'Yes, but dried chickpeas need soaking overnight and 1-2 hours of cooking. Canned chickpeas are convenient—drain, rinse, and add. One 15-oz can equals about 1.5 cups cooked chickpeas.',
    },
    {
      question: 'What spices go with chickpeas and rice?',
      answer: 'Cumin, turmeric, curry powder, and garam masala work for Indian flavors. For Mediterranean, try oregano, lemon, and garlic. Cinnamon and allspice suit Middle Eastern pilafs.',
    },
    {
      question: 'How do I make chickpea curry with rice?',
      answer: 'Sauté aromatics, add curry spices, then diced tomatoes and coconut milk. Simmer, add chickpeas, and cook until sauce thickens. Serve over basmati or jasmine rice. Garam masala adds depth.',
    },
  ],
  'ground-turkey-rice': [
    {
      question: 'Is ground turkey and rice good for meal prep?',
      answer: 'Yes. Ground turkey is lean and affordable, and rice reheats well. Prepare bowls or casseroles and portion into containers. They keep 4-5 days in the fridge and freeze well for up to 3 months.',
    },
    {
      question: 'How do I keep ground turkey from drying out with rice?',
      answer: 'Don\'t overcook the turkey—cook just until no pink remains. Add moisture with sauces, broth, or cream. Mixing turkey with rice in a casserole or saucy skillet helps retain moisture.',
    },
    {
      question: 'What seasonings work best for ground turkey and rice?',
      answer: 'For Asian: soy sauce, ginger, teriyaki. For Mexican: taco seasoning, cumin, chili powder. For Greek: oregano, lemon. For Italian: garlic, basil, marinara. Ground turkey is versatile and takes on flavors well.',
    },
    {
      question: 'Can I use ground turkey instead of ground beef in rice recipes?',
      answer: 'Yes. Ground turkey is a lean swap for ground beef in most rice recipes—bowls, casseroles, stuffed peppers, and skillets. Use 93% lean for best texture; 99% lean can be drier.',
    },
    {
      question: 'How long does ground turkey and rice take to cook?',
      answer: 'Most ground turkey and rice recipes take 25-40 minutes. Skillet and bowl dishes are fastest (25-30 min). Casseroles and stuffed peppers need 45-55 minutes including baking time.',
    },
  ],
  'sausage-potatoes': [
    {
      question: 'What type of sausage is best with potatoes?',
      answer: 'Italian sausage (sweet or hot), smoked sausage, kielbasa, and andouille all work well. Italian and breakfast sausage suit casseroles and hash. Smoked sausage and kielbasa are great for sheet pans and soup.',
    },
    {
      question: 'How long to roast sausage and potatoes?',
      answer: 'At 425°F, roast 30-40 minutes total. Cut potatoes small for faster cooking. Add sausage after 15-20 minutes if it cooks faster than potatoes, or roast together if sizes are similar.',
    },
    {
      question: 'Can I make sausage and potatoes in a slow cooker?',
      answer: 'Yes. Combine sausage, potatoes, and broth in a slow cooker. Cook on high 4 hours or low 6-7 hours. Add cream or cheese at the end for a creamy version. Cut potatoes into chunks for even cooking.',
    },
    {
      question: 'What vegetables go with sausage and potatoes?',
      answer: 'Bell peppers, onions, and green beans are popular. Broccoli, zucchini, and carrots also work. For sheet pans, choose vegetables that roast in similar time—peppers and onions match well.',
    },
    {
      question: 'Why are my potatoes not crispy with sausage?',
      answer: 'Crowding the pan causes steaming. Spread in a single layer with space between pieces. Use high heat (425°F). Parboil potatoes 5 minutes before roasting for crispier results. Don\'t add too much oil.',
    },
  ],
}
