import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const comboRecipesNew1: Record<string, RecipeIdea[]> = {
  'chicken-breast-potatoes': [
    {
      title: 'One-Pan Herb-Roasted Chicken and Potatoes',
      description: 'Juicy chicken breasts and golden roasted potatoes with fresh rosemary and thyme on one pan. Minimal cleanup, maximum flavor.',
      timeMinutes: 50,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless, skinless chicken breasts, halved horizontally',
        '1.5 pounds baby potatoes, halved',
        '3 tablespoons olive oil',
        '2 tablespoons fresh rosemary, chopped',
        '1 tablespoon fresh thyme leaves',
        '4 cloves garlic, minced',
        '1 teaspoon paprika',
        'Salt and black pepper to taste',
        'Lemon wedges for serving',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment paper.',
        'In a large bowl, toss halved potatoes with 1 tablespoon olive oil, half the rosemary, thyme, salt, and pepper. Spread on one side of the sheet pan.',
        'Season chicken breasts with paprika, remaining olive oil, salt, and pepper. Place on the sheet pan beside the potatoes.',
        'Sprinkle everything with remaining herbs and minced garlic.',
        'Roast for 25-30 minutes until chicken reaches 165°F internally and potatoes are tender and golden.',
        'Let rest 5 minutes. Serve with lemon wedges.',
      ],
      nutrition: { calories: 440, protein: 38, carbs: 35, fat: 16 },
    },
    {
      title: 'Loaded Potato Chicken Bake',
      description: 'Tender chicken breast nestled with crispy potato wedges, bacon, cheese, and sour cream. A comfort-food casserole the whole family will love.',
      timeMinutes: 50,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 large chicken breasts, cut into bite-sized chunks',
        '1.5 pounds russet potatoes, cut into wedges',
        '6 strips bacon, cooked and crumbled',
        '1 cup shredded cheddar cheese',
        '1/2 cup sour cream',
        '2 green onions, sliced',
        '2 tablespoons olive oil',
        '1 teaspoon garlic powder',
        '1/2 teaspoon paprika',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C). Grease a 9x13-inch baking dish.',
        'In a bowl, toss potato wedges with olive oil, garlic powder, paprika, salt, and pepper. Spread in the baking dish and bake for 15 minutes.',
        'Season chicken chunks with salt and pepper. Add chicken to the potatoes and stir to combine. Bake another 15 minutes until chicken is cooked through and potatoes are tender.',
        'Top with shredded cheddar and crumbled bacon. Return to oven for 5 minutes until cheese melts.',
        'Serve with dollops of sour cream and sprinkled green onions.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 32, fat: 20 },
    },
    {
      title: 'Creamy Chicken and Potato Soup',
      description: 'Hearty soup with shredded chicken, tender potato chunks, carrots, and celery in a silky cream broth. Perfect for chilly nights.',
      timeMinutes: 45,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 large chicken breasts',
        '1.5 pounds potatoes, diced',
        '3 cups chicken broth',
        '1 cup heavy cream',
        '1 cup diced carrots',
        '1 cup diced celery',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '2 tablespoons butter',
        '1 teaspoon dried thyme',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Melt butter in a large pot over medium heat. Add onion, carrots, and celery. Sauté for 5 minutes until softened. Add garlic and cook 30 seconds.',
        'Pour in chicken broth and bring to a boil. Add potatoes and chicken breasts. Simmer for 15-20 minutes until chicken reaches 165°F and potatoes are tender.',
        'Remove chicken and shred with two forks. Return to the pot.',
        'Stir in heavy cream and thyme. Simmer 5 more minutes. Season with salt and pepper. Serve hot.',
      ],
      nutrition: { calories: 380, protein: 26, carbs: 28, fat: 18 },
    },
    {
      title: 'Greek-Style Chicken and Potato Sheet Pan',
      description: 'Mediterranean-inspired sheet pan dinner with lemon-oregano chicken, roasted potatoes, olives, and feta. Bright and satisfying.',
      timeMinutes: 50,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '2 large chicken breasts, cut into strips',
        '1.5 pounds baby potatoes, halved',
        '1/4 cup olive oil',
        '3 tablespoons lemon juice',
        '2 teaspoons dried oregano',
        '3 cloves garlic, minced',
        '1/2 cup kalamata olives, halved',
        '1/2 cup crumbled feta cheese',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Line a sheet pan with parchment paper.',
        'Whisk together olive oil, lemon juice, oregano, garlic, salt, and pepper. Toss potatoes with half the mixture and spread on the pan.',
        'Toss chicken strips with the remaining mixture. Arrange beside potatoes.',
        'Roast for 30-35 minutes until chicken reaches 165°F and potatoes are golden and tender.',
        'Top with kalamata olives and crumbled feta. Serve with lemon wedges.',
      ],
      nutrition: { calories: 450, protein: 34, carbs: 38, fat: 18 },
    },
    {
      title: 'Cajun Chicken and Potato Skillet',
      description: 'Spicy one-skillet meal with Cajun-seasoned chicken breast and crispy pan-roasted potatoes. Bold, hearty, and ready in 35 minutes.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 large chicken breasts, sliced into cutlets',
        '1 pound red potatoes, diced',
        '2 tablespoons olive oil',
        '2 tablespoons Cajun seasoning',
        '1 bell pepper, diced',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon olive oil in a large skillet over medium-high heat. Add diced potatoes and cook 10-12 minutes, stirring occasionally, until golden and tender. Remove and set aside.',
        'Season chicken with Cajun seasoning, salt, and pepper. Add remaining oil to skillet. Cook chicken 5-6 minutes per side until 165°F. Remove and set aside.',
        'In same skillet, sauté bell pepper and onion for 3-4 minutes. Add garlic and cook 30 seconds.',
        'Return potatoes and chicken to skillet. Toss everything together and serve.',
      ],
      nutrition: { calories: 360, protein: 32, carbs: 32, fat: 12 },
    },
    {
      title: 'Chicken Potato Curry',
      description: 'Indian-inspired curry with tender chicken, potato chunks, and spinach in a aromatic tomato-coconut sauce. Serve over rice or with naan.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Indian',
      ingredients: [
        '2 large chicken breasts, cubed',
        '2 medium potatoes, peeled and cubed',
        '1 can (14 oz) diced tomatoes',
        '1/2 cup coconut milk',
        '2 cups fresh spinach',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon curry powder',
        '1 teaspoon garam masala',
        '1 tablespoon vegetable oil',
        'Salt to taste',
      ],
      instructions: [
        'Heat oil in a large skillet over medium heat. Add onion and cook 4 minutes. Add garlic, curry powder, and garam masala. Cook 1 minute.',
        'Add chicken and potato cubes. Stir to coat in spices. Cook 3-4 minutes.',
        'Pour in diced tomatoes and coconut milk. Bring to a simmer. Cover and cook 15-20 minutes until potatoes are tender and chicken is cooked through.',
        'Stir in spinach until wilted. Season with salt. Serve hot.',
      ],
      nutrition: { calories: 390, protein: 30, carbs: 35, fat: 15 },
    },
    {
      title: 'Slow Cooker Chicken and Potato Stew',
      description: 'Set-it-and-forget-it comfort stew with tender chicken breast, potatoes, carrots, and peas in a rich broth. Come home to a ready dinner.',
      timeMinutes: 360,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 345,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds boneless, skinless chicken breast, cubed',
        '1.5 pounds potatoes, cubed',
        '2 carrots, sliced',
        '1 cup frozen peas',
        '4 cups chicken broth',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '2 tablespoons cornstarch mixed with 2 tablespoons water',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Place cubed chicken breast, potatoes, carrots, onion, and garlic in slow cooker.',
        'Add chicken broth, thyme, salt, and pepper. Cover and cook on low for 6 hours or high for 3 hours.',
        'Stir to break up the chicken into chunks. Add frozen peas and cornstarch slurry.',
        'Cover and cook 15 more minutes until thickened. Taste and adjust seasoning. Serve hot.',
      ],
      nutrition: { calories: 320, protein: 32, carbs: 32, fat: 6 },
    },
    {
      title: 'Baked Chicken Stuffed Potatoes',
      description: 'Fluffy baked potatoes stuffed with seasoned shredded chicken, cheese, and green onions. A fun twist on loaded potatoes.',
      timeMinutes: 75,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 55,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 large russet potatoes',
        '2 large chicken breasts, cooked and shredded',
        '1 cup shredded cheddar cheese',
        '1/2 cup sour cream',
        '2 green onions, sliced',
        '2 tablespoons butter',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C). Scrub potatoes and prick with a fork. Bake directly on rack for 50-60 minutes until tender.',
        'While potatoes bake, season shredded chicken with garlic powder, salt, and pepper. Heat in a skillet if needed.',
        'Cut potatoes in half lengthwise and scoop out flesh, leaving a 1/4-inch shell. Mash the flesh with butter, sour cream, salt, and pepper.',
        'Mix in shredded chicken and half the cheese. Stuff back into potato skins. Top with remaining cheese.',
        'Return to oven for 10 minutes until cheese melts. Garnish with green onions.',
      ],
      nutrition: { calories: 520, protein: 36, carbs: 48, fat: 22 },
    },
  ],

  'pork-chops-rice': [
    {
      title: 'Smothered Pork Chops over Rice',
      description: 'Southern-style pork chops smothered in savory gravy with onions and bell peppers. Served over fluffy white rice for the ultimate comfort meal.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'Southern',
      ingredients: [
        '4 bone-in pork chops, about 1 inch thick',
        '2 cups cooked white rice',
        '1 large onion, sliced',
        '1 bell pepper, sliced',
        '2 cups chicken broth',
        '2 tablespoons all-purpose flour',
        '2 tablespoons vegetable oil',
        '2 cloves garlic, minced',
        '1 teaspoon paprika',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season pork chops with paprika, salt, and pepper. Heat oil in a large skillet over medium-high heat. Brown chops 3-4 minutes per side. Remove and set aside.',
        'In same skillet, sauté onion and bell pepper for 5 minutes. Add garlic and flour. Cook 1 minute, stirring.',
        'Gradually whisk in chicken broth. Bring to a simmer. Return pork chops to skillet.',
        'Cover and simmer 15-20 minutes until pork reaches 145°F. Serve over rice with gravy.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 38, fat: 16 },
    },
    {
      title: 'Teriyaki Pork Chops with Rice',
      description: 'Sweet and sticky teriyaki-glazed pork chops served over steamed jasmine rice with broccoli. Better than takeout.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Japanese',
      ingredients: [
        '4 boneless pork chops',
        '3 cups cooked jasmine rice',
        '1/3 cup soy sauce',
        '3 tablespoons honey',
        '2 tablespoons rice vinegar',
        '1 tablespoon cornstarch mixed with 2 tablespoons water',
        '2 cloves garlic, minced',
        '1 teaspoon grated ginger',
        '2 cups broccoli florets',
        '1 tablespoon vegetable oil',
      ],
      instructions: [
        'Whisk soy sauce, honey, rice vinegar, garlic, and ginger in a bowl. Set aside.',
        'Heat oil in a large skillet over medium-high heat. Sear pork chops 4-5 minutes per side until 145°F. Remove and rest.',
        'Steam broccoli until tender-crisp. Set aside.',
        'Pour teriyaki sauce into skillet. Add cornstarch slurry and simmer until thickened. Return pork to coat.',
        'Serve pork over rice with steamed broccoli and extra sauce.',
      ],
      nutrition: { calories: 480, protein: 34, carbs: 52, fat: 12 },
    },
    {
      title: 'One-Pan Pork Chops and Rice',
      description: 'Pork chops and rice cook together in one pan with mushrooms and onions. Easy weeknight dinner with minimal cleanup.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless pork chops',
        '1.5 cups long-grain white rice',
        '2.5 cups chicken broth',
        '1 cup sliced mushrooms',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season pork chops with salt and pepper. Heat 1 tablespoon oil in a large deep skillet. Sear chops 2-3 minutes per side. Remove.',
        'Add remaining oil. Sauté onion and mushrooms 5 minutes. Add garlic and rice. Stir 1 minute.',
        'Pour in broth and thyme. Nestle pork chops into rice. Bring to boil, reduce heat, cover.',
        'Simmer 20-25 minutes until rice is tender and pork reaches 145°F. Rest 5 minutes before serving.',
      ],
      nutrition: { calories: 460, protein: 32, carbs: 52, fat: 12 },
    },
    {
      title: 'Baked Pork Chop Rice Casserole',
      description: 'Creamy rice casserole with seasoned pork chops baked in a mushroom soup and cheese sauce. Old-fashioned comfort in one dish.',
      timeMinutes: 55,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 40,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '6 bone-in pork chops',
        '1.5 cups uncooked long-grain rice',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 can (10.5 oz) chicken broth',
        '1 cup sour cream',
        '1 cup shredded cheddar cheese',
        '1 packet dry onion soup mix',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 350°F (175°C). Grease a 9x13-inch baking dish.',
        'Mix rice, cream of mushroom soup, chicken broth, sour cream, and half the cheese. Spread in dish.',
        'Season pork chops with salt and pepper. Place on top of rice mixture. Sprinkle with onion soup mix.',
        'Cover tightly with foil. Bake 40-45 minutes until rice is tender and pork reaches 145°F.',
        'Uncover, top with remaining cheese. Bake 5 more minutes. Rest 5 minutes before serving.',
      ],
      nutrition: { calories: 520, protein: 36, carbs: 42, fat: 24 },
    },
    {
      title: 'Asian Pork Chop Rice Bowls',
      description: 'Grilled pork chops with hoisin glaze over rice with pickled cucumbers and scallions. A restaurant-style bowl at home.',
      timeMinutes: 30,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '4 boneless pork chops',
        '3 cups cooked white rice',
        '1/4 cup hoisin sauce',
        '2 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '1 cucumber, thinly sliced',
        '4 green onions, sliced',
        '1 teaspoon sesame oil',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'Mix hoisin, soy sauce, and rice vinegar. Brush half onto pork chops. Grill or pan-sear 4-5 minutes per side until 145°F.',
        'Toss cucumber with rice vinegar and a pinch of sugar for quick pickle.',
        'Divide rice among bowls. Top with sliced pork, cucumber, and green onions.',
        'Drizzle with remaining sauce and sesame oil. Sprinkle sesame seeds.',
      ],
      nutrition: { calories: 450, protein: 34, carbs: 48, fat: 12 },
    },
    {
      title: 'Mediterranean Pork Chops with Rice',
      description: 'Herb-crusted pork chops served over lemon rice with tomatoes and olives. Fresh and bright Mediterranean flavors.',
      timeMinutes: 40,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '4 boneless pork chops',
        '2 cups cooked rice',
        '2 tablespoons lemon juice',
        '2 cloves garlic, minced',
        '1 teaspoon dried oregano',
        '1 cup cherry tomatoes, halved',
        '1/2 cup kalamata olives',
        '2 tablespoons olive oil',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Season pork with oregano, salt, and pepper. Heat 1 tablespoon oil in skillet. Cook chops 5-6 minutes per side until 145°F. Remove.',
        'In same pan, add remaining oil. Sauté garlic 30 seconds. Add rice, lemon juice, tomatoes, and olives. Toss to warm.',
        'Serve pork over lemon rice. Garnish with parsley.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 38, fat: 16 },
    },
    {
      title: 'Instant Pot Pork Chops and Rice',
      description: 'Tender pork chops and fluffy rice pressure-cooked in 20 minutes. Perfect for busy nights when you need dinner fast.',
      timeMinutes: 25,
      method: 'instant-pot',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless pork chops',
        '1.5 cups long-grain rice',
        '2 cups chicken broth',
        '1 packet dry onion soup mix',
        '2 tablespoons butter',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Add rice, broth, and onion soup mix to Instant Pot. Stir. Place pork chops on top. Season with salt and pepper. Dot with butter.',
        'Seal lid. Cook on high pressure 8 minutes. Natural release 10 minutes.',
        'Remove pork and fluff rice. Serve pork over rice with pan juices.',
      ],
      nutrition: { calories: 440, protein: 32, carbs: 48, fat: 12 },
    },
    {
      title: 'Creamy Mushroom Pork Chops over Rice',
      description: 'Pork chops in a rich mushroom cream sauce served over steamed rice. Elegant enough for company, easy enough for weeknights.',
      timeMinutes: 40,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless pork chops',
        '3 cups cooked white rice',
        '8 oz sliced mushrooms',
        '1 cup heavy cream',
        '1/2 cup chicken broth',
        '2 cloves garlic, minced',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
        '1 tablespoon fresh thyme',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season pork with salt and pepper. Heat olive oil in large skillet. Sear chops 4-5 minutes per side. Remove.',
        'Melt butter in same pan. Sauté mushrooms 5 minutes. Add garlic and thyme. Cook 30 seconds.',
        'Pour in broth and cream. Simmer 5 minutes. Return pork to pan. Cook 2-3 minutes. Serve over rice.',
      ],
      nutrition: { calories: 520, protein: 34, carbs: 42, fat: 26 },
    },
  ],

  'sausage-rice': [
    {
      title: 'Cajun Jambalaya',
      description: 'Classic one-pot jambalaya with smoked sausage, chicken, rice, and the Holy Trinity. Bold, spicy, and deeply satisfying.',
      timeMinutes: 50,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 35,
      servings: 6,
      cuisine: 'Cajun',
      ingredients: [
        '1 pound smoked sausage, sliced',
        '1.5 cups long-grain rice',
        '3 cups chicken broth',
        '1 large onion, diced',
        '2 celery stalks, diced',
        '1 bell pepper, diced',
        '3 cloves garlic, minced',
        '1 can (14 oz) diced tomatoes',
        '2 tablespoons Cajun seasoning',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat oil in a large Dutch oven. Add sausage and brown 5 minutes. Remove.',
        'Sauté onion, celery, and bell pepper 5 minutes. Add garlic and Cajun seasoning. Cook 1 minute.',
        'Add rice, diced tomatoes, and chicken broth. Bring to boil. Reduce heat, cover, simmer 25 minutes.',
        'Return sausage. Stir and cook 5 more minutes. Fluff and serve.',
      ],
      nutrition: { calories: 480, protein: 18, carbs: 48, fat: 22 },
    },
    {
      title: 'Dirty Rice with Sausage',
      description: 'Louisiana-style dirty rice with ground sausage, aromatics, and Cajun spices. Savory, hearty, and perfect with greens.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Southern',
      ingredients: [
        '1 pound ground pork sausage',
        '2 cups cooked long-grain rice',
        '1 onion, diced',
        '2 celery stalks, diced',
        '1 bell pepper, diced',
        '4 cloves garlic, minced',
        '2 tablespoons butter',
        '2 teaspoons Cajun seasoning',
        '1/2 cup chicken broth',
        '2 green onions, sliced',
      ],
      instructions: [
        'Brown sausage in a large skillet over medium-high heat. Break into crumbles. Remove and set aside, leave 2 tablespoons fat.',
        'Sauté onion, celery, and bell pepper in fat 6 minutes. Add garlic and Cajun seasoning. Cook 1 minute.',
        'Return sausage. Add cooked rice and broth. Stir and cook 5 minutes until heated through.',
        'Garnish with green onions. Serve hot.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 38, fat: 24 },
    },
    {
      title: 'Sausage and Rice Casserole',
      description: 'Cheesy baked casserole with smoked sausage, rice, peppers, and onions. Comfort food that feeds a crowd.',
      timeMinutes: 55,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 40,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 pound smoked sausage, sliced',
        '2 cups cooked rice',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 cup shredded cheddar cheese',
        '1 bell pepper, diced',
        '1 onion, diced',
        '1/2 cup milk',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F (190°C). Grease a 9x13-inch baking dish.',
        'In a large bowl, mix rice, soup, milk, half the cheese, pepper, onion, garlic powder, salt, and pepper.',
        'Fold in sausage slices. Transfer to baking dish. Top with remaining cheese.',
        'Bake 35-40 minutes until bubbly and golden. Rest 5 minutes.',
      ],
      nutrition: { calories: 480, protein: 18, carbs: 38, fat: 28 },
    },
    {
      title: 'Smoked Sausage Rice Skillet',
      description: 'One-skillet meal with kielbasa, rice, and veggies. Quick, filling, and perfect for busy weeknights.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '14 oz smoked sausage, sliced',
        '1.5 cups long-grain rice',
        '2.5 cups chicken broth',
        '1 cup frozen mixed vegetables',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon paprika',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat oil in a large skillet. Brown sausage slices 3-4 minutes. Remove.',
        'Sauté onion 4 minutes. Add garlic and rice. Stir 1 minute.',
        'Add broth, vegetables, paprika, salt, and pepper. Bring to boil. Reduce heat, cover, simmer 18 minutes.',
        'Return sausage. Fluff and serve.',
      ],
      nutrition: { calories: 520, protein: 18, carbs: 52, fat: 24 },
    },
    {
      title: 'Italian Sausage Rice Bowls',
      description: 'Spicy Italian sausage with peppers and onions over rice, topped with marinara and parmesan. A satisfying one-bowl meal.',
      timeMinutes: 35,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 pound Italian sausage, casings removed',
        '3 cups cooked rice',
        '1 bell pepper, sliced',
        '1 onion, sliced',
        '1 cup marinara sauce',
        '1/2 cup grated parmesan',
        '2 cloves garlic, minced',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat oil in skillet. Brown sausage, breaking into crumbles. Remove.',
        'Sauté bell pepper and onion 6 minutes. Add garlic 30 seconds.',
        'Return sausage. Add marinara. Simmer 5 minutes.',
        'Serve over rice. Top with parmesan.',
      ],
      nutrition: { calories: 580, protein: 22, carbs: 52, fat: 32 },
    },
    {
      title: 'One-Pot Sausage and Rice',
      description: 'Simplest sausage and rice combo: everything cooks together in one pot with minimal effort. Weeknight winner.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 pound smoked sausage, sliced',
        '1.5 cups long-grain rice',
        '2.5 cups chicken broth',
        '1 teaspoon onion powder',
        '1/2 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Combine all ingredients in a large pot. Bring to boil over high heat.',
        'Reduce to low, cover tightly. Simmer 20 minutes until rice is tender and liquid absorbed.',
        'Fluff with fork. Serve.',
      ],
      nutrition: { calories: 520, protein: 18, carbs: 48, fat: 26 },
    },
    {
      title: 'Spanish Sausage and Rice (Arroz con Chorizo)',
      description: 'Spanish-style rice with chorizo, tomatoes, and saffron. Bold, flavorful, and perfect for dinner or meal prep.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'Spanish',
      ingredients: [
        '12 oz Spanish chorizo, sliced',
        '1.5 cups arborio or short-grain rice',
        '3 cups chicken broth',
        '1 can (14 oz) diced tomatoes',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1/2 teaspoon saffron threads',
        '2 tablespoons olive oil',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Heat oil in large pan. Brown chorizo 4 minutes. Remove.',
        'Sauté onion 5 minutes. Add garlic and rice. Toast 2 minutes.',
        'Add tomatoes, broth, and saffron. Bring to boil. Reduce heat, cover, simmer 25 minutes.',
        'Return chorizo. Fluff. Garnish with parsley.',
      ],
      nutrition: { calories: 580, protein: 20, carbs: 52, fat: 32 },
    },
    {
      title: 'Sausage Fried Rice',
      description: 'Smoked sausage in classic fried rice with eggs, peas, and soy sauce. A quick dinner that beats takeout.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '12 oz smoked sausage, diced',
        '3 cups day-old cooked rice',
        '2 large eggs, beaten',
        '1 cup frozen peas',
        '3 green onions, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '2 cloves garlic, minced',
      ],
      instructions: [
        'Heat 1 tablespoon oil in wok over high heat. Scramble eggs. Remove.',
        'Add sausage. Cook 3 minutes. Add remaining oil, rice, peas. Stir-fry 4 minutes.',
        'Add garlic, soy sauce, sesame oil. Return eggs. Toss. Garnish with green onions.',
      ],
      nutrition: { calories: 520, protein: 20, carbs: 48, fat: 26 },
    },
  ],

  'eggs-tortillas': [
    {
      title: 'Breakfast Burritos',
      description: 'Fluffy scrambled eggs, cheese, and your favorite fixings wrapped in a warm tortilla. Make-ahead friendly for busy mornings or breakfast-for-dinner.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '8 large eggs',
        '4 large flour tortillas',
        '1 cup shredded cheddar cheese',
        '4 strips bacon, cooked and crumbled',
        '2 tablespoons butter',
        'Salt and black pepper to taste',
        'Salsa and sour cream for serving',
      ],
      instructions: [
        'Scramble eggs in butter over medium-low heat. Season with salt and pepper. Keep them soft and fluffy.',
        'Warm tortillas in a dry skillet or microwave.',
        'Divide eggs among tortillas. Top with cheese and bacon.',
        'Fold in sides and roll tightly. Serve with salsa and sour cream.',
      ],
      nutrition: { calories: 420, protein: 24, carbs: 28, fat: 24 },
    },
    {
      title: 'Egg Tacos (Tacos de Huevo)',
      description: 'Simple Mexican-style egg tacos with scrambled eggs, cheese, and salsa. Light, fast, and endlessly customizable.',
      timeMinutes: 15,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '6 large eggs',
        '8 small corn tortillas',
        '1/2 cup shredded cheese',
        '1/2 cup salsa',
        '2 tablespoons butter',
        '1/4 cup chopped cilantro',
        'Lime wedges',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Scramble eggs in butter. Season with salt and pepper.',
        'Char tortillas over gas flame or warm in skillet.',
        'Fill each tortilla with eggs, cheese, and salsa. Top with cilantro and lime.',
      ],
      nutrition: { calories: 320, protein: 18, carbs: 32, fat: 14 },
    },
    {
      title: 'Migas',
      description: 'Tex-Mex scrambled eggs with crispy tortilla strips, peppers, and cheese. A satisfying breakfast that works any time of day.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '6 large eggs',
        '4 corn tortillas, cut into strips',
        '1/2 cup shredded cheddar',
        '1/2 poblano pepper, diced',
        '1/4 cup diced onion',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
        'Salsa and avocado for serving',
      ],
      instructions: [
        'Fry tortilla strips in oil until crispy. Remove.',
        'Sauté pepper and onion 3 minutes. Add eggs. Scramble until almost set.',
        'Add tortilla strips and cheese. Fold in. Serve with salsa and avocado.',
      ],
      nutrition: { calories: 340, protein: 18, carbs: 28, fat: 18 },
    },
    {
      title: 'Huevos Rancheros',
      description: 'Fried eggs on crispy tortillas with warm ranchero sauce, refried beans, and avocado. A classic Mexican breakfast-for-dinner.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '8 eggs',
        '4 corn tortillas',
        '1 can (14 oz) diced tomatoes',
        '1/2 onion, diced',
        '1 jalapeño, minced',
        '2 cloves garlic, minced',
        '1 can refried beans',
        '1 avocado, sliced',
        '2 tablespoons vegetable oil',
        'Cilantro and lime for garnish',
      ],
      instructions: [
        'Blend tomatoes, onion, jalapeño, garlic. Simmer 10 minutes for ranchero sauce.',
        'Fry tortillas in oil until slightly crisp. Warm refried beans.',
        'Fry eggs to preferred doneness. Place each egg on a tortilla. Top with sauce, beans, avocado, cilantro, and lime.',
      ],
      nutrition: { calories: 400, protein: 20, carbs: 38, fat: 20 },
    },
    {
      title: 'Chilaquiles',
      description: 'Crispy tortilla chips simmered in salsa, topped with fried eggs, cheese, and crema. The ultimate breakfast-for-dinner comfort.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '6 corn tortillas, cut into triangles',
        '6 eggs',
        '2 cups salsa verde or roja',
        '1/2 cup crumbled queso fresco',
        '1/4 cup Mexican crema',
        '2 tablespoons vegetable oil',
        'Cilantro and lime for garnish',
      ],
      instructions: [
        'Fry tortilla triangles until crispy. Drain.',
        'Heat salsa in large skillet. Add tortilla chips. Simmer 3 minutes.',
        'Make wells. Crack eggs into wells. Cover and cook 4-5 minutes until eggs set.',
        'Top with queso fresco, crema, cilantro, and lime.',
      ],
      nutrition: { calories: 380, protein: 18, carbs: 35, fat: 20 },
    },
    {
      title: 'Breakfast Quesadillas',
      description: 'Crispy quesadillas stuffed with scrambled eggs, cheese, and optional bacon or chorizo. Quick, cheesy, and kid-friendly.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '6 large eggs, scrambled',
        '4 large flour tortillas',
        '2 cups shredded Mexican cheese blend',
        '4 strips bacon, cooked and crumbled',
        '2 tablespoons butter',
        'Salsa and sour cream for serving',
      ],
      instructions: [
        'Scramble eggs. Set aside.',
        'Place tortilla in skillet. Sprinkle half with cheese, eggs, bacon, more cheese. Fold.',
        'Cook 2-3 minutes per side until golden. Repeat for remaining quesadillas.',
        'Slice and serve with salsa and sour cream.',
      ],
      nutrition: { calories: 480, protein: 26, carbs: 32, fat: 28 },
    },
    {
      title: 'Egg and Potato Breakfast Tacos',
      description: 'Soft tacos filled with crispy potatoes, scrambled eggs, and cheese. Hearty enough for dinner any night.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '6 large eggs',
        '2 medium potatoes, diced',
        '8 small flour or corn tortillas',
        '1 cup shredded cheddar',
        '2 tablespoons vegetable oil',
        '1/2 teaspoon cumin',
        'Salt and black pepper to taste',
        'Hot sauce for serving',
      ],
      instructions: [
        'Fry potatoes in oil until golden and crisp. Season with cumin, salt, pepper. Remove.',
        'Scramble eggs in same pan. Add potatoes back. Mix.',
        'Warm tortillas. Fill with egg-potato mix and cheese. Serve with hot sauce.',
      ],
      nutrition: { calories: 420, protein: 20, carbs: 42, fat: 18 },
    },
    {
      title: 'Shakshuka-Style Eggs in Tortilla Boats',
      description: 'Baked eggs in a spiced tomato sauce nestled in tortilla boats. A fun fusion of Middle Eastern and Mexican flavors.',
      timeMinutes: 35,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Fusion',
      ingredients: [
        '6 large eggs',
        '4 large flour tortillas',
        '1 can (14 oz) diced tomatoes',
        '1 bell pepper, diced',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon cumin',
        '1/2 teaspoon paprika',
        '2 tablespoons olive oil',
        'Fresh cilantro and feta for garnish',
      ],
      instructions: [
        'Sauté pepper and onion in oil 5 minutes. Add garlic, cumin, paprika. Cook 1 minute.',
        'Add tomatoes. Simmer 10 minutes. Season with salt.',
        'Form tortillas into boats in a baking dish. Spoon sauce in. Crack eggs on top.',
        'Bake at 375°F 12-15 minutes until eggs set. Top with feta and cilantro.',
      ],
      nutrition: { calories: 320, protein: 16, carbs: 32, fat: 14 },
    },
  ],

  'ground-beef-tortillas': [
    {
      title: 'Classic Beef Tacos',
      description: 'Seasoned ground beef tacos with all the fixings. The ultimate taco night essential—simple, delicious, and endlessly customizable.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound ground beef',
        '8 taco shells or soft tortillas',
        '1 packet taco seasoning',
        '1/2 cup water',
        '1 cup shredded lettuce',
        '1 cup diced tomatoes',
        '1/2 cup shredded cheddar',
        '1/2 cup sour cream',
        'Salsa and lime wedges',
      ],
      instructions: [
        'Brown ground beef in skillet. Drain excess fat. Add taco seasoning and water. Simmer 5 minutes.',
        'Warm taco shells or tortillas according to package.',
        'Fill with beef. Top with lettuce, tomato, cheese, sour cream, and salsa. Serve with lime.',
      ],
      nutrition: { calories: 480, protein: 26, carbs: 38, fat: 26 },
    },
    {
      title: 'Ground Beef Burritos',
      description: 'Loaded burritos with seasoned beef, rice, beans, cheese, and all your favorite toppings. Hearty and satisfying.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound ground beef',
        '4 large flour tortillas',
        '2 cups cooked rice',
        '1 can (15 oz) black beans, drained',
        '2 cups shredded cheese',
        '1 cup salsa',
        '1 tablespoon taco seasoning',
        'Sour cream and guacamole for serving',
      ],
      instructions: [
        'Brown beef. Add taco seasoning. Cook 2 minutes. Set aside.',
        'Warm tortillas. Layer rice, beef, beans, cheese, and salsa.',
        'Fold in sides and roll tightly. Optional: crisp in skillet. Serve with sour cream and guac.',
      ],
      nutrition: { calories: 680, protein: 34, carbs: 62, fat: 32 },
    },
    {
      title: 'Beef Quesadillas',
      description: 'Crispy flour tortillas stuffed with seasoned ground beef and melted cheese. Quick, cheesy, and perfect for kids and adults.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound ground beef',
        '4 large flour tortillas',
        '2 cups shredded Mexican cheese',
        '1 tablespoon taco seasoning',
        '2 tablespoons vegetable oil',
        'Salsa and sour cream for dipping',
      ],
      instructions: [
        'Brown beef. Add taco seasoning. Cook 2 minutes. Drain. Set aside.',
        'Place tortilla in oiled skillet. Add cheese, beef, more cheese. Top with another tortilla.',
        'Cook 2-3 minutes per side until golden. Slice and serve with salsa and sour cream.',
      ],
      nutrition: { calories: 560, protein: 32, carbs: 32, fat: 34 },
    },
    {
      title: 'Beef Enchiladas',
      description: 'Rolled tortillas filled with seasoned beef, smothered in enchilada sauce and cheese. Baked until bubbly and golden.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound ground beef',
        '12 corn tortillas',
        '2 cups enchilada sauce',
        '2 cups shredded cheddar',
        '1 onion, diced',
        '1 tablespoon taco seasoning',
        '2 tablespoons vegetable oil',
        'Sour cream and cilantro for garnish',
      ],
      instructions: [
        'Brown beef with onion. Add taco seasoning. Set aside.',
        'Warm tortillas. Fill with beef and cheese. Roll and place seam-side down in baking dish.',
        'Pour enchilada sauce over. Top with remaining cheese. Bake 25 minutes at 375°F.',
        'Garnish with sour cream and cilantro.',
      ],
      nutrition: { calories: 420, protein: 24, carbs: 38, fat: 20 },
    },
    {
      title: 'Taco Salad with Tortilla Bowl',
      description: 'Crunchy tortilla bowl filled with seasoned beef, lettuce, beans, cheese, and all the fixings. A fun, handheld taco salad.',
      timeMinutes: 30,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '1 pound ground beef',
        '4 large flour tortillas',
        '4 cups shredded lettuce',
        '1 can (15 oz) kidney beans, drained',
        '1 cup shredded cheddar',
        '1 cup salsa',
        '1/2 cup sour cream',
        '1 avocado, diced',
        '1 tablespoon taco seasoning',
      ],
      instructions: [
        'Press tortillas into oven-safe bowls. Bake at 375°F 10 minutes until crisp.',
        'Brown beef. Add taco seasoning. Set aside.',
        'Fill tortilla bowls with lettuce, beef, beans, cheese, salsa, sour cream, and avocado.',
      ],
      nutrition: { calories: 580, protein: 32, carbs: 48, fat: 30 },
    },
    {
      title: 'Beef Nachos',
      description: 'Loaded nachos with seasoned ground beef, cheese, beans, jalapeños, and all the toppings. Perfect for game day or dinner.',
      timeMinutes: 25,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '1 pound ground beef',
        '1 bag tortilla chips',
        '2 cups shredded cheese',
        '1 can (15 oz) black beans, drained',
        '1/2 cup pickled jalapeños',
        '1 cup salsa',
        '1/2 cup sour cream',
        '1 tablespoon taco seasoning',
      ],
      instructions: [
        'Brown beef. Add taco seasoning. Set aside.',
        'Layer chips, beef, beans, cheese on sheet pan. Bake 10 minutes at 400°F until cheese melts.',
        'Top with jalapeños, salsa, sour cream. Serve immediately.',
      ],
      nutrition: { calories: 720, protein: 36, carbs: 52, fat: 44 },
    },
    {
      title: 'Beef Tostadas',
      description: 'Crispy flat tortillas topped with refried beans, seasoned beef, lettuce, cheese, and crema. A satisfying open-faced taco.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 pound ground beef',
        '8 tostada shells',
        '1 can refried beans',
        '2 cups shredded lettuce',
        '1 cup shredded cheese',
        '1/2 cup Mexican crema',
        '1 tablespoon taco seasoning',
        'Salsa and lime for serving',
      ],
      instructions: [
        'Brown beef. Add taco seasoning. Set aside.',
        'Warm refried beans. Spread on tostadas.',
        'Top with beef, lettuce, cheese, and crema. Serve with salsa and lime.',
      ],
      nutrition: { calories: 520, protein: 28, carbs: 42, fat: 28 },
    },
    {
      title: 'Crunchwrap-Style Beef Wrap',
      description: 'Copycat crunchwrap: seasoned beef, cheese, and a crispy tortilla center wrapped in a soft tortilla. Grilled to perfection.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '1 pound ground beef',
        '4 large flour tortillas',
        '4 tostada shells',
        '2 cups shredded cheese',
        '1 cup sour cream',
        '1 cup shredded lettuce',
        '1 cup diced tomatoes',
        '1 tablespoon taco seasoning',
      ],
      instructions: [
        'Brown beef. Add taco seasoning. Set aside.',
        'Place tortilla. Layer beef, tostada, cheese, sour cream, lettuce, tomato in center.',
        'Fold tortilla edges over to form hexagon. Grill seam-side down 3 minutes per side.',
      ],
      nutrition: { calories: 680, protein: 34, carbs: 48, fat: 40 },
    },
  ],

  'chicken-breast-tortillas': [
    {
      title: 'Chicken Tacos',
      description: 'Tender seasoned chicken breast in soft tortillas with fresh toppings. Lighter than beef tacos, just as delicious.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 large chicken breasts, sliced',
        '8 soft flour or corn tortillas',
        '1 tablespoon taco seasoning',
        '2 tablespoons olive oil',
        '1 cup shredded lettuce',
        '1 cup diced tomatoes',
        '1/2 cup shredded cheese',
        '1/2 cup salsa',
        'Lime wedges',
      ],
      instructions: [
        'Season chicken with taco seasoning. Heat oil in skillet. Cook chicken 6-7 minutes until 165°F. Slice.',
        'Warm tortillas. Fill with chicken. Top with lettuce, tomato, cheese, salsa. Serve with lime.',
      ],
      nutrition: { calories: 380, protein: 34, carbs: 38, fat: 10 },
    },
    {
      title: 'Chicken Burritos',
      description: 'Shredded chicken burritos with rice, beans, and cheese. Healthy, filling, and perfect for meal prep.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 large chicken breasts',
        '4 large flour tortillas',
        '2 cups cooked rice',
        '1 can (15 oz) black beans',
        '2 cups shredded cheese',
        '1 cup salsa',
        '1 tablespoon taco seasoning',
        'Sour cream and cilantro',
      ],
      instructions: [
        'Cook chicken. Shred and mix with taco seasoning.',
        'Warm tortillas. Layer rice, chicken, beans, cheese, salsa.',
        'Fold and roll. Optional: crisp in skillet. Serve with sour cream and cilantro.',
      ],
      nutrition: { calories: 620, protein: 42, carbs: 62, fat: 24 },
    },
    {
      title: 'Chicken Quesadillas',
      description: 'Crispy quesadillas with seasoned chicken and melted cheese. Quick, cheesy, and a family favorite.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 large chicken breasts, cooked and shredded',
        '4 large flour tortillas',
        '2 cups shredded Mexican cheese',
        '1 tablespoon taco seasoning',
        '2 tablespoons butter',
        'Salsa and sour cream',
      ],
      instructions: [
        'Season shredded chicken with taco seasoning.',
        'Butter one side of tortilla. Place butter-side down. Add cheese, chicken, more cheese. Fold.',
        'Cook 2-3 minutes per side until golden. Slice and serve.',
      ],
      nutrition: { calories: 520, protein: 38, carbs: 32, fat: 26 },
    },
    {
      title: 'Chicken Enchiladas',
      description: 'Shredded chicken enchiladas in green or red sauce, baked with cheese. Comforting and crowd-pleasing.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 25,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '2 large chicken breasts, cooked and shredded',
        '12 corn tortillas',
        '2 cups enchilada sauce',
        '2 cups shredded cheddar',
        '1/2 cup sour cream',
        '2 tablespoons taco seasoning',
        'Cilantro for garnish',
      ],
      instructions: [
        'Mix chicken with taco seasoning. Warm tortillas.',
        'Fill each tortilla with chicken and cheese. Roll. Place in baking dish.',
        'Pour sauce over. Top with cheese. Bake 25 minutes at 375°F. Garnish with cilantro.',
      ],
      nutrition: { calories: 420, protein: 30, carbs: 38, fat: 18 },
    },
    {
      title: 'Chicken Fajitas',
      description: 'Sizzling chicken strips with bell peppers and onions in warm tortillas. A classic Tex-Mex dinner.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '2 large chicken breasts, sliced into strips',
        '3 bell peppers, sliced',
        '1 large onion, sliced',
        '8 flour tortillas',
        '2 tablespoons fajita seasoning',
        '2 tablespoons olive oil',
        'Lime wedges and sour cream',
      ],
      instructions: [
        'Season chicken with fajita seasoning. Heat oil. Cook chicken 6 minutes. Remove.',
        'Sauté peppers and onions 6 minutes. Return chicken. Toss.',
        'Warm tortillas. Serve with lime and sour cream.',
      ],
      nutrition: { calories: 420, protein: 34, carbs: 42, fat: 14 },
    },
    {
      title: 'Chicken Wrap with Ranch',
      description: 'Grilled chicken, crisp lettuce, and ranch in a soft tortilla wrap. Simple, fresh, and satisfying.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 large chicken breasts',
        '4 large flour tortillas',
        '2 cups shredded lettuce',
        '1 cup diced tomatoes',
        '1/2 cup ranch dressing',
        '1 cup shredded cheese',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season chicken. Grill or pan-sear 6-7 minutes per side. Slice.',
        'Warm tortillas. Layer lettuce, chicken, tomato, cheese, ranch. Roll tightly.',
      ],
      nutrition: { calories: 480, protein: 34, carbs: 38, fat: 24 },
    },
    {
      title: 'Buffalo Chicken Tacos',
      description: 'Spicy buffalo chicken in tortillas with blue cheese and celery. A fun twist on taco night.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 large chicken breasts, cooked and shredded',
        '8 small flour tortillas',
        '1/2 cup Buffalo sauce',
        '1/2 cup crumbled blue cheese',
        '1 cup shredded lettuce',
        '1 stalk celery, diced',
        '2 tablespoons butter',
      ],
      instructions: [
        'Toss shredded chicken with Buffalo sauce and butter.',
        'Fill tortillas with chicken. Top with blue cheese, lettuce, celery.',
      ],
      nutrition: { calories: 420, protein: 34, carbs: 32, fat: 18 },
    },
    {
      title: 'Chicken Taco Salad Bowl',
      description: 'Deconstructed taco in a bowl: seasoned chicken over greens with beans, corn, and tortilla strips.',
      timeMinutes: 30,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '2 large chicken breasts',
        '6 cups mixed greens',
        '1 can (15 oz) black beans',
        '1 cup corn',
        '1 cup tortilla strips',
        '1 cup salsa',
        '1/2 cup shredded cheese',
        '1 tablespoon taco seasoning',
        '2 tablespoons olive oil',
      ],
      instructions: [
        'Season chicken. Grill or pan-sear. Slice.',
        'Divide greens among bowls. Top with chicken, beans, corn, tortilla strips, salsa, cheese.',
      ],
      nutrition: { calories: 420, protein: 36, carbs: 48, fat: 12 },
    },
  ],

  'bacon-eggs': [
    {
      title: 'Bacon and Egg Fried Rice',
      description: 'Classic fried rice with crispy bacon and scrambled eggs. Breakfast-for-dinner at its finest—salty, savory, and satisfying.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '6 strips bacon, diced',
        '3 cups day-old cooked rice',
        '3 large eggs, beaten',
        '3 green onions, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 cloves garlic, minced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon in wok until crispy. Remove, leave 2 tablespoons fat.',
        'Scramble eggs in bacon fat. Remove. Add rice. Stir-fry 3 minutes.',
        'Add garlic, soy sauce, sesame oil. Return bacon and eggs. Toss. Garnish with green onions.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 42, fat: 20 },
    },
    {
      title: 'Bacon Carbonara',
      description: 'Creamy pasta carbonara with crispy bacon, eggs, and parmesan. No cream—just egg yolk magic for a silky sauce.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '12 oz spaghetti',
        '8 strips bacon, diced',
        '3 large egg yolks plus 1 whole egg',
        '1 cup grated parmesan',
        '2 cloves garlic, minced',
        'Salt and black pepper to taste',
        'Reserved pasta water',
      ],
      instructions: [
        'Cook pasta. Reserve 1 cup pasta water. Drain.',
        'Cook bacon until crisp. Add garlic 30 seconds. Remove from heat.',
        'Whisk eggs and parmesan. Add hot pasta to bacon pan. Toss with egg mixture. Add pasta water to thin. Season. Serve immediately.',
      ],
      nutrition: { calories: 580, protein: 28, carbs: 52, fat: 30 },
    },
    {
      title: 'BLT Egg Sandwich',
      description: 'Toasted sandwich with crispy bacon, lettuce, tomato, and a perfectly fried egg. Breakfast or dinner hero.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 2,
      cuisine: 'American',
      ingredients: [
        '4 strips bacon',
        '2 large eggs',
        '4 slices bread',
        '2 lettuce leaves',
        '2 tomato slices',
        '2 tablespoons mayonnaise',
        'Butter for frying',
      ],
      instructions: [
        'Cook bacon until crisp. Fry eggs to preferred doneness.',
        'Toast bread. Spread mayo. Layer bacon, lettuce, tomato, egg. Top with second slice.',
      ],
      nutrition: { calories: 520, protein: 24, carbs: 38, fat: 32 },
    },
    {
      title: 'Bacon Egg Burritos',
      description: 'Scrambled eggs, crispy bacon, and cheese wrapped in a warm tortilla. The ultimate breakfast burrito for any meal.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Tex-Mex',
      ingredients: [
        '6 strips bacon',
        '6 large eggs',
        '4 large flour tortillas',
        '1 cup shredded cheddar',
        '2 tablespoons butter',
        'Salsa and sour cream',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon until crisp. Crumble. Scramble eggs in butter.',
        'Warm tortillas. Fill with eggs, bacon, cheese. Roll. Serve with salsa and sour cream.',
      ],
      nutrition: { calories: 480, protein: 24, carbs: 28, fat: 32 },
    },
    {
      title: 'Bacon and Cheese Quiche',
      description: 'Flaky pie crust filled with egg custard, bacon, and cheddar. Elegant enough for brunch, simple enough for dinner.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 40,
      servings: 6,
      cuisine: 'French',
      ingredients: [
        '1 refrigerated pie crust',
        '8 strips bacon, cooked and crumbled',
        '6 large eggs',
        '1 cup heavy cream',
        '1 cup shredded cheddar',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
        '1/4 teaspoon nutmeg',
      ],
      instructions: [
        'Preheat oven to 375°F. Fit pie crust into 9-inch pie dish. Crimp edges.',
        'Sprinkle bacon and half the cheese in crust. Whisk eggs, cream, salt, pepper, nutmeg. Pour over.',
        'Top with remaining cheese. Bake 35-40 minutes until set. Rest 10 minutes.',
      ],
      nutrition: { calories: 420, protein: 18, carbs: 18, fat: 32 },
    },
    {
      title: 'Shakshuka with Bacon',
      description: 'North African eggs in tomato sauce with crispy bacon crumbled on top. A hearty, flavorful one-pan meal.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Middle Eastern',
      ingredients: [
        '6 strips bacon',
        '6 large eggs',
        '1 can (14 oz) diced tomatoes',
        '1 bell pepper, diced',
        '1 onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon cumin',
        '1/2 teaspoon paprika',
        '2 tablespoons olive oil',
        'Fresh cilantro and feta',
      ],
      instructions: [
        'Cook bacon until crisp. Crumble. Set aside.',
        'Sauté pepper and onion 5 minutes. Add garlic, cumin, paprika. Add tomatoes. Simmer 10 minutes.',
        'Make wells. Crack eggs. Cover and cook 5-7 minutes. Top with bacon, feta, cilantro.',
      ],
      nutrition: { calories: 380, protein: 22, carbs: 18, fat: 26 },
    },
    {
      title: 'Bacon Egg and Potato Hash',
      description: 'Crispy potatoes with bacon and onions, topped with fried eggs. A diner-style classic for breakfast or dinner.',
      timeMinutes: 40,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '6 strips bacon',
        '4 large eggs',
        '1.5 pounds potatoes, diced',
        '1 onion, diced',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon. Remove, crumble. Add potatoes to bacon fat. Cook 15 minutes until golden.',
        'Add onion. Cook 5 minutes. Return bacon. Make wells. Crack eggs. Cover 4-5 minutes.',
      ],
      nutrition: { calories: 420, protein: 20, carbs: 38, fat: 22 },
    },
    {
      title: 'Bacon Cheddar Egg Muffins',
      description: 'Baked egg muffins with bacon and cheddar. Perfect for meal prep—grab and go or reheat for a quick dinner.',
      timeMinutes: 30,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '8 strips bacon, cooked and crumbled',
        '8 large eggs',
        '1 cup shredded cheddar',
        '1/4 cup milk',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 350°F. Grease 12-cup muffin tin.',
        'Whisk eggs, milk, salt, pepper. Stir in bacon and half the cheese.',
        'Divide among muffin cups. Top with remaining cheese. Bake 18-20 minutes until set.',
      ],
      nutrition: { calories: 220, protein: 16, carbs: 2, fat: 16 },
    },
  ],
}

export const comboFaqsNew1: Record<string, FAQ[]> = {
  'chicken-breast-potatoes': [
    {
      question: 'What goes well with chicken breast and potatoes?',
      answer: 'Roasted vegetables like carrots or green beans, a simple salad, or steamed broccoli pair great. Gravy or lemon butter sauce also complements this combination.',
    },
    {
      question: 'How long to bake chicken and potatoes together?',
      answer: 'For sheet pan dinners at 425°F, chicken and potatoes typically need 35-45 minutes. Chicken should reach 165°F internally; potatoes should be tender and golden.',
    },
    {
      question: 'Can I use sweet potatoes instead of regular potatoes with chicken?',
      answer: 'Yes! Sweet potatoes work wonderfully—they caramelize nicely and add a slight sweetness. Adjust cooking time as needed since they may cook faster than russets.',
    },
    {
      question: 'What is the best way to keep chicken moist with potatoes?',
      answer: 'Use bone-in, skin-on thighs for more moisture, or brine breasts before cooking. Don\'t overcook—165°F is the target. Basting with pan juices also helps.',
    },
    {
      question: 'Are chicken and potato meals healthy?',
      answer: 'Yes, when prepared with moderate fat. Chicken breast is lean protein; potatoes provide fiber and nutrients. Roast instead of fry, and use olive oil in moderation for a balanced meal.',
    },
  ],
  'pork-chops-rice': [
    {
      question: 'What is the best way to cook pork chops with rice?',
      answer: 'Sear the chops first for flavor, then either simmer them in the rice (one-pan), serve over cooked rice with gravy, or bake them in a rice casserole. Internal temp should reach 145°F.',
    },
    {
      question: 'How do I keep pork chops from drying out?',
      answer: 'Use chops at least 1 inch thick, brine them 30 minutes before cooking, and don\'t overcook—145°F with a slight pink center is safe. Let them rest 5 minutes before serving.',
    },
    {
      question: 'What rice goes best with pork chops?',
      answer: 'White rice, jasmine rice, or even brown rice all work. For Southern-style, plain white rice with gravy is classic. For Asian-inspired dishes, jasmine is ideal.',
    },
    {
      question: 'Can I make pork chops and rice in one pan?',
      answer: 'Yes! Brown the chops, remove them, add rice and liquid, then nestle the chops back in. Cover and simmer until rice is tender and pork reaches 145°F.',
    },
    {
      question: 'What seasonings work best for pork chops and rice?',
      answer: 'For Southern: garlic, onion, paprika, and thyme. For Asian: soy sauce, ginger, and teriyaki. For Mediterranean: lemon, oregano, and garlic.',
    },
  ],
  'sausage-rice': [
    {
      question: 'What kind of sausage is best for rice dishes?',
      answer: 'Smoked sausage (kielbasa) and andouille are popular for jambalaya and dirty rice. Italian sausage works for Mediterranean-style. Spanish chorizo is great for arroz con chorizo.',
    },
    {
      question: 'Can I make sausage and rice in one pot?',
      answer: 'Absolutely! Many sausage-rice recipes are one-pot. Brown the sausage first, add rice and liquid, then simmer until rice is tender. Jambalaya and simple skillet versions work this way.',
    },
    {
      question: 'What is dirty rice?',
      answer: 'Dirty rice is a Louisiana dish where white rice is "dirtied" with ground meat (often pork sausage), aromatics, and Cajun spices. It\'s savory, hearty, and traditionally includes liver.',
    },
    {
      question: 'How long does sausage and rice take to cook?',
      answer: 'Simple one-pot versions: about 25-30 minutes. Jambalaya and casseroles: 45-55 minutes. Stovetop skillet dishes: typically 30-40 minutes.',
    },
    {
      question: 'Can I use instant rice for sausage and rice recipes?',
      answer: 'Yes, but adjust liquid and cooking time per package instructions. For best texture in jambalaya and similar dishes, long-grain rice is preferred.',
    },
  ],
  'eggs-tortillas': [
    {
      question: 'What can I make with eggs and tortillas?',
      answer: 'Breakfast burritos, egg tacos, migas, huevos rancheros, chilaquiles, breakfast quesadillas, and egg-potato tacos. All work for breakfast or breakfast-for-dinner.',
    },
    {
      question: 'What is the difference between migas and chilaquiles?',
      answer: 'Migas are scrambled eggs with crispy tortilla strips mixed in. Chilaquiles are tortilla chips simmered in salsa, then topped with eggs. Both are Tex-Mex/Mexican egg-and-tortilla dishes.',
    },
    {
      question: 'Can I use flour or corn tortillas for egg recipes?',
      answer: 'Both work! Corn tortillas are traditional for huevos rancheros, tacos, and chilaquiles. Flour tortillas are great for burritos and quesadillas. Choose based on the recipe.',
    },
    {
      question: 'How do I keep breakfast burritos from getting soggy?',
      answer: 'Let scrambled eggs cool slightly before wrapping. Don\'t overfill. Warm (don\'t overheat) tortillas. Wrap tightly in foil if making ahead; reheat in oven or skillet to crisp.',
    },
    {
      question: 'Are egg and tortilla meals healthy?',
      answer: 'Eggs provide protein and nutrients. Tortillas add carbs. Keep it balanced with vegetables, moderate cheese, and whole wheat or corn tortillas. Skip excess oil for a lighter meal.',
    },
  ],
  'ground-beef-tortillas': [
    {
      question: 'What can I make with ground beef and tortillas?',
      answer: 'Tacos, burritos, quesadillas, enchiladas, taco salad, nachos, tostadas, and crunchwraps. Ground beef and tortillas are incredibly versatile for Tex-Mex and Mexican-style meals.',
    },
    {
      question: 'How do I season ground beef for tacos?',
      answer: 'Use a store-bought taco seasoning packet, or make your own with chili powder, cumin, garlic powder, onion powder, paprika, and a pinch of oregano. Add a splash of water and simmer to let flavors blend.',
    },
    {
      question: 'Soft or hard shells for beef tacos?',
      answer: 'Both are popular! Soft tortillas are easier to eat and hold more. Hard shells add crunch. Many people serve both and let everyone choose. Warm soft tortillas before serving.',
    },
    {
      question: 'Can I make ground beef tacos ahead of time?',
      answer: 'Yes. Cook and season the beef; store in fridge up to 3 days. Reheat in a skillet. Prepare toppings separately. Assemble tacos when ready to eat for best texture.',
    },
    {
      question: 'What toppings go on ground beef tacos?',
      answer: 'Lettuce, diced tomatoes, shredded cheese, sour cream, salsa, guacamole, cilantro, lime, diced onions, and pickled jalapeños. Cabbage slaw and cotija cheese are also popular.',
    },
  ],
  'chicken-breast-tortillas': [
    {
      question: 'What can I make with chicken breast and tortillas?',
      answer: 'Chicken tacos, burritos, quesadillas, enchiladas, fajitas, and wraps. Chicken breast is lean and versatile—great for a lighter taco night or healthy wrap option.',
    },
    {
      question: 'How do I keep chicken breast moist in tacos?',
      answer: 'Don\'t overcook—165°F internal temp. Slice against the grain. Marinate before cooking. Consider brining. Add a bit of salsa or lime juice when serving for extra moisture.',
    },
    {
      question: 'What seasoning is best for chicken tacos?',
      answer: 'Taco seasoning (chili powder, cumin, garlic), fajita seasoning, or a simple mix of lime, cilantro, and garlic. For variety, try chipotle, adobo, or citrus-based marinades.',
    },
    {
      question: 'Can I use rotisserie chicken for chicken tortilla recipes?',
      answer: 'Yes! Rotisserie chicken is a huge time-saver. Shred it, season with taco or fajita seasoning, and use in tacos, burritos, quesadillas, or enchiladas.',
    },
    {
      question: 'Are chicken tacos healthier than beef tacos?',
      answer: 'Chicken breast is leaner than ground beef, so chicken tacos typically have less fat and fewer calories. Top with fresh veggies and moderate cheese for a balanced meal.',
    },
  ],
  'bacon-eggs': [
    {
      question: 'What can I make with bacon and eggs?',
      answer: 'Bacon and egg fried rice, carbonara, BLT egg sandwiches, breakfast burritos, quiche, shakshuka with bacon, bacon egg hash, and egg muffins. Great for breakfast or dinner.',
    },
    {
      question: 'How do I make bacon and eggs for a crowd?',
      answer: 'Bake bacon on a sheet pan at 400°F. Make scrambled eggs in batches or bake a large quiche or egg casserole. Egg muffins and breakfast burritos are also easy to scale.',
    },
    {
      question: 'Is bacon and eggs healthy?',
      answer: 'In moderation, yes. Eggs provide protein and nutrients. Bacon is high in fat and sodium—enjoy occasionally. Pair with vegetables, whole grains, or fruit for balance.',
    },
    {
      question: 'What is the best way to cook bacon for eggs?',
      answer: 'Pan-fry for control, or bake on a sheet pan at 400°F for hands-off cooking. For less mess, cook bacon first, then use the fat to cook eggs for extra flavor.',
    },
    {
      question: 'Can I meal prep bacon and egg recipes?',
      answer: 'Yes! Breakfast burritos and egg muffins freeze well. Cook bacon and store; reheat. Hard-boiled eggs with bacon bits work for salads. Quiche slices keep 3-4 days in the fridge.',
    },
  ],
}
