import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const dietRecipes2: Record<string, RecipeIdea[]> = {
  'high-protein-meals': [
    {
      title: 'Grilled Chimichurri Chicken Power Bowl',
      description: 'Juicy grilled chicken drizzled with zesty chimichurri over quinoa, roasted sweet potatoes, and fresh greens. A macro-friendly bowl packed with lean protein.',
      timeMinutes: 35,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Argentine',
      ingredients: [
        '4 chicken breasts (about 6 oz each)',
        '1.5 cups quinoa, rinsed',
        '2 medium sweet potatoes, peeled and cubed',
        '4 cups mixed greens (arugula and spinach)',
        '1 cup fresh parsley, packed',
        '1/4 cup fresh cilantro, packed',
        '3 cloves garlic, minced',
        '1/4 cup red wine vinegar',
        '1/2 cup extra-virgin olive oil',
        '1/2 teaspoon red pepper flakes',
        '1 teaspoon dried oregano',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Make the chimichurri by blending parsley, cilantro, garlic, red wine vinegar, olive oil, red pepper flakes, and oregano in a food processor until finely chopped but not pureed.',
        'Preheat grill or grill pan to medium-high heat and season chicken breasts generously with salt and pepper.',
        'Cook quinoa according to package directions, about 15 minutes, then fluff with a fork.',
        'Toss cubed sweet potatoes with 1 tablespoon olive oil, salt, and pepper, and roast at 425°F for 20 minutes until golden and tender.',
        'Grill chicken for 6-7 minutes per side until internal temperature reaches 165°F, then let rest for 5 minutes before slicing.',
        'Assemble bowls with quinoa, mixed greens, roasted sweet potatoes, and sliced chicken.',
        'Spoon chimichurri generously over each bowl and serve immediately.',
      ],
      nutrition: { calories: 520, protein: 46, carbs: 42, fat: 18 },
    },
    {
      title: 'Miso-Glazed Salmon with Sesame Bok Choy',
      description: 'Buttery salmon fillets coated in a sweet and savory miso glaze, baked alongside tender bok choy. A high-protein sheet-pan dinner with big umami flavor.',
      timeMinutes: 30,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Japanese',
      ingredients: [
        '4 salmon fillets (6 oz each, skin-on)',
        '4 heads baby bok choy, halved lengthwise',
        '3 tablespoons white miso paste',
        '2 tablespoons mirin',
        '1 tablespoon soy sauce',
        '1 tablespoon rice vinegar',
        '1 tablespoon honey',
        '1 tablespoon sesame oil',
        '2 teaspoons fresh ginger, grated',
        '1 tablespoon sesame seeds',
        '2 green onions, sliced',
      ],
      instructions: [
        'Preheat oven to 400°F and line a sheet pan with parchment paper.',
        'Whisk together miso paste, mirin, soy sauce, rice vinegar, honey, and ginger in a small bowl until smooth.',
        'Place salmon fillets skin-side down on one half of the sheet pan and brush generously with the miso glaze, reserving 2 tablespoons.',
        'Toss halved bok choy with sesame oil and a pinch of salt, then arrange cut-side down on the other half of the pan.',
        'Bake for 15-18 minutes until salmon flakes easily with a fork and bok choy is tender.',
        'Brush salmon with remaining glaze and sprinkle sesame seeds and sliced green onions over everything.',
        'Serve immediately with steamed rice on the side if desired.',
      ],
      nutrition: { calories: 410, protein: 40, carbs: 14, fat: 22 },
    },
    {
      title: 'Smoky Turkey Meatball and White Bean Skillet',
      description: 'Tender turkey meatballs simmered in a smoky tomato sauce with white beans, spinach, and parmesan. High in protein, low in fuss.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1.25 lbs ground turkey (93% lean)',
        '1/3 cup panko breadcrumbs',
        '1 large egg',
        '3 cloves garlic, minced (divided)',
        '1 teaspoon smoked paprika',
        '1 can (15 oz) cannellini beans, drained and rinsed',
        '1 can (14 oz) crushed tomatoes',
        '3 cups fresh baby spinach',
        '1/4 cup grated parmesan cheese',
        '2 tablespoons olive oil',
        '1 small onion, diced',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
        'Fresh basil leaves for garnish',
      ],
      instructions: [
        'In a large bowl combine ground turkey, panko, egg, half the minced garlic, smoked paprika, salt, and pepper, then form into 16 meatballs about 1.5 inches each.',
        'Heat olive oil in a large skillet over medium-high heat and brown the meatballs on all sides for about 5 minutes, then transfer to a plate.',
        'In the same skillet, sauté diced onion for 3 minutes until softened, then add remaining garlic and Italian seasoning, stirring for 30 seconds.',
        'Pour in crushed tomatoes and stir in the cannellini beans, bringing the sauce to a gentle simmer.',
        'Nestle the meatballs back into the sauce, cover, and simmer for 12-15 minutes until meatballs are cooked through (165°F internal).',
        'Stir in baby spinach and let it wilt for 1-2 minutes, then sprinkle with parmesan cheese.',
        'Garnish with fresh basil and serve with crusty bread or over whole wheat pasta.',
      ],
      nutrition: { calories: 430, protein: 42, carbs: 28, fat: 16 },
    },
    {
      title: 'Chipotle-Lime Steak Stir-Fry with Peppers',
      description: 'Smoky chipotle-marinated sirloin stir-fried with colorful bell peppers and onions over cauliflower rice. A low-carb, high-protein weeknight winner.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1.5 lbs sirloin steak, sliced into thin strips',
        '1 red bell pepper, sliced',
        '1 green bell pepper, sliced',
        '1 yellow onion, sliced',
        '2 chipotle peppers in adobo, minced',
        '1 tablespoon adobo sauce (from the can)',
        '3 tablespoons lime juice',
        '2 cloves garlic, minced',
        '1 tablespoon cumin',
        '2 tablespoons avocado oil',
        '4 cups riced cauliflower',
        '1/4 cup fresh cilantro, chopped',
        'Salt and pepper to taste',
        'Lime wedges for serving',
      ],
      instructions: [
        'Toss sliced steak with chipotle peppers, adobo sauce, 2 tablespoons lime juice, garlic, cumin, salt, and pepper in a bowl and let marinate for 10 minutes.',
        'Heat 1 tablespoon avocado oil in a large wok or skillet over high heat until smoking.',
        'Add the steak strips in a single layer and sear for 2-3 minutes per side until browned, then remove and set aside.',
        'Add remaining oil to the wok, toss in bell peppers and onion, and stir-fry for 3-4 minutes until crisp-tender.',
        'While vegetables cook, microwave or sauté riced cauliflower for 3-4 minutes until tender.',
        'Return the steak to the wok with vegetables, add remaining lime juice, and toss together for 1 minute.',
        'Serve stir-fry over cauliflower rice, garnished with cilantro and lime wedges.',
      ],
      nutrition: { calories: 380, protein: 44, carbs: 14, fat: 17 },
    },
    {
      title: 'Herb-Crusted Baked Cod with Lentils',
      description: 'Flaky white cod topped with a Dijon-herb breadcrumb crust, baked over a bed of seasoned French lentils. An elegant high-protein meal that is surprisingly simple.',
      timeMinutes: 40,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'French',
      ingredients: [
        '4 cod fillets (6 oz each)',
        '1 cup French green lentils (du Puy)',
        '2 cups chicken broth',
        '1/3 cup panko breadcrumbs',
        '2 tablespoons Dijon mustard',
        '2 tablespoons fresh parsley, finely chopped',
        '1 tablespoon fresh dill, chopped',
        '2 tablespoons olive oil',
        '1 shallot, diced',
        '1 medium carrot, diced',
        '1 celery stalk, diced',
        '1 tablespoon lemon juice',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Combine lentils and chicken broth in a saucepan, bring to a boil, then reduce heat and simmer for 20-25 minutes until tender but still holding their shape.',
        'While lentils cook, preheat oven to 400°F and line a baking dish with parchment paper.',
        'Sauté shallot, carrot, and celery in 1 tablespoon olive oil for 4 minutes until softened, then stir into the cooked drained lentils with lemon juice, salt, and pepper.',
        'Pat cod fillets dry and season with salt and pepper, then spread a thin layer of Dijon mustard over the top of each fillet.',
        'Mix panko, parsley, dill, remaining olive oil, and a pinch of salt, then press the herb crust onto the mustard-topped fillets.',
        'Spread lentils in the baking dish and nestle the cod fillets on top, then bake for 15-18 minutes until the crust is golden and fish flakes easily.',
        'Serve immediately with a squeeze of fresh lemon and a side of steamed green beans.',
      ],
      nutrition: { calories: 400, protein: 48, carbs: 32, fat: 10 },
    },
    {
      title: 'Garlic Shrimp and Quinoa One-Pan',
      description: 'Plump garlic-butter shrimp cooked with fluffy quinoa, cherry tomatoes, and fresh spinach all in one pan. Twenty-five minutes from stove to table.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '1.5 lbs large shrimp, peeled and deveined',
        '1.5 cups quinoa, rinsed',
        '2.5 cups chicken broth',
        '1 cup cherry tomatoes, halved',
        '3 cups fresh baby spinach',
        '4 cloves garlic, minced',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
        '1/2 teaspoon red pepper flakes',
        '2 tablespoons fresh lemon juice',
        '2 tablespoons fresh parsley, chopped',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large deep skillet over medium-high heat, add shrimp seasoned with salt and pepper, and cook for 2 minutes per side until pink, then remove and set aside.',
        'In the same skillet, melt butter, add garlic and red pepper flakes, and cook for 30 seconds until fragrant.',
        'Stir in quinoa and toast for 1 minute, then pour in chicken broth and bring to a boil.',
        'Reduce heat to low, cover, and simmer for 15 minutes until quinoa is fluffy and liquid is absorbed.',
        'Fold in cherry tomatoes and baby spinach, stirring until spinach wilts, about 1-2 minutes.',
        'Return shrimp to the skillet, drizzle with lemon juice, and toss gently to combine.',
        'Garnish with fresh parsley and serve immediately.',
      ],
      nutrition: { calories: 440, protein: 42, carbs: 38, fat: 14 },
    },
    {
      title: 'Spiced Chickpea and Sausage Soup',
      description: 'Hearty soup loaded with chicken sausage, chickpeas, kale, and warm Middle Eastern spices. A protein-packed bowl that is cozy and deeply satisfying.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Middle Eastern',
      ingredients: [
        '12 oz fully-cooked chicken sausage links, sliced into rounds',
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '4 cups chicken broth',
        '1 can (14 oz) diced tomatoes',
        '4 cups chopped kale, stems removed',
        '1 medium onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon cumin',
        '1/2 teaspoon turmeric',
        '1/2 teaspoon coriander',
        '2 tablespoons olive oil',
        '1 tablespoon lemon juice',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large Dutch oven or soup pot over medium heat and cook sliced sausage rounds for 3-4 minutes until lightly browned on each side.',
        'Add diced onion and cook for 3 minutes until softened, then stir in garlic, cumin, turmeric, and coriander for 30 seconds until fragrant.',
        'Pour in chicken broth and diced tomatoes, then add the chickpeas and bring to a boil.',
        'Reduce heat to medium-low and simmer for 15 minutes to let the flavors meld together.',
        'Add the chopped kale and stir until wilted, about 3-4 minutes.',
        'Stir in lemon juice and season with salt and pepper to taste.',
        'Ladle into bowls and serve with crusty bread or warm pita on the side.',
      ],
      nutrition: { calories: 410, protein: 34, carbs: 38, fat: 14 },
    },
    {
      title: 'Seared Tuna and Edamame Protein Salad',
      description: 'Rare-seared ahi tuna over a crunchy salad of edamame, cucumber, avocado, and shredded cabbage with a ginger-soy dressing. Light yet loaded with protein.',
      timeMinutes: 20,
      method: 'salad',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 5,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '4 ahi tuna steaks (5 oz each, sushi-grade)',
        '1.5 cups shelled edamame, thawed',
        '2 cups shredded Napa cabbage',
        '1 English cucumber, diced',
        '1 ripe avocado, sliced',
        '1/4 cup shredded carrots',
        '3 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '1 tablespoon sesame oil',
        '1 teaspoon fresh ginger, grated',
        '1 tablespoon honey',
        '2 tablespoons avocado oil (for searing)',
        '1 tablespoon sesame seeds',
        '2 green onions, sliced',
      ],
      instructions: [
        'Whisk together soy sauce, rice vinegar, sesame oil, grated ginger, and honey in a small bowl to make the dressing.',
        'Combine shredded cabbage, edamame, diced cucumber, shredded carrots, and green onions in a large salad bowl.',
        'Pat tuna steaks dry with paper towels and season generously with salt and pepper on both sides.',
        'Heat avocado oil in a skillet over very high heat until nearly smoking, then sear each tuna steak for 60-90 seconds per side for a rare center.',
        'Let tuna rest for 2 minutes, then slice against the grain into thin strips.',
        'Toss the salad with two-thirds of the dressing and divide among 4 plates, then top with sliced tuna and avocado.',
        'Drizzle remaining dressing over the tuna, sprinkle with sesame seeds, and serve immediately.',
      ],
      nutrition: { calories: 390, protein: 44, carbs: 16, fat: 18 },
    },
  ],

  'vegetarian-dinners': [
    {
      title: 'Wild Mushroom and Thyme Stroganoff',
      description: 'A medley of cremini, shiitake, and oyster mushrooms in a rich sour cream and Dijon sauce over wide egg noodles. Comforting, earthy, and completely meatless.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Eastern European',
      ingredients: [
        '8 oz cremini mushrooms, sliced',
        '6 oz shiitake mushrooms, stems removed and sliced',
        '4 oz oyster mushrooms, torn into pieces',
        '12 oz wide egg noodles',
        '1 large onion, diced',
        '3 cloves garlic, minced',
        '1 cup vegetable broth',
        '3/4 cup sour cream',
        '1 tablespoon Dijon mustard',
        '2 tablespoons butter',
        '1 tablespoon olive oil',
        '1 tablespoon fresh thyme leaves',
        '2 tablespoons fresh parsley, chopped',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cook egg noodles in salted boiling water according to package directions, drain, and set aside.',
        'Heat butter and olive oil in a large skillet over medium-high heat, then add all mushrooms and cook for 6-7 minutes without stirring until golden brown.',
        'Add diced onion and sauté for 3 minutes until softened, then stir in garlic and thyme for 30 seconds.',
        'Pour in vegetable broth, scraping up any browned bits, and simmer for 3-4 minutes until reduced by half.',
        'Remove skillet from heat and stir in sour cream and Dijon mustard until the sauce is smooth and creamy.',
        'Add the cooked noodles to the skillet and toss until everything is well coated in the stroganoff sauce.',
        'Season with salt and pepper, garnish with fresh parsley, and serve immediately.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 52, fat: 18 },
    },
    {
      title: 'Golden Coconut Chickpea Curry',
      description: 'Chickpeas simmered in a fragrant coconut-tomato curry with warming spices, spinach, and a squeeze of lime. Vegan-friendly and loaded with plant protein.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Indian',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '1 can (14 oz) full-fat coconut milk',
        '1 can (14 oz) diced tomatoes',
        '4 cups fresh baby spinach',
        '1 large onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '2 tablespoons curry powder',
        '1 teaspoon garam masala',
        '1/2 teaspoon turmeric',
        '2 tablespoons coconut oil',
        '1 tablespoon lime juice',
        'Fresh cilantro for garnish',
        'Salt to taste',
      ],
      instructions: [
        'Heat coconut oil in a large deep skillet or Dutch oven over medium heat, then sauté diced onion for 4 minutes until softened and translucent.',
        'Add garlic and ginger, stirring for 30 seconds, then stir in curry powder, garam masala, and turmeric, cooking for 1 minute until very fragrant.',
        'Pour in diced tomatoes and coconut milk, stirring to combine into a smooth curry base.',
        'Add the chickpeas, bring the curry to a simmer, and cook for 12-15 minutes until thickened and the chickpeas absorb some of the flavor.',
        'Stir in the baby spinach and cook until wilted, about 2 minutes.',
        'Add lime juice, season with salt to taste, and stir to incorporate.',
        'Serve over steamed basmati rice, garnished with fresh cilantro and a wedge of lime.',
      ],
      nutrition: { calories: 440, protein: 18, carbs: 42, fat: 24 },
    },
    {
      title: 'Crispy Black Bean Tacos with Mango Salsa',
      description: 'Seasoned black beans in crispy corn tortillas topped with a bright mango-jalapeño salsa, avocado crema, and crunchy cabbage. Taco Tuesday, elevated.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz each) black beans, drained and rinsed',
        '8 small corn tortillas',
        '1 ripe mango, diced',
        '1/2 red onion, finely diced',
        '1 jalapeño, seeded and minced',
        '1/4 cup fresh cilantro, chopped',
        '2 tablespoons lime juice',
        '1 ripe avocado',
        '1/4 cup sour cream',
        '1 cup shredded red cabbage',
        '1 teaspoon cumin',
        '1 teaspoon chili powder',
        '2 tablespoons olive oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Make the mango salsa by combining diced mango, half the red onion, jalapeño, cilantro, 1 tablespoon lime juice, and a pinch of salt in a bowl.',
        'Blend avocado, sour cream, remaining lime juice, and a pinch of salt in a small food processor until smooth to make the avocado crema.',
        'Heat olive oil in a large skillet over medium heat, add black beans, cumin, chili powder, and remaining diced onion, and cook for 5 minutes, mashing some beans with a fork for texture.',
        'Warm corn tortillas in a dry skillet or directly over a gas flame for about 30 seconds per side until slightly charred.',
        'Fill each tortilla with a generous scoop of the seasoned black beans, then top with mango salsa and shredded cabbage.',
        'Drizzle avocado crema over the tacos and garnish with extra cilantro.',
        'Serve immediately with lime wedges on the side.',
      ],
      nutrition: { calories: 410, protein: 16, carbs: 58, fat: 14 },
    },
    {
      title: 'Baked Eggplant Parmesan Stacks',
      description: 'Thick eggplant rounds breaded and baked until crispy, layered with marinara and melted mozzarella. A lighter take on the Italian classic that does not sacrifice flavor.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '2 large eggplants, sliced into 1/2-inch rounds',
        '2 cups marinara sauce',
        '2 cups shredded mozzarella cheese',
        '1/2 cup grated parmesan cheese',
        '1 cup panko breadcrumbs',
        '2 large eggs, beaten',
        '1/2 cup all-purpose flour',
        '1 teaspoon garlic powder',
        '1 teaspoon Italian seasoning',
        '2 tablespoons olive oil',
        'Fresh basil leaves for garnish',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F and line two baking sheets with parchment paper.',
        'Salt the eggplant rounds on both sides and let sit for 10 minutes to draw out moisture, then pat dry with paper towels.',
        'Set up a breading station with flour in one dish, beaten eggs in a second, and panko mixed with garlic powder, Italian seasoning, and parmesan in a third.',
        'Dredge each eggplant round in flour, dip in egg, and press into the panko mixture, then place on the prepared baking sheets and drizzle with olive oil.',
        'Bake for 20 minutes, flipping halfway, until the eggplant is golden and crispy on both sides.',
        'Layer the baked eggplant rounds in a baking dish, spooning marinara and mozzarella between each layer, then bake for 10 more minutes until cheese is melted and bubbly.',
        'Garnish with fresh basil leaves and serve immediately with a side salad or garlic bread.',
      ],
      nutrition: { calories: 380, protein: 22, carbs: 34, fat: 18 },
    },
    {
      title: 'Red Lentil and Sweet Potato Soup',
      description: 'Velvety red lentil soup enriched with sweet potato, warming ginger, and a touch of coconut cream. Naturally high in fiber and plant-based protein.',
      timeMinutes: 40,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 6,
      cuisine: 'Indian',
      ingredients: [
        '1.5 cups red lentils, rinsed',
        '2 medium sweet potatoes, peeled and diced',
        '6 cups vegetable broth',
        '1 can (14 oz) diced tomatoes',
        '1 large onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '2 teaspoons curry powder',
        '1 teaspoon cumin',
        '1/2 teaspoon smoked paprika',
        '2 tablespoons olive oil',
        '1/4 cup coconut cream',
        '1 tablespoon lemon juice',
        'Salt and pepper to taste',
        'Fresh cilantro for garnish',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium heat, add onion, and cook for 4 minutes until softened.',
        'Stir in garlic, ginger, curry powder, cumin, and smoked paprika, cooking for 1 minute until very fragrant.',
        'Add diced sweet potatoes, red lentils, diced tomatoes, and vegetable broth, then bring to a boil.',
        'Reduce heat to medium-low and simmer for 25 minutes until lentils are fully broken down and sweet potatoes are tender.',
        'Use an immersion blender to partially blend the soup, leaving some chunks for texture.',
        'Stir in coconut cream and lemon juice, then season with salt and pepper to taste.',
        'Ladle into bowls, drizzle with a swirl of coconut cream, and garnish with fresh cilantro.',
      ],
      nutrition: { calories: 340, protein: 16, carbs: 52, fat: 8 },
    },
    {
      title: 'Crispy Sesame Tofu Pad Thai',
      description: 'Golden pan-fried tofu tossed with rice noodles, crunchy bean sprouts, and peanuts in a sweet-tangy tamarind sauce. Better than takeout and entirely plant-based.',
      timeMinutes: 30,
      method: 'stir-fry',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '14 oz extra-firm tofu, pressed and cubed',
        '8 oz flat rice noodles',
        '2 cups bean sprouts',
        '3 green onions, sliced',
        '1/4 cup roasted peanuts, roughly chopped',
        '3 tablespoons tamarind paste',
        '2 tablespoons soy sauce',
        '1 tablespoon maple syrup',
        '1 tablespoon rice vinegar',
        '1 tablespoon sriracha',
        '2 tablespoons sesame oil',
        '2 tablespoons cornstarch',
        '2 cloves garlic, minced',
        '2 large eggs, beaten',
        'Lime wedges and cilantro for serving',
      ],
      instructions: [
        'Soak rice noodles in hot water for 8-10 minutes until pliable but not fully soft, then drain.',
        'Toss cubed tofu with cornstarch and a pinch of salt until evenly coated.',
        'Heat 1 tablespoon sesame oil in a large wok over high heat, add tofu in a single layer, and cook for 5-6 minutes, turning occasionally until crispy on all sides, then remove.',
        'Whisk together tamarind paste, soy sauce, maple syrup, rice vinegar, and sriracha in a small bowl for the sauce.',
        'Add remaining sesame oil to the wok, scramble the eggs, then add garlic and drained noodles, tossing for 2 minutes.',
        'Pour the sauce over the noodles and toss until well coated, then add bean sprouts, crispy tofu, and green onions, tossing for another minute.',
        'Serve immediately topped with chopped peanuts, fresh cilantro, and lime wedges.',
      ],
      nutrition: { calories: 460, protein: 22, carbs: 56, fat: 18 },
    },
    {
      title: 'Slow-Cooker Three-Bean Chili Verde',
      description: 'A hearty green chili loaded with pinto beans, black beans, and kidney beans simmered low and slow with tomatillos, poblanos, and warm spices. Set it and forget it.',
      timeMinutes: 360,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 345,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '1 can (15 oz) pinto beans, drained and rinsed',
        '1 can (15 oz) black beans, drained and rinsed',
        '1 can (15 oz) kidney beans, drained and rinsed',
        '1 lb tomatillos, husked and quartered',
        '2 poblano peppers, seeded and diced',
        '1 large onion, diced',
        '3 cloves garlic, minced',
        '1 jalapeño, seeded and minced',
        '2 cups vegetable broth',
        '1 teaspoon cumin',
        '1 teaspoon oregano',
        '1/2 teaspoon coriander',
        '1 tablespoon olive oil',
        'Salt and pepper to taste',
        'Toppings: sour cream, shredded cheese, diced avocado, cilantro',
      ],
      instructions: [
        'Heat olive oil in a skillet over medium heat, sauté onion and poblano peppers for 4 minutes until softened, then add garlic and jalapeño for 30 seconds.',
        'Transfer the sautéed vegetables to a slow cooker along with all three types of beans.',
        'Add quartered tomatillos, vegetable broth, cumin, oregano, coriander, salt, and pepper to the slow cooker.',
        'Cover and cook on low for 6 hours or high for 3 hours until the tomatillos have broken down and flavors are deeply melded.',
        'Use a potato masher to crush some of the beans for a thicker consistency while leaving plenty whole.',
        'Taste and adjust seasoning with more salt, pepper, or a squeeze of lime juice.',
        'Ladle into bowls and top with sour cream, shredded cheese, diced avocado, and fresh cilantro.',
      ],
      nutrition: { calories: 320, protein: 18, carbs: 50, fat: 6 },
    },
    {
      title: 'Mediterranean Halloumi and Grain Salad',
      description: 'Pan-seared halloumi cheese over a vibrant salad of farro, roasted red peppers, cucumbers, olives, and a lemon-herb vinaigrette. Satisfying, fresh, and full of texture.',
      timeMinutes: 25,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '8 oz halloumi cheese, sliced into 1/4-inch slabs',
        '2 cups cooked farro',
        '1 cup roasted red peppers (jarred), diced',
        '1 English cucumber, diced',
        '1/2 cup kalamata olives, halved',
        '1/4 cup red onion, thinly sliced',
        '1/4 cup fresh mint leaves, torn',
        '1/4 cup fresh parsley, chopped',
        '3 tablespoons extra-virgin olive oil',
        '2 tablespoons lemon juice',
        '1 teaspoon dried oregano',
        '1 clove garlic, minced',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Whisk together olive oil, lemon juice, oregano, minced garlic, salt, and pepper in a small bowl to make the vinaigrette.',
        'In a large bowl, combine cooked farro, diced roasted red peppers, cucumber, olives, red onion, mint, and parsley.',
        'Pour the vinaigrette over the grain salad and toss to coat evenly.',
        'Heat a non-stick skillet over medium-high heat without any oil and sear halloumi slices for 2 minutes per side until golden brown with crispy edges.',
        'Divide the grain salad among 4 plates and arrange seared halloumi on top.',
        'Drizzle with any remaining vinaigrette and garnish with extra mint leaves.',
        'Serve immediately while the halloumi is warm and slightly squeaky.',
      ],
      nutrition: { calories: 420, protein: 20, carbs: 34, fat: 24 },
    },
  ],
}

export const dietFaqs2: Record<string, FAQ[]> = {
  'high-protein-meals': [
    {
      question: 'What are the best high-protein dinner ideas?',
      answer: 'Great high-protein dinners include grilled chicken or salmon bowls, lean steak stir-fries, turkey meatball skillets, shrimp with quinoa, and lentil-based dishes. Combining a lean protein source with whole grains and vegetables creates a balanced, satisfying meal that supports muscle recovery.',
    },
    {
      question: 'How much protein should I eat per meal at dinner?',
      answer: 'Most adults benefit from 25-40 grams of protein per meal, depending on body weight and activity level. Aim for at least 30 grams at dinner to support muscle maintenance and keep you feeling full throughout the evening.',
    },
    {
      question: 'What are the best high-protein foods for dinner?',
      answer: 'Top high-protein dinner foods include chicken breast (31g per 4 oz), salmon (25g per 4 oz), lean ground turkey (22g per 4 oz), shrimp (24g per 4 oz), lentils (18g per cup cooked), and eggs (6g each). Combining these with quinoa or beans boosts the total protein even more.',
    },
    {
      question: 'What are easy high-protein meals I can make quickly?',
      answer: 'Quick high-protein meals include shrimp stir-fries (15 minutes), pre-seasoned salmon baked on a sheet pan (20 minutes), canned chickpea and sausage soup (25 minutes), and seared tuna salads (20 minutes). Keeping pre-cooked grains and canned beans on hand also speeds up assembly bowls.',
    },
    {
      question: 'What are good high-protein meal prep dinner ideas?',
      answer: 'Grilled chicken with quinoa and roasted vegetables, turkey meatballs with marinara and whole wheat pasta, and baked cod over lentils all reheat well for meal prep. Cook proteins and grains in bulk on Sunday, then portion into containers with different sauces and vegetables for variety throughout the week.',
    },
  ],

  'vegetarian-dinners': [
    {
      question: 'What are easy vegetarian dinner ideas for weeknights?',
      answer: 'Quick vegetarian dinners include coconut chickpea curry (30 minutes), black bean tacos with mango salsa (25 minutes), mushroom stroganoff (30 minutes), and grain bowls with halloumi cheese (25 minutes). Keeping canned beans, tofu, and pre-cooked grains stocked makes weeknight meatless meals effortless.',
    },
    {
      question: 'What are the best vegetarian protein sources for dinner?',
      answer: 'Excellent vegetarian protein sources include tofu (20g per cup), lentils (18g per cup cooked), chickpeas (15g per cup), black beans (15g per cup), eggs (6g each), halloumi cheese (14g per 2 oz), and tempeh (31g per cup). Combining legumes with whole grains creates a complete protein.',
    },
    {
      question: 'How do you make tofu taste good for dinner?',
      answer: 'The key is pressing tofu to remove excess moisture, then coating it in cornstarch before pan-frying for a crispy exterior. Marinating in flavorful sauces like soy-ginger, tamarind, or sesame-sriracha also helps tofu absorb bold flavors that make it genuinely craveable.',
    },
    {
      question: 'What are quick meatless dinners I can make in under 30 minutes?',
      answer: 'Black bean tacos, coconut chickpea curry, mushroom stroganoff, grain salads with halloumi, and tofu pad Thai can all be made in 25-30 minutes. The trick is relying on canned beans for instant protein and quick-cooking vegetables like spinach, bell peppers, and mushrooms.',
    },
    {
      question: 'What are good vegetarian meal prep ideas for dinner?',
      answer: 'Three-bean chili verde, red lentil soup, and coconut chickpea curry all freeze beautifully and taste even better the next day. For non-soup options, prepare grain bowls with pre-cooked farro or quinoa, roasted vegetables, and a protein like marinated baked tofu, then store components separately for easy assembly.',
    },
  ],
}
