import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const dietRecipes1: Record<string, RecipeIdea[]> = {
  'keto-dinner-ideas': [
    {
      title: 'Bacon-Wrapped Jalapeño Chicken Skillet',
      description: 'Juicy chicken thighs stuffed with cream cheese and jalapeños, wrapped in crispy bacon, and seared to perfection in a buttery skillet.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless skinless chicken thighs',
        '8 slices thick-cut bacon',
        '4 oz cream cheese, softened',
        '2 jalapeño peppers, seeded and finely diced',
        '1 cup shredded cheddar cheese',
        '2 tablespoons butter',
        '2 cloves garlic, minced',
        '1 teaspoon smoked paprika',
        '1/2 teaspoon onion powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. In a small bowl, mix the softened cream cheese, diced jalapeños, and half of the shredded cheddar until well combined.',
        'Butterfly each chicken thigh by slicing horizontally without cutting all the way through, then open flat and season both sides with smoked paprika, onion powder, salt, and pepper.',
        'Spread about 2 tablespoons of the cream cheese mixture onto each opened chicken thigh, then fold closed and wrap each tightly with 2 slices of bacon, securing with toothpicks if needed.',
        'Melt butter in a large oven-safe skillet over medium-high heat. Sear the bacon-wrapped chicken for 3-4 minutes per side until the bacon is crispy and golden.',
        'Transfer the skillet to the oven and bake for 12-15 minutes until chicken reaches an internal temperature of 165°F.',
        'Remove from oven, sprinkle the remaining cheddar cheese over the chicken, and let it melt for 2 minutes under residual heat.',
        'Remove toothpicks, let rest for 3 minutes, then serve with a drizzle of the pan juices.',
      ],
      nutrition: { calories: 520, protein: 42, carbs: 3, fat: 38 },
    },
    {
      title: 'Garlic Butter Salmon and Asparagus Sheet Pan',
      description: 'Flaky salmon fillets and tender asparagus roasted together with an herbed garlic butter glaze. A hands-off keto dinner ready in under 25 minutes.',
      timeMinutes: 25,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 salmon fillets (6 oz each)',
        '1 lb fresh asparagus, trimmed',
        '4 tablespoons butter, melted',
        '4 cloves garlic, minced',
        '1 tablespoon fresh lemon juice',
        '1 tablespoon fresh dill, chopped',
        '1 teaspoon dried Italian seasoning',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Lemon wedges for serving',
      ],
      instructions: [
        'Preheat oven to 400°F and line a large sheet pan with parchment paper.',
        'In a small bowl, combine the melted butter, minced garlic, lemon juice, chopped dill, and Italian seasoning.',
        'Arrange the trimmed asparagus on one side of the sheet pan, drizzle with olive oil, and season with salt and pepper.',
        'Place the salmon fillets skin-side down on the other side of the sheet pan and spoon the garlic butter mixture generously over each fillet.',
        'Roast in the oven for 12-15 minutes until the salmon flakes easily with a fork and the asparagus is tender-crisp.',
        'Serve immediately with lemon wedges on the side.',
      ],
      nutrition: { calories: 440, protein: 38, carbs: 5, fat: 30 },
    },
    {
      title: 'Cheesy Cauliflower and Sausage Gratin',
      description: 'A bubbly, golden casserole of tender cauliflower florets and savory Italian sausage baked in a rich three-cheese sauce.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 large head cauliflower, cut into small florets',
        '1 lb Italian sausage, casings removed',
        '1 cup heavy cream',
        '1 cup shredded mozzarella cheese',
        '1/2 cup shredded sharp cheddar cheese',
        '1/4 cup grated parmesan cheese',
        '2 tablespoons butter',
        '3 cloves garlic, minced',
        '1 teaspoon Dijon mustard',
        '1/2 teaspoon red pepper flakes',
        'Salt and black pepper to taste',
        'Fresh chives for garnish',
      ],
      instructions: [
        'Preheat oven to 375°F and grease a 9x13-inch baking dish with butter.',
        'Steam or boil the cauliflower florets for 4-5 minutes until just tender but still firm, then drain thoroughly and pat dry with paper towels to remove excess moisture.',
        'In a large skillet over medium-high heat, brown the Italian sausage, breaking it into crumbles, until cooked through, about 6-7 minutes. Remove and set aside.',
        'In the same skillet, melt the butter over medium heat. Add garlic and cook 30 seconds, then pour in the heavy cream and Dijon mustard. Simmer for 3-4 minutes until slightly thickened. Stir in half the mozzarella, half the cheddar, salt, and pepper until melted and smooth.',
        'Combine the cauliflower and sausage in the prepared baking dish. Pour the cheese sauce over the top and gently stir to coat everything evenly.',
        'Sprinkle the remaining mozzarella, cheddar, and parmesan over the top along with red pepper flakes.',
        'Bake for 20-25 minutes until bubbly and golden brown on top. Garnish with fresh chives before serving.',
      ],
      nutrition: { calories: 480, protein: 28, carbs: 8, fat: 38 },
    },
    {
      title: 'Creamy Tuscan Chicken Soup',
      description: 'A rich and velvety keto soup loaded with shredded chicken, sun-dried tomatoes, spinach, and a parmesan-infused cream broth.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1.5 lbs boneless skinless chicken thighs',
        '4 cups chicken broth',
        '1 cup heavy cream',
        '1/2 cup sun-dried tomatoes (oil-packed), chopped',
        '3 cups fresh baby spinach',
        '1/2 cup grated parmesan cheese',
        '3 cloves garlic, minced',
        '1 small onion, diced',
        '2 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        '1/2 teaspoon red pepper flakes',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large pot or Dutch oven over medium-high heat. Season chicken thighs with Italian seasoning, salt, and pepper, then sear for 4-5 minutes per side until golden. Remove and set aside.',
        'In the same pot, sauté the diced onion until softened, about 3 minutes. Add garlic and cook 30 seconds until fragrant.',
        'Pour in the chicken broth and sun-dried tomatoes. Bring to a boil, then reduce heat to a simmer.',
        'Return the chicken thighs to the pot and simmer for 12-15 minutes until fully cooked through. Remove chicken, shred with two forks, and return to the pot.',
        'Stir in the heavy cream, parmesan cheese, and red pepper flakes. Simmer gently for 3-4 minutes until the soup is creamy and heated through.',
        'Add the baby spinach and stir until wilted, about 1-2 minutes. Season with additional salt and pepper to taste.',
        'Ladle into bowls and serve with an extra sprinkle of parmesan on top.',
      ],
      nutrition: { calories: 410, protein: 34, carbs: 6, fat: 28 },
    },
    {
      title: 'Spicy Avocado Tuna Poke Bowl',
      description: 'A refreshing no-cook keto bowl with sushi-grade tuna, creamy avocado, cucumber, and a spicy sesame sriracha dressing over shredded cabbage.',
      timeMinutes: 15,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 0,
      servings: 2,
      cuisine: 'Asian',
      ingredients: [
        '12 oz sushi-grade ahi tuna, cut into 1/2-inch cubes',
        '1 large ripe avocado, diced',
        '1 Persian cucumber, thinly sliced',
        '2 cups shredded napa cabbage',
        '2 tablespoons soy sauce or coconut aminos',
        '1 tablespoon sesame oil',
        '1 teaspoon sriracha sauce',
        '1 teaspoon rice vinegar',
        '1 tablespoon sesame seeds',
        '2 green onions, sliced',
        '1 teaspoon fresh ginger, grated',
        'Nori strips for garnish',
      ],
      instructions: [
        'In a medium bowl, whisk together the soy sauce, sesame oil, sriracha, rice vinegar, and grated ginger to make the dressing.',
        'Add the cubed tuna to the dressing and gently toss to coat. Let it marinate for 5 minutes while you prepare the other ingredients.',
        'Divide the shredded napa cabbage between two bowls as the base.',
        'Arrange the marinated tuna, diced avocado, and sliced cucumber in sections on top of the cabbage.',
        'Drizzle any remaining dressing from the tuna bowl over the top of each poke bowl.',
        'Sprinkle with sesame seeds, sliced green onions, and nori strips. Serve immediately.',
      ],
      nutrition: { calories: 390, protein: 36, carbs: 9, fat: 24 },
    },
    {
      title: 'Parmesan-Crusted Pork Chops with Roasted Broccoli',
      description: 'Thick-cut pork chops coated in a golden parmesan and almond flour crust, baked until crispy, and served alongside roasted garlic broccoli.',
      timeMinutes: 40,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '4 bone-in pork chops (about 1 inch thick)',
        '1/2 cup grated parmesan cheese',
        '1/3 cup almond flour',
        '1 teaspoon garlic powder',
        '1 teaspoon smoked paprika',
        '2 large eggs, beaten',
        '1 lb broccoli florets',
        '3 tablespoons olive oil',
        '3 cloves garlic, minced',
        '2 tablespoons butter, melted',
        'Salt and black pepper to taste',
        'Fresh lemon wedges for serving',
      ],
      instructions: [
        'Preheat oven to 400°F and line a large baking sheet with parchment paper.',
        'In a shallow dish, combine the parmesan, almond flour, garlic powder, smoked paprika, salt, and pepper. In another shallow dish, place the beaten eggs.',
        'Pat the pork chops dry and season with salt and pepper. Dip each pork chop into the egg, then press firmly into the parmesan mixture to coat both sides evenly.',
        'Place the coated pork chops on one side of the prepared baking sheet and drizzle with melted butter.',
        'Toss the broccoli florets with olive oil, minced garlic, salt, and pepper. Spread them on the other side of the baking sheet.',
        'Bake for 22-25 minutes until the pork chops reach 145°F internally and the crust is golden brown, and the broccoli is tender with lightly charred edges.',
        'Let the pork chops rest for 5 minutes before serving alongside the roasted broccoli with lemon wedges.',
      ],
      nutrition: { calories: 490, protein: 44, carbs: 7, fat: 32 },
    },
    {
      title: 'Creamy Lemon Butter Shrimp with Zucchini',
      description: 'Plump shrimp sautéed with zucchini noodles in a luscious lemon butter cream sauce with capers and fresh herbs. Ready in just 20 minutes.',
      timeMinutes: 20,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '1.5 lbs large shrimp, peeled and deveined',
        '4 medium zucchini, spiralized into noodles',
        '4 tablespoons butter',
        '3 cloves garlic, minced',
        '1/2 cup heavy cream',
        '2 tablespoons fresh lemon juice',
        '1 teaspoon lemon zest',
        '2 tablespoons capers, drained',
        '1/4 cup fresh parsley, chopped',
        '1/4 teaspoon red pepper flakes',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Pat the shrimp dry and season with salt and pepper. Melt 2 tablespoons of butter in a large skillet over medium-high heat.',
        'Add the shrimp in a single layer and cook for 2 minutes per side until pink and curled. Remove and set aside on a plate.',
        'In the same skillet, melt the remaining 2 tablespoons of butter. Add the garlic and cook for 30 seconds until fragrant.',
        'Pour in the heavy cream, lemon juice, lemon zest, and capers. Stir and simmer for 2-3 minutes until the sauce thickens slightly.',
        'Add the spiralized zucchini noodles to the skillet and toss with the sauce for 2 minutes until just tender but still firm.',
        'Return the shrimp to the pan, add red pepper flakes and chopped parsley, and toss everything together gently.',
        'Serve immediately in shallow bowls with an extra squeeze of lemon on top.',
      ],
      nutrition: { calories: 380, protein: 36, carbs: 8, fat: 24 },
    },
    {
      title: 'Slow-Cooker Mississippi Pot Roast',
      description: 'Melt-in-your-mouth chuck roast slow-cooked with butter, ranch seasoning, tangy pepperoncini, and savory au jus. A keto comfort food classic.',
      timeMinutes: 480,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 470,
      servings: 8,
      cuisine: 'American',
      ingredients: [
        '3 lb beef chuck roast',
        '4 tablespoons butter',
        '1 packet ranch seasoning mix (check for low-carb)',
        '1 packet au jus gravy mix',
        '8-10 pepperoncini peppers, whole',
        '1/4 cup pepperoncini juice from the jar',
        '2 tablespoons olive oil',
        '4 cloves garlic, minced',
        '1 teaspoon onion powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season the chuck roast generously on all sides with salt, pepper, and onion powder.',
        'Heat olive oil in a large skillet over high heat. Sear the roast for 3-4 minutes per side until a deep brown crust forms on all sides.',
        'Place the seared roast in the slow cooker. Sprinkle the ranch seasoning mix and au jus mix evenly over the top of the meat.',
        'Place the butter on top of the roast. Scatter the pepperoncini peppers around and over the meat, then pour in the pepperoncini juice.',
        'Add the minced garlic around the roast. Cover and cook on low for 8 hours or on high for 5 hours until the meat is fall-apart tender.',
        'Remove the roast and shred with two forks. Return the shredded beef to the juices in the slow cooker and stir to coat.',
        'Serve the shredded beef with a generous ladle of the cooking juices. Pairs well with cauliflower mash or a simple side salad.',
      ],
      nutrition: { calories: 450, protein: 40, carbs: 4, fat: 30 },
    },
  ],

  'low-carb-dinners': [
    {
      title: 'Thai Basil Chicken Lettuce Wraps',
      description: 'Aromatic ground chicken stir-fried with Thai basil, chilies, and garlic, served in crisp butter lettuce cups with a tangy lime dipping sauce.',
      timeMinutes: 20,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '1.5 lbs ground chicken',
        '1 head butter lettuce, leaves separated',
        '1 cup fresh Thai basil leaves',
        '4 cloves garlic, minced',
        '2 Thai bird chilies, thinly sliced (or 1 teaspoon red pepper flakes)',
        '2 tablespoons soy sauce',
        '1 tablespoon fish sauce',
        '1 tablespoon oyster sauce',
        '1 teaspoon sesame oil',
        '2 tablespoons vegetable oil',
        '1 small shallot, thinly sliced',
        '2 limes, cut into wedges',
        'Fresh cilantro for garnish',
      ],
      instructions: [
        'In a small bowl, stir together the soy sauce, fish sauce, oyster sauce, and sesame oil to make the sauce. Set aside.',
        'Heat vegetable oil in a large wok or skillet over high heat until smoking. Add the sliced shallot and garlic and stir-fry for 30 seconds until fragrant.',
        'Add the ground chicken, breaking it into small pieces with a spatula. Cook for 5-6 minutes, stirring frequently, until the chicken is browned and cooked through with some crispy bits.',
        'Add the sliced Thai chilies and pour the prepared sauce over the chicken. Toss to coat evenly and cook for 1 minute.',
        'Remove from heat and fold in the fresh Thai basil leaves, stirring until they just begin to wilt.',
        'Spoon the chicken mixture into butter lettuce cups and garnish with fresh cilantro.',
        'Serve with lime wedges on the side for squeezing over the top.',
      ],
      nutrition: { calories: 320, protein: 34, carbs: 6, fat: 18 },
    },
    {
      title: 'Stuffed Bell Peppers with Ground Turkey and Cheese',
      description: 'Vibrant bell peppers filled with a savory mixture of seasoned ground turkey, diced tomatoes, and melted cheese. A colorful and satisfying low-carb dinner.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 large bell peppers (assorted colors), tops cut off and seeds removed',
        '1.5 lbs ground turkey',
        '1 can (14 oz) diced tomatoes, drained',
        '1 cup shredded Mexican blend cheese',
        '1 small onion, finely diced',
        '3 cloves garlic, minced',
        '1 teaspoon cumin',
        '1 teaspoon chili powder',
        '1/2 teaspoon smoked paprika',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Fresh cilantro and sour cream for topping',
      ],
      instructions: [
        'Preheat oven to 375°F. Lightly oil a baking dish large enough to hold the peppers upright.',
        'Heat olive oil in a large skillet over medium-high heat. Sauté the diced onion for 3 minutes until softened, then add garlic and cook 30 seconds.',
        'Add the ground turkey, cumin, chili powder, smoked paprika, salt, and pepper. Cook for 6-7 minutes, breaking into crumbles, until fully browned.',
        'Stir in the drained diced tomatoes and half of the shredded cheese. Mix until the cheese melts into the filling.',
        'Spoon the turkey mixture into each hollowed-out bell pepper, packing it firmly and mounding it on top. Place peppers upright in the baking dish.',
        'Bake for 25 minutes until the peppers are tender. Sprinkle the remaining cheese on top and bake 5 more minutes until melted and bubbly.',
        'Let cool for 5 minutes, then serve topped with a dollop of sour cream and fresh cilantro.',
      ],
      nutrition: { calories: 420, protein: 38, carbs: 14, fat: 24 },
    },
    {
      title: 'Zucchini Noodle Shrimp Scampi',
      description: 'Garlicky, buttery shrimp tossed with tender zucchini noodles, white wine, and a splash of lemon. A light and elegant low-carb take on the Italian classic.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1.5 lbs large shrimp, peeled and deveined',
        '4 medium zucchini, spiralized into noodles',
        '4 tablespoons butter',
        '3 tablespoons olive oil',
        '6 cloves garlic, thinly sliced',
        '1/4 cup dry white wine',
        '2 tablespoons fresh lemon juice',
        '1/4 teaspoon red pepper flakes',
        '1/4 cup fresh parsley, chopped',
        '2 tablespoons grated parmesan cheese',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Pat the shrimp dry and season with salt and pepper. Heat 2 tablespoons of olive oil in a large skillet over medium-high heat.',
        'Add the shrimp in a single layer and cook for 1-2 minutes per side until just pink. Remove and set aside on a plate.',
        'Reduce heat to medium. Add butter, the remaining tablespoon of olive oil, and sliced garlic to the skillet. Cook for 1 minute until garlic is golden and fragrant.',
        'Pour in the white wine and lemon juice, scraping up any browned bits from the bottom of the pan. Simmer for 2 minutes until the sauce reduces slightly.',
        'Add the spiralized zucchini noodles and toss in the sauce for 1-2 minutes until just tender but still slightly firm.',
        'Return the shrimp to the skillet, add red pepper flakes and parsley, and toss everything together.',
        'Serve immediately topped with grated parmesan cheese.',
      ],
      nutrition: { calories: 350, protein: 34, carbs: 10, fat: 20 },
    },
    {
      title: 'Sheet-Pan Chipotle Lime Chicken Fajitas',
      description: 'Smoky chipotle-rubbed chicken and colorful peppers roasted on a single sheet pan, served with all the fixings. Dinner for the whole family with almost no cleanup.',
      timeMinutes: 35,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1.5 lbs boneless skinless chicken thighs, sliced into strips',
        '2 large bell peppers (1 red, 1 green), sliced into strips',
        '1 large onion, sliced into half-moons',
        '2 tablespoons olive oil',
        '2 tablespoons fresh lime juice',
        '1 tablespoon chipotle chili powder',
        '1 teaspoon cumin',
        '1 teaspoon garlic powder',
        '1/2 teaspoon smoked paprika',
        'Salt and black pepper to taste',
        'Butter lettuce leaves for wrapping',
        'Sour cream, guacamole, and salsa for serving',
      ],
      instructions: [
        'Preheat oven to 425°F and line a large sheet pan with parchment paper.',
        'In a large bowl, whisk together the olive oil, lime juice, chipotle chili powder, cumin, garlic powder, smoked paprika, salt, and pepper.',
        'Add the chicken strips, sliced bell peppers, and onion to the bowl. Toss until everything is evenly coated in the spice mixture.',
        'Spread the chicken and vegetables in a single layer across the sheet pan, making sure not to overcrowd.',
        'Roast for 18-20 minutes, flipping halfway through, until the chicken is cooked through and the edges of the peppers are slightly charred.',
        'Serve the fajita mixture in butter lettuce wraps instead of tortillas to keep it low carb.',
        'Set out bowls of sour cream, guacamole, and salsa for topping.',
      ],
      nutrition: { calories: 340, protein: 36, carbs: 12, fat: 16 },
    },
    {
      title: 'Italian Sausage and Kale One-Pan',
      description: 'Spicy crumbled Italian sausage cooked with hearty kale, white beans, and garlic in a savory chicken broth. Rustic, warming, and effortlessly low carb.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1.5 lbs hot Italian sausage, casings removed',
        '1 large bunch lacinato kale, stems removed and leaves roughly chopped',
        '1/2 cup canned cannellini beans, drained and rinsed',
        '1 cup chicken broth',
        '4 cloves garlic, minced',
        '1 small onion, diced',
        '2 tablespoons olive oil',
        '1/4 teaspoon red pepper flakes',
        '1/4 cup grated parmesan cheese',
        'Salt and black pepper to taste',
        '1 tablespoon red wine vinegar',
      ],
      instructions: [
        'Heat olive oil in a large deep skillet or Dutch oven over medium-high heat. Add the sausage and break it into crumbles with a wooden spoon, cooking for 6-7 minutes until browned and crispy.',
        'Add the diced onion to the pan and sauté for 2-3 minutes until softened. Add the garlic and red pepper flakes and cook for 30 seconds.',
        'Pour in the chicken broth and scrape up any browned bits from the bottom of the pan.',
        'Add the chopped kale in batches, stirring and allowing each batch to wilt slightly before adding more. Cook for 3-4 minutes until all the kale is tender.',
        'Stir in the cannellini beans and red wine vinegar. Cook for 2 more minutes until the beans are heated through and the liquid has reduced slightly.',
        'Season with salt and pepper to taste. Serve in bowls topped with grated parmesan cheese.',
      ],
      nutrition: { calories: 440, protein: 30, carbs: 14, fat: 28 },
    },
    {
      title: 'Cauliflower Crust Margherita Pizza',
      description: 'A crispy homemade cauliflower crust topped with San Marzano tomato sauce, fresh mozzarella, and fragrant basil. Pizza night without the carb overload.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 large head cauliflower, riced (about 4 cups riced)',
        '1 large egg',
        '1/2 cup shredded mozzarella cheese (for the crust)',
        '2 tablespoons almond flour',
        '1 teaspoon dried oregano',
        '1/2 teaspoon garlic powder',
        '1/2 cup San Marzano tomato sauce',
        '8 oz fresh mozzarella, sliced',
        '1/4 cup fresh basil leaves',
        '1 tablespoon olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F and line a baking sheet with parchment paper. Microwave the riced cauliflower for 5 minutes, then let cool and squeeze out as much moisture as possible using a clean kitchen towel.',
        'In a bowl, combine the squeezed cauliflower, egg, shredded mozzarella, almond flour, oregano, garlic powder, salt, and pepper. Mix until a dough forms.',
        'Press the cauliflower dough into a thin round or rectangle on the prepared baking sheet, about 1/4 inch thick. Brush the top with olive oil.',
        'Bake the crust alone for 15-18 minutes until golden brown and firm to the touch.',
        'Remove from oven and spread the tomato sauce evenly over the crust, leaving a small border. Arrange the fresh mozzarella slices on top.',
        'Return to the oven and bake for 8-10 more minutes until the cheese is melted and bubbly with golden spots.',
        'Remove from oven, scatter fresh basil leaves over the top, slice into portions, and serve immediately.',
      ],
      nutrition: { calories: 310, protein: 22, carbs: 12, fat: 18 },
    },
    {
      title: 'Instant-Pot Chicken Tikka Masala',
      description: 'Tender chunks of chicken simmered in a creamy, aromatic spiced tomato sauce. This pressure cooker version delivers deep flavor in a fraction of the time.',
      timeMinutes: 30,
      method: 'instant-pot',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 20,
      servings: 6,
      cuisine: 'Indian',
      ingredients: [
        '2 lbs boneless skinless chicken thighs, cut into chunks',
        '1 can (14 oz) crushed tomatoes',
        '1 cup heavy cream',
        '1 medium onion, diced',
        '4 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '2 tablespoons garam masala',
        '1 tablespoon ground cumin',
        '1 teaspoon turmeric',
        '1 teaspoon smoked paprika',
        '1/2 teaspoon cayenne pepper',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
        'Salt to taste',
        'Fresh cilantro for garnish',
      ],
      instructions: [
        'Set the Instant Pot to sauté mode. Heat olive oil and butter, then cook the diced onion for 3-4 minutes until softened.',
        'Add the garlic and ginger, stirring for 1 minute until fragrant. Stir in the garam masala, cumin, turmeric, smoked paprika, and cayenne pepper, cooking for 30 seconds.',
        'Add the chicken chunks and toss to coat in the spice mixture. Pour in the crushed tomatoes and stir to combine.',
        'Seal the lid and set to pressure cook on high for 10 minutes. Allow a natural pressure release for 5 minutes, then quick release the remaining pressure.',
        'Open the lid and stir in the heavy cream until fully incorporated. Switch to sauté mode and simmer for 3-4 minutes until the sauce thickens to your desired consistency.',
        'Season with salt to taste. Serve garnished with fresh cilantro. Pairs well with cauliflower rice or a simple side salad.',
      ],
      nutrition: { calories: 400, protein: 36, carbs: 10, fat: 24 },
    },
    {
      title: 'Mediterranean Lamb Meatball Salad Bowl',
      description: 'Juicy spiced lamb meatballs served over a bed of mixed greens with cucumber, tomato, kalamata olives, feta, and a creamy tahini dressing.',
      timeMinutes: 30,
      method: 'salad',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '1.5 lbs ground lamb',
        '1/4 cup fresh parsley, finely chopped',
        '2 cloves garlic, minced',
        '1 teaspoon ground cumin',
        '1 teaspoon ground coriander',
        '1/2 teaspoon cinnamon',
        '6 cups mixed salad greens',
        '1 cup cherry tomatoes, halved',
        '1 Persian cucumber, sliced',
        '1/4 cup kalamata olives, halved',
        '1/3 cup crumbled feta cheese',
        '3 tablespoons tahini',
        '2 tablespoons lemon juice',
        '2 tablespoons warm water',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F and line a baking sheet with parchment paper.',
        'In a large bowl, combine the ground lamb, parsley, garlic, cumin, coriander, cinnamon, salt, and pepper. Mix gently until just combined, then form into 20 small meatballs, about 1.5 inches each.',
        'Place meatballs on the prepared baking sheet and drizzle with olive oil. Bake for 14-16 minutes until cooked through and lightly browned.',
        'While the meatballs bake, make the tahini dressing by whisking together the tahini, lemon juice, warm water, a pinch of salt, and pepper until smooth and drizzleable.',
        'Divide the mixed greens among 4 bowls. Top each with cherry tomatoes, cucumber slices, kalamata olives, and crumbled feta.',
        'Place 5 warm meatballs on each salad bowl and drizzle generously with the tahini dressing.',
        'Serve immediately while the meatballs are still warm against the cool, crisp salad.',
      ],
      nutrition: { calories: 480, protein: 34, carbs: 10, fat: 34 },
    },
  ],
}

export const dietFaqs1: Record<string, FAQ[]> = {
  'keto-dinner-ideas': [
    {
      question: 'What can I eat for dinner on keto?',
      answer: 'On keto, focus on dinners built around proteins like chicken, beef, pork, salmon, and shrimp paired with low-carb vegetables such as broccoli, cauliflower, zucchini, and spinach. Add healthy fats from butter, olive oil, avocado, and cheese to keep you satisfied and in ketosis.',
    },
    {
      question: 'Is cauliflower keto friendly?',
      answer: 'Yes, cauliflower is one of the most popular keto vegetables with only about 3g net carbs per cup. It is incredibly versatile and works as a substitute for rice, mashed potatoes, pizza crust, and even mac and cheese.',
    },
    {
      question: 'How many carbs should I eat per day to stay in ketosis?',
      answer: 'Most people need to stay under 20-50g of total carbs per day to maintain ketosis, with 20g being the most reliable target for beginners. Net carbs (total carbs minus fiber) are what matter most, so load up on high-fiber, low-carb vegetables to stay on track.',
    },
    {
      question: 'What are easy keto dinner ideas for beginners?',
      answer: 'Start with simple recipes like bacon-wrapped chicken, sheet-pan salmon with vegetables, or a cheeseburger bowl without the bun. These recipes use basic ingredients, require minimal prep, and are naturally high in fat and very low in carbs without needing specialty products.',
    },
    {
      question: 'Can you eat dairy on keto?',
      answer: 'Most dairy products are excellent for keto, including butter, heavy cream, hard cheeses, cream cheese, and sour cream. Avoid sweetened yogurts and milk in large quantities since they contain more sugar. Always check labels for hidden carbs in processed dairy products.',
    },
  ],

  'low-carb-dinners': [
    {
      question: 'What are some easy low carb dinner ideas?',
      answer: 'Easy low-carb dinners include lettuce-wrap tacos, stuffed bell peppers, zucchini noodle pasta dishes, sheet-pan chicken fajitas, and stir-fries served over cauliflower rice. These swap out high-carb bases like bread, pasta, and rice for vegetable alternatives without sacrificing flavor.',
    },
    {
      question: 'What is considered a low carb diet?',
      answer: 'A low-carb diet typically means eating fewer than 100-150g of carbs per day, with stricter versions aiming for under 50g. For dinner specifically, keeping each meal under 20g of carbs is a practical target that leaves room for small amounts of carbs at other meals and snacks.',
    },
    {
      question: 'What are good low carb substitutes for pasta, rice, and bread?',
      answer: 'Spiralized zucchini or "zoodles" are the most popular pasta substitute, while riced cauliflower works perfectly in place of rice. For bread, use large lettuce leaves as wraps, portobello mushroom caps as buns, or make cloud bread from eggs and cream cheese.',
    },
    {
      question: 'What are easy low carb meals for beginners?',
      answer: 'Start with meals that are naturally low in carbs rather than trying to recreate carb-heavy dishes right away. Grilled chicken with roasted vegetables, stir-fried shrimp with broccoli, or a big salad with protein and avocado are all satisfying and require no special low-carb ingredients.',
    },
    {
      question: 'Are beans and legumes low carb?',
      answer: 'Most beans and legumes are relatively high in carbs, with a half-cup of black beans containing about 20g of carbs. However, small portions can fit into a low-carb diet since they also provide fiber and protein. Green beans and edamame are the lowest-carb legume options at around 4-6g net carbs per serving.',
    },
  ],
}
