import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const dietRecipes3: Record<string, RecipeIdea[]> = {
  'gluten-free-dinners': [
    {
      title: 'Tamari Chicken Teriyaki Stir-Fry with Jasmine Rice',
      description: 'Tender chicken strips glazed in a rich tamari teriyaki sauce with crisp snap peas, carrots, and bell pepper over fluffy jasmine rice.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1.5 pounds boneless, skinless chicken breasts, sliced into thin strips',
        '3 cups cooked jasmine rice',
        '1 cup snap peas, trimmed',
        '1 large carrot, julienned',
        '1 red bell pepper, thinly sliced',
        '1/4 cup gluten-free tamari',
        '2 tablespoons honey',
        '1 tablespoon rice vinegar',
        '1 tablespoon cornstarch mixed with 2 tablespoons water',
        '2 cloves garlic, minced',
        '1 teaspoon fresh ginger, grated',
        '2 tablespoons vegetable oil',
        '1 tablespoon sesame oil',
        'Sesame seeds and sliced green onions for garnish',
      ],
      instructions: [
        'Whisk together tamari, honey, rice vinegar, garlic, and ginger in a small bowl to make the teriyaki sauce.',
        'Heat vegetable oil in a large wok or skillet over high heat until shimmering.',
        'Add chicken strips in a single layer and cook without stirring for 2 minutes, then stir-fry until golden and cooked through, about 5 minutes total. Remove and set aside.',
        'Add snap peas, carrot, and bell pepper to the wok and stir-fry for 2-3 minutes until crisp-tender.',
        'Return chicken to the wok, pour in the teriyaki sauce and cornstarch slurry, and toss until the sauce thickens and coats everything, about 1-2 minutes.',
        'Drizzle with sesame oil and toss once more.',
        'Serve over jasmine rice and garnish with sesame seeds and sliced green onions.',
      ],
      nutrition: { calories: 430, protein: 38, carbs: 46, fat: 11 },
    },
    {
      title: 'Pan-Seared Salmon with Herb Butter and Roasted Asparagus',
      description: 'Crispy-skinned salmon fillets finished with a bright lemon-herb compound butter alongside tender roasted asparagus spears.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '4 skin-on salmon fillets (6 oz each)',
        '1 pound asparagus, trimmed',
        '3 tablespoons unsalted butter, softened',
        '1 tablespoon fresh dill, finely chopped',
        '1 tablespoon fresh parsley, finely chopped',
        '1 lemon, zested and juiced',
        '2 cloves garlic, minced',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Lemon wedges for serving',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C). Toss asparagus with 1 tablespoon olive oil, salt, and pepper on a sheet pan and roast for 12-15 minutes until tender.',
        'While asparagus roasts, mix softened butter with dill, parsley, lemon zest, and half the lemon juice to make the herb butter.',
        'Pat salmon fillets dry and season generously with salt and pepper on both sides.',
        'Heat remaining olive oil in a large oven-safe skillet over medium-high heat. Place salmon skin-side down and cook for 4 minutes until skin is crispy.',
        'Flip salmon and cook for 3-4 more minutes until the fish is cooked through but still moist in the center.',
        'Top each fillet with a generous pat of herb butter and a squeeze of remaining lemon juice.',
        'Plate the salmon alongside roasted asparagus and serve with lemon wedges.',
      ],
      nutrition: { calories: 410, protein: 36, carbs: 6, fat: 28 },
    },
    {
      title: 'Sheet-Pan Shrimp Fajitas with Charred Corn Tortillas',
      description: 'Sizzling seasoned shrimp with caramelized peppers and onions piled into warm corn tortillas and finished with fresh lime and cilantro.',
      timeMinutes: 30,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1.5 pounds large shrimp, peeled and deveined',
        '2 large bell peppers (1 red, 1 yellow), sliced into strips',
        '1 large red onion, sliced into half-moons',
        '2 tablespoons olive oil',
        '1 tablespoon chili powder',
        '1 teaspoon cumin',
        '1 teaspoon smoked paprika',
        '1/2 teaspoon garlic powder',
        '12 corn tortillas',
        '1 avocado, sliced',
        '1/4 cup fresh cilantro, chopped',
        '2 limes, cut into wedges',
        'Salt and pepper to taste',
        'Hot sauce for serving',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment paper.',
        'In a large bowl, combine chili powder, cumin, smoked paprika, garlic powder, salt, and pepper.',
        'Toss sliced bell peppers and onion with 1 tablespoon olive oil and half the spice mixture, then spread on the sheet pan. Roast for 10 minutes.',
        'Toss shrimp with remaining olive oil and spice mixture. Scatter shrimp over the vegetables and roast for 8-10 minutes until shrimp are pink and curled.',
        'Warm corn tortillas in a dry skillet or directly over a gas flame for about 30 seconds per side.',
        'Assemble fajitas by filling tortillas with shrimp, peppers, and onions.',
        'Top with avocado slices, fresh cilantro, a squeeze of lime juice, and hot sauce.',
      ],
      nutrition: { calories: 390, protein: 32, carbs: 42, fat: 12 },
    },
    {
      title: 'Hawaiian Ahi Tuna Poke Bowl with Sticky Rice',
      description: 'Fresh cubed ahi tuna marinated in tamari and sesame tossed over sushi rice with avocado, edamame, cucumber, and spicy mayo.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 5,
      servings: 4,
      cuisine: 'Hawaiian',
      ingredients: [
        '1 pound sushi-grade ahi tuna, cut into 1/2-inch cubes',
        '3 cups cooked sushi rice',
        '1 tablespoon rice vinegar (for the rice)',
        '3 tablespoons gluten-free tamari',
        '1 tablespoon sesame oil',
        '1 teaspoon sriracha',
        '1 avocado, diced',
        '1 cup shelled edamame, thawed',
        '1 small cucumber, diced',
        '2 green onions, sliced',
        '1 tablespoon sesame seeds',
        '1/4 cup mayonnaise mixed with 1 teaspoon sriracha for spicy mayo',
        'Pickled ginger for serving',
      ],
      instructions: [
        'Season cooked sushi rice with rice vinegar while still warm, gently folding to combine.',
        'In a medium bowl, gently toss cubed tuna with tamari, sesame oil, and sriracha. Let marinate for 5-10 minutes.',
        'Divide seasoned rice among 4 bowls.',
        'Arrange marinated tuna, diced avocado, edamame, and cucumber in sections on top of the rice.',
        'Drizzle each bowl with spicy mayo.',
        'Sprinkle with sesame seeds and sliced green onions.',
        'Serve immediately with pickled ginger on the side.',
      ],
      nutrition: { calories: 460, protein: 34, carbs: 48, fat: 14 },
    },
    {
      title: 'Roasted Tomato and Red Pepper Soup with Crispy Potato Bites',
      description: 'Velvety smooth roasted tomato and red pepper soup served with golden crispy potato bites for dipping. Naturally gluten-free comfort food.',
      timeMinutes: 50,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 pounds roma tomatoes, halved',
        '3 large red bell peppers, quartered and seeded',
        '1 medium yellow onion, quartered',
        '6 cloves garlic, peeled',
        '3 tablespoons olive oil',
        '3 cups vegetable broth',
        '1 teaspoon smoked paprika',
        '1/2 teaspoon red pepper flakes',
        '1 pound baby potatoes, quartered',
        '2 tablespoons fresh basil, chopped',
        'Salt and black pepper to taste',
        'Sour cream or coconut cream for serving',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Arrange tomatoes, bell peppers, onion, and garlic on a large sheet pan. Drizzle with 2 tablespoons olive oil, salt, and pepper. Roast for 25 minutes until charred and tender.',
        'While vegetables roast, toss quartered baby potatoes with remaining olive oil, salt, and smoked paprika on a separate sheet pan. Roast alongside the vegetables for 25 minutes until golden and crispy.',
        'Transfer roasted tomatoes, peppers, onion, and garlic to a large pot. Add vegetable broth and red pepper flakes.',
        'Use an immersion blender to puree the soup until silky smooth, or blend in batches in a regular blender.',
        'Simmer over medium heat for 10 minutes, then taste and adjust salt and pepper.',
        'Ladle soup into bowls and top with crispy potato bites and a swirl of sour cream.',
        'Garnish with fresh basil and a drizzle of olive oil before serving.',
      ],
      nutrition: { calories: 280, protein: 7, carbs: 38, fat: 12 },
    },
    {
      title: 'One-Pan Greek Lemon Chicken with Potatoes and Green Beans',
      description: 'Juicy chicken thighs roasted with baby potatoes and green beans in a zesty oregano-lemon sauce. A complete meal from one pan.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '4 bone-in, skin-on chicken thighs',
        '1 pound baby potatoes, halved',
        '8 ounces green beans, trimmed',
        '3 tablespoons olive oil',
        '3 lemons (juice of 2, 1 sliced into rounds)',
        '4 cloves garlic, minced',
        '2 teaspoons dried oregano',
        '1 teaspoon dried thyme',
        '1/2 cup chicken broth',
        'Salt and black pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Season chicken thighs generously with salt, pepper, oregano, and thyme.',
        'Heat 1 tablespoon olive oil in a large oven-safe skillet over medium-high heat. Sear chicken thighs skin-side down for 5 minutes until golden and crispy. Remove and set aside.',
        'Toss halved potatoes with remaining olive oil, garlic, salt, and pepper. Spread in the skillet in a single layer.',
        'Nestle green beans between the potatoes. Pour lemon juice and chicken broth into the pan.',
        'Place seared chicken thighs skin-side up on top of the vegetables. Lay lemon slices around the chicken.',
        'Roast in the oven for 25-30 minutes until chicken reaches 175°F internally and potatoes are fork-tender.',
        'Garnish with fresh parsley and serve directly from the skillet.',
      ],
      nutrition: { calories: 460, protein: 32, carbs: 30, fat: 24 },
    },
    {
      title: 'Baked Stuffed Bell Peppers with Turkey, Rice, and Tomato Sauce',
      description: 'Vibrant bell peppers filled with seasoned ground turkey, fluffy rice, and vegetables baked in a savory tomato sauce until bubbly.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 35,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 large bell peppers (any color), tops cut and seeded',
        '1 pound ground turkey',
        '1 cup cooked white rice',
        '1 can (14 oz) diced tomatoes, drained',
        '1 can (8 oz) tomato sauce',
        '1 small onion, finely diced',
        '2 cloves garlic, minced',
        '1 teaspoon cumin',
        '1 teaspoon smoked paprika',
        '1/2 cup shredded Monterey Jack cheese',
        '1 tablespoon olive oil',
        'Salt and black pepper to taste',
        'Fresh cilantro for garnish',
      ],
      instructions: [
        'Preheat oven to 375°F (190°C). Place hollowed-out peppers upright in a deep baking dish.',
        'Heat olive oil in a large skillet over medium-high heat. Sauté onion for 3 minutes until softened, then add garlic and cook 30 seconds.',
        'Add ground turkey and cook, breaking it up with a spoon, until no longer pink, about 5-6 minutes. Drain any excess fat.',
        'Stir in cooked rice, diced tomatoes, cumin, smoked paprika, salt, and pepper. Cook for 2 minutes until well combined.',
        'Spoon the turkey-rice mixture into each pepper, packing them generously. Pour tomato sauce over and around the peppers.',
        'Cover with foil and bake for 25 minutes. Remove foil, top each pepper with shredded cheese, and bake uncovered for 10 more minutes until cheese is melted and bubbly.',
        'Let rest 5 minutes, garnish with fresh cilantro, and serve.',
      ],
      nutrition: { calories: 380, protein: 30, carbs: 32, fat: 14 },
    },
    {
      title: 'Slow-Cooker Thai Green Curry with Chicken and Rice Noodles',
      description: 'Creamy coconut green curry with tender chicken, bamboo shoots, and Thai basil ladled over silky rice noodles. Set it and forget it.',
      timeMinutes: 250,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 235,
      servings: 6,
      cuisine: 'Thai',
      ingredients: [
        '2 pounds boneless, skinless chicken thighs',
        '8 ounces rice noodles (pad Thai style)',
        '1 can (14 oz) full-fat coconut milk',
        '3 tablespoons Thai green curry paste (check label for GF)',
        '1 cup canned bamboo shoots, drained',
        '1 red bell pepper, sliced',
        '1 small zucchini, sliced into half-moons',
        '2 tablespoons fish sauce',
        '1 tablespoon brown sugar',
        '1 cup chicken broth',
        'Juice of 1 lime',
        'Fresh Thai basil leaves for serving',
        'Sliced red chili for garnish',
      ],
      instructions: [
        'Place chicken thighs in the bottom of the slow cooker. Spread green curry paste over the chicken.',
        'Pour in coconut milk and chicken broth. Add fish sauce and brown sugar, stirring gently to combine.',
        'Add bamboo shoots, sliced bell pepper, and zucchini around the chicken.',
        'Cover and cook on low for 3.5-4 hours or on high for 2 hours until chicken is fork-tender.',
        'Shred the chicken with two forks directly in the slow cooker and stir everything together.',
        'Cook rice noodles according to package directions, drain, and divide among bowls.',
        'Ladle the green curry over the noodles, squeeze lime juice on top, and garnish with Thai basil and sliced red chili.',
      ],
      nutrition: { calories: 480, protein: 34, carbs: 44, fat: 18 },
    },
  ],

  'dairy-free-dinners': [
    {
      title: 'Sesame Ginger Beef and Vegetable Stir-Fry',
      description: 'Thinly sliced beef tossed in a bold sesame-ginger sauce with broccoli, snow peas, and mushrooms. A fast weeknight dinner full of umami.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1.5 pounds flank steak, thinly sliced against the grain',
        '3 cups cooked jasmine rice',
        '2 cups broccoli florets',
        '1 cup snow peas, trimmed',
        '1 cup shiitake mushrooms, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '1 tablespoon rice vinegar',
        '1 tablespoon honey',
        '2 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '1 tablespoon cornstarch mixed with 2 tablespoons water',
        '2 tablespoons vegetable oil',
        'Sesame seeds and sliced green onions for garnish',
      ],
      instructions: [
        'Whisk together soy sauce, sesame oil, rice vinegar, honey, garlic, and ginger in a small bowl to make the stir-fry sauce.',
        'Heat 1 tablespoon vegetable oil in a large wok or skillet over high heat until smoking.',
        'Add sliced beef in a single layer and sear without stirring for 1-2 minutes, then stir-fry until just browned, about 3 minutes total. Remove and set aside.',
        'Add remaining vegetable oil to the wok. Stir-fry broccoli, snow peas, and mushrooms for 3-4 minutes until tender-crisp.',
        'Return beef to the wok, pour in the sauce and cornstarch slurry, and toss until everything is coated and the sauce thickens, about 1-2 minutes.',
        'Serve immediately over jasmine rice.',
        'Garnish with sesame seeds and sliced green onions.',
      ],
      nutrition: { calories: 470, protein: 38, carbs: 44, fat: 16 },
    },
    {
      title: 'One-Pan Jerk Chicken with Coconut Rice and Caramelized Plantains',
      description: 'Bold Jamaican jerk-spiced chicken cooked alongside fragrant coconut rice and sweet caramelized plantains for a vibrant Caribbean feast.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Caribbean',
      ingredients: [
        '4 boneless, skinless chicken thighs',
        '1.5 cups long-grain white rice',
        '1 can (14 oz) full-fat coconut milk',
        '1 cup water',
        '2 ripe plantains, sliced on a diagonal',
        '2 tablespoons jerk seasoning paste',
        '1 tablespoon lime juice',
        '2 tablespoons coconut oil',
        '3 green onions, sliced',
        '2 cloves garlic, minced',
        '1 sprig fresh thyme',
        'Salt and black pepper to taste',
        'Lime wedges for serving',
      ],
      instructions: [
        'Rub chicken thighs with jerk seasoning paste and lime juice, making sure to coat evenly. Season with salt and pepper.',
        'Heat 1 tablespoon coconut oil in a large deep skillet or Dutch oven over medium-high heat. Sear chicken thighs for 3-4 minutes per side until deeply browned. Remove and set aside.',
        'In the same pan, sauté garlic for 30 seconds. Add rice and stir for 1 minute. Pour in coconut milk, water, and thyme sprig. Bring to a boil.',
        'Nestle seared chicken thighs into the rice. Reduce heat to low, cover tightly, and cook for 20 minutes until rice is tender and chicken is cooked through.',
        'While rice cooks, heat remaining coconut oil in a separate skillet over medium heat. Fry plantain slices for 2-3 minutes per side until golden and caramelized.',
        'Remove thyme sprig and fluff rice with a fork. Arrange caramelized plantains on top.',
        'Garnish with sliced green onions and serve with lime wedges.',
      ],
      nutrition: { calories: 560, protein: 32, carbs: 64, fat: 20 },
    },
    {
      title: 'Mediterranean Grilled Chicken Power Bowl with Tahini Dressing',
      description: 'Herby grilled chicken over quinoa with roasted chickpeas, cucumber, cherry tomatoes, and Kalamata olives drizzled with creamy tahini.',
      timeMinutes: 35,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 large chicken breasts, butterflied',
        '2 cups cooked quinoa',
        '1 can (15 oz) chickpeas, drained, rinsed, and patted dry',
        '1 cup cherry tomatoes, halved',
        '1 large cucumber, diced',
        '1/3 cup Kalamata olives, halved',
        '2 tablespoons olive oil',
        '1 teaspoon dried oregano',
        '1 teaspoon smoked paprika',
        '3 tablespoons tahini',
        '2 tablespoons lemon juice',
        '1 tablespoon warm water',
        '1 clove garlic, minced',
        'Salt and black pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Season chicken breasts with 1 tablespoon olive oil, oregano, smoked paprika, salt, and pepper. Grill or pan-sear over medium-high heat for 6-7 minutes per side until cooked through. Let rest, then slice.',
        'Toss chickpeas with remaining olive oil and a pinch of salt. Spread on a sheet pan and roast at 400°F (200°C) for 15-20 minutes until crispy.',
        'Make the tahini dressing by whisking tahini, lemon juice, warm water, garlic, and a pinch of salt until smooth and pourable.',
        'Divide quinoa among 4 bowls.',
        'Arrange sliced chicken, roasted chickpeas, cherry tomatoes, cucumber, and olives on top of the quinoa.',
        'Drizzle generously with tahini dressing.',
        'Garnish with fresh parsley and serve.',
      ],
      nutrition: { calories: 480, protein: 38, carbs: 40, fat: 18 },
    },
    {
      title: 'Cashew Cream Fettuccine with Roasted Mushrooms and Spinach',
      description: 'Silky cashew cream sauce tossed with fettuccine, earthy roasted mushrooms, and wilted spinach. A rich and satisfying dairy-free pasta.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '12 ounces fettuccine pasta',
        '1 cup raw cashews, soaked in boiling water for 15 minutes, then drained',
        '3/4 cup vegetable broth',
        '2 tablespoons nutritional yeast',
        '2 tablespoons lemon juice',
        '8 ounces cremini mushrooms, quartered',
        '3 cups fresh baby spinach',
        '4 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1/4 teaspoon nutmeg',
        'Salt and black pepper to taste',
        'Fresh basil and crushed red pepper for garnish',
      ],
      instructions: [
        'Cook fettuccine according to package directions until al dente. Reserve 1/2 cup pasta water before draining.',
        'Blend soaked cashews, vegetable broth, nutritional yeast, lemon juice, nutmeg, and a pinch of salt in a high-speed blender until completely smooth and creamy.',
        'Heat olive oil in a large skillet over medium-high heat. Add mushrooms and cook without stirring for 3-4 minutes until golden, then stir and cook 2 more minutes. Season with salt and pepper.',
        'Add garlic to the mushrooms and sauté for 30 seconds until fragrant.',
        'Reduce heat to medium-low. Pour the cashew cream sauce into the skillet and stir until heated through.',
        'Add drained fettuccine and baby spinach to the skillet, tossing until the spinach wilts and pasta is evenly coated. Add reserved pasta water a splash at a time to reach desired consistency.',
        'Serve garnished with fresh basil and a pinch of crushed red pepper.',
      ],
      nutrition: { calories: 490, protein: 18, carbs: 58, fat: 22 },
    },
    {
      title: 'Sheet-Pan Harissa Salmon with Roasted Cauliflower and Sweet Potatoes',
      description: 'Spiced harissa-glazed salmon fillets roasted alongside caramelized cauliflower and sweet potato wedges on one pan for easy cleanup.',
      timeMinutes: 35,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'North African',
      ingredients: [
        '4 salmon fillets (6 oz each)',
        '2 cups cauliflower florets',
        '2 medium sweet potatoes, cut into 1/2-inch wedges',
        '2 tablespoons harissa paste',
        '1 tablespoon maple syrup',
        '3 tablespoons olive oil',
        '1 teaspoon cumin',
        '1/2 teaspoon cinnamon',
        'Salt and black pepper to taste',
        '2 tablespoons fresh cilantro, chopped',
        '2 tablespoons pomegranate seeds for garnish',
        'Lemon wedges for serving',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment paper.',
        'Toss cauliflower and sweet potato wedges with 2 tablespoons olive oil, cumin, cinnamon, salt, and pepper. Spread in a single layer on the sheet pan and roast for 10 minutes.',
        'Mix harissa paste, maple syrup, remaining olive oil, and a pinch of salt. Brush generously over the salmon fillets.',
        'After the vegetables have roasted for 10 minutes, push them to the sides and place salmon fillets in the center of the pan.',
        'Return to the oven and roast for 12-15 minutes until salmon flakes easily with a fork and vegetables are caramelized.',
        'Remove from oven and let rest for 2 minutes.',
        'Garnish with fresh cilantro and pomegranate seeds, and serve with lemon wedges.',
      ],
      nutrition: { calories: 440, protein: 36, carbs: 30, fat: 20 },
    },
    {
      title: 'Thai Coconut Lemongrass Soup with Shrimp',
      description: 'Aromatic and comforting Thai soup with plump shrimp, mushrooms, and cherry tomatoes in a fragrant coconut lemongrass broth. Warming and bright.',
      timeMinutes: 30,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Thai',
      ingredients: [
        '1 pound large shrimp, peeled and deveined',
        '1 can (14 oz) full-fat coconut milk',
        '3 cups chicken broth',
        '2 stalks lemongrass, cut into 2-inch pieces and smashed',
        '3 slices fresh galangal or ginger',
        '4 kaffir lime leaves (or zest of 1 lime)',
        '8 ounces oyster mushrooms, torn into pieces',
        '1 cup cherry tomatoes, halved',
        '2 tablespoons fish sauce',
        '1 tablespoon lime juice',
        '1 teaspoon chili paste (sambal oelek)',
        'Fresh cilantro for garnish',
        'Sliced red chili for garnish',
      ],
      instructions: [
        'Bring chicken broth to a boil in a large pot. Add lemongrass, galangal, and kaffir lime leaves. Simmer for 5 minutes to infuse the aromatics.',
        'Pour in coconut milk and stir until combined. Return to a gentle simmer.',
        'Add mushrooms and cherry tomatoes, cooking for 3-4 minutes until mushrooms are tender.',
        'Add shrimp to the soup and cook for 3-4 minutes until they turn pink and curl.',
        'Stir in fish sauce, lime juice, and chili paste. Taste and adjust seasoning as needed.',
        'Remove lemongrass pieces, galangal slices, and lime leaves before serving.',
        'Ladle into bowls and garnish with fresh cilantro and sliced red chili.',
      ],
      nutrition: { calories: 320, protein: 28, carbs: 12, fat: 18 },
    },
    {
      title: 'Baked Lemon-Herb Chicken Thighs with Roasted Root Vegetables',
      description: 'Golden-crisp chicken thighs seasoned with lemon, rosemary, and garlic baked over a bed of carrots, parsnips, and red onion.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 40,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '6 bone-in, skin-on chicken thighs',
        '3 large carrots, peeled and cut into chunks',
        '2 parsnips, peeled and cut into chunks',
        '1 large red onion, cut into wedges',
        '4 cloves garlic, smashed',
        '3 tablespoons olive oil',
        '2 tablespoons lemon juice',
        '1 tablespoon lemon zest',
        '2 sprigs fresh rosemary',
        '4 sprigs fresh thyme',
        '1 teaspoon smoked paprika',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C).',
        'Toss carrots, parsnips, and red onion wedges with 1 tablespoon olive oil, salt, and pepper. Spread in a large roasting pan or cast-iron skillet.',
        'Season chicken thighs generously with smoked paprika, lemon zest, salt, and pepper. Drizzle with remaining olive oil and lemon juice.',
        'Nestle chicken thighs skin-side up over the root vegetables. Tuck rosemary sprigs, thyme sprigs, and smashed garlic between the chicken pieces.',
        'Roast for 35-40 minutes until chicken skin is deeply golden and crispy and the internal temperature reaches 175°F.',
        'Let rest in the pan for 5 minutes so the juices redistribute.',
        'Serve chicken over the roasted root vegetables, spooning any pan juices on top.',
      ],
      nutrition: { calories: 490, protein: 34, carbs: 26, fat: 28 },
    },
    {
      title: 'Slow-Cooker Chipotle Pulled Pork Tacos with Avocado-Lime Slaw',
      description: 'Smoky chipotle-spiced pulled pork slow-cooked until fork-tender, piled into warm tortillas, and topped with a crunchy dairy-free avocado-lime slaw.',
      timeMinutes: 310,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 290,
      servings: 8,
      cuisine: 'Mexican',
      ingredients: [
        '3 pounds boneless pork shoulder, trimmed of excess fat',
        '2 chipotle peppers in adobo sauce, minced',
        '2 tablespoons adobo sauce (from the can)',
        '1 tablespoon cumin',
        '1 tablespoon smoked paprika',
        '1 teaspoon garlic powder',
        '1/2 cup orange juice',
        '2 tablespoons apple cider vinegar',
        '16 corn or flour tortillas',
        '2 cups shredded purple cabbage',
        '1 avocado, diced',
        '1/4 cup fresh cilantro, chopped',
        '2 tablespoons lime juice',
        '2 tablespoons olive oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Mix cumin, smoked paprika, garlic powder, salt, and pepper. Rub the spice mixture all over the pork shoulder.',
        'Place the seasoned pork in the slow cooker. Add minced chipotle peppers, adobo sauce, orange juice, and apple cider vinegar.',
        'Cover and cook on low for 8-10 hours or on high for 4-5 hours until the pork is fall-apart tender.',
        'Remove pork from the slow cooker and shred with two forks. Return to the cooking liquid and toss to coat.',
        'Make the slaw: toss shredded cabbage, diced avocado, cilantro, lime juice, olive oil, salt, and pepper in a bowl.',
        'Warm tortillas in a dry skillet or microwave.',
        'Assemble tacos with pulled pork, avocado-lime slaw, and extra cilantro. Serve with lime wedges.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 34, fat: 18 },
    },
  ],
}

export const dietFaqs3: Record<string, FAQ[]> = {
  'gluten-free-dinners': [
    {
      question: 'What are some easy gluten-free dinner ideas for busy weeknights?',
      answer: 'Stir-fries with tamari and rice, sheet-pan fajitas with corn tortillas, and one-pan chicken with potatoes are all naturally gluten-free and ready in under 30 minutes. The key is to focus on proteins, vegetables, and naturally GF grains like rice, quinoa, and corn.',
    },
    {
      question: 'Is soy sauce gluten-free?',
      answer: 'Traditional soy sauce contains wheat and is not gluten-free. However, tamari is a Japanese soy sauce that is typically made without wheat—just check the label to confirm it is certified gluten-free. Coconut aminos are another excellent gluten-free alternative with a slightly sweeter flavor.',
    },
    {
      question: 'What are the best gluten-free substitutes for common dinner ingredients?',
      answer: 'Use tamari instead of soy sauce, rice noodles or GF pasta instead of regular pasta, cornstarch instead of flour for thickening, and corn tortillas instead of flour tortillas. For breading, crushed rice cereal or GF breadcrumbs work perfectly.',
    },
    {
      question: 'What are some gluten-free dinners the whole family will enjoy?',
      answer: 'Stuffed bell peppers with rice, taco nights with corn tortillas, teriyaki chicken bowls, and baked salmon with roasted potatoes are all crowd-pleasers that happen to be gluten-free. Most people won\'t even notice the difference when the recipe is naturally gluten-free rather than relying on substitutions.',
    },
    {
      question: 'Are these recipes safe for someone with celiac disease?',
      answer: 'The recipes use inherently gluten-free ingredients, but cross-contamination is a concern for people with celiac disease. Always verify that packaged ingredients like tamari, curry paste, and broth are certified gluten-free, and use dedicated cookware if needed to avoid cross-contact.',
    },
  ],

  'dairy-free-dinners': [
    {
      question: 'What are easy dairy-free dinner ideas that still taste great?',
      answer: 'Stir-fries with sesame-ginger sauce, coconut curry dishes, Mediterranean bowls with tahini dressing, and sheet-pan roasted proteins with vegetables are all naturally dairy-free and packed with flavor. Many Asian, Caribbean, and Middle Eastern cuisines are inherently dairy-free, making them a great starting point.',
    },
    {
      question: 'What are the best dairy-free substitutes for cooking?',
      answer: 'Use coconut cream in place of heavy cream, cashew cream or blended silken tofu for creamy sauces, olive oil or coconut oil instead of butter, and nutritional yeast to add a savory, cheese-like flavor. For baking, oat milk and coconut milk are reliable substitutes for regular milk.',
    },
    {
      question: 'How do I make creamy sauces without dairy?',
      answer: 'Soaked and blended raw cashews make an incredibly silky sauce base that rivals heavy cream. Coconut cream works well in curries and soups, while tahini blended with lemon juice and water creates a rich Mediterranean-style dressing. Adding nutritional yeast gives any sauce a savory, umami-rich depth.',
    },
    {
      question: 'What are quick dairy-free meals I can make on a weeknight?',
      answer: 'Stir-fries come together in 20-25 minutes, sheet-pan dinners need minimal hands-on time, and coconut curry soup can be ready in 30 minutes. Keeping coconut milk, tahini, and cashews stocked in your pantry makes it easy to whip up dairy-free meals any night of the week.',
    },
    {
      question: 'Is coconut milk a good replacement for dairy in savory recipes?',
      answer: 'Full-fat coconut milk is one of the best dairy replacements for savory cooking, especially in curries, soups, and rice dishes. Its natural richness mimics the creaminess of heavy cream without an overpowering coconut flavor, particularly when combined with bold spices and aromatics.',
    },
  ],
}
