import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const pantryRecipes: Record<string, RecipeIdea[]> = {
  'chicken-broth': [
    {
      title: 'Classic Chicken Noodle Soup',
      description: 'A comforting bowl of tender chicken, egg noodles, carrots, and celery in a rich, homemade broth. The ultimate feel-good dinner.',
      timeMinutes: 45,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '6 cups chicken broth',
        '2 boneless, skinless chicken breasts (about 1 lb)',
        '8 oz egg noodles',
        '3 medium carrots, sliced',
        '3 celery stalks, sliced',
        '1 medium onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '2 bay leaves',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Heat olive oil in a large Dutch oven over medium heat. Add onion, carrots, and celery. Sauté for 5-6 minutes until vegetables soften. Add garlic and cook 1 minute.',
        'Pour in chicken broth and add bay leaves, thyme, salt, and pepper. Bring to a boil, then reduce heat to simmer.',
        'Add chicken breasts to the pot. Simmer uncovered for 15-20 minutes until chicken is cooked through (165°F).',
        'Remove chicken and shred with two forks. Return shredded chicken to the soup.',
        'Add egg noodles and cook 8-10 minutes until tender, stirring occasionally.',
        'Discard bay leaves. Taste and adjust seasoning. Ladle into bowls and garnish with fresh parsley.',
      ],
      nutrition: { calories: 280, protein: 24, carbs: 32, fat: 7 },
    },
    {
      title: 'Creamy Chicken Rice Pilaf',
      description: 'Fluffy rice cooked in chicken broth with herbs and a touch of butter. Simple, fragrant, and satisfying as a side or light main.',
      timeMinutes: 35,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cups long-grain white rice',
        '4 cups chicken broth',
        '2 tablespoons butter',
        '1 small onion, finely diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried parsley',
        '1/2 teaspoon dried thyme',
        '1/4 teaspoon salt',
        '1/4 teaspoon black pepper',
        '2 tablespoons fresh parsley, chopped',
      ],
      instructions: [
        'Melt butter in a medium saucepan over medium heat. Add diced onion and sauté for 3-4 minutes until translucent.',
        'Add garlic, dried parsley, thyme, salt, and pepper. Stir for 30 seconds until fragrant.',
        'Add rice and stir to coat in butter for 1 minute.',
        'Pour in chicken broth and bring to a boil. Reduce heat to low, cover, and simmer for 18-20 minutes until liquid is absorbed and rice is tender.',
        'Remove from heat and let stand covered for 5 minutes. Fluff with a fork and stir in fresh parsley before serving.',
      ],
      nutrition: { calories: 320, protein: 8, carbs: 58, fat: 7 },
    },
    {
      title: 'Quick Ramen with Chicken Broth',
      description: 'Upgrade instant ramen with a rich chicken broth base, soft egg, greens, and scallions. Restaurant-style noodle soup at home.',
      timeMinutes: 20,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 2,
      cuisine: 'Asian',
      ingredients: [
        '4 cups chicken broth',
        '2 packets instant ramen noodles (discard seasoning packets)',
        '2 soft-boiled eggs, halved',
        '2 cups baby spinach',
        '2 green onions, sliced',
        '1 tablespoon soy sauce',
        '1 teaspoon sesame oil',
        '1 teaspoon sriracha (optional)',
        'Sesame seeds and nori for garnish',
      ],
      instructions: [
        'Bring chicken broth to a boil in a medium pot. Add soy sauce and sesame oil. Reduce to a simmer.',
        'Add ramen noodles and cook according to package directions until just tender (about 3 minutes).',
        'Stir in baby spinach until wilted, about 30 seconds.',
        'Divide noodles and broth between two bowls. Top each with a soft-boiled egg half.',
        'Garnish with green onions, sesame seeds, nori, and sriracha if desired. Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 16, carbs: 52, fat: 12 },
    },
    {
      title: 'French Onion Soup',
      description: 'Caramelized onions simmered in chicken broth, topped with crusty bread and melted Gruyère. Cozy bistro-style comfort in a bowl.',
      timeMinutes: 60,
      method: 'soup',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 45,
      servings: 4,
      cuisine: 'French',
      ingredients: [
        '6 cups chicken broth',
        '4 large yellow onions, thinly sliced',
        '3 tablespoons butter',
        '1 tablespoon olive oil',
        '2 cloves garlic, minced',
        '1 teaspoon fresh thyme leaves',
        '1/2 cup dry white wine',
        '1 bay leaf',
        '4 slices crusty baguette, toasted',
        '2 cups shredded Gruyère cheese',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Melt butter and olive oil in a large Dutch oven over medium-low heat. Add onions and a pinch of salt. Cook 35-40 minutes, stirring occasionally, until deeply caramelized and golden brown.',
        'Add garlic and thyme. Cook 1 minute. Pour in white wine, scraping up any browned bits. Simmer 2-3 minutes.',
        'Add chicken broth and bay leaf. Bring to a boil, then reduce heat and simmer 15 minutes. Season with salt and pepper.',
        'Preheat broiler. Ladle soup into oven-safe bowls. Top each with a baguette slice and generous Gruyère.',
        'Broil 2-3 minutes until cheese is melted and bubbly. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 18, carbs: 28, fat: 26 },
    },
    {
      title: 'Creamy Mushroom Risotto',
      description: 'Creamy Arborio rice with sautéed mushrooms, finished with parmesan. The chicken broth is the secret to depth of flavor.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 35,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '5-6 cups chicken broth, warmed',
        '1.5 cups Arborio rice',
        '8 oz cremini mushrooms, sliced',
        '1 small onion, finely diced',
        '3 cloves garlic, minced',
        '1/2 cup dry white wine',
        '1/2 cup grated parmesan cheese',
        '3 tablespoons butter',
        '2 tablespoons olive oil',
        '2 tablespoons fresh parsley, chopped',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat chicken broth in a saucepan and keep warm over low heat. In a large skillet, heat olive oil over medium-high heat. Add mushrooms and cook 5-6 minutes until golden. Remove and set aside.',
        'Melt 1 tablespoon butter in the same skillet. Add onion and cook 3-4 minutes until soft. Add garlic and rice. Stir 2 minutes until rice is lightly toasted.',
        'Pour in white wine. Stir until absorbed. Add 1 cup warm broth and stir frequently until mostly absorbed. Repeat, adding broth 1 cup at a time, for 20-25 minutes until rice is creamy and al dente.',
        'Stir in cooked mushrooms, remaining butter, and parmesan. Season with salt and pepper. Garnish with parsley. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 12, carbs: 58, fat: 14 },
    },
    {
      title: 'Slow Cooker Chicken Tortilla Soup',
      description: 'Hearty Mexican-style soup with shredded chicken, black beans, corn, and crispy tortilla strips. Set it and forget it.',
      timeMinutes: 240,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 225,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '6 cups chicken broth',
        '1.5 lbs boneless, skinless chicken thighs',
        '1 can (15 oz) black beans, drained and rinsed',
        '1 can (15 oz) corn, drained',
        '1 can (14.5 oz) diced tomatoes with green chiles',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '2 teaspoons cumin',
        '1 teaspoon chili powder',
        '1/2 teaspoon paprika',
        'Juice of 1 lime',
        '1/4 cup fresh cilantro, chopped',
        '6 corn tortillas, cut into strips and fried or baked until crisp',
        'Shredded cheese, avocado, and sour cream for serving',
      ],
      instructions: [
        'Combine chicken broth, chicken thighs, black beans, corn, diced tomatoes, onion, garlic, cumin, chili powder, and paprika in a slow cooker.',
        'Cover and cook on low for 6-7 hours or high for 3-4 hours until chicken shreds easily.',
        'Remove chicken, shred with two forks, and return to the soup. Stir in lime juice and cilantro.',
        'Ladle soup into bowls. Top with crispy tortilla strips, shredded cheese, avocado, and sour cream. Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 32, carbs: 42, fat: 10 },
    },
    {
      title: 'Easy Egg Drop Soup',
      description: 'Silky ribbons of egg in a delicate ginger-scented chicken broth. Light, quick, and endlessly comforting.',
      timeMinutes: 15,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 4,
      cuisine: 'Chinese',
      ingredients: [
        '4 cups chicken broth',
        '3 large eggs, beaten',
        '2 green onions, thinly sliced',
        '1 inch fresh ginger, minced',
        '1 tablespoon cornstarch mixed with 2 tablespoons water',
        '1 teaspoon soy sauce',
        '1/2 teaspoon sesame oil',
        'Salt and white pepper to taste',
      ],
      instructions: [
        'Bring chicken broth to a boil in a medium pot. Add ginger and soy sauce. Reduce to a gentle simmer.',
        'Stir in cornstarch slurry to thicken slightly. Cook 1 minute.',
        'Slowly pour beaten eggs into the soup in a thin stream while stirring gently with a fork to create silky ribbons.',
        'Remove from heat. Add sesame oil, salt, and white pepper. Ladle into bowls and garnish with green onions. Serve immediately.',
      ],
      nutrition: { calories: 95, protein: 8, carbs: 3, fat: 6 },
    },
    {
      title: 'Braised Chicken Thighs with Vegetables',
      description: 'Tender chicken thighs braised in chicken broth with carrots, potatoes, and herbs. A one-pot Sunday supper.',
      timeMinutes: 55,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 40,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cups chicken broth',
        '4 bone-in, skin-on chicken thighs',
        '3 medium carrots, cut into chunks',
        '1.5 lbs baby potatoes, halved',
        '1 medium onion, cut into wedges',
        '4 cloves garlic, smashed',
        '2 sprigs fresh rosemary',
        '2 sprigs fresh thyme',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Season chicken thighs with salt and pepper. Heat olive oil in a large oven-safe Dutch oven over medium-high heat. Sear chicken skin-side down for 6-7 minutes until golden. Flip and sear 2 minutes. Remove and set aside.',
        'Add onion, carrots, potatoes, and garlic to the pot. Sauté 3-4 minutes. Nestle chicken thighs back in, skin-side up. Add rosemary and thyme.',
        'Pour chicken broth over everything. Bring to a simmer, then cover and transfer to the oven.',
        'Bake 35-40 minutes until chicken reaches 165°F and vegetables are tender. Remove herbs. Serve with pan juices.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 38, fat: 16 },
    },
  ],

  'black-beans': [
    {
      title: 'Black Bean Tacos with Lime Crema',
      description: 'Spiced black beans in warm tortillas with crunchy cabbage, avocado, and zesty lime crema. A fast, satisfying plant-based dinner.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz each) black beans, drained and rinsed',
        '8 small corn or flour tortillas',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 tablespoon chili powder',
        '1 teaspoon cumin',
        '1/2 teaspoon smoked paprika',
        '2 tablespoons olive oil',
        '1/2 cup sour cream',
        '2 tablespoons lime juice',
        '2 cups shredded cabbage',
        '1 avocado, sliced',
        'Fresh cilantro and lime wedges for serving',
      ],
      instructions: [
        'Heat olive oil in a large skillet over medium heat. Sauté onion 3 minutes until soft. Add garlic, chili powder, cumin, and smoked paprika. Cook 1 minute.',
        'Add black beans and 1/4 cup water. Mash half the beans with a fork for texture. Simmer 5-7 minutes until thickened. Season with salt.',
        'Mix sour cream and lime juice for the crema. Warm tortillas over a gas flame or in a dry skillet.',
        'Fill tortillas with black bean mixture, cabbage, avocado slices, and a drizzle of crema. Garnish with cilantro and lime wedges.',
      ],
      nutrition: { calories: 410, protein: 16, carbs: 52, fat: 16 },
    },
    {
      title: 'Black Bean Stuffed Sweet Potatoes',
      description: 'Tender baked sweet potatoes loaded with seasoned black beans, melted cheese, avocado, and a drizzle of lime crema. A hearty plant-forward meal.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 40,
      servings: 4,
      cuisine: 'Southwestern',
      ingredients: [
        '4 medium sweet potatoes',
        '2 cans (15 oz each) black beans, drained and rinsed',
        '1 tablespoon chili powder',
        '1 teaspoon cumin',
        '1/2 teaspoon smoked paprika',
        '1/4 teaspoon cayenne pepper',
        '2 tablespoons olive oil',
        '1 cup shredded Monterey Jack cheese',
        '1 avocado, diced',
        '1/4 cup sour cream',
        '2 tablespoons lime juice',
        '2 green onions, sliced',
        'Fresh cilantro for garnish',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. Prick sweet potatoes with a fork and place on a lined baking sheet. Bake 40-45 minutes until tender when pierced.',
        'While potatoes bake, heat olive oil in a skillet over medium heat. Add black beans, chili powder, cumin, smoked paprika, cayenne, salt, and 2 tablespoons water. Simmer 5-7 minutes until thickened.',
        'Mix sour cream and lime juice in a small bowl for the crema.',
        'Slice sweet potatoes open lengthwise and fluff the flesh with a fork. Season lightly with salt.',
        'Fill each potato generously with seasoned black beans. Top with cheese and return to oven 3-4 minutes until cheese melts.',
        'Top with diced avocado, green onions, lime crema, and cilantro. Serve immediately.',
      ],
      nutrition: { calories: 480, protein: 18, carbs: 62, fat: 18 },
    },
    {
      title: 'Black Bean Soup',
      description: 'Thick, hearty black bean soup with smoky spices, lime, and fresh cilantro. Top with sour cream and avocado for the full experience.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '3 cans (15 oz each) black beans, drained and rinsed',
        '4 cups vegetable broth',
        '1 medium onion, diced',
        '3 cloves garlic, minced',
        '1 jalapeño, seeded and minced',
        '1 teaspoon cumin',
        '1/2 teaspoon smoked paprika',
        '1/4 teaspoon cayenne',
        '2 tablespoons olive oil',
        'Juice of 2 limes',
        '1/4 cup fresh cilantro, chopped',
        'Sour cream, avocado, and lime wedges for serving',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium heat. Sauté onion, garlic, and jalapeño 4-5 minutes until softened.',
        'Add cumin, smoked paprika, and cayenne. Stir 30 seconds. Add black beans and vegetable broth. Bring to a boil.',
        'Reduce heat and simmer 15 minutes. Use an immersion blender to purée until smooth (or blend in batches). Add lime juice and cilantro.',
        'Season with salt and pepper. Ladle into bowls. Top with sour cream, diced avocado, and lime wedges. Serve immediately.',
      ],
      nutrition: { calories: 240, protein: 14, carbs: 42, fat: 4 },
    },
    {
      title: 'Black Bean Burgers',
      description: 'Hearty veggie burgers with mashed black beans, oats, and Southwest spices. Crispy on the outside, tender on the inside.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (15 oz each) black beans, drained and rinsed',
        '1/2 cup rolled oats',
        '1/2 cup breadcrumbs',
        '1 small onion, finely diced',
        '2 cloves garlic, minced',
        '1 tablespoon chili powder',
        '1 teaspoon cumin',
        '1 egg',
        '2 tablespoons olive oil',
        '4 burger buns',
        'Lettuce, tomato, avocado, and your favorite toppings',
      ],
      instructions: [
        'In a large bowl, mash black beans with a fork until mostly smooth with some chunks. Add oats, breadcrumbs, onion, garlic, chili powder, cumin, egg, salt, and pepper. Mix until combined.',
        'Form into 4 patties. If mixture is too wet, add more breadcrumbs. Refrigerate 10 minutes to firm up.',
        'Heat olive oil in a large skillet over medium heat. Cook patties 4-5 minutes per side until golden and heated through.',
        'Toast buns. Assemble burgers with lettuce, tomato, avocado, and your favorite toppings. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 18, carbs: 58, fat: 14 },
    },
    {
      title: 'Black Bean Enchiladas',
      description: 'Rolled tortillas filled with spiced black beans and cheese, smothered in red sauce and baked until bubbly. Comfort food at its best.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 25,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz each) black beans, drained and rinsed',
        '12 corn tortillas',
        '2 cups enchilada sauce',
        '2 cups shredded Mexican cheese blend',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon cumin',
        '2 tablespoons olive oil',
        'Sour cream and chopped cilantro for serving',
      ],
      instructions: [
        'Preheat oven to 375°F. Heat olive oil in a skillet. Sauté onion and garlic 3 minutes. Add black beans and cumin. Mash slightly and warm through. Season with salt.',
        'Spread 1/2 cup enchilada sauce in a 9x13-inch baking dish. Warm tortillas in the microwave to prevent cracking.',
        'Fill each tortilla with black bean mixture and a sprinkle of cheese. Roll and place seam-side down in the dish.',
        'Pour remaining sauce over enchiladas. Top with remaining cheese. Bake 25 minutes until bubbly and golden. Serve with sour cream and cilantro.',
      ],
      nutrition: { calories: 380, protein: 18, carbs: 48, fat: 14 },
    },
    {
      title: 'Black Bean Burrito Bowls',
      description: 'Chipotle-style bowl with cilantro lime rice, seasoned black beans, fresh salsa, and all your favorite toppings. Customize and dig in.',
      timeMinutes: 35,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz each) black beans, drained and rinsed',
        '3 cups cooked rice',
        '1/4 cup fresh lime juice',
        '1/2 cup chopped cilantro',
        '1 cup corn (fresh or frozen)',
        '1 cup cherry tomatoes, halved',
        '1 avocado, diced',
        '1/2 red onion, thinly sliced',
        '1 tablespoon chili powder',
        '1 teaspoon cumin',
        '2 tablespoons olive oil',
        'Shredded cheese and salsa for topping',
      ],
      instructions: [
        'Mix cooked rice with 2 tablespoons lime juice and half the cilantro. Set aside. Heat olive oil in a skillet. Add black beans, chili powder, cumin, salt, and 2 tablespoons water. Simmer 5 minutes.',
        'Warm corn in the microwave or a dry skillet. Prepare tomato, avocado, and red onion for topping.',
        'Divide cilantro lime rice among 4 bowls. Top with black beans, corn, tomatoes, avocado, and red onion.',
        'Add shredded cheese, salsa, and extra cilantro. Serve with lime wedges.',
      ],
      nutrition: { calories: 450, protein: 16, carbs: 68, fat: 14 },
    },
    {
      title: 'Black Bean Quesadillas',
      description: 'Crispy quesadillas stuffed with seasoned black beans, melty cheese, and corn. Serve with guacamole and salsa for dipping.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1 can (15 oz) black beans, drained and rinsed',
        '8 flour tortillas',
        '2 cups shredded Monterey Jack or cheddar cheese',
        '1/2 cup corn kernels',
        '1 teaspoon cumin',
        '1/2 teaspoon garlic powder',
        '2 tablespoons olive oil',
        'Guacamole and salsa for serving',
      ],
      instructions: [
        'Mash black beans with a fork. Mix in cumin and garlic powder. Add corn.',
        'Heat 1 tablespoon olive oil in a large skillet over medium heat. Place one tortilla in the pan. Sprinkle with cheese, spoon black bean mixture over half, then more cheese. Fold tortilla in half.',
        'Cook 2-3 minutes per side until golden and cheese is melted. Repeat with remaining tortillas, adding oil as needed.',
        'Cut quesadillas into wedges. Serve with guacamole and salsa. Serve immediately.',
      ],
      nutrition: { calories: 480, protein: 22, carbs: 52, fat: 20 },
    },
    {
      title: 'Black Bean and Corn Salad',
      description: 'Fresh, vibrant salad with black beans, sweet corn, bell pepper, and lime dressing. Perfect as a side or light main.',
      timeMinutes: 20,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 0,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '2 cans (15 oz each) black beans, drained and rinsed',
        '2 cups corn (fresh, canned, or thawed frozen)',
        '1 red bell pepper, diced',
        '1/2 red onion, finely diced',
        '1/4 cup fresh cilantro, chopped',
        '1/4 cup lime juice',
        '2 tablespoons olive oil',
        '1 teaspoon cumin',
        '1/2 teaspoon chili powder',
        'Salt and black pepper to taste',
        'Avocado for garnish',
      ],
      instructions: [
        'In a large bowl, combine black beans, corn, bell pepper, red onion, and cilantro.',
        'In a small bowl, whisk together lime juice, olive oil, cumin, chili powder, salt, and pepper.',
        'Pour dressing over the bean mixture. Toss to coat. Let sit 10 minutes for flavors to meld.',
        'Taste and adjust seasoning. Serve with avocado slices and extra cilantro. Can be made ahead and refrigerated up to 3 days.',
      ],
      nutrition: { calories: 220, protein: 10, carbs: 36, fat: 6 },
    },
  ],

  'chickpeas': [
    {
      title: 'Chana Masala (Chickpea Curry)',
      description: 'Aromatic Indian curry with tender chickpeas in a spiced tomato-onion gravy. Serve over basmati rice or with naan.',
      timeMinutes: 40,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'Indian',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '1 can (14.5 oz) diced tomatoes',
        '1 large onion, diced',
        '4 cloves garlic, minced',
        '1 inch fresh ginger, grated',
        '2 tablespoons garam masala',
        '1 tablespoon cumin',
        '1 teaspoon turmeric',
        '1/2 teaspoon cayenne',
        '2 tablespoons vegetable oil',
        '1/2 cup water',
        '1/4 cup fresh cilantro, chopped',
        'Juice of 1 lemon',
        'Cooked basmati rice for serving',
      ],
      instructions: [
        'Heat oil in a large skillet over medium heat. Sauté onion 6-7 minutes until golden. Add garlic and ginger. Cook 1 minute.',
        'Add garam masala, cumin, turmeric, and cayenne. Stir 30 seconds until fragrant. Add diced tomatoes and their juice. Simmer 5 minutes.',
        'Add chickpeas and water. Bring to a simmer. Cook 10-12 minutes, mashing some chickpeas against the side of the pan to thicken the sauce.',
        'Stir in cilantro and lemon juice. Season with salt. Serve over basmati rice with naan if desired.',
      ],
      nutrition: { calories: 290, protein: 12, carbs: 42, fat: 10 },
    },
    {
      title: 'Crispy Roasted Chickpeas',
      description: 'Crunchy, spiced chickpeas roasted until golden. Snack on them or use as a salad or bowl topper.',
      timeMinutes: 35,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained, rinsed, and patted dry',
        '2 tablespoons olive oil',
        '1 teaspoon paprika',
        '1/2 teaspoon cumin',
        '1/2 teaspoon garlic powder',
        '1/4 teaspoon cayenne',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
      ],
      instructions: [
        'Preheat oven to 400°F. Line a baking sheet with parchment paper. Pat chickpeas very dry with a towel—remove any loose skins for crispier results.',
        'Toss chickpeas with olive oil, paprika, cumin, garlic powder, cayenne, salt, and pepper until evenly coated.',
        'Spread in a single layer on the baking sheet. Roast 25-30 minutes, shaking the pan halfway, until golden and crispy.',
        'Let cool 5 minutes. Serve as a snack or over salads and grain bowls. Best eaten fresh.',
      ],
      nutrition: { calories: 240, protein: 10, carbs: 32, fat: 10 },
    },
    {
      title: 'Mediterranean Chickpea Bowl',
      description: 'Hummus-style chickpeas over greens with cucumber, tomato, feta, and a lemony tahini drizzle. Fresh and satisfying.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 5,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '4 cups mixed greens or chopped romaine',
        '1 cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '1/2 cup kalamata olives, halved',
        '1/2 cup crumbled feta cheese',
        '1/4 cup tahini',
        '3 tablespoons lemon juice',
        '2 tablespoons water',
        '2 cloves garlic, minced',
        '1/4 teaspoon cumin',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Make tahini dressing: whisk tahini, lemon juice, water, garlic, cumin, salt, and pepper until smooth. Add more water if needed.',
        'In a bowl, roughly mash half the chickpeas with a fork. Mix with remaining whole chickpeas and 2 tablespoons dressing.',
        'Divide greens among 4 bowls. Top with chickpea mixture, cucumber, tomatoes, olives, and feta. Drizzle with remaining tahini dressing. Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 16, carbs: 38, fat: 20 },
    },
    {
      title: 'Chickpea Shakshuka',
      description: 'Eggs poached in a spiced tomato and chickpea sauce. Hearty, warming, and perfect for brunch or dinner.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Middle Eastern',
      ingredients: [
        '1 can (15 oz) chickpeas, drained and rinsed',
        '1 can (28 oz) crushed tomatoes',
        '1 bell pepper, diced',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 teaspoon cumin',
        '1 teaspoon paprika',
        '1/4 teaspoon cayenne',
        '4 large eggs',
        '2 tablespoons olive oil',
        'Fresh parsley and crumbled feta for garnish',
        'Crusty bread for serving',
      ],
      instructions: [
        'Heat olive oil in a large skillet over medium heat. Sauté onion and bell pepper 5-6 minutes until soft. Add garlic, cumin, paprika, and cayenne. Cook 1 minute.',
        'Add crushed tomatoes and chickpeas. Simmer 12-15 minutes until thickened. Season with salt and pepper.',
        'Make 4 wells in the sauce. Crack an egg into each. Cover and cook 5-7 minutes until egg whites are set and yolks are still runny.',
        'Garnish with parsley and feta. Serve with crusty bread for dipping. Serve immediately.',
      ],
      nutrition: { calories: 280, protein: 14, carbs: 32, fat: 12 },
    },
    {
      title: 'Moroccan Chickpea Stew',
      description: 'Warm, fragrant stew with chickpeas, sweet potato, apricots, and warming spices. Serve over couscous for a complete meal.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Moroccan',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '2 medium sweet potatoes, peeled and cubed',
        '1 can (14.5 oz) diced tomatoes',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon cumin',
        '1 teaspoon cinnamon',
        '1/2 teaspoon turmeric',
        '1/4 cup dried apricots, chopped',
        '4 cups vegetable broth',
        '2 tablespoons olive oil',
        'Fresh cilantro and lemon wedges for serving',
        'Cooked couscous for serving',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium heat. Sauté onion 4-5 minutes. Add garlic, cumin, cinnamon, and turmeric. Cook 1 minute.',
        'Add sweet potatoes, chickpeas, diced tomatoes, apricots, and vegetable broth. Bring to a boil, then reduce heat and simmer 20-25 minutes until sweet potatoes are tender.',
        'Mash some chickpeas against the side of the pot to thicken. Season with salt and pepper.',
        'Serve over couscous. Garnish with cilantro and lemon wedges. Serve immediately.',
      ],
      nutrition: { calories: 280, protein: 10, carbs: 52, fat: 6 },
    },
    {
      title: 'Creamy Chickpea Pasta',
      description: 'Pasta in a smooth, creamy chickpea sauce with garlic and lemon. Rich, comforting, and surprisingly light.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 can (15 oz) chickpeas, drained and rinsed',
        '12 oz pasta (penne or rigatoni)',
        '4 cloves garlic, minced',
        '1/2 cup chicken or vegetable broth',
        '1/4 cup heavy cream',
        '2 tablespoons lemon juice',
        '2 tablespoons olive oil',
        '1/4 cup grated parmesan cheese',
        'Fresh basil and red pepper flakes for garnish',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Reserve 1/2 cup pasta water before draining. Drain pasta.',
        'While pasta cooks, heat olive oil in a large skillet. Sauté garlic 1 minute. Add chickpeas and broth. Simmer 3 minutes. Remove from heat.',
        'Transfer chickpea mixture to a blender. Add cream, lemon juice, parmesan, salt, and pepper. Blend until smooth.',
        'Return sauce to skillet. Add cooked pasta and toss. Add pasta water if needed for consistency. garnish with basil and red pepper flakes. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 58, fat: 14 },
    },
    {
      title: 'Falafel-Style Chickpea Wraps',
      description: 'Spiced chickpea patties in warm pita with tahini, cucumber, and tomato. Lighter than traditional falafel but just as flavorful.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Middle Eastern',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '4 pita breads',
        '1/2 cup breadcrumbs',
        '1 small onion, grated',
        '3 cloves garlic, minced',
        '2 tablespoons flour',
        '1 tablespoon cumin',
        '1 teaspoon coriander',
        '2 tablespoons olive oil',
        '1/2 cup tahini',
        '3 tablespoons lemon juice',
        '2 tablespoons water',
        '1 cucumber, sliced',
        '1 cup cherry tomatoes, halved',
        'Lettuce and pickled turnips for serving',
      ],
      instructions: [
        'Mash chickpeas in a bowl. Add breadcrumbs, grated onion, garlic, flour, cumin, coriander, salt, and pepper. Mix until combined. Form into 8 small patties.',
        'Heat olive oil in a skillet over medium heat. Cook patties 3-4 minutes per side until golden and crisp. Drain on paper towels.',
        'Whisk tahini, lemon juice, water, and salt for sauce. Warm pitas.',
        'Stuff pitas with lettuce, chickpea patties, cucumber, tomatoes, and tahini sauce. Add pickled turnips if desired. Serve immediately.',
      ],
      nutrition: { calories: 520, protein: 20, carbs: 64, fat: 22 },
    },
    {
      title: 'Lemony Chickpea Salad',
      description: 'Bright, crunchy chickpea salad with cucumber, red onion, herbs, and a tangy lemon dressing. Perfect for meal prep.',
      timeMinutes: 20,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 0,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '2 cans (15 oz each) chickpeas, drained and rinsed',
        '1 cucumber, diced',
        '1/2 red onion, thinly sliced',
        '1/2 cup cherry tomatoes, halved',
        '1/4 cup fresh parsley, chopped',
        '1/4 cup fresh dill, chopped',
        '1/3 cup olive oil',
        '1/4 cup lemon juice',
        '1 clove garlic, minced',
        '1/2 teaspoon Dijon mustard',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'In a large bowl, combine chickpeas, cucumber, red onion, tomatoes, parsley, and dill.',
        'In a small bowl, whisk olive oil, lemon juice, garlic, Dijon, salt, and pepper until emulsified.',
        'Pour dressing over the salad. Toss to coat. Taste and adjust seasoning.',
        'Serve immediately or refrigerate up to 3 days. Flavors deepen over time. Great over greens or with pita.',
      ],
      nutrition: { calories: 320, protein: 10, carbs: 36, fat: 18 },
    },
  ],

  'frozen-broccoli': [
    {
      title: 'Broccoli Cheddar Soup',
      description: 'Creamy, cheesy soup loaded with tender broccoli florets. Cozy comfort in a bowl, perfect with a crusty bread.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '24 oz frozen broccoli florets, thawed',
        '4 cups chicken or vegetable broth',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '2 cups shredded cheddar cheese',
        '1 cup heavy cream',
        '3 tablespoons butter',
        '3 tablespoons all-purpose flour',
        '1/2 teaspoon nutmeg',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Melt butter in a large pot over medium heat. Sauté onion 4-5 minutes until soft. Add garlic and flour. Cook 2 minutes, stirring constantly.',
        'Gradually whisk in broth until smooth. Add broccoli. Bring to a simmer and cook 10-12 minutes until broccoli is very tender.',
        'Use an immersion blender to partially purée (leave some chunks) or mash with a potato masher. Add cream and nutmeg.',
        'Reduce heat to low. Stir in cheddar until melted. Season with salt and pepper. Serve hot with bread. Do not boil after adding cheese.',
      ],
      nutrition: { calories: 320, protein: 14, carbs: 14, fat: 24 },
    },
    {
      title: 'Broccoli Stir-Fry with Garlic Sauce',
      description: 'Crisp-tender broccoli in a savory garlic-ginger sauce. Add your favorite protein or enjoy as a vibrant side.',
      timeMinutes: 20,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '24 oz frozen broccoli florets, thawed and patted dry',
        '4 cloves garlic, minced',
        '1 inch fresh ginger, minced',
        '3 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '1 teaspoon sesame oil',
        '1 teaspoon cornstarch mixed with 2 tablespoons water',
        '2 tablespoons vegetable oil',
        '2 tablespoons water',
        'Sesame seeds and red pepper flakes for garnish',
      ],
      instructions: [
        'Heat vegetable oil in a large wok or skillet over high heat. Add broccoli and stir-fry 4-5 minutes until bright green and tender-crisp. Add 2 tablespoons water and cover 1 minute to steam. Remove broccoli and set aside.',
        'In the same pan, add a bit more oil if needed. Sauté garlic and ginger 30 seconds until fragrant. Do not burn.',
        'Add soy sauce, rice vinegar, and sesame oil. Stir in cornstarch slurry. Cook until sauce thickens, about 1 minute.',
        'Return broccoli to the pan. Toss to coat in sauce. Garnish with sesame seeds and red pepper flakes. Serve immediately over rice if desired.',
      ],
      nutrition: { calories: 120, protein: 6, carbs: 12, fat: 6 },
    },
    {
      title: 'Broccoli Cheddar Casserole',
      description: 'Creamy broccoli and cheese baked with a buttery cracker topping. A classic side that steals the show.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '24 oz frozen broccoli florets, thawed',
        '2 cups shredded cheddar cheese',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 cup sour cream',
        '1/2 cup mayonnaise',
        '1 sleeve Ritz crackers, crushed',
        '4 tablespoons butter, melted',
        '1/2 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 350°F. Grease a 9x13-inch baking dish. Steam or microwave broccoli until tender. Drain well and pat dry.',
        'In a large bowl, combine broccoli, 1.5 cups cheddar, cream of mushroom soup, sour cream, mayonnaise, garlic powder, salt, and pepper.',
        'Spread mixture in the prepared dish. Top with remaining cheese. Mix crushed crackers with melted butter and sprinkle over the top.',
        'Bake 30-35 minutes until bubbly and topping is golden. Let stand 5 minutes before serving.',
      ],
      nutrition: { calories: 420, protein: 14, carbs: 22, fat: 32 },
    },
    {
      title: 'Sheet Pan Italian Sausage and Broccoli',
      description: 'Savory Italian sausage links and broccoli florets roasted on one pan with bell peppers, red onion, and a balsamic drizzle. Easy, hearty, and packed with flavor.',
      timeMinutes: 40,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '20 oz frozen broccoli florets, thawed and patted dry',
        '4 Italian sausage links (about 1 lb), sweet or hot',
        '1 large red bell pepper, cut into strips',
        '1 medium red onion, cut into wedges',
        '3 tablespoons olive oil',
        '4 cloves garlic, minced',
        '1 teaspoon dried oregano',
        '1/2 teaspoon red pepper flakes',
        '2 tablespoons balsamic vinegar',
        'Salt and black pepper to taste',
        'Fresh basil for garnish',
      ],
      instructions: [
        'Preheat oven to 400°F. Line a large baking sheet with parchment paper.',
        'Arrange sausage links on the sheet pan. Roast 10 minutes to start rendering fat.',
        'Toss broccoli, bell pepper, and red onion with olive oil, garlic, oregano, red pepper flakes, salt, and pepper.',
        'Remove pan from oven. Add vegetables around the sausages. Drizzle balsamic vinegar over everything.',
        'Roast 20-22 minutes more until sausages are cooked through (165°F) and vegetables are tender with caramelized edges.',
        'Let rest 5 minutes. Slice sausages if desired. Garnish with fresh basil and serve.',
      ],
      nutrition: { calories: 410, protein: 24, carbs: 16, fat: 28 },
    },
    {
      title: 'Broccoli Fried Rice',
      description: 'Quick fried rice with broccoli, scrambled egg, and soy sauce. A veggie-packed twist on a takeout favorite.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '16 oz frozen broccoli florets, thawed and chopped small',
        '3 cups cooked rice (day-old works best)',
        '2 large eggs, beaten',
        '3 green onions, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '2 cloves garlic, minced',
        '1 teaspoon ginger, grated',
        'Salt to taste',
      ],
      instructions: [
        'Heat 1 tablespoon vegetable oil in a large wok or skillet over high heat. Add broccoli and stir-fry 4-5 minutes until tender-crisp. Remove and set aside.',
        'Add remaining oil. Push rice to the side, pour eggs into the empty space, and scramble until set. Mix with rice.',
        'Add garlic and ginger. Stir-fry 30 seconds. Add broccoli back to the pan. Pour soy sauce and sesame oil over. Toss everything together 2-3 minutes until heated through.',
        'Garnish with green onions. Serve immediately.',
      ],
      nutrition: { calories: 320, protein: 12, carbs: 48, fat: 10 },
    },
    {
      title: 'Broccoli Pasta with Lemon and Parmesan',
      description: 'Tender broccoli and pasta tossed in a light lemon-butter sauce with parmesan. Simple, fresh, and ready in minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '16 oz frozen broccoli florets',
        '12 oz pasta (penne or fusilli)',
        '4 tablespoons butter',
        '3 cloves garlic, minced',
        '1/4 cup pasta water',
        '1/2 cup grated parmesan cheese',
        '2 tablespoons lemon juice',
        'Zest of 1 lemon',
        'Red pepper flakes and fresh basil for garnish',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta according to package directions. Add broccoli to the boiling water during the last 4-5 minutes of cooking. Reserve 1/2 cup pasta water. Drain pasta and broccoli together.',
        'Melt butter in the same pot over medium heat. Add garlic and cook 1 minute. Add pasta, broccoli, lemon juice, zest, and 1/4 cup pasta water. Toss to coat.',
        'Add parmesan and toss again. Add more pasta water if needed for a silky sauce. Season with salt, pepper, and red pepper flakes.',
        'Divide among bowls. Garnish with basil. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 16, carbs: 58, fat: 14 },
    },
    {
      title: 'Broccoli Rice Casserole',
      description: 'Cheesy broccoli and rice baked until golden and bubbly. A crowd-pleasing side for any dinner.',
      timeMinutes: 50,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 35,
      servings: 8,
      cuisine: 'American',
      ingredients: [
        '24 oz frozen broccoli florets, thawed and chopped',
        '2 cups cooked white rice',
        '1 can (10.5 oz) cream of chicken soup',
        '1 cup sour cream',
        '1.5 cups shredded cheddar cheese',
        '1/2 cup milk',
        '1/2 small onion, diced',
        '1/2 cup crushed butter crackers',
        '2 tablespoons melted butter',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 350°F. Grease a 9x13-inch baking dish. In a large bowl, combine broccoli, rice, cream of chicken soup, sour cream, 1 cup cheese, milk, onion, salt, and pepper.',
        'Spread mixture in the prepared dish. Top with remaining cheese. Mix crushed crackers with melted butter and sprinkle over the top.',
        'Bake 35-40 minutes until bubbly and top is golden. Let stand 5 minutes before serving.',
      ],
      nutrition: { calories: 280, protein: 10, carbs: 24, fat: 16 },
    },
    {
      title: 'Broccoli Cheese Baked Potato Bowls',
      description: 'Loaded baked potato style with steamed broccoli and melty cheddar. Comfort food at its simplest.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 40,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '16 oz frozen broccoli florets, steamed',
        '4 large russet potatoes, baked',
        '2 cups shredded cheddar cheese',
        '1/2 cup sour cream',
        '4 slices bacon, cooked and crumbled',
        '2 green onions, sliced',
        '2 tablespoons butter',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F. Bake potatoes 45-60 minutes until tender, or microwave 8-10 minutes. Steam broccoli until tender. Set aside.',
        'Slice each potato open lengthwise. Fluff the flesh with a fork. Top each with 1/2 tablespoon butter, broccoli, and cheese.',
        'Place on a baking sheet. Broil 2-3 minutes until cheese melts. Top with sour cream, bacon, and green onions.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 480, protein: 22, carbs: 52, fat: 22 },
    },
  ],
}

export const pantryFaqs: Record<string, FAQ[]> = {
  'chicken-broth': [
    {
      question: 'What can I make with chicken broth for dinner?',
      answer: 'Chicken broth is incredibly versatile. Use it for classic chicken noodle soup, ramen, French onion soup, risotto, braised chicken, rice pilaf, and slow cooker tortilla soup. It adds depth to any dish where liquid is needed.',
    },
    {
      question: 'Can I substitute vegetable broth for chicken broth?',
      answer: 'Yes, vegetable broth works well in most recipes. The flavor will be slightly different but still delicious. For a closer match, add a pinch of nutritional yeast or a dash of soy sauce to mimic umami.',
    },
    {
      question: 'How long does chicken broth last in the fridge?',
      answer: 'Homemade chicken broth lasts 3-4 days in the refrigerator. Store-bought broth, once opened, lasts about 4-5 days. Freeze in portions for up to 3 months if you need to extend its life.',
    },
    {
      question: 'Is chicken broth the same as chicken stock?',
      answer: 'They are very similar. Stock is typically made from bones and simmered longer for a richer, more gelatinous result. Broth is made with meat and has a lighter flavor. For most recipes, they are interchangeable.',
    },
    {
      question: 'Can I use low-sodium chicken broth?',
      answer: 'Absolutely. Low-sodium broth gives you more control over seasoning. You can always add salt to taste. This is especially helpful if you are watching sodium intake or using other salty ingredients.',
    },
  ],
  'black-beans': [
    {
      question: 'What can I make with black beans for dinner?',
      answer: 'Black beans are incredibly versatile. Try tacos, Cuban black beans and rice, black bean soup, burgers, enchiladas, burrito bowls, quesadillas, or a fresh black bean and corn salad. They work in Mexican, Cuban, and American cuisines.',
    },
    {
      question: 'Do I need to rinse canned black beans?',
      answer: 'Yes, rinsing removes excess sodium and the starchy liquid that can make dishes muddy. For Cuban-style recipes, some cooks use the bean liquid for flavor—check your recipe. For most dishes, drained and rinsed is best.',
    },
    {
      question: 'Are black beans healthy?',
      answer: 'Black beans are an excellent source of plant-based protein, fiber, folate, and iron. They are low in fat and help support heart health and digestion. They make a great base for meatless meals.',
    },
    {
      question: 'Can I use dried black beans instead of canned?',
      answer: 'Yes. One 15-ounce can equals about 1.5 cups cooked beans. Soak dried beans overnight, then simmer 1-2 hours until tender. Dried beans are cheaper and let you control sodium, but require more planning.',
    },
    {
      question: 'How do I make black beans taste better?',
      answer: 'Sauté onion and garlic before adding beans. Season with cumin, chili powder, and a splash of lime juice. A bay leaf or epazote adds depth. For a restaurant touch, finish with a little butter or olive oil.',
    },
  ],
  'chickpeas': [
    {
      question: 'What can I make with chickpeas for dinner?',
      answer: 'Chickpeas are endlessly versatile. Try chana masala (Indian curry), roasted chickpeas, Mediterranean bowls, shakshuka with chickpeas, Moroccan stew, creamy chickpea pasta, falafel-style wraps, or a lemony chickpea salad. They work in Indian, Mediterranean, Middle Eastern, and Italian dishes.',
    },
    {
      question: 'Are chickpeas and garbanzo beans the same thing?',
      answer: 'Yes, they are the same legume. Chickpea is the common name in the US and UK; garbanzo comes from Spanish. Use them interchangeably in any recipe.',
    },
    {
      question: 'How do I make chickpeas less mushy?',
      answer: 'For salads and bowls, use them straight from the can—don\'t overcook. For roasting, pat them very dry and remove loose skins. For curries and stews, add them toward the end so they hold their shape.',
    },
    {
      question: 'Can I use chickpea liquid (aquafaba)?',
      answer: 'Yes! The liquid from canned chickpeas, called aquafaba, can be whipped like egg whites for meringues and used as an egg substitute in baked goods. For savory cooking, you can add a little to thicken sauces.',
    },
    {
      question: 'Do chickpeas need to be cooked from canned?',
      answer: 'Canned chickpeas are already cooked and ready to eat. You can use them cold in salads or heat them in curries, soups, and sautés. Just drain, rinse, and add to your recipe. Cooking further softens them and lets them absorb flavor.',
    },
  ],
  'frozen-broccoli': [
    {
      question: 'What can I make with frozen broccoli for dinner?',
      answer: 'Frozen broccoli is incredibly convenient. Use it for broccoli cheddar soup, stir-fry with garlic sauce, casseroles, sheet pan chicken and broccoli, broccoli fried rice, pasta with broccoli, or a cheesy broccoli rice bake. It works in soups, stir-fries, casseroles, and sheet pan meals.',
    },
    {
      question: 'Do I need to thaw frozen broccoli before cooking?',
      answer: 'It depends on the dish. For stir-fries, thaw and pat dry to avoid steaming. For soups, casseroles, and pasta, you can add it frozen—just add a few extra minutes of cook time. Avoid overcooking or it will become mushy.',
    },
    {
      question: 'Why is my frozen broccoli mushy?',
      answer: 'Overcooking is the main cause. Broccoli cooks quickly—aim for bright green and tender-crisp. For stir-fries, use high heat and don\'t crowd the pan. For casseroles, steam or blanch first, then drain well before mixing in.',
    },
    {
      question: 'Is frozen broccoli as nutritious as fresh?',
      answer: 'Yes. Frozen broccoli is typically flash-frozen at peak ripeness, so it often retains vitamins well. It can be equal or even slightly higher in some nutrients compared to fresh broccoli that has been stored for a while.',
    },
    {
      question: 'Can I roast frozen broccoli?',
      answer: 'Yes, but thaw and pat it very dry first. Excess moisture will steam instead of roast. Toss with oil and seasonings, spread on a sheet pan, and roast at 425°F for 15-20 minutes until edges are golden and crisp.',
    },
  ],
}
