import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const proteinRecipes1: Record<string, RecipeIdea[]> = {
  'chicken-breast': [
    {
      title: 'Chicken Piccata',
      description: 'Tender chicken breasts in a bright lemon-caper butter sauce. This classic Italian-American dish is elegant enough for company and easy enough for weeknights.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '4 chicken breasts, pounded to 1/2-inch thickness',
        '1/3 cup all-purpose flour for dredging',
        '3 tablespoons butter',
        '2 tablespoons olive oil',
        '1/2 cup dry white wine',
        '1/3 cup fresh lemon juice (about 2 lemons)',
        '1/4 cup capers, drained',
        '1/2 cup chicken broth',
        '2 tablespoons fresh parsley, chopped',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season chicken with salt and pepper, then dredge in flour, shaking off excess.',
        'Heat olive oil and 1 tablespoon butter in a large skillet over medium-high heat. Cook chicken 3-4 minutes per side until golden and cooked through (165°F). Transfer to a plate and tent with foil.',
        'Pour white wine into the skillet, scraping up browned bits. Simmer 2 minutes until reduced by half.',
        'Add chicken broth, lemon juice, and capers. Simmer 3-4 minutes until sauce reduces slightly.',
        'Remove from heat and swirl in remaining 2 tablespoons butter until melted and sauce is glossy.',
        'Return chicken to the skillet and spoon sauce over the top. Garnish with fresh parsley.',
        'Serve immediately over angel hair pasta or with crusty bread to soak up the sauce.',
      ],
      nutrition: { calories: 395, protein: 40, carbs: 12, fat: 18 },
    },
    {
      title: 'Pan-Seared Chicken with Mushroom Sauce',
      description: 'Juicy pan-seared chicken breasts topped with a rich, creamy mushroom and garlic sauce. Restaurant-quality dinner in 30 minutes.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 chicken breasts, pounded to even thickness',
        '8 ounces cremini mushrooms, sliced',
        '3 cloves garlic, minced',
        '1/2 cup chicken broth',
        '1/2 cup heavy cream',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
        '1 teaspoon fresh thyme leaves',
        '2 tablespoons fresh parsley, chopped',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season chicken breasts with salt and pepper on both sides. Heat 1 tablespoon olive oil in a large skillet over medium-high heat.',
        'Add chicken and cook for 6-7 minutes per side until golden and cooked through (165°F). Transfer to a plate and tent with foil.',
        'In the same skillet, melt butter over medium heat. Add mushrooms and cook for 5-6 minutes until golden and any liquid has evaporated.',
        'Add garlic and thyme, stirring for 30 seconds until fragrant.',
        'Pour in chicken broth, scraping up any browned bits. Simmer for 2 minutes, then stir in heavy cream.',
        'Return chicken to the skillet and simmer for 2 minutes until sauce thickens slightly.',
        'Garnish with fresh parsley. Serve chicken topped with mushroom sauce.',
      ],
      nutrition: { calories: 380, protein: 42, carbs: 6, fat: 20 },
    },
    {
      title: 'Sheet Pan Lemon Herb Chicken',
      description: 'Golden-roasted chicken breasts with potatoes and green beans on one pan. Minimal cleanup and maximum flavor.',
      timeMinutes: 45,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '4 chicken breasts, pounded to even thickness',
        '1 pound baby potatoes, halved',
        '12 ounces green beans, trimmed',
        '3 tablespoons olive oil',
        '3 tablespoons lemon juice',
        '2 cloves garlic, minced',
        '1 tablespoon fresh rosemary, chopped',
        '1 teaspoon dried oregano',
        '1/2 teaspoon lemon zest',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Line a large sheet pan with parchment paper.',
        'In a bowl, toss potatoes with 1 tablespoon olive oil, salt, and pepper. Spread on one side of the sheet pan and roast for 15 minutes.',
        'Meanwhile, season chicken with 1 tablespoon olive oil, half the lemon juice, garlic, rosemary, oregano, salt, and pepper.',
        'Add chicken to the sheet pan. Toss green beans with remaining olive oil and salt, then add to the pan.',
        'Roast for 18-20 minutes until chicken reaches 165°F and potatoes are tender.',
        'Drizzle with remaining lemon juice and lemon zest. Serve immediately.',
      ],
      nutrition: { calories: 395, protein: 38, carbs: 28, fat: 16 },
    },
    {
      title: 'Creamy Tuscan Chicken',
      description: 'Tender chicken breasts in a luxurious cream sauce with sun-dried tomatoes, spinach, and garlic. Italian-inspired perfection.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '4 chicken breasts, pounded thin',
        '1/2 cup sun-dried tomatoes, chopped',
        '3 cups fresh spinach',
        '1 cup heavy cream',
        '1/2 cup chicken broth',
        '1/2 cup grated Parmesan cheese',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season chicken with salt, pepper, and Italian seasoning. Heat olive oil in a large skillet over medium-high heat.',
        'Cook chicken for 5-6 minutes per side until golden and cooked through (165°F). Remove and set aside.',
        'In the same skillet, add garlic and cook for 30 seconds. Pour in chicken broth and heavy cream, stirring to combine.',
        'Add sun-dried tomatoes and Parmesan. Simmer for 3-4 minutes until sauce thickens.',
        'Stir in spinach until wilted, about 1 minute. Return chicken to the skillet and coat with sauce.',
        'Serve chicken with sauce spooned over the top. Garnish with extra Parmesan if desired.',
      ],
      nutrition: { calories: 465, protein: 44, carbs: 12, fat: 28 },
    },
    {
      title: 'Greek Chicken Salad Bowl',
      description: 'Grilled chicken over a refreshing salad with cucumber, tomatoes, feta, olives, and homemade tzatziki. Light and satisfying.',
      timeMinutes: 30,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '2 large chicken breasts, sliced for grilling',
        '6 cups mixed salad greens',
        '1 large cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '1/2 cup kalamata olives, halved',
        '1/2 cup crumbled feta cheese',
        '1 cup plain Greek yogurt',
        '2 tablespoons lemon juice',
        '1 clove garlic, minced',
        '2 teaspoons fresh dill, chopped',
        '2 tablespoons olive oil',
        '1 teaspoon dried oregano',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Make tzatziki: mix Greek yogurt, half the cucumber, lemon juice, garlic, dill, salt, and pepper. refrigerate until serving.',
        'Season chicken with olive oil, oregano, salt, and pepper. Grill or pan-sear over medium-high heat for 6-7 minutes per side until 165°F. Let rest, then slice.',
        'Divide salad greens among 4 bowls. Top with remaining cucumber, tomatoes, olives, and feta.',
        'Arrange sliced chicken on top of each salad. Add a generous dollop of tzatziki.',
        'Drizzle with olive oil and serve with warm pita if desired.',
      ],
      nutrition: { calories: 385, protein: 42, carbs: 18, fat: 16 },
    },
    {
      title: 'Honey Garlic Chicken Stir-Fry',
      description: 'Tender chicken and crisp vegetables in a sweet-savory honey garlic sauce. Quick weeknight stir-fry that the whole family loves.',
      timeMinutes: 25,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '2 large chicken breasts, sliced into thin strips',
        '2 cups broccoli florets',
        '1 red bell pepper, sliced',
        '1/3 cup soy sauce',
        '1/4 cup honey',
        '3 cloves garlic, minced',
        '1 tablespoon rice vinegar',
        '1 teaspoon cornstarch mixed with 2 tablespoons water',
        '2 tablespoons vegetable oil',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'Whisk together soy sauce, honey, garlic, and rice vinegar in a small bowl.',
        'Heat 1 tablespoon oil in a large wok or skillet over high heat. Add chicken and stir-fry for 5-6 minutes until cooked through. Remove and set aside.',
        'Add remaining oil to the pan. Stir-fry broccoli and bell pepper for 3-4 minutes until tender-crisp.',
        'Pour in the honey garlic sauce and bring to a simmer. Add cornstarch slurry and stir until thickened.',
        'Return chicken to the pan and toss to coat. Serve over rice, garnished with sesame seeds.',
      ],
      nutrition: { calories: 345, protein: 34, carbs: 32, fat: 10 },
    },
    {
      title: 'Baked Stuffed Chicken Breast',
      description: 'Chicken breasts stuffed with cream cheese, spinach, and sun-dried tomatoes, baked until golden. Elegant enough for company.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 30,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '4 chicken breasts, butterflied and pounded thin',
        '4 ounces cream cheese, softened',
        '1 cup fresh spinach, chopped',
        '1/4 cup sun-dried tomatoes, chopped',
        '1/2 cup shredded mozzarella',
        '2 cloves garlic, minced',
        '1 tablespoon olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F (190°C). Mix cream cheese, spinach, sun-dried tomatoes, garlic, and half the mozzarella in a bowl.',
        'Lay each butterflied chicken breast flat. Spread 2-3 tablespoons of the cream cheese mixture on one half, then fold over.',
        'Secure with toothpicks if needed. Season outside with olive oil, Italian seasoning, salt, and pepper.',
        'Place in a baking dish and bake for 28-32 minutes until chicken reaches 165°F.',
        'Sprinkle with remaining mozzarella and bake 2 more minutes until melted. Rest 5 minutes before serving.',
      ],
      nutrition: { calories: 425, protein: 48, carbs: 6, fat: 22 },
    },
    {
      title: 'One-Pan Chicken Fajita Rice',
      description: 'All the flavors of sizzling fajitas in one pan with chicken, bell peppers, onions, and seasoned rice. Easy Mexican-inspired dinner.',
      timeMinutes: 40,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 large chicken breasts, diced',
        '1.5 cups long-grain rice',
        '2.5 cups chicken broth',
        '2 bell peppers (any color), sliced',
        '1 large onion, sliced',
        '2 tablespoons taco seasoning',
        '2 tablespoons lime juice',
        '2 tablespoons olive oil',
        '1/4 cup fresh cilantro, chopped',
        'Salt to taste',
      ],
      instructions: [
        'Season chicken with 1 tablespoon taco seasoning and salt. Heat 1 tablespoon olive oil in a large deep skillet over medium-high heat.',
        'Cook chicken until browned, about 5-6 minutes. Remove and set aside.',
        'Add remaining oil to the skillet. Sauté onion and bell peppers for 4-5 minutes until softened.',
        'Add rice and remaining taco seasoning, stirring for 1 minute. Pour in chicken broth and lime juice.',
        'Return chicken to the pan. Bring to a boil, then reduce heat to low, cover, and simmer for 18-20 minutes until rice is tender.',
        'Fluff with a fork and stir in cilantro. Serve with lime wedges.',
      ],
      nutrition: { calories: 445, protein: 38, carbs: 52, fat: 10 },
    },
  ],

  'ground-beef': [
    {
      title: 'Philly Cheesesteak Skillet',
      description: 'All the flavors of a Philly cheesesteak in a quick one-skillet dinner. Seasoned ground beef with peppers, onions, and melty provolone.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground beef (85/15)',
        '1 large green bell pepper, sliced thin',
        '1 large onion, sliced thin',
        '8 ounces mushrooms, sliced',
        '4 slices provolone cheese',
        '2 tablespoons Worcestershire sauce',
        '1 tablespoon garlic powder',
        '2 tablespoons vegetable oil',
        '4 hoagie rolls (optional, for serving)',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon oil in a large skillet over medium-high heat. Add ground beef, breaking into crumbles. Cook 6-7 minutes until browned. Drain excess grease and transfer to a plate.',
        'Add remaining oil to the skillet. Sauté onion, bell pepper, and mushrooms for 5-6 minutes until softened and slightly caramelized.',
        'Return beef to the skillet. Add Worcestershire sauce, garlic powder, salt, and pepper. Stir to combine and cook 2 minutes.',
        'Lay provolone slices over the top. Cover and cook 1-2 minutes until cheese is fully melted.',
        'Serve straight from the skillet, or spoon into hoagie rolls for a sandwich-style dinner.',
      ],
      nutrition: { calories: 510, protein: 36, carbs: 8, fat: 38 },
    },
    {
      title: 'Hamburger Steak with Onion Gravy',
      description: 'Old-fashioned hamburger steaks smothered in a rich brown onion gravy. Southern comfort food at its best, ready in 30 minutes.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground beef',
        '1/3 cup breadcrumbs',
        '1 large egg, beaten',
        '2 large onions, sliced into rings',
        '2 cups beef broth',
        '2 tablespoons all-purpose flour',
        '2 tablespoons butter',
        '1 tablespoon Worcestershire sauce',
        '1 teaspoon garlic powder',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'In a bowl, combine ground beef, breadcrumbs, egg, garlic powder, salt, and pepper. Mix gently and form into 4 oval patties about 3/4-inch thick.',
        'Heat oil in a large skillet over medium-high heat. Cook patties 4-5 minutes per side until browned and cooked through. Transfer to a plate.',
        'Melt butter in the same skillet. Add sliced onions and cook 6-8 minutes until golden and caramelized, stirring occasionally.',
        'Sprinkle flour over the onions and stir for 1 minute. Gradually whisk in beef broth and Worcestershire sauce.',
        'Bring to a simmer and cook 3-4 minutes until gravy thickens. Season with salt and pepper.',
        'Nestle hamburger steaks back into the gravy. Spoon gravy over the top and simmer 2 minutes to heat through.',
        'Serve over mashed potatoes or egg noodles with the onion gravy spooned generously on top.',
      ],
      nutrition: { calories: 495, protein: 36, carbs: 18, fat: 30 },
    },
    {
      title: 'Beef Empanada Skillet',
      description: 'A deconstructed empanada in skillet form with seasoned ground beef, olives, raisins, and warm spices. Latin-inspired comfort food in one pan.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Latin American',
      ingredients: [
        '1.5 pounds ground beef',
        '1 small onion, diced',
        '1 red bell pepper, diced',
        '3 cloves garlic, minced',
        '1/2 cup pimento-stuffed green olives, halved',
        '1/4 cup golden raisins',
        '1 can (8 oz) tomato sauce',
        '1 teaspoon ground cumin',
        '1 teaspoon smoked paprika',
        '1/2 teaspoon oregano',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet over medium-high heat. Add ground beef and cook 6-7 minutes, breaking into crumbles, until browned. Drain excess grease.',
        'Add onion and bell pepper. Cook 4-5 minutes until softened. Stir in garlic, cumin, smoked paprika, and oregano for 30 seconds.',
        'Pour in tomato sauce and stir to combine. Add olives and raisins.',
        'Reduce heat to medium-low and simmer 8-10 minutes until sauce thickens and flavors meld.',
        'Season with salt and pepper. Taste and adjust spices as desired.',
        'Serve over white rice or with warm crusty bread. Garnish with fresh cilantro if desired.',
      ],
      nutrition: { calories: 485, protein: 34, carbs: 18, fat: 32 },
    },
    {
      title: 'Beef Stroganoff',
      description: 'Tender ground beef in a creamy mushroom sauce over egg noodles. Classic comfort food that never gets old.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground beef',
        '8 ounces egg noodles',
        '8 ounces mushrooms, sliced',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 cup beef broth',
        '1 cup sour cream',
        '2 tablespoons all-purpose flour',
        '2 tablespoons butter',
        '1 tablespoon Worcestershire sauce',
        '1/2 teaspoon paprika',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook egg noodles according to package directions. Drain and set aside.',
        'In a large skillet, brown ground beef over medium-high heat. Drain and set aside.',
        'Melt butter in the same skillet. Sauté mushrooms and onion for 5-6 minutes until softened. Add garlic for 30 seconds.',
        'Sprinkle flour over the vegetables and stir for 1 minute. Gradually whisk in beef broth and Worcestershire sauce.',
        'Simmer for 3-4 minutes until thickened. Reduce heat to low and stir in sour cream and paprika. Return beef to the pan.',
        'Season with salt and pepper. Serve over egg noodles.',
      ],
      nutrition: { calories: 620, protein: 38, carbs: 48, fat: 32 },
    },
    {
      title: 'Taco Pasta Skillet',
      description: 'One-pan ground beef taco pasta with tomatoes, corn, and cheese. Kid-friendly and ready in 30 minutes.',
      timeMinutes: 30,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 25,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '1.5 pounds ground beef',
        '1 pound elbow macaroni',
        '1 can (15 oz) tomato sauce',
        '1 can (15 oz) corn, drained',
        '1 cup shredded cheddar cheese',
        '2 tablespoons taco seasoning',
        '1 small onion, diced',
        '3 cups water',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Brown ground beef with onion in a large deep skillet over medium-high heat. Drain excess grease.',
        'Add taco seasoning, tomato sauce, corn, water, and uncooked pasta. Stir to combine.',
        'Bring to a boil, then reduce heat to medium. Cover and simmer for 12-15 minutes, stirring occasionally, until pasta is tender.',
        'Remove from heat. Sprinkle cheese over the top and cover until melted, about 2 minutes.',
        'Serve with optional toppings: sour cream, cilantro, hot sauce.',
      ],
      nutrition: { calories: 535, protein: 32, carbs: 52, fat: 22 },
    },
    {
      title: 'Loaded Beef and Potato Casserole',
      description: 'Savory ground beef layered with sliced potatoes and a creamy cheesy sauce. Shepherd\'s pie meets scalloped potatoes.',
      timeMinutes: 60,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 40,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground beef',
        '2 pounds russet potatoes, thinly sliced',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 cup sour cream',
        '1 cup shredded cheddar cheese',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F (190°C). Brown ground beef with onion and garlic. Drain and season with salt and pepper.',
        'In a bowl, mix cream of mushroom soup and sour cream until smooth.',
        'Layer half the potato slices in a greased 9x13-inch dish. Top with ground beef mixture, then half the soup mixture and half the cheese.',
        'Layer remaining potatoes, soup mixture, and cheese on top.',
        'Cover with foil and bake for 35-40 minutes. Uncover and bake 10 more minutes until potatoes are tender and top is golden.',
      ],
      nutrition: { calories: 545, protein: 28, carbs: 42, fat: 30 },
    },
    {
      title: 'Sloppy Joes',
      description: 'Sweet, tangy, and savory ground beef in a rich tomato sauce piled high on toasted buns. A nostalgic family favorite ready in 25 minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground beef',
        '1 small onion, finely diced',
        '1 green bell pepper, finely diced',
        '2 cloves garlic, minced',
        '1 cup ketchup',
        '2 tablespoons brown sugar',
        '1 tablespoon yellow mustard',
        '1 tablespoon Worcestershire sauce',
        '1 tablespoon apple cider vinegar',
        '6 hamburger buns, toasted',
        '1 tablespoon vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat oil in a large skillet over medium-high heat. Add ground beef and cook 6-7 minutes, breaking into fine crumbles, until browned. Drain excess grease.',
        'Add onion, bell pepper, and garlic. Cook 4-5 minutes until vegetables are softened.',
        'Stir in ketchup, brown sugar, mustard, Worcestershire sauce, and apple cider vinegar. Mix well.',
        'Reduce heat to medium-low and simmer 10 minutes, stirring occasionally, until sauce thickens and clings to the beef.',
        'Season with salt and pepper to taste.',
        'Spoon the Sloppy Joe mixture generously onto toasted hamburger buns. Serve with pickle chips and coleslaw on the side.',
      ],
      nutrition: { calories: 485, protein: 32, carbs: 42, fat: 22 },
    },
    {
      title: 'Classic Meatloaf',
      description: 'Old-fashioned meatloaf with a sweet ketchup glaze. Hearty, comforting, and perfect for Sunday dinner.',
      timeMinutes: 70,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 55,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 pounds ground beef',
        '1 cup breadcrumbs',
        '1 small onion, finely diced',
        '2 large eggs, beaten',
        '1/2 cup milk',
        '3 tablespoons ketchup',
        '2 cloves garlic, minced',
        '1 teaspoon Worcestershire sauce',
        '1 teaspoon salt',
        '1/2 teaspoon black pepper',
        '1/2 cup ketchup for glaze',
        '2 tablespoons brown sugar',
      ],
      instructions: [
        'Preheat oven to 350°F (175°C). Line a loaf pan with parchment or grease well.',
        'In a large bowl, combine ground beef, breadcrumbs, onion, eggs, milk, 3 tablespoons ketchup, garlic, Worcestershire, salt, and pepper. Mix gently until just combined.',
        'Shape into a loaf and place in the pan. Bake for 45 minutes.',
        'Mix remaining ketchup with brown sugar for glaze. Spread over the top of the meatloaf.',
        'Bake 10 more minutes until glaze is set and internal temperature reaches 160°F. Rest 10 minutes before slicing.',
      ],
      nutrition: { calories: 445, protein: 32, carbs: 28, fat: 22 },
    },
  ],

  'ground-turkey': [
    {
      title: 'Turkey Lettuce Wraps',
      description: 'Asian-inspired ground turkey in crisp lettuce cups with a savory-sweet sauce. Light, flavorful, and fun to eat.',
      timeMinutes: 25,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1.5 pounds ground turkey',
        '1 head butter lettuce, leaves separated',
        '1/4 cup hoisin sauce',
        '2 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '4 green onions, sliced',
        '2 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '1 can (8 oz) water chestnuts, diced',
        '2 tablespoons vegetable oil',
        'Sriracha for serving',
      ],
      instructions: [
        'Heat oil in a large skillet over medium-high heat. Add ground turkey and cook for 6-7 minutes, breaking into crumbles.',
        'Add garlic and ginger, stirring for 30 seconds. Stir in hoisin sauce, soy sauce, and rice vinegar.',
        'Add water chestnuts and half the green onions. Cook 2 more minutes until heated through.',
        'Spoon turkey mixture into lettuce cups. Garnish with remaining green onions and sriracha. Serve immediately.',
      ],
      nutrition: { calories: 345, protein: 38, carbs: 22, fat: 12 },
    },
    {
      title: 'Turkey Stuffed Bell Peppers',
      description: 'Colorful bell peppers stuffed with seasoned turkey, rice, tomatoes, and cheese. Baked to perfection.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 35,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '1.5 pounds ground turkey',
        '4 large bell peppers, tops cut and seeded',
        '2 cups cooked rice',
        '1 can (15 oz) diced tomatoes',
        '1 cup shredded mozzarella',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon Italian seasoning',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F (190°C). Place bell peppers in a baking dish.',
        'Heat olive oil in a skillet. Brown ground turkey with onion and garlic. Add Italian seasoning, salt, and pepper.',
        'Stir in rice and diced tomatoes. Simmer for 2 minutes. Remove from heat and fold in half the cheese.',
        'Stuff each pepper with the turkey mixture. Top with remaining cheese.',
        'Cover with foil and bake 25 minutes. Uncover and bake 10 more minutes until peppers are tender. Serve hot.',
      ],
      nutrition: { calories: 485, protein: 42, carbs: 48, fat: 14 },
    },
    {
      title: 'Turkey Taco Bowls',
      description: 'Lean ground turkey taco bowls over cilantro lime rice with beans, corn, and fresh toppings. Guilt-free taco night.',
      timeMinutes: 30,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '1.5 pounds ground turkey',
        '3 cups cooked rice',
        '2 tablespoons lime juice',
        '1/4 cup fresh cilantro, chopped',
        '1 can (15 oz) black beans, drained',
        '1 cup corn kernels',
        '1 avocado, sliced',
        '1/2 cup salsa',
        '2 tablespoons taco seasoning',
        '2 tablespoons olive oil',
        'Salt to taste',
      ],
      instructions: [
        'Heat oil in a skillet. Cook ground turkey with taco seasoning until no pink remains, about 6-7 minutes. Season with salt.',
        'Stir lime juice and cilantro into the cooked rice.',
        'Warm black beans and corn in a small pan or microwave.',
        'Divide rice among 4 bowls. Top with turkey, black beans, corn, avocado, and salsa.',
        'Garnish with extra cilantro and lime wedges. Serve with sour cream if desired.',
      ],
      nutrition: { calories: 525, protein: 42, carbs: 52, fat: 16 },
    },
    {
      title: 'Turkey Meatballs in Marinara',
      description: 'Tender turkey meatballs simmered in rich marinara sauce. Serve over pasta or with crusty bread for a cozy dinner.',
      timeMinutes: 40,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 25,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1.5 pounds ground turkey',
        '1/2 cup breadcrumbs',
        '1/4 cup grated Parmesan',
        '1 large egg, beaten',
        '3 cloves garlic, minced',
        '2 tablespoons fresh parsley, chopped',
        '1 jar (24 oz) marinara sauce',
        '2 tablespoons olive oil',
        '1 teaspoon Italian seasoning',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'In a bowl, mix ground turkey, breadcrumbs, Parmesan, egg, half the garlic, parsley, Italian seasoning, salt, and pepper. Form into 20-24 meatballs.',
        'Heat olive oil in a large skillet over medium heat. Brown meatballs in batches, about 2-3 minutes per side. Transfer to a plate.',
        'Add remaining garlic to the skillet. Pour in marinara sauce and bring to a simmer.',
        'Return meatballs to the sauce. Cover and simmer for 15-18 minutes until meatballs are cooked through (165°F).',
        'Serve over pasta or with crusty bread. Garnish with Parmesan and fresh basil.',
      ],
      nutrition: { calories: 425, protein: 38, carbs: 28, fat: 18 },
    },
    {
      title: 'Turkey Chili',
      description: 'Hearty white bean and turkey chili with green chiles and warming spices. Comfort in a bowl without the guilt.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground turkey',
        '2 cans (15 oz each) cannellini beans, drained',
        '1 can (14.5 oz) diced tomatoes',
        '1 can (4 oz) diced green chiles',
        '1 small onion, diced',
        '3 cloves garlic, minced',
        '2 tablespoons chili powder',
        '1 teaspoon cumin',
        '2 cups chicken broth',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium-high heat. Brown ground turkey with onion and garlic for 6-7 minutes.',
        'Add chili powder and cumin. Stir for 30 seconds.',
        'Pour in diced tomatoes, green chiles, chicken broth, and beans. Bring to a boil.',
        'Reduce heat and simmer for 15-20 minutes until slightly thickened. Season with salt and pepper.',
        'Serve with shredded cheese, sour cream, and cilantro. Optional: add cornbread on the side.',
      ],
      nutrition: { calories: 325, protein: 35, carbs: 28, fat: 10 },
    },
    {
      title: 'Turkey Burger Skillet',
      description: 'Seasoned turkey burger patties with sautéed onions and mushrooms in a skillet. Simple, healthy, and satisfying.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground turkey',
        '1 small onion, sliced',
        '8 ounces mushrooms, sliced',
        '4 burger buns',
        '2 tablespoons Worcestershire sauce',
        '1 teaspoon garlic powder',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Form ground turkey into 4 patties. Season with Worcestershire, garlic powder, salt, and pepper.',
        'Heat 1 tablespoon oil in a large skillet over medium-high heat. Cook patties 5-6 minutes per side until 165°F. Remove and set aside.',
        'Add remaining oil to the skillet. Sauté onion and mushrooms for 5-6 minutes until golden.',
        'Serve turkey burgers on buns topped with onions and mushrooms. Add lettuce, tomato, and your favorite condiments.',
      ],
      nutrition: { calories: 425, protein: 40, carbs: 32, fat: 16 },
    },
    {
      title: 'Greek Turkey and Rice Skillet',
      description: 'One-skillet ground turkey with rice, tomatoes, olives, and feta. Mediterranean flavors in 35 minutes.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '1.5 pounds ground turkey',
        '1 cup long-grain rice',
        '2 cups chicken broth',
        '1 can (14.5 oz) diced tomatoes',
        '1/2 cup kalamata olives, halved',
        '1/2 cup crumbled feta',
        '2 teaspoons dried oregano',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet. Brown ground turkey with onion and garlic. Drain if needed.',
        'Add rice, chicken broth, diced tomatoes, oregano, salt, and pepper. Bring to a boil.',
        'Reduce heat to low, cover, and simmer for 18-20 minutes until rice is tender and liquid is absorbed.',
        'Stir in olives and half the feta. Top with remaining feta. Cover and let rest 2 minutes. Serve with lemon wedges.',
      ],
      nutrition: { calories: 485, protein: 40, carbs: 45, fat: 18 },
    },
    {
      title: 'Turkey Shepherd\'s Pie',
      description: 'Lighter take on the classic with ground turkey and vegetable filling under fluffy mashed potatoes. Comfort food made lean.',
      timeMinutes: 55,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 35,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1.5 pounds ground turkey',
        '2 pounds potatoes, peeled and cubed',
        '1/2 cup milk',
        '2 tablespoons butter',
        '1 cup frozen mixed vegetables',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 cup chicken broth',
        '2 tablespoons tomato paste',
        '1 teaspoon thyme',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Boil potatoes until tender. Drain, mash with milk and butter, season with salt and pepper. Set aside.',
        'Preheat oven to 400°F (200°C). Brown ground turkey with onion and garlic. Add thyme, tomato paste, broth, and frozen vegetables.',
        'Simmer for 5 minutes until thickened. Season with salt and pepper. Transfer to a 9x13-inch baking dish.',
        'Spread mashed potatoes over the top. Use a fork to create peaks. Bake for 25-30 minutes until golden.',
        'Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 365, protein: 32, carbs: 38, fat: 12 },
    },
  ],

  'beef-stew-meat': [
    {
      title: 'Classic Beef Stew',
      description: 'Tender chunks of beef simmered with potatoes, carrots, and onions in a rich savory broth. The ultimate comfort food.',
      timeMinutes: 180,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 160,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2.5 pounds beef stew meat, cubed',
        '4 large potatoes, cubed',
        '4 large carrots, cut into chunks',
        '1 large onion, diced',
        '3 cloves garlic, minced',
        '4 cups beef broth',
        '2 tablespoons tomato paste',
        '2 tablespoons Worcestershire sauce',
        '1 teaspoon thyme',
        '2 bay leaves',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season beef with salt and pepper. Heat oil in a large pot and brown beef in batches, about 4-5 minutes per batch. Transfer to slow cooker.',
        'Add onion and garlic to the pot. Sauté for 2 minutes. Add tomato paste, broth, and Worcestershire. Scrape up browned bits and pour into slow cooker.',
        'Add potatoes, carrots, thyme, and bay leaves to the slow cooker. Stir to combine.',
        'Cover and cook on low for 7-8 hours or high for 4-5 hours until beef is fork-tender.',
        'Remove bay leaves. Season with salt and pepper. Serve with crusty bread.',
      ],
      nutrition: { calories: 485, protein: 42, carbs: 42, fat: 18 },
    },
    {
      title: 'Beef Bourguignon',
      description: 'French-style beef stew with red wine, mushrooms, and pearl onions. Elegant and deeply flavorful.',
      timeMinutes: 210,
      method: 'slow-cooker',
      difficulty: 'medium',
      prepTime: 30,
      cookTime: 180,
      servings: 6,
      cuisine: 'French',
      ingredients: [
        '2.5 pounds beef stew meat',
        '1 bottle (750 ml) red wine (Burgundy or Pinot Noir)',
        '8 ounces mushrooms, halved',
        '1 cup pearl onions, peeled',
        '4 slices bacon, diced',
        '2 carrots, chopped',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '2 tablespoons tomato paste',
        '2 cups beef broth',
        '2 bay leaves',
        '1 teaspoon thyme',
        '2 tablespoons flour',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon in a large pot until crispy. Remove and set aside. Brown beef in batches in bacon fat. Transfer to slow cooker.',
        'Sauté diced onion and carrots in the pot for 3 minutes. Add garlic and tomato paste. Pour in wine, scraping up browned bits. Simmer 2 minutes.',
        'Pour wine mixture and beef broth into slow cooker. Add bay leaves, thyme, salt, and pepper. Cover and cook on low 6-7 hours.',
        'Add mushrooms and pearl onions. Cook 1 more hour. Mix flour with 2 tablespoons water, stir into stew to thicken. Remove bay leaves. Garnish with bacon.',
      ],
      nutrition: { calories: 545, protein: 40, carbs: 18, fat: 22 },
    },
    {
      title: 'Instant Pot Beef Stew',
      description: 'Tender beef stew with vegetables in under an hour. Pressure cooking delivers deep flavor in a fraction of the time.',
      timeMinutes: 55,
      method: 'instant-pot',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 40,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2.5 pounds beef stew meat, cubed',
        '4 potatoes, cubed',
        '4 carrots, cut into chunks',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '3 cups beef broth',
        '2 tablespoons tomato paste',
        '1 tablespoon Worcestershire sauce',
        '1 teaspoon thyme',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Set Instant Pot to sauté. Heat oil and brown beef in batches. Set aside.',
        'Add onion and garlic. Sauté 1 minute. Add tomato paste, broth, Worcestershire, thyme, salt, and pepper. Stir to combine.',
        'Return beef to pot. Add potatoes and carrots. Lock lid, set to high pressure for 35 minutes.',
        'Allow natural release for 10 minutes, then quick release. Remove lid.',
        'If desired, use sauté to reduce liquid for thicker stew. Season and serve.',
      ],
      nutrition: { calories: 455, protein: 42, carbs: 38, fat: 16 },
    },
    {
      title: 'Beef and Barley Soup',
      description: 'Hearty beef soup with tender meat, pearl barley, and vegetables. Stick-to-your-ribs goodness.',
      timeMinutes: 150,
      method: 'soup',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 130,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2.5 pounds beef stew meat, cubed',
        '1 cup pearl barley',
        '4 carrots, sliced',
        '2 stalks celery, sliced',
        '1 large onion, diced',
        '3 cloves garlic, minced',
        '8 cups beef broth',
        '2 tablespoons tomato paste',
        '1 teaspoon thyme',
        '2 bay leaves',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat oil in a large pot. Brown beef in batches. Remove and set aside.',
        'Sauté onion, carrot, and celery for 5 minutes. Add garlic for 30 seconds.',
        'Return beef to pot. Add broth, tomato paste, thyme, bay leaves, barley, salt, and pepper. Bring to a boil.',
        'Reduce heat and simmer for 2 hours, stirring occasionally, until beef and barley are tender.',
        'Remove bay leaves. Season and serve with crusty bread.',
      ],
      nutrition: { calories: 465, protein: 40, carbs: 42, fat: 16 },
    },
    {
      title: 'Beef Chili with Beans',
      description: 'Hearty chili with beef stew meat, kidney beans, and warming spices. Perfect for game day or a cozy night in.',
      timeMinutes: 180,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 165,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2.5 pounds beef stew meat, cubed',
        '2 cans (15 oz each) kidney beans, drained',
        '1 can (28 oz) crushed tomatoes',
        '1 can (15 oz) tomato sauce',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '3 tablespoons chili powder',
        '1 tablespoon cumin',
        '2 cups beef broth',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Brown beef in oil in a skillet. Transfer to slow cooker.',
        'Add onion, garlic, crushed tomatoes, tomato sauce, broth, chili powder, cumin, salt, and pepper to the slow cooker. Stir to combine.',
        'Cover and cook on low for 6-7 hours until beef is tender.',
        'Stir in kidney beans. Cook 30 more minutes. Season to taste.',
        'Serve with shredded cheese, sour cream, and green onions.',
      ],
      nutrition: { calories: 485, protein: 42, carbs: 38, fat: 20 },
    },
    {
      title: 'Korean Beef Stew (Kalbi Jjim Style)',
      description: 'Sweet and savory Korean-style braised beef with carrots and potatoes. Fall-apart tender and deeply flavored.',
      timeMinutes: 165,
      method: 'slow-cooker',
      difficulty: 'medium',
      prepTime: 25,
      cookTime: 140,
      servings: 6,
      cuisine: 'Korean',
      ingredients: [
        '2.5 pounds beef stew meat',
        '1/2 cup soy sauce',
        '1/4 cup brown sugar',
        '4 cloves garlic, minced',
        '1 tablespoon sesame oil',
        '2 carrots, cut into chunks',
        '2 potatoes, cubed',
        '4 green onions, cut into 2-inch pieces',
        '1 teaspoon sesame seeds',
        '2 cups beef broth',
        '2 tablespoons vegetable oil',
        'Salt to taste',
      ],
      instructions: [
        'Heat oil and brown beef in batches. Transfer to slow cooker.',
        'Whisk soy sauce, brown sugar, garlic, sesame oil, and broth. Pour over beef.',
        'Add carrots and potatoes. Cover and cook on low for 6-7 hours until beef is fork-tender.',
        'Add green onions. Cook 15 more minutes. Garnish with sesame seeds.',
        'Serve over steamed rice with kimchi on the side if desired.',
      ],
      nutrition: { calories: 425, protein: 40, carbs: 35, fat: 14 },
    },
    {
      title: 'Indian Beef Curry',
      description: 'Fragrant beef curry with tomatoes, coconut milk, and warming Indian spices. Serve over rice or with naan.',
      timeMinutes: 140,
      method: 'slow-cooker',
      difficulty: 'medium',
      prepTime: 25,
      cookTime: 115,
      servings: 6,
      cuisine: 'Indian',
      ingredients: [
        '2.5 pounds beef stew meat',
        '1 can (14 oz) coconut milk',
        '1 can (14.5 oz) diced tomatoes',
        '2 tablespoons curry powder',
        '1 tablespoon garam masala',
        '1 onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon fresh ginger, grated',
        '2 tablespoons vegetable oil',
        '1/2 cup beef broth',
        'Salt to taste',
      ],
      instructions: [
        'Brown beef in oil. Transfer to slow cooker.',
        'Sauté onion, garlic, and ginger for 2 minutes. Add curry powder and garam masala, stirring 30 seconds.',
        'Add tomatoes, coconut milk, and broth to slow cooker. Stir in onion mixture. Cover and cook on low 5-6 hours.',
        'Season with salt. Serve over basmati rice with cilantro and lime.',
      ],
      nutrition: { calories: 465, protein: 40, carbs: 12, fat: 30 },
    },
    {
      title: 'Instant Pot Beef and Broccoli',
      description: 'Tender beef in a savory sauce with broccoli. Pressure cooker makes it possible on a weeknight.',
      timeMinutes: 45,
      method: 'instant-pot',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '1.5 pounds beef stew meat, cubed',
        '4 cups broccoli florets',
        '1/2 cup soy sauce',
        '1/4 cup beef broth',
        '3 tablespoons brown sugar',
        '2 cloves garlic, minced',
        '1 teaspoon fresh ginger, grated',
        '1 tablespoon cornstarch mixed with 2 tablespoons water',
        '2 tablespoons vegetable oil',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'Set Instant Pot to sauté. Heat oil and brown beef. Add garlic and ginger for 30 seconds.',
        'Add soy sauce, broth, and brown sugar. Lock lid, high pressure 15 minutes.',
        'Quick release. Set to sauté. Add broccoli and cornstarch slurry. Cook 3-4 minutes until broccoli is tender and sauce thickens.',
        'Serve over rice. Garnish with sesame seeds.',
      ],
      nutrition: { calories: 385, protein: 38, carbs: 22, fat: 16 },
    },
  ],

  'pork-chops': [
    {
      title: 'Pan-Seared Pork Chops with Apple Cider Glaze',
      description: 'Juicy pan-seared pork chops with a sweet-tangy apple cider glaze. Restaurant-quality in 25 minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 bone-in pork chops (1 inch thick)',
        '1 cup apple cider',
        '2 tablespoons apple cider vinegar',
        '2 tablespoons butter',
        '2 tablespoons olive oil',
        '2 cloves garlic, minced',
        '1 teaspoon fresh thyme',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season pork chops with salt and pepper. Heat olive oil in a large skillet over medium-high heat.',
        'Sear pork chops 4-5 minutes per side until golden and 145°F internal. Transfer to a plate.',
        'In the same skillet, add garlic and thyme. Pour in apple cider and vinegar. Boil 4-5 minutes until reduced by half.',
        'Remove from heat. Swirl in butter. Pour glaze over pork chops and serve.',
      ],
      nutrition: { calories: 385, protein: 38, carbs: 8, fat: 22 },
    },
    {
      title: 'Baked Pork Chops with Garlic Butter',
      description: 'Tender baked pork chops smothered in garlic butter. Simple, juicy, and perfect for weeknights.',
      timeMinutes: 35,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 bone-in pork chops',
        '4 tablespoons butter, melted',
        '4 cloves garlic, minced',
        '1 teaspoon paprika',
        '1/2 teaspoon onion powder',
        '2 tablespoons fresh parsley, chopped',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C). Place pork chops in a baking dish.',
        'Mix melted butter, garlic, paprika, onion powder, parsley, salt, and pepper. Brush over pork chops.',
        'Bake 25-28 minutes until internal temperature reaches 145°F.',
        'Let rest 5 minutes. Drizzle with pan juices and serve.',
      ],
      nutrition: { calories: 365, protein: 36, carbs: 2, fat: 24 },
    },
    {
      title: 'Smothered Pork Chops',
      description: 'Southern-style pork chops smothered in rich onion gravy. Comfort food at its finest.',
      timeMinutes: 45,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 bone-in pork chops',
        '2 large onions, sliced',
        '2 cups chicken broth',
        '1/4 cup all-purpose flour',
        '2 tablespoons vegetable oil',
        '1 teaspoon thyme',
        '2 cloves garlic, minced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season pork chops with salt and pepper. Dredge in flour. Heat oil in a large skillet.',
        'Brown pork chops 4-5 minutes per side. Remove and set aside.',
        'Add onions to the skillet. Cook 8-10 minutes until golden. Add garlic and remaining flour. Stir 1 minute.',
        'Gradually whisk in chicken broth and thyme. Bring to a simmer. Return pork chops to the pan.',
        'Cover and simmer 15-18 minutes until pork is tender and sauce thickens. Serve with mashed potatoes.',
      ],
      nutrition: { calories: 385, protein: 36, carbs: 18, fat: 18 },
    },
    {
      title: 'Sheet Pan Pork Chops and Vegetables',
      description: 'Pork chops roasted alongside potatoes and green beans on one pan. Minimal cleanup, maximum flavor.',
      timeMinutes: 45,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless pork chops',
        '1 pound baby potatoes, halved',
        '12 ounces green beans, trimmed',
        '3 tablespoons olive oil',
        '2 teaspoons Italian seasoning',
        '2 cloves garlic, minced',
        '1 lemon, juiced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Toss potatoes with 1 tablespoon oil, salt, and pepper. Spread on a sheet pan. Roast 15 minutes.',
        'Season pork chops with 1 tablespoon oil, Italian seasoning, garlic, salt, and pepper.',
        'Add pork chops and green beans (tossed with remaining oil) to the sheet pan.',
        'Roast 18-20 minutes until pork reaches 145°F and vegetables are tender.',
        'Drizzle with lemon juice. Serve immediately.',
      ],
      nutrition: { calories: 425, protein: 38, carbs: 32, fat: 18 },
    },
    {
      title: 'Honey Garlic Pork Chops',
      description: 'Sticky-sweet honey garlic glaze on tender pan-seared pork chops. Irresistible and ready in 20 minutes.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '4 boneless pork chops',
        '1/4 cup honey',
        '3 tablespoons soy sauce',
        '3 cloves garlic, minced',
        '1 tablespoon rice vinegar',
        '1 tablespoon vegetable oil',
        '1 teaspoon red pepper flakes',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'Season pork chops. Heat oil in a large skillet over medium-high heat. Sear 4-5 minutes per side until 145°F. Remove.',
        'Add garlic to the skillet. Stir 30 seconds. Add honey, soy sauce, vinegar, and red pepper flakes. Simmer 2 minutes.',
        'Return pork chops to the pan. Turn to coat in glaze. Serve over rice, garnished with sesame seeds.',
      ],
      nutrition: { calories: 365, protein: 36, carbs: 28, fat: 12 },
    },
    {
      title: 'Pork Chop Casserole',
      description: 'Baked pork chops with creamy mushroom soup and stuffing. Retro comfort food the family will love.',
      timeMinutes: 55,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 40,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless pork chops',
        '1 can (10.5 oz) cream of mushroom soup',
        '1/2 cup milk',
        '2 cups stuffing mix',
        '1 small onion, diced',
        '2 tablespoons butter',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F (190°C). Season pork chops and brown in a skillet 2 minutes per side. Transfer to a 9x13 dish.',
        'Mix soup and milk. Pour over pork chops.',
        'Prepare stuffing according to package. Spread over the pork and soup layer.',
        'Bake uncovered 35-40 minutes until pork reaches 145°F and topping is golden.',
        'Let rest 5 minutes. Serve with a vegetable side.',
      ],
      nutrition: { calories: 485, protein: 38, carbs: 38, fat: 22 },
    },
    {
      title: 'Breaded Parmesan Pork Chops',
      description: 'Crispy breaded pork chops with a Parmesan crust. Kid-friendly and satisfying.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 boneless pork chops',
        '1/2 cup breadcrumbs',
        '1/2 cup grated Parmesan',
        '1 large egg, beaten',
        '2 tablespoons all-purpose flour',
        '3 tablespoons olive oil',
        '1 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Set up breading: flour, egg, then breadcrumbs mixed with Parmesan, garlic powder, salt, and pepper.',
        'Dredge each pork chop in flour, egg, then breadcrumb mixture. Press to adhere.',
        'Heat olive oil in a large skillet over medium heat. Cook chops 5-6 minutes per side until golden and 145°F.',
        'Drain on paper towels. Serve with lemon wedges.',
      ],
      nutrition: { calories: 445, protein: 42, carbs: 18, fat: 24 },
    },
    {
      title: 'Mediterranean Pork Chops',
      description: 'Pork chops with tomatoes, olives, and feta. Bright Mediterranean flavors in one skillet.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '4 boneless pork chops',
        '1 pint cherry tomatoes, halved',
        '1/2 cup kalamata olives',
        '1/2 cup crumbled feta',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 teaspoon oregano',
        '2 tablespoons fresh basil, chopped',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Season pork chops. Heat 1 tablespoon oil in a skillet. Sear 4-5 minutes per side until 145°F. Remove.',
        'Add remaining oil, tomatoes, olives, garlic, oregano, salt, and pepper. Cook 4-5 minutes until tomatoes soften.',
        'Return pork chops to the pan. Top with feta and basil. Cover and warm 1 minute. Serve.',
      ],
      nutrition: { calories: 425, protein: 38, carbs: 8, fat: 28 },
    },
  ],

  'bacon': [
    {
      title: 'Bacon-Wrapped Stuffed Jalapeños',
      description: 'Crispy bacon-wrapped jalapeño halves stuffed with a savory cream cheese filling. The ultimate appetizer-turned-dinner with a side salad.',
      timeMinutes: 40,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 20,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '12 large jalapeño peppers, halved and seeded',
        '12 slices bacon, cut in half',
        '8 ounces cream cheese, softened',
        '1 cup shredded cheddar cheese',
        '1/4 cup cooked bacon bits (for filling)',
        '2 green onions, finely sliced',
        '1/2 teaspoon garlic powder',
        '1/2 teaspoon smoked paprika',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C). Line a large baking sheet with a wire rack set on top (or use parchment paper).',
        'In a bowl, mix cream cheese, cheddar, bacon bits, green onions, garlic powder, salt, and pepper until well combined.',
        'Fill each jalapeño half with a generous spoonful of the cream cheese mixture.',
        'Wrap each stuffed jalapeño with a half slice of bacon, securing with a toothpick if needed.',
        'Arrange on the prepared baking sheet. Sprinkle with smoked paprika.',
        'Bake 18-22 minutes until bacon is crispy and filling is bubbling. Let cool 5 minutes before serving.',
        'Serve as a dinner with a side salad and ranch dressing for dipping.',
      ],
      nutrition: { calories: 425, protein: 20, carbs: 6, fat: 36 },
    },
    {
      title: 'BLT Pasta',
      description: 'All the flavors of a BLT in pasta form. Crispy bacon, fresh tomatoes, and lettuce in a light creamy sauce.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '12 ounces penne pasta',
        '10 slices bacon, chopped',
        '2 cups cherry tomatoes, halved',
        '4 cups shredded romaine lettuce',
        '1/2 cup mayonnaise',
        '2 tablespoons lemon juice',
        '2 cloves garlic, minced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta. Drain and set aside. Cook bacon until crispy. Drain, reserve 2 tablespoons grease.',
        'Whisk mayonnaise, lemon juice, and garlic. Add reserved bacon grease if desired for flavor.',
        'Toss warm pasta with bacon, tomatoes, and mayo mixture. Fold in lettuce just before serving.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 545, protein: 18, carbs: 48, fat: 32 },
    },
    {
      title: 'Bacon-Wrapped Chicken',
      description: 'Chicken breasts wrapped in smoky bacon and baked until golden. Simple yet impressive.',
      timeMinutes: 45,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '4 chicken breasts',
        '8 slices bacon',
        '2 tablespoons brown sugar',
        '1/2 teaspoon paprika',
        '1/4 teaspoon cayenne',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 400°F (200°C). Season chicken with paprika, cayenne, salt, and pepper.',
        'Wrap each chicken breast with 2 slices bacon. Secure with toothpicks. Sprinkle with brown sugar.',
        'Place in a baking dish. Bake 28-32 minutes until chicken reaches 165°F and bacon is crispy.',
        'Broil 1-2 minutes for extra crispy bacon if desired. Rest 5 minutes. Serve.',
      ],
      nutrition: { calories: 425, protein: 48, carbs: 8, fat: 22 },
    },
    {
      title: 'Loaded Baked Potato Soup',
      description: 'Creamy potato soup loaded with bacon, cheddar, and green onions. Comfort in a bowl.',
      timeMinutes: 45,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '6 slices bacon, diced',
        '2 pounds russet potatoes, peeled and cubed',
        '1 onion, diced',
        '4 cups chicken broth',
        '1 cup heavy cream',
        '1.5 cups shredded cheddar cheese',
        '4 green onions, sliced',
        '1/2 cup sour cream',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon until crispy. Remove and drain. Sauté onion in 2 tablespoons bacon grease until softened.',
        'Add potatoes and chicken broth. Bring to a boil, then simmer 15-20 minutes until potatoes are tender.',
        'Use a blender or immersion blender to partially puree the soup. Stir in cream and cheese until melted.',
        'Season with salt and pepper. Serve topped with bacon, sour cream, and green onions.',
      ],
      nutrition: { calories: 465, protein: 18, carbs: 42, fat: 28 },
    },
    {
      title: 'Sheet Pan Bacon and Eggs',
      description: 'Crispy bacon and baked eggs with hash browns on one pan. Breakfast for dinner made easy.',
      timeMinutes: 35,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '12 slices bacon',
        '4 large eggs',
        '1 pound frozen hash browns',
        '1 cup shredded cheddar',
        '2 green onions, sliced',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Spread hash browns on a sheet pan. Bake 15 minutes.',
        'Push hash browns to the sides. Arrange bacon in the center. Bake 8-10 minutes until bacon is crisp.',
        'Remove bacon. Crack eggs into small spaces. Sprinkle cheese over hash browns. Bake 6-8 minutes until egg whites are set.',
        'Top with bacon and green onions. Serve immediately.',
      ],
      nutrition: { calories: 485, protein: 22, carbs: 32, fat: 32 },
    },
    {
      title: 'Bacon Brussels Sprout Salad',
      description: 'Warm salad with crispy bacon, roasted Brussels sprouts, and a tangy vinaigrette. Perfect for dinner.',
      timeMinutes: 30,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '8 slices bacon, chopped',
        '1.5 pounds Brussels sprouts, halved',
        '2 tablespoons olive oil',
        '2 tablespoons apple cider vinegar',
        '1 tablespoon Dijon mustard',
        '1/4 cup dried cranberries',
        '2 tablespoons pepitas',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon until crispy. Remove and drain. Sauté Brussels sprouts in 2 tablespoons bacon grease until tender and charred, 8-10 minutes.',
        'Whisk olive oil, vinegar, and Dijon for vinaigrette.',
        'Combine warm Brussels sprouts with bacon, cranberries, and pepitas. Drizzle with vinaigrette. Toss and serve.',
      ],
      nutrition: { calories: 345, protein: 14, carbs: 28, fat: 22 },
    },
    {
      title: 'Bacon Mac and Cheese',
      description: 'Creamy homemade mac and cheese loaded with crispy bacon. The ultimate comfort food upgrade.',
      timeMinutes: 40,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '1 pound elbow macaroni',
        '10 slices bacon, chopped',
        '4 tablespoons butter',
        '1/4 cup flour',
        '3 cups milk',
        '2 cups shredded cheddar',
        '1 cup shredded Gruyère',
        '1/2 teaspoon mustard powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook pasta. Drain. Cook bacon until crispy. Remove and drain.',
        'Melt butter in a large pot. Whisk in flour. Cook 1 minute. Gradually add milk, whisking until smooth. Simmer 5 minutes.',
        'Remove from heat. Stir in cheeses and mustard until melted. Add pasta and bacon. Season. Serve.',
      ],
      nutrition: { calories: 585, protein: 28, carbs: 52, fat: 32 },
    },
    {
      title: 'Bacon Cheeseburger Skillet',
      description: 'Ground beef and bacon in a cheesy one-skillet meal. All the flavors of a loaded burger without the bun.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 pound ground beef',
        '8 slices bacon, chopped',
        '1 small onion, diced',
        '1 cup shredded cheddar',
        '2 tablespoons ketchup',
        '1 tablespoon mustard',
        '2 tablespoons vegetable oil',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Cook bacon until crispy. Remove and drain. Brown ground beef with onion in the same skillet. Drain excess grease.',
        'Stir in ketchup and mustard. Top with cheese. Cover until melted.',
        'Crumble bacon over the top. Serve with pickle spears and lettuce if desired.',
      ],
      nutrition: { calories: 545, protein: 35, carbs: 8, fat: 42 },
    },
  ],
}

export const proteinFaqs1: Record<string, FAQ[]> = {
  'chicken-breast': [
    {
      question: 'What can I make with chicken breast for dinner?',
      answer: 'Chicken breast is incredibly versatile. Try stir-fries, sheet pan meals, grilled salads, creamy skillet dishes, or baked stuffed chicken. Popular options include chicken fried rice, pan-seared chicken with mushroom sauce, and Greek chicken salad bowls. Most recipes take 25-45 minutes.',
    },
    {
      question: 'How do I keep chicken breast moist when cooking?',
      answer: 'Pound chicken to even thickness so it cooks evenly, avoid overcooking (remove at 165°F), and let it rest 5 minutes before slicing. Marinating or brining for 30 minutes also helps. Add chicken to sauces near the end of cooking when possible.',
    },
    {
      question: 'What is the best way to cook chicken breast quickly?',
      answer: 'Pounding chicken thin (1/2 inch) and pan-searing over medium-high heat is fastest—about 4-5 minutes per side. Stir-frying diced chicken is another quick option. Sheet pan meals work well too since you can prep while the oven heats.',
    },
    {
      question: 'Can I use frozen chicken breast for dinner recipes?',
      answer: 'Yes. Thaw completely in the fridge overnight for best results, or use the defrost setting on your microwave. Never cook frozen chicken breast from frozen—the outside will overcook before the center is done.',
    },
    {
      question: 'What vegetables go well with chicken breast?',
      answer: 'Broccoli, bell peppers, spinach, mushrooms, asparagus, and green beans all pair beautifully. For stir-fries, use snap peas and carrots. Sheet pan dinners work great with potatoes, Brussels sprouts, and zucchini.',
    },
  ],
  'ground-beef': [
    {
      question: 'What can I make with ground beef for dinner?',
      answer: 'Ground beef is perfect for tacos, burgers, skillet meals, casseroles, and bowls. Try Korean beef bowls, classic tacos, cheeseburger casserole, beef stroganoff, or Mediterranean rice bowls. Most recipes take 20-60 minutes.',
    },
    {
      question: 'What is the best fat content for ground beef?',
      answer: '80/20 (80% lean, 20% fat) offers the best balance of flavor and moisture for most recipes. Use 85/15 or 90/10 for leaner options—just add a bit of oil when browning to prevent dryness. Drain excess grease after cooking if needed.',
    },
    {
      question: 'How do I season ground beef for tacos?',
      answer: 'Use 2 tablespoons of store-bought taco seasoning per pound of beef, or make your own with chili powder, cumin, garlic powder, and oregano. Add 1/2 cup water and simmer for 3-4 minutes so the beef absorbs the flavor.',
    },
    {
      question: 'Can I substitute ground turkey for ground beef?',
      answer: 'Yes, in most recipes. Ground turkey is leaner, so add a bit of olive oil when browning to prevent dryness. Season generously since turkey has a milder flavor. It works especially well in tacos, chili, and casseroles.',
    },
    {
      question: 'What can I make with ground beef and rice?',
      answer: 'Korean beef bowls, cheesy casseroles, stuffed pepper skillets, and one-pan taco rice are all excellent. Ground beef and rice is budget-friendly and versatile—try Asian, Tex-Mex, or Mediterranean flavor profiles.',
    },
  ],
  'ground-turkey': [
    {
      question: 'What can I make with ground turkey for dinner?',
      answer: 'Ground turkey works in tacos, lettuce wraps, stuffed peppers, meatballs, chili, and burgers. Try turkey lettuce wraps, stuffed bell peppers, taco bowls, or turkey meatballs in marinara. It is a lean alternative to ground beef.',
    },
    {
      question: 'How do I keep ground turkey from being dry?',
      answer: 'Add moisture with onions, tomatoes, or broth. Don\'t overcook—cook just until no pink remains. Mix in breadcrumbs and egg for meatballs and burgers. Consider using 85/15 turkey instead of 99% lean for more fat and flavor.',
    },
    {
      question: 'Is ground turkey healthier than ground beef?',
      answer: 'Ground turkey is typically lower in saturated fat and calories, especially 93% or 99% lean varieties. It is a great option for lighter meals while still providing plenty of protein. Both can fit into a balanced diet.',
    },
    {
      question: 'What seasonings work best with ground turkey?',
      answer: 'Garlic, onions, cumin, chili powder, Italian seasoning, and soy sauce all complement turkey well. Since turkey is mild, be generous with herbs and spices. Worcestershire sauce and a touch of olive oil add richness.',
    },
    {
      question: 'Can I use ground turkey in place of ground beef in chili?',
      answer: 'Absolutely. Turkey chili is a popular lighter option. Use the same seasonings and add beans, tomatoes, and broth. Simmer for 20-25 minutes so flavors meld. Top with cheese, sour cream, and cilantro.',
    },
  ],
  'beef-stew-meat': [
    {
      question: 'What can I make with beef stew meat?',
      answer: 'Beef stew meat shines in slow-cooked dishes. Make classic beef stew, beef bourguignon, chili, curry, or Instant Pot beef and broccoli. It becomes fall-apart tender when braised low and slow. Plan for 1.5-3 hours depending on the method.',
    },
    {
      question: 'How long does beef stew meat need to cook?',
      answer: 'In a slow cooker on low, plan for 6-8 hours. On high, 4-5 hours. In an Instant Pot, 35-40 minutes under pressure. Traditional stovetop simmering takes about 2 hours. The meat is done when it is fork-tender.',
    },
    {
      question: 'Should I brown beef stew meat before slow cooking?',
      answer: 'Yes. Browning adds depth of flavor and better texture. Sear in a hot skillet in batches—don\'t crowd the pan. The fond (browned bits) left in the pan also adds flavor when deglazed with broth or wine.',
    },
    {
      question: 'What cuts work best for beef stew?',
      answer: 'Chuck roast, shoulder, or round cut into 1-1.5 inch cubes work best. These tougher cuts have more connective tissue that breaks down during long cooking, becoming tender and flavorful. Avoid lean cuts like sirloin for stew.',
    },
    {
      question: 'Can I make beef stew in an Instant Pot?',
      answer: 'Yes. Instant Pot beef stew typically takes 35-40 minutes under pressure plus release time. Brown the beef first for best flavor. Add vegetables and broth, then pressure cook. It is much faster than slow cooking.',
    },
  ],
  'pork-chops': [
    {
      question: 'What can I make with pork chops for dinner?',
      answer: 'Pork chops work for pan-searing, baking, sheet pan meals, and smothered dishes. Try apple cider glazed chops, honey garlic pork chops, smothered pork chops, or a sheet pan dinner with vegetables. Most recipes take 25-45 minutes.',
    },
    {
      question: 'What temperature should pork chops be cooked to?',
      answer: 'Cook pork chops to 145°F internal temperature, then let rest 3-5 minutes. The USDA recommends this safe temperature, and the pork will be juicy with a slight pink center. Use a meat thermometer for accuracy.',
    },
    {
      question: 'How do I keep pork chops from drying out?',
      answer: 'Don\'t overcook—145°F is the target. Use bone-in chops when possible (they stay juicier). Brine for 30-60 minutes before cooking, or pound chops to even thickness so they cook uniformly. Let rest before serving.',
    },
    {
      question: 'Should I use bone-in or boneless pork chops?',
      answer: 'Both work. Bone-in chops tend to stay juicier and have more flavor, and they are often thicker. Boneless chops cook faster and are easier to cut. Choose based on recipe and preference—both are versatile.',
    },
    {
      question: 'What sauce goes well with pork chops?',
      answer: 'Apple cider glaze, honey garlic, mushroom gravy, and mustard cream sauce all pair beautifully. Smothered pork chops with onion gravy is a classic. For something lighter, try lemon herb butter or a fruit-based sauce.',
    },
  ],
  'bacon': [
    {
      question: 'What can I make with bacon for dinner?',
      answer: 'Bacon elevates many dishes. Try carbonara, BLT pasta, bacon-wrapped chicken, loaded potato soup, or a bacon cheeseburger skillet. It also adds smoky flavor to salads, casseroles, and sheet pan meals. Breakfast-for-dinner with bacon and eggs is always a hit.',
    },
    {
      question: 'How do I cook bacon crispy?',
      answer: 'Cook in a cold skillet over medium heat, flipping occasionally. For oven method, place on a foil-lined sheet pan at 400°F for 18-20 minutes. Drain on paper towels. Thick-cut bacon may need a few extra minutes.',
    },
    {
      question: 'Can I use turkey bacon instead of pork bacon?',
      answer: 'Yes, in most recipes. Turkey bacon is leaner and may not crisp up as much. Cook it a bit longer. For carbonara or dishes where bacon fat is used for flavor, pork bacon delivers more richness.',
    },
    {
      question: 'How do I store cooked bacon?',
      answer: 'Store in the refrigerator for up to 5 days or freeze for 2-3 months. Reheat in a skillet or microwave. Save bacon grease in a jar in the fridge—it adds flavor when cooking eggs, vegetables, or gravy.',
    },
    {
      question: 'What pasta goes best with bacon?',
      answer: 'Spaghetti is classic for carbonara. Penne, rigatoni, and fettuccine also work well with bacon-based sauces. Short shapes like penne catch bits of bacon. For BLT pasta, penne or fusilli hold the toppings nicely.',
    },
  ],
}
