import type { RecipeIdea, FAQ } from '../recipe-ideas'

export const proteinRecipes2: Record<string, RecipeIdea[]> = {
  sausage: [
    {
      title: 'Italian Sausage Sheet Pan with Peppers and Onions',
      description: 'Roasted Italian sausage links with colorful bell peppers and sweet onions on one pan. Minimal cleanup, maximum flavor for busy weeknights.',
      timeMinutes: 40,
      method: 'sheet-pan',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 30,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 pound Italian sausage links (sweet or hot)',
        '3 bell peppers (assorted colors), sliced into strips',
        '2 large yellow onions, sliced into wedges',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 teaspoon dried oregano',
        '1/2 teaspoon red pepper flakes',
        'Salt and black pepper to taste',
        'Fresh basil for garnish',
      ],
      instructions: [
        'Preheat oven to 425°F. Line a large sheet pan with parchment paper.',
        'Arrange sausage links, bell peppers, and onions on the sheet pan in a single layer.',
        'Drizzle with olive oil and sprinkle with oregano, red pepper flakes, salt, and pepper. Toss vegetables to coat.',
        'Roast for 25-30 minutes, flipping sausage and stirring vegetables halfway through, until sausage is cooked through and vegetables are tender and slightly charred.',
        'Add minced garlic and toss. Roast 2 more minutes until fragrant.',
        'Slice sausage into coins and serve over the peppers and onions. Garnish with fresh basil.',
      ],
      nutrition: { calories: 380, protein: 18, carbs: 14, fat: 28 },
    },
    {
      title: 'Sausage and White Bean Soup',
      description: 'Hearty Italian-inspired soup with crumbled sausage, creamy cannellini beans, kale, and a rich tomato broth. Comfort in a bowl.',
      timeMinutes: 35,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1 pound Italian sausage, casings removed',
        '2 cans (15 oz each) cannellini beans, drained and rinsed',
        '1 bunch kale, stems removed and leaves torn',
        '1 can (14.5 oz) diced tomatoes',
        '4 cups chicken broth',
        '1 yellow onion, diced',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 teaspoon dried oregano',
        '1/2 teaspoon red pepper flakes',
        'Salt and black pepper to taste',
        'Parmesan cheese for serving',
      ],
      instructions: [
        'Heat olive oil in a large Dutch oven over medium-high heat. Add sausage and cook, breaking into crumbles, until browned and cooked through, about 6-7 minutes. Remove and set aside.',
        'In the same pot, sauté onion until softened, about 4 minutes. Add garlic and cook 30 seconds until fragrant.',
        'Add diced tomatoes, chicken broth, oregano, red pepper flakes, salt, and pepper. Bring to a boil.',
        'Add cannellini beans and kale. Simmer for 10 minutes until kale is tender.',
        'Return sausage to the pot. Taste and adjust seasoning.',
        'Ladle into bowls and serve with grated Parmesan cheese.',
      ],
      nutrition: { calories: 320, protein: 20, carbs: 28, fat: 14 },
    },
    {
      title: 'Sausage and Peppers Stir-Fry',
      description: 'Quick skillet meal with sliced smoked sausage, bell peppers, and onions in a savory soy-garlic sauce. A weeknight dinner ready in 20 minutes.',
      timeMinutes: 20,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 8,
      cookTime: 12,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '14 ounces smoked sausage (kielbasa), sliced into 1/2-inch coins',
        '2 bell peppers (red and green), sliced into strips',
        '1 large onion, sliced',
        '3 cloves garlic, minced',
        '2 tablespoons soy sauce',
        '1 tablespoon Worcestershire sauce',
        '1 tablespoon vegetable oil',
        '1/2 teaspoon black pepper',
        'Chopped green onions for garnish',
      ],
      instructions: [
        'Heat vegetable oil in a large skillet or wok over high heat. Add sausage slices and cook until browned on both sides, about 3-4 minutes. Remove and set aside.',
        'Add bell peppers and onion to the hot pan. Stir-fry for 4-5 minutes until softened and slightly charred.',
        'Add garlic and cook 30 seconds until fragrant.',
        'Return sausage to the pan. Add soy sauce and Worcestershire sauce. Toss everything together for 1-2 minutes until heated through.',
        'Season with black pepper. Garnish with green onions and serve over rice if desired.',
      ],
      nutrition: { calories: 340, protein: 16, carbs: 12, fat: 26 },
    },
    {
      title: 'Baked Sausage Ziti',
      description: 'Layered pasta bake with crumbled Italian sausage, marinara, ricotta, and bubbly mozzarella. A crowd-pleasing comfort classic.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 35,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '1 pound Italian sausage, casings removed',
        '1 pound ziti pasta',
        '3 cups marinara sauce',
        '2 cups shredded mozzarella cheese',
        '1 cup ricotta cheese',
        '1/2 cup grated Parmesan cheese',
        '1 yellow onion, diced',
        '3 cloves garlic, minced',
        '1 tablespoon olive oil',
        '1 teaspoon dried basil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Cook ziti according to package directions until al dente. Drain.',
        'Heat olive oil in a large skillet. Add sausage and onion, breaking sausage into crumbles. Cook until browned, 6-7 minutes. Add garlic and cook 30 seconds.',
        'Stir in marinara sauce and dried basil. Simmer 2-3 minutes.',
        'In a 9x13-inch baking dish, layer half the ziti, half the sausage sauce, dollops of ricotta, and half the mozzarella. Repeat layers.',
        'Sprinkle Parmesan on top. Cover with foil and bake 25 minutes. Uncover and bake 10 more minutes until cheese is golden and bubbly.',
        'Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 580, protein: 28, carbs: 52, fat: 28 },
    },
    {
      title: 'Sausage Jambalaya',
      description: 'Creole-style one-pot rice with andouille sausage, shrimp, peppers, and Cajun spice. Bold, flavorful, and perfect for feeding a crowd.',
      timeMinutes: 45,
      method: 'one-pan',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'Cajun',
      ingredients: [
        '1 pound andouille sausage, sliced into coins',
        '1 pound large shrimp, peeled and deveined',
        '2 cups long-grain white rice',
        '4 cups chicken broth',
        '1 green bell pepper, diced',
        '1 red bell pepper, diced',
        '1 large onion, diced',
        '3 stalks celery, diced',
        '4 cloves garlic, minced',
        '1 can (14.5 oz) diced tomatoes',
        '2 tablespoons Cajun seasoning',
        '1 tablespoon olive oil',
        '2 bay leaves',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large Dutch oven over medium-high heat. Add andouille sausage and cook until browned, 3-4 minutes. Remove and set aside.',
        'In the same pot, sauté onion, bell peppers, and celery until softened, about 5 minutes. Add garlic and Cajun seasoning, cook 1 minute.',
        'Add rice and stir to coat. Pour in chicken broth, diced tomatoes, and bay leaves. Bring to a boil.',
        'Reduce heat to low, cover, and simmer 18-20 minutes until rice is tender and liquid is absorbed.',
        'Add shrimp and reserved sausage. Cover and cook 3-4 minutes until shrimp are pink and cooked through. Remove bay leaves.',
        'Fluff with a fork, taste for seasoning, and serve hot.',
      ],
      nutrition: { calories: 480, protein: 32, carbs: 52, fat: 16 },
    },
    {
      title: 'Sausage and Potato Skillet',
      description: 'One-pan comfort meal with browned sausage, tender potatoes, and melted cheddar. Hearty and satisfying with minimal cleanup.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 25,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '1 pound breakfast sausage links or bulk sausage',
        '4 medium russet potatoes, diced into 1/2-inch cubes',
        '1 small onion, diced',
        '2 tablespoons vegetable oil',
        '1 cup shredded cheddar cheese',
        '2 tablespoons chopped fresh parsley',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Heat 1 tablespoon oil in a large skillet over medium-high heat. Add sausage and cook until browned and cooked through, 6-8 minutes. Slice into coins if using links. Remove and set aside.',
        'Add remaining oil to the skillet. Add potatoes and onion. Cook, stirring occasionally, until potatoes are golden and tender, 15-18 minutes.',
        'Return sausage to the skillet. Sprinkle shredded cheese over the top.',
        'Cover and let cheese melt, about 2 minutes. Remove lid, sprinkle with parsley, salt, and pepper.',
        'Serve hot directly from the skillet.',
      ],
      nutrition: { calories: 520, protein: 22, carbs: 42, fat: 30 },
    },
    {
      title: 'Sausage Pesto Pasta',
      description: 'Quick weeknight pasta with crumbled Italian sausage, basil pesto, and sun-dried tomatoes. Ready in 20 minutes, packed with flavor.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 8,
      cookTime: 17,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '1 pound Italian sausage, casings removed',
        '12 ounces penne or rigatoni pasta',
        '1/2 cup basil pesto',
        '1/4 cup sun-dried tomatoes, chopped',
        '2 cloves garlic, minced',
        '1/4 cup reserved pasta water',
        '2 tablespoons olive oil',
        'Grated Parmesan cheese for serving',
        'Fresh basil leaves for garnish',
      ],
      instructions: [
        'Bring a large pot of salted water to boil. Cook pasta until al dente. Reserve 1/2 cup pasta water before draining.',
        'Heat olive oil in a large skillet over medium-high heat. Add sausage and cook, breaking into crumbles, until browned and cooked through, 6-7 minutes.',
        'Add garlic and sun-dried tomatoes. Cook 1 minute.',
        'Reduce heat to low. Add cooked pasta, pesto, and a splash of pasta water. Toss until evenly coated. Add more pasta water if needed for sauciness.',
        'Serve immediately with grated Parmesan and fresh basil.',
      ],
      nutrition: { calories: 620, protein: 26, carbs: 52, fat: 36 },
    },
    {
      title: 'Slow Cooker Sausage and Peppers',
      description: 'Set-it-and-forget-it Italian sausage with peppers and onions in a savory tomato sauce. Perfect for busy days when you want dinner ready when you get home.',
      timeMinutes: 360,
      method: 'slow-cooker',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 350,
      servings: 6,
      cuisine: 'Italian',
      ingredients: [
        '2 pounds Italian sausage links',
        '4 bell peppers (assorted colors), sliced into strips',
        '2 large onions, sliced into wedges',
        '1 can (14.5 oz) crushed tomatoes',
        '1/2 cup chicken broth',
        '3 cloves garlic, minced',
        '1 teaspoon dried oregano',
        '1 teaspoon dried basil',
        '1/2 teaspoon red pepper flakes',
        'Salt and black pepper to taste',
        'Hoagie rolls or crusty bread for serving',
      ],
      instructions: [
        'Place sausage links in the slow cooker. Add bell peppers and onions on top.',
        'In a bowl, combine crushed tomatoes, chicken broth, garlic, oregano, basil, red pepper flakes, salt, and pepper. Pour over the sausage and vegetables.',
        'Cover and cook on LOW for 6 hours or HIGH for 3 hours, until sausage is cooked through and vegetables are tender.',
        'Slice sausages if desired. Serve in hoagie rolls with peppers and onions, or over mashed potatoes or polenta.',
      ],
      nutrition: { calories: 420, protein: 20, carbs: 18, fat: 30 },
    },
  ],
  'rotisserie-chicken': [
    {
      title: 'Rotisserie Chicken Cobb Salad',
      description: 'Classic Cobb salad with shredded rotisserie chicken, crispy bacon, avocado, blue cheese, and hard-boiled eggs. A complete meal in one bowl.',
      timeMinutes: 15,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 0,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '3 cups shredded rotisserie chicken',
        '6 strips cooked bacon, crumbled',
        '2 hard-boiled eggs, sliced',
        '1 avocado, sliced',
        '1/2 cup crumbled blue cheese',
        '6 cups mixed salad greens',
        '1 cup cherry tomatoes, halved',
        '1/4 cup red wine vinaigrette',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Arrange salad greens on a large platter or divide among 4 plates.',
        'Arrange shredded chicken, bacon, egg slices, avocado, tomatoes, and blue cheese in rows or sections over the greens.',
        'Drizzle with red wine vinaigrette. Season with salt and pepper.',
        'Serve immediately. Toss gently at the table if desired.',
      ],
      nutrition: { calories: 450, protein: 42, carbs: 12, fat: 28 },
    },
    {
      title: 'Rotisserie Chicken Enchiladas',
      description: 'Cheesy enchiladas filled with shredded rotisserie chicken, smothered in red sauce, and baked until bubbly. Quick to assemble since the chicken is already cooked.',
      timeMinutes: 35,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 20,
      servings: 6,
      cuisine: 'Mexican',
      ingredients: [
        '3 cups shredded rotisserie chicken',
        '2 cups enchilada sauce',
        '8 flour tortillas (8-inch)',
        '2 cups shredded Mexican blend cheese',
        '1/2 cup sour cream',
        '1 small onion, diced',
        '1 teaspoon ground cumin',
        '2 tablespoons chopped cilantro',
        'Sliced green onions for garnish',
      ],
      instructions: [
        'Preheat oven to 375°F. Spread 1/2 cup enchilada sauce in the bottom of a 9x13-inch baking dish.',
        'In a bowl, toss shredded chicken with cumin and half the cheese.',
        'Warm tortillas in the microwave for 20 seconds. Fill each tortilla with chicken mixture, roll tightly, and place seam-side down in the dish.',
        'Pour remaining enchilada sauce over the enchiladas. Top with remaining cheese.',
        'Bake 20-25 minutes until cheese is melted and edges are golden.',
        'Dollop with sour cream, sprinkle with cilantro and green onions. Serve hot.',
      ],
      nutrition: { calories: 520, protein: 38, carbs: 38, fat: 22 },
    },
    {
      title: 'Rotisserie Chicken Noodle Soup',
      description: 'Classic chicken noodle soup using rotisserie chicken for instant depth of flavor. Comforting, warming, and ready in 25 minutes.',
      timeMinutes: 25,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 15,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '3 cups shredded rotisserie chicken',
        '6 cups chicken broth',
        '8 ounces egg noodles',
        '2 carrots, sliced',
        '2 stalks celery, diced',
        '1 small onion, diced',
        '2 cloves garlic, minced',
        '1 teaspoon dried thyme',
        '2 tablespoons olive oil',
        'Salt and black pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'Heat olive oil in a large pot over medium heat. Sauté onion, carrots, and celery until softened, about 5 minutes. Add garlic and thyme, cook 30 seconds.',
        'Pour in chicken broth and bring to a boil. Add egg noodles and cook 8-10 minutes until tender.',
        'Stir in shredded rotisserie chicken. Cook 2 more minutes to heat through.',
        'Season with salt and pepper. Ladle into bowls and garnish with fresh parsley.',
      ],
      nutrition: { calories: 320, protein: 28, carbs: 32, fat: 10 },
    },
    {
      title: 'Rotisserie Chicken Casserole',
      description: 'Creamy baked casserole with rotisserie chicken, rice, broccoli, and a golden cheese topping. The ultimate weeknight comfort dinner.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '3 cups shredded rotisserie chicken',
        '2 cups cooked white rice',
        '2 cups broccoli florets, steamed',
        '1 can (10.5 oz) cream of chicken soup',
        '1 cup sour cream',
        '1.5 cups shredded cheddar cheese',
        '1/2 cup milk',
        '1/2 cup crushed Ritz crackers',
        '2 tablespoons melted butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. Grease a 9x13-inch baking dish.',
        'In a large bowl, combine shredded chicken, rice, broccoli, cream of chicken soup, sour cream, milk, and 1 cup cheddar. Season with salt and pepper.',
        'Spread mixture into the prepared dish. Sprinkle remaining cheese on top.',
        'Mix crushed crackers with melted butter. Sprinkle over the casserole.',
        'Bake 25-30 minutes until bubbly and topping is golden. Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 480, protein: 32, carbs: 36, fat: 24 },
    },
    {
      title: 'Rotisserie Chicken Wraps',
      description: 'Quick wraps filled with shredded rotisserie chicken, crisp lettuce, tomato, and creamy dressing. Perfect for lunch or a light dinner.',
      timeMinutes: 10,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 0,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cups shredded rotisserie chicken',
        '4 large flour tortillas (10-inch)',
        '2 cups shredded lettuce',
        '1 large tomato, diced',
        '1/2 cup ranch dressing',
        '1/2 cup shredded cheddar cheese',
        '1/4 cup sliced black olives',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Warm tortillas in the microwave for 15 seconds if desired.',
        'Place each tortilla on a clean surface. Layer with lettuce, shredded chicken, tomato, cheese, and olives.',
        'Drizzle with ranch dressing. Season with salt and pepper.',
        'Fold in the sides and roll tightly. Slice in half and serve immediately.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 32, fat: 20 },
    },
    {
      title: 'Rotisserie Chicken Pot Pie',
      description: 'Classic chicken pot pie with a flaky golden crust, creamy filling, and tender vegetables. Uses rotisserie chicken for a shortcut that tastes homemade.',
      timeMinutes: 50,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '3 cups shredded rotisserie chicken',
        '2 refrigerated pie crusts',
        '2 cups frozen mixed vegetables (peas, carrots, corn, green beans)',
        '1/3 cup butter',
        '1/3 cup all-purpose flour',
        '1.5 cups chicken broth',
        '2/3 cup whole milk',
        '1 small onion, diced',
        '1/2 teaspoon dried thyme',
        '1/2 teaspoon garlic powder',
        'Salt and black pepper to taste',
      ],
      instructions: [
        'Preheat oven to 425°F (220°C). Press one pie crust into a 9-inch deep-dish pie plate.',
        'Melt butter in a large saucepan over medium heat. Add onion and cook 3-4 minutes until softened.',
        'Whisk in flour and cook 1 minute. Gradually pour in chicken broth and milk, whisking constantly until smooth.',
        'Bring to a simmer and cook 4-5 minutes until thickened. Stir in thyme, garlic powder, salt, and pepper.',
        'Fold in shredded chicken and frozen vegetables. Pour filling into the pie crust.',
        'Place the second crust on top, crimping edges to seal. Cut 4-5 slits in the top for steam to escape.',
        'Bake 28-32 minutes until crust is golden brown and filling is bubbling. Let cool 10 minutes before serving.',
      ],
      nutrition: { calories: 480, protein: 28, carbs: 38, fat: 24 },
    },
    {
      title: 'Rotisserie Chicken Greek Salad Bowl',
      description: 'Mediterranean-style bowl with rotisserie chicken, cucumber, tomato, olives, feta, and tzatziki over greens. Fresh and satisfying.',
      timeMinutes: 12,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 12,
      cookTime: 0,
      servings: 4,
      cuisine: 'Greek',
      ingredients: [
        '2 cups shredded rotisserie chicken',
        '4 cups mixed greens or romaine',
        '1 large cucumber, diced',
        '1 cup cherry tomatoes, halved',
        '1/2 cup kalamata olives, halved',
        '1/2 cup crumbled feta cheese',
        '1/2 cup tzatziki sauce',
        '2 tablespoons olive oil',
        '1 tablespoon lemon juice',
        '1 teaspoon dried oregano',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Divide greens among 4 bowls. Top with shredded chicken, cucumber, tomatoes, olives, and feta.',
        'Dollop tzatziki over each bowl. Drizzle with olive oil and lemon juice.',
        'Sprinkle with oregano, salt, and pepper. Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 36, carbs: 14, fat: 22 },
    },
    {
      title: 'Rotisserie Chicken Tacos',
      description: 'Quick tacos with seasoned shredded rotisserie chicken, fresh toppings, and lime. Dinner in 10 minutes.',
      timeMinutes: 12,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 2,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '2 cups shredded rotisserie chicken',
        '8 small flour or corn tortillas',
        '1 tablespoon taco seasoning',
        '2 tablespoons water',
        '1 cup shredded lettuce',
        '1/2 cup salsa',
        '1/2 cup shredded cheese',
        '1/4 cup sour cream',
        '1 lime, cut into wedges',
        'Chopped cilantro for garnish',
      ],
      instructions: [
        'Warm shredded chicken in a skillet with taco seasoning and water. Stir 2 minutes until heated and coated.',
        'Warm tortillas in a dry skillet or over a gas flame until lightly charred.',
        'Fill tortillas with seasoned chicken. Top with lettuce, salsa, cheese, and sour cream.',
        'Garnish with cilantro and lime wedges. Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 30, carbs: 34, fat: 14 },
    },
  ],
  'canned-chicken': [
    {
      title: 'Classic Canned Chicken Salad',
      description: 'Creamy chicken salad with celery, red onion, and a tangy mayo-dijon dressing. Perfect for sandwiches, lettuce wraps, or crackers.',
      timeMinutes: 15,
      method: 'salad',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 0,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '1/2 cup mayonnaise',
        '2 teaspoons Dijon mustard',
        '2 stalks celery, finely diced',
        '1/4 cup red onion, finely diced',
        '1/4 cup chopped fresh parsley',
        'Salt and black pepper to taste',
        'Lemon juice to taste',
      ],
      instructions: [
        'In a medium bowl, flake the canned chicken with a fork until well separated.',
        'Add mayonnaise, Dijon mustard, celery, red onion, and parsley. Stir until combined.',
        'Season with salt, pepper, and a squeeze of lemon juice. Mix well.',
        'Chill for at least 15 minutes before serving. Serve on bread, in lettuce cups, or with crackers.',
      ],
      nutrition: { calories: 320, protein: 28, carbs: 4, fat: 22 },
    },
    {
      title: 'Canned Chicken Quesadillas',
      description: 'Crispy cheesy quesadillas with seasoned canned chicken. Budget-friendly and ready in 10 minutes.',
      timeMinutes: 12,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 7,
      servings: 2,
      cuisine: 'Mexican',
      ingredients: [
        '1 can (12.5 oz) canned chicken, drained and flaked',
        '4 flour tortillas (8-inch)',
        '1.5 cups shredded Monterey Jack cheese',
        '1/2 cup salsa',
        '1 teaspoon taco seasoning',
        '2 tablespoons butter',
        'Sour cream and guacamole for serving',
      ],
      instructions: [
        'In a bowl, mix flaked chicken with taco seasoning and 2 tablespoons salsa.',
        'Melt 1/2 tablespoon butter in a skillet over medium heat. Place one tortilla in the pan.',
        'Spread half the chicken mixture on one half of the tortilla. Top with 1/3 cup cheese. Fold tortilla in half.',
        'Cook 2-3 minutes per side until golden and cheese melts. Repeat for remaining quesadillas.',
        'Cut into wedges and serve with sour cream and guacamole.',
      ],
      nutrition: { calories: 520, protein: 36, carbs: 36, fat: 26 },
    },
    {
      title: 'Canned Chicken Casserole',
      description: 'Creamy baked casserole with canned chicken, stuffing mix, and green beans. Comforting pantry staple dinner.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 35,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '1 can (10.5 oz) cream of chicken soup',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 can (14.5 oz) green beans, drained',
        '1 box (6 oz) stuffing mix',
        '1/2 cup sour cream',
        '1/2 cup chicken broth',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 350°F. Grease a 9x13-inch baking dish.',
        'In a large bowl, combine flaked chicken, both soups, sour cream, chicken broth, and green beans. Season with salt and pepper.',
        'Spread mixture in the baking dish. Sprinkle dry stuffing mix evenly over the top.',
        'Bake 35 minutes until bubbling and stuffing is golden. Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 340, protein: 28, carbs: 32, fat: 12 },
    },
    {
      title: 'Canned Chicken Buffalo Dip',
      description: 'Creamy, spicy buffalo chicken dip with cream cheese and ranch. Perfect for game day or as a meal with chips and veggies.',
      timeMinutes: 25,
      method: 'baked',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 8,
      cuisine: 'American',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '8 ounces cream cheese, softened',
        '1/2 cup Buffalo hot sauce',
        '1/2 cup ranch dressing',
        '1 cup shredded cheddar cheese',
        '1/2 cup blue cheese crumbles',
        '2 green onions, sliced',
        'Tortilla chips or celery for serving',
      ],
      instructions: [
        'Preheat oven to 350°F. Grease an 8x8-inch baking dish.',
        'In a large bowl, mix flaked chicken, cream cheese, Buffalo sauce, ranch dressing, and half the cheddar until combined.',
        'Spread into the baking dish. Top with remaining cheddar and blue cheese crumbles.',
        'Bake 20 minutes until hot and bubbly. Garnish with green onions.',
        'Serve warm with tortilla chips or celery sticks.',
      ],
      nutrition: { calories: 320, protein: 24, carbs: 6, fat: 24 },
    },
    {
      title: 'Canned Chicken Noodle Soup',
      description: 'Quick and easy chicken noodle soup using canned chicken. Cozy comfort in under 20 minutes.',
      timeMinutes: 20,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 15,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '6 cups chicken broth',
        '4 ounces egg noodles',
        '2 carrots, sliced',
        '2 stalks celery, diced',
        '1 teaspoon dried thyme',
        '1 bay leaf',
        'Salt and pepper to taste',
        'Fresh parsley for garnish',
      ],
      instructions: [
        'In a large pot, bring chicken broth to a boil. Add carrots, celery, thyme, and bay leaf. Simmer 8 minutes.',
        'Add egg noodles and cook 8-10 minutes until tender.',
        'Stir in flaked canned chicken. Cook 2 minutes to heat through. Remove bay leaf.',
        'Season with salt and pepper. Ladle into bowls and garnish with parsley.',
      ],
      nutrition: { calories: 280, protein: 30, carbs: 26, fat: 6 },
    },
    {
      title: 'Canned Chicken Wraps',
      description: 'Light and quick wraps with canned chicken, lettuce, cheese, and a creamy dressing. Ideal for lunch or a fast dinner.',
      timeMinutes: 10,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 0,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '4 large flour tortillas',
        '2 cups shredded lettuce',
        '1/2 cup ranch or Caesar dressing',
        '1/2 cup shredded cheddar cheese',
        '1 tomato, diced',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, combine flaked chicken with 2 tablespoons dressing. Season with salt and pepper.',
        'Lay tortillas flat. Divide chicken mixture, lettuce, tomato, and cheese among tortillas.',
        'Drizzle with remaining dressing. Roll tightly, tucking in the sides.',
        'Cut in half and serve.',
      ],
      nutrition: { calories: 420, protein: 32, carbs: 34, fat: 18 },
    },
    {
      title: 'Canned Chicken Pot Pie',
      description: 'Homestyle pot pie with canned chicken, mixed vegetables, and a flaky biscuit or pie crust topping. Comfort in every bite.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '1 can (10.5 oz) cream of chicken soup',
        '1 cup chicken broth',
        '2 cups frozen mixed vegetables (peas, carrots, corn)',
        '1/2 teaspoon garlic powder',
        '1/2 teaspoon onion powder',
        '1 refrigerated pie crust or biscuit dough',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 375°F. In a large bowl, combine flaked chicken, cream of chicken soup, broth, frozen vegetables, garlic powder, onion powder, salt, and pepper.',
        'Pour mixture into a 9x13-inch or deep 9-inch pie dish.',
        'Top with pie crust (trim and crimp edges) or drop biscuit dough over the filling.',
        'Bake 30 minutes until golden and bubbling. Let cool 5 minutes before serving.',
      ],
      nutrition: { calories: 340, protein: 24, carbs: 32, fat: 14 },
    },
    {
      title: 'Canned Chicken Rice Bowls',
      description: 'Asian-inspired bowl with canned chicken, rice, soy-ginger sauce, and quick-pickled veggies. Simple and satisfying.',
      timeMinutes: 20,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 10,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '2 cans (12.5 oz each) canned chicken, drained and flaked',
        '3 cups cooked jasmine rice',
        '3 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '1 tablespoon honey',
        '1 teaspoon sesame oil',
        '1 clove garlic, minced',
        '1 teaspoon grated ginger',
        '2 cups shredded cabbage or coleslaw mix',
        '2 green onions, sliced',
        'Sesame seeds for garnish',
      ],
      instructions: [
        'In a small bowl, whisk soy sauce, rice vinegar, honey, sesame oil, garlic, and ginger.',
        'Warm flaked chicken in a skillet with half the sauce for 2-3 minutes.',
        'Divide rice among 4 bowls. Top with warmed chicken, shredded cabbage, and green onions.',
        'Drizzle with remaining sauce. Garnish with sesame seeds. Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 32, carbs: 42, fat: 8 },
    },
  ],
  'canned-tuna': [
    {
      title: 'Classic Tuna Melt',
      description: 'Creamy tuna salad topped with melted cheese on toasted bread. A diner classic that hits the spot every time.',
      timeMinutes: 15,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 8,
      cookTime: 7,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (5 oz each) chunk light tuna in water, drained',
        '1/4 cup mayonnaise',
        '2 tablespoons celery, finely diced',
        '2 tablespoons red onion, finely diced',
        '1 tablespoon Dijon mustard',
        '8 slices bread',
        '4 slices cheddar or American cheese',
        '2 tablespoons butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, flake tuna. Mix with mayonnaise, celery, red onion, mustard, salt, and pepper.',
        'Spread tuna mixture on 4 slices of bread. Top each with a slice of cheese and the remaining bread.',
        'Melt butter in a large skillet over medium heat. Cook sandwiches 3-4 minutes per side until golden and cheese melts.',
        'Serve hot.',
      ],
      nutrition: { calories: 420, protein: 28, carbs: 32, fat: 20 },
    },
    {
      title: 'Spicy Tuna Cucumber Bites',
      description: 'Fresh cucumber rounds topped with a zesty spicy tuna mixture, sriracha mayo, and sesame seeds. A light, no-cook dinner that is refreshing and satisfying.',
      timeMinutes: 15,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 0,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '2 cans (5 oz each) chunk light tuna, drained well',
        '3 large English cucumbers, sliced into 1/2-inch rounds',
        '2 tablespoons sriracha sauce',
        '3 tablespoons mayonnaise',
        '1 tablespoon soy sauce',
        '1 teaspoon sesame oil',
        '1 avocado, finely diced',
        '2 green onions, thinly sliced',
        '1 teaspoon sesame seeds',
        '1 tablespoon rice vinegar',
      ],
      instructions: [
        'In a medium bowl, flake tuna with a fork. Add mayonnaise, sriracha, soy sauce, sesame oil, and rice vinegar. Mix until well combined.',
        'Gently fold in diced avocado, being careful not to mash it.',
        'Arrange cucumber rounds on a serving platter in a single layer.',
        'Spoon a generous tablespoon of the spicy tuna mixture onto each cucumber round.',
        'Garnish with sliced green onions and sesame seeds.',
        'Serve immediately as a light dinner alongside miso soup or edamame.',
      ],
      nutrition: { calories: 280, protein: 24, carbs: 12, fat: 16 },
    },
    {
      title: 'Tuna Nicoise Salad',
      description: 'French-inspired salad with tuna, boiled eggs, green beans, olives, and a tangy vinaigrette. Elegant yet simple.',
      timeMinutes: 25,
      method: 'salad',
      difficulty: 'medium',
      prepTime: 20,
      cookTime: 5,
      servings: 4,
      cuisine: 'French',
      ingredients: [
        '2 cans (5 oz each) solid white tuna in water, drained',
        '4 large eggs, hard-boiled and quartered',
        '8 ounces green beans, blanched',
        '4 cups mixed salad greens',
        '1/2 cup Niçoise or kalamata olives',
        '1 cup cherry tomatoes, halved',
        '3 tablespoons olive oil',
        '2 tablespoons red wine vinegar',
        '1 teaspoon Dijon mustard',
        '1 small shallot, minced',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Whisk together olive oil, vinegar, mustard, shallot, salt, and pepper for the vinaigrette.',
        'Arrange greens on 4 plates. Top with tuna (flaked), eggs, green beans, olives, and tomatoes.',
        'Drizzle with vinaigrette. Serve immediately.',
      ],
      nutrition: { calories: 340, protein: 28, carbs: 12, fat: 22 },
    },
    {
      title: 'Tuna Patties',
      description: 'Crispy pan-fried tuna cakes with breadcrumbs, egg, and herbs. Serve with lemon aioli or a side salad.',
      timeMinutes: 20,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 8,
      cookTime: 12,
      servings: 4,
      cuisine: 'American',
      ingredients: [
        '2 cans (5 oz each) chunk light tuna, drained well',
        '1/2 cup plain breadcrumbs',
        '1 large egg, beaten',
        '2 tablespoons mayonnaise',
        '2 tablespoons red onion, minced',
        '2 tablespoons parsley, chopped',
        '1 tablespoon lemon juice',
        '2 tablespoons vegetable oil',
        'Salt and pepper to taste',
      ],
      instructions: [
        'In a bowl, flake tuna. Add breadcrumbs, egg, mayonnaise, red onion, parsley, lemon juice, salt, and pepper. Mix until combined.',
        'Form into 4 patties, about 1/2 inch thick.',
        'Heat oil in a skillet over medium heat. Cook patties 3-4 minutes per side until golden and crisp.',
        'Serve with lemon wedges and a simple side salad or coleslaw.',
      ],
      nutrition: { calories: 220, protein: 22, carbs: 12, fat: 10 },
    },
    {
      title: 'Tuna Casserole',
      description: 'Creamy baked casserole with tuna, egg noodles, peas, and a crunchy topping. Nostalgic comfort food.',
      timeMinutes: 45,
      method: 'casserole',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 30,
      servings: 6,
      cuisine: 'American',
      ingredients: [
        '2 cans (5 oz each) chunk light tuna, drained',
        '8 ounces egg noodles',
        '1 can (10.5 oz) cream of mushroom soup',
        '1 cup milk',
        '1 cup frozen peas',
        '1/2 cup shredded cheddar cheese',
        '1/2 cup crushed potato chips or French fried onions',
        '2 tablespoons butter',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat oven to 350°F. Cook egg noodles until al dente. Drain.',
        'In a large bowl, combine noodles, flaked tuna, cream of mushroom soup, milk, peas, and half the cheese. Season with salt and pepper.',
        'Transfer to a 9x13-inch baking dish. Top with remaining cheese and crushed chips.',
        'Bake 25-30 minutes until bubbly and topping is golden. Let rest 5 minutes before serving.',
      ],
      nutrition: { calories: 380, protein: 24, carbs: 42, fat: 14 },
    },
    {
      title: 'Tuna Pasta with Lemon and Capers',
      description: 'Light and fresh pasta with canned tuna, lemon, capers, and parsley. Italian-inspired and ready in 20 minutes.',
      timeMinutes: 22,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 17,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '2 cans (5 oz each) solid white tuna in olive oil, drained (reserve 2 tbsp oil)',
        '12 ounces spaghetti or linguine',
        '3 cloves garlic, minced',
        '3 tablespoons capers, drained',
        '1/4 cup fresh parsley, chopped',
        '2 lemons (juice and zest)',
        '2 tablespoons olive oil',
        'Red pepper flakes to taste',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Cook pasta until al dente. Reserve 1/2 cup pasta water. Drain.',
        'Heat olive oil and reserved tuna oil in a large skillet. Add garlic and red pepper flakes, cook 30 seconds.',
        'Add flaked tuna, capers, lemon juice, and zest. Toss 1 minute.',
        'Add pasta and pasta water. Toss until coated. Stir in parsley.',
        'Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 440, protein: 28, carbs: 52, fat: 16 },
    },
    {
      title: 'Tuna Avocado Bowls',
      description: 'Healthy grain bowl with tuna, avocado, edamame, and rice. Topped with a soy-sesame dressing.',
      timeMinutes: 15,
      method: 'bowl',
      difficulty: 'easy',
      prepTime: 15,
      cookTime: 0,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '2 cans (5 oz each) chunk light tuna, drained',
        '3 cups cooked rice or quinoa',
        '1 avocado, sliced',
        '1 cup shelled edamame',
        '2 tablespoons soy sauce',
        '1 tablespoon rice vinegar',
        '1 teaspoon sesame oil',
        '1 teaspoon sesame seeds',
        '2 green onions, sliced',
        'Lime wedges for serving',
      ],
      instructions: [
        'Whisk soy sauce, rice vinegar, and sesame oil for the dressing.',
        'Divide rice among 4 bowls. Top with flaked tuna, avocado, edamame, and green onions.',
        'Drizzle with dressing. Sprinkle sesame seeds. Serve with lime wedges.',
      ],
      nutrition: { calories: 380, protein: 28, carbs: 42, fat: 12 },
    },
    {
      title: 'One-Pot Tuna Tomato Pasta',
      description: 'Simple one-pot pasta with tuna, cherry tomatoes, garlic, and white wine. Minimal cleanup, maximum flavor.',
      timeMinutes: 25,
      method: 'one-pan',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 20,
      servings: 4,
      cuisine: 'Italian',
      ingredients: [
        '2 cans (5 oz each) chunk light tuna, drained',
        '12 ounces penne pasta',
        '2 cups cherry tomatoes, halved',
        '3 cloves garlic, sliced',
        '1/4 cup white wine or chicken broth',
        '4 cups chicken broth',
        '2 tablespoons olive oil',
        '1/4 cup fresh basil, torn',
        'Red pepper flakes to taste',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large pot. Add garlic and red pepper flakes, cook 30 seconds.',
        'Add pasta, cherry tomatoes, chicken broth, and wine. Bring to a boil.',
        'Reduce heat and simmer 12-15 minutes, stirring occasionally, until pasta is tender and liquid is mostly absorbed.',
        'Stir in flaked tuna and basil. Season with salt and pepper. Serve immediately.',
      ],
      nutrition: { calories: 420, protein: 30, carbs: 52, fat: 10 },
    },
  ],
  eggs: [
    {
      title: 'Shakshuka',
      description: 'Middle Eastern eggs poached in a spiced tomato and bell pepper sauce. Serve with crusty bread for dipping.',
      timeMinutes: 30,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 10,
      cookTime: 20,
      servings: 4,
      cuisine: 'Middle Eastern',
      ingredients: [
        '6 large eggs',
        '1 can (28 oz) crushed tomatoes',
        '1 red bell pepper, diced',
        '1 yellow onion, diced',
        '3 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 teaspoon cumin',
        '1 teaspoon paprika',
        '1/2 teaspoon red pepper flakes',
        '1/4 cup fresh cilantro, chopped',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Heat olive oil in a large skillet. Sauté onion and bell pepper until softened, 5-6 minutes. Add garlic, cumin, paprika, and red pepper flakes. Cook 1 minute.',
        'Pour in crushed tomatoes. Simmer 10-12 minutes until thickened. Season with salt and pepper.',
        'Create 6 wells in the sauce. Crack an egg into each well.',
        'Cover and cook 5-7 minutes until egg whites are set and yolks are runny, or to desired doneness.',
        'Garnish with cilantro. Serve with warm pita or crusty bread.',
      ],
      nutrition: { calories: 220, protein: 14, carbs: 16, fat: 12 },
    },
    {
      title: 'Spanish Potato and Egg Frittata',
      description: 'Hearty frittata with sliced potatoes, onion, and eggs. A classic tapas-style dish for breakfast or dinner.',
      timeMinutes: 35,
      method: 'skillet',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 20,
      servings: 6,
      cuisine: 'Spanish',
      ingredients: [
        '8 large eggs',
        '2 medium potatoes, thinly sliced',
        '1 onion, thinly sliced',
        '3 tablespoons olive oil',
        'Salt and black pepper to taste',
        '1/4 cup fresh parsley, chopped',
      ],
      instructions: [
        'Heat 2 tablespoons olive oil in a 10-inch oven-safe skillet. Add potato and onion. Cook 12-15 minutes until potatoes are tender, stirring occasionally. Season with salt and pepper.',
        'In a bowl, beat eggs with salt and pepper. Pour over the potato mixture. Do not stir.',
        'Cook over medium-low heat 5-6 minutes until edges are set. Broil 2-3 minutes until top is golden (or flip carefully).',
        'Garnish with parsley. Cut into wedges and serve warm or at room temperature.',
      ],
      nutrition: { calories: 200, protein: 10, carbs: 14, fat: 12 },
    },
    {
      title: 'Egg Fried Rice',
      description: 'Classic fried rice with scrambled eggs, day-old rice, and soy sauce. Better than takeout in 15 minutes.',
      timeMinutes: 18,
      method: 'stir-fry',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 13,
      servings: 4,
      cuisine: 'Asian',
      ingredients: [
        '3 large eggs, beaten',
        '3 cups cooked white rice (day-old preferred)',
        '1 cup frozen peas and carrots',
        '3 green onions, sliced',
        '3 tablespoons soy sauce',
        '1 tablespoon sesame oil',
        '2 tablespoons vegetable oil',
        '2 cloves garlic, minced',
        '1/2 teaspoon white pepper',
      ],
      instructions: [
        'Heat 1 tablespoon oil in a wok over high heat. Add eggs and scramble until set. Remove and set aside.',
        'Add remaining oil. Add peas and carrots, stir-fry 2 minutes. Add rice, breaking up clumps. Stir-fry 4-5 minutes.',
        'Add garlic, soy sauce, sesame oil, and white pepper. Toss to combine. Return eggs and add green onions.',
        'Serve immediately.',
      ],
      nutrition: { calories: 340, protein: 12, carbs: 42, fat: 14 },
    },
    {
      title: 'Spinach and Feta Frittata',
      description: 'Fluffy frittata with wilted spinach, creamy feta, and herbs. Perfect for breakfast-for-dinner or brunch.',
      timeMinutes: 25,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 8,
      cookTime: 17,
      servings: 4,
      cuisine: 'Mediterranean',
      ingredients: [
        '6 large eggs',
        '4 cups fresh spinach',
        '1/2 cup crumbled feta cheese',
        '1/4 cup milk',
        '2 cloves garlic, minced',
        '2 tablespoons olive oil',
        '1 teaspoon dried oregano',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Preheat broiler. Heat olive oil in a 10-inch oven-safe skillet. Add spinach and garlic, cook until spinach wilts, 2-3 minutes.',
        'In a bowl, beat eggs with milk, oregano, salt, and pepper. Pour over spinach. Sprinkle feta on top.',
        'Cook over medium-low heat 8-10 minutes until edges are set. Broil 2 minutes until top is golden.',
        'Let rest 2 minutes. Cut into wedges and serve.',
      ],
      nutrition: { calories: 240, protein: 14, carbs: 4, fat: 18 },
    },
    {
      title: 'Egg Drop Soup',
      description: 'Silky Chinese egg drop soup with a light chicken broth and delicate egg ribbons. Comfort in a bowl in 10 minutes.',
      timeMinutes: 12,
      method: 'soup',
      difficulty: 'easy',
      prepTime: 2,
      cookTime: 10,
      servings: 4,
      cuisine: 'Chinese',
      ingredients: [
        '3 large eggs, beaten',
        '4 cups chicken broth',
        '1 tablespoon cornstarch mixed with 2 tablespoons water',
        '2 green onions, sliced',
        '1/2 teaspoon sesame oil',
        '1/4 teaspoon white pepper',
        'Salt to taste',
      ],
      instructions: [
        'Bring chicken broth to a boil in a medium pot. Reduce to a simmer.',
        'Stir in cornstarch slurry. Simmer 1-2 minutes until slightly thickened.',
        'Slowly pour beaten eggs in a thin stream while stirring gently. Eggs will form ribbons.',
        'Add sesame oil, white pepper, and salt. Garnish with green onions. Serve immediately.',
      ],
      nutrition: { calories: 80, protein: 8, carbs: 4, fat: 4 },
    },
    {
      title: 'Breakfast-for-Dinner Burrito',
      description: 'Scrambled eggs, cheese, and your choice of add-ins wrapped in a warm tortilla. Quick, customizable, and satisfying.',
      timeMinutes: 15,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 4,
      cuisine: 'Mexican',
      ingredients: [
        '6 large eggs, beaten',
        '4 large flour tortillas',
        '1 cup shredded cheddar cheese',
        '1/2 cup salsa',
        '2 tablespoons butter',
        'Optional: black beans, avocado, cooked bacon or sausage',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Melt butter in a skillet over medium heat. Add eggs and scramble until softly set. Season with salt and pepper.',
        'Warm tortillas. Divide eggs among tortillas. Top with cheese, salsa, and any optional add-ins.',
        'Fold in sides and roll tightly. Optional: toast in a dry skillet for a crispy exterior.',
        'Serve immediately.',
      ],
      nutrition: { calories: 380, protein: 20, carbs: 28, fat: 22 },
    },
    {
      title: 'Broccoli Cheddar Quiche',
      description: 'Creamy quiche with tender broccoli and sharp cheddar in a buttery crust. Elegant enough for company, easy enough for weeknights.',
      timeMinutes: 55,
      method: 'baked',
      difficulty: 'medium',
      prepTime: 15,
      cookTime: 40,
      servings: 6,
      cuisine: 'French',
      ingredients: [
        '6 large eggs',
        '1 pie crust (store-bought or homemade)',
        '2 cups broccoli florets, steamed and chopped',
        '1.5 cups shredded sharp cheddar',
        '1 cup heavy cream',
        '1/2 teaspoon salt',
        '1/4 teaspoon black pepper',
        '1/4 teaspoon nutmeg',
      ],
      instructions: [
        'Preheat oven to 375°F. Press pie crust into a 9-inch pie dish. Prick bottom with a fork. Bake 10 minutes.',
        'In a bowl, whisk eggs, cream, salt, pepper, and nutmeg. Stir in broccoli and 1 cup cheese.',
        'Pour filling into par-baked crust. Top with remaining cheese.',
        'Bake 35-40 minutes until set and golden. Let rest 10 minutes before slicing.',
      ],
      nutrition: { calories: 420, protein: 18, carbs: 18, fat: 32 },
    },
    {
      title: 'Loaded Veggie Omelet',
      description: 'Fluffy three-egg omelet stuffed with bell peppers, mushrooms, cheese, and herbs. A protein-packed dinner in 15 minutes.',
      timeMinutes: 15,
      method: 'skillet',
      difficulty: 'easy',
      prepTime: 5,
      cookTime: 10,
      servings: 2,
      cuisine: 'American',
      ingredients: [
        '6 large eggs',
        '1/2 bell pepper, diced',
        '1/2 cup sliced mushrooms',
        '1/2 cup shredded cheddar cheese',
        '2 tablespoons butter',
        '2 tablespoons milk',
        '1 tablespoon chopped chives',
        'Salt and pepper to taste',
      ],
      instructions: [
        'Beat eggs with milk, salt, and pepper. Melt 1 tablespoon butter in a nonstick skillet over medium heat.',
        'Sauté bell pepper and mushrooms 3-4 minutes. Remove to a plate.',
        'Melt remaining butter. Pour in eggs. When edges set, gently push toward center. Sprinkle vegetables and cheese on one half.',
        'Fold omelet in half. Cook 1 minute. Slide onto a plate. Garnish with chives.',
      ],
      nutrition: { calories: 380, protein: 24, carbs: 6, fat: 28 },
    },
  ],
}

export const proteinFaqs2: Record<string, FAQ[]> = {
  sausage: [
    {
      question: 'What can I make with sausage for dinner?',
      answer: 'Sausage is incredibly versatile for dinner. Try sheet pan meals with peppers and onions, pasta dishes like sausage marinara or pesto pasta, hearty soups with white beans, jambalaya, or skillet meals with potatoes. Italian, breakfast, and smoked varieties all work well depending on the cuisine.',
    },
    {
      question: 'Do I need to cook sausage before adding it to a recipe?',
      answer: 'It depends on the recipe. For crumbled sausage in pasta or casseroles, browning it first develops flavor and renders fat. For slow cooker or sheet pan dishes, you can add raw links—they will cook through. Pre-cooked smoked sausage just needs heating.',
    },
    {
      question: 'What is the difference between Italian sausage and breakfast sausage?',
      answer: 'Italian sausage is flavored with fennel, garlic, and herbs—ideal for pasta, peppers, and Mediterranean dishes. Breakfast sausage has sage and a milder profile, great for skillets with potatoes and eggs. Both work in many recipes; choose based on the flavor you want.',
    },
    {
      question: 'How long does sausage last in the fridge?',
      answer: 'Raw sausage lasts 1-2 days in the fridge. Cooked sausage keeps 3-4 days. For longer storage, freeze raw sausage for up to 2 months. Always check the sell-by date and ensure proper refrigeration.',
    },
    {
      question: 'Can I use turkey or chicken sausage instead of pork?',
      answer: 'Yes! Turkey and chicken sausage are leaner alternatives that work in most recipes. They may cook faster and produce less fat, so you might need to add a bit of olive oil when browning. Flavored varieties like Italian-style turkey sausage work well in pasta and skillet dishes.',
    },
  ],
  'rotisserie-chicken': [
    {
      question: 'What can I make with rotisserie chicken for dinner?',
      answer: 'Rotisserie chicken is perfect for quick dinners since it is already cooked. Make enchiladas, tacos, chicken salad, soups, casseroles, fried rice, or wraps. Shred or dice the meat and add it to your favorite recipe—most dishes come together in 15-30 minutes.',
    },
    {
      question: 'How do I shred rotisserie chicken?',
      answer: 'Remove the skin and pull the meat from the bones. Use two forks to shred, or place warm meat in a stand mixer and pulse on low. You can also chop it finely with a knife. Shredded chicken works best for tacos, enchiladas, and casseroles.',
    },
    {
      question: 'Can I freeze rotisserie chicken?',
      answer: 'Yes. Shred or dice the meat, store in airtight containers or freezer bags, and freeze for up to 4 months. Thaw in the fridge before using. The skin does not freeze as well, so remove it before freezing for best results.',
    },
    {
      question: 'How long does rotisserie chicken last in the fridge?',
      answer: 'Rotisserie chicken lasts 3-4 days in the refrigerator when stored in an airtight container. Use it within that window for salads and cold dishes. For cooked dishes, it is safe to reheat if it was stored properly.',
    },
    {
      question: 'What parts of the rotisserie chicken should I use?',
      answer: 'Use both white and dark meat for variety—breast for leaner dishes like salads, thighs and legs for richer soups and casseroles. The carcass and bones are great for making homemade stock. Do not use the giblets if included unless the packaging indicates they are meant to be cooked.',
    },
  ],
  'canned-chicken': [
    {
      question: 'What can I make with canned chicken for dinner?',
      answer: 'Canned chicken is perfect for quick, budget-friendly meals. Make chicken salad, quesadillas, casseroles, soup, wraps, Buffalo dip, or pot pie. It is already cooked, so most recipes come together in 15-30 minutes. Great for pantry-staple dinners.',
    },
    {
      question: 'Is canned chicken as good as fresh chicken?',
      answer: 'Canned chicken has a softer texture and milder flavor but is perfectly fine for dishes like chicken salad, casseroles, soups, and dips where it is mixed with other ingredients. For dishes where chicken is the star, fresh or rotisserie chicken often tastes better, but canned works in a pinch.',
    },
    {
      question: 'Should I drain canned chicken before using?',
      answer: 'Yes. Drain and flake the chicken with a fork before adding to recipes. You can also rinse it briefly with cold water if you want to reduce sodium. Pat dry with a paper towel if the recipe benefits from less moisture.',
    },
    {
      question: 'How long does canned chicken last after opening?',
      answer: 'Once opened, transfer canned chicken to an airtight container and refrigerate. Use within 3-4 days. Unopened cans last for years in the pantry—check the best-by date on the can.',
    },
    {
      question: 'Can I substitute canned chicken for rotisserie chicken?',
      answer: 'Yes, in most recipes. Use a 12.5 oz can per 1.5-2 cups of shredded rotisserie chicken. The texture will be softer, but it works well in casseroles, soups, salads, and tacos. For dishes where texture matters (like fried rice), rotisserie may be preferable.',
    },
  ],
  'canned-tuna': [
    {
      question: 'What can I make with canned tuna for dinner?',
      answer: 'Canned tuna is versatile and budget-friendly. Make tuna melts, pasta salad, Niçoise salad, tuna patties, casseroles, or light pasta with lemon and capers. Most recipes are ready in 15-30 minutes. Great for quick weeknight meals.',
    },
    {
      question: 'What is the difference between chunk light and solid white tuna?',
      answer: 'Chunk light tuna comes from smaller fish like skipjack, has a stronger flavor, and is often more affordable. Solid white (albacore) is firmer, milder, and works well in salads and recipes where you want visible chunks. Both are nutritious and work in most recipes.',
    },
    {
      question: 'How do I make canned tuna taste better?',
      answer: 'Drain it well and flake with a fork. Mix with mayonnaise, lemon juice, mustard, and celery for classic salad. For hot dishes, season with garlic, herbs, or a squeeze of lemon. Adding acid (lemon, vinegar) and fat (mayo, olive oil) greatly improves flavor.',
    },
    {
      question: 'Is canned tuna healthy?',
      answer: 'Yes. Canned tuna is high in protein and omega-3 fatty acids. Choose tuna in water for fewer calories, or in olive oil for more flavor. The FDA recommends 2-3 servings of low-mercury fish per week; chunk light typically has lower mercury than albacore.',
    },
    {
      question: 'Can I use canned tuna in hot recipes?',
      answer: 'Absolutely. Canned tuna works well in hot casseroles, tuna melts, pasta dishes, and tuna patties. Add it near the end of cooking to avoid overcooking. Tuna in olive oil holds up better in heated dishes than tuna in water, though both work.',
    },
  ],
  eggs: [
    {
      question: 'What can I make with eggs for dinner?',
      answer: 'Eggs are incredibly versatile for dinner. Try shakshuka, frittatas, fried rice, egg drop soup, breakfast-for-dinner burritos, quiche, or loaded omelets. They cook quickly and pair with vegetables, cheese, and grains for satisfying, affordable meals.',
    },
    {
      question: 'How do I make a fluffy omelet?',
      answer: 'Beat eggs with a splash of milk or water until frothy. Use medium-low heat and butter in a nonstick pan. Let the eggs set slightly before gently pushing cooked edges toward the center. Add fillings when the top is still slightly wet, then fold. Do not overcrowd with fillings.',
    },
    {
      question: 'What is the best way to poach eggs?',
      answer: 'Use fresh eggs and simmering (not boiling) water with a splash of vinegar. Crack each egg into a small bowl, create a gentle whirlpool, and slide the egg in. Cook 3-4 minutes for runny yolks. Use a slotted spoon to remove and drain on a paper towel.',
    },
    {
      question: 'Can I freeze eggs?',
      answer: 'Raw eggs can be frozen: beat whole eggs or separate yolks and whites. Store in ice cube trays or freezer bags. Thaw in the fridge before using. Cooked eggs (like hard-boiled) do not freeze well—the texture becomes rubbery.',
    },
    {
      question: 'How long do eggs last in the fridge?',
      answer: 'Whole eggs in the shell last 3-5 weeks in the fridge. Hard-boiled eggs keep about 1 week. Use the sell-by or expiration date as a guide. Store eggs in their carton on a shelf, not in the door, for more consistent temperature.',
    },
  ],
}
